### ISSUE TITLE
Sites detects blocker

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1000]
@gorhill Using uBO 1.3.6 for Firefox, these high Alexa rank sites have adblock detection that appear at the top of their main page:

* [extremetube.com](http://extremetube.com)
* [pornhub.com](http://pornhub.com) - highest Alexa rank
* [keezmovies.com](http://keezmovies.com)
* [youporn.com](http://youporn.com)
* [youporngay.com](http://youporngay.com)
* [sextube.com](http://sextube.com) put this message over the videos: "Don't you like banners? We neither. But advertisement on this website is the only thing that helps to cover the expenses for servers and bandwith. Please consider switching off AdBlockers? for our domain."
* [spankwire.com](http://spankwire.com)
* [mofosex.com](http://mofosex.com)

Is it possible for you to add a mechanism in uBO to circumvent the adblock detection system used by these sites?

Long ago, I [reported](https://forums.lanik.us/viewtopic.php?f=62&t=23492&p=71983#p71983) this issue to the developer of Adblock Warning Removal List‎ filter that can be selected in uBO 3rd-party filters, but they didn't care about it.

**Comment by Hrxn** [comment]
Maybe it's just me, but I am not really understanding what are you trying to say?

The link referenced in the changelog does work (blocked successfully), or does not work (creepy ad warning messages)?

I'm currently running Chrome Stable with uBO v.1.3.3, which still seems to be the latest version from the Chrome Web Store, and that link doesn't work for me, I get a redirect (http://dayt.se/adblock.php) and they are begging me to turn off Adblock..

But since inline script tag filtering doesn't work with Blink-based browsers, this should not come as a surprise.

When I'm home, I can test that link with my Firefox, if you want..

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/140

**Comment by flyingzebras** [comment]
@Hrxn I update the issue.

**Comment by gorhill** [comment]
> I get a redirect (http://dayt.se/adblock.php) and they are begging me to turn off Adblock.

For that specific case (dayt.se), this is addressed in latest dev build, using another technique.

**Comment by gorhill** [comment]
> Is it possible for you to add a mechanism in uBO to circumvent the adblock detection system used by these sites?

No.

**Comment by Hrxn** [comment]
#140 is not related..

This was about an internal page used by the extension, which was listed in the manifest.json of the Chromium extension so that this page could be accessed via web, making it possible to detect uBO this way, but this is already fixed.

There other blocker detection mechanisms, I assume, but they work differently.
That is all some crazy, obscure, obfuscated (Intentionally, I guess) JavaScript stuff which is way above me...

But I sure would like to learn more about that stuff...

**Comment by gorhill** [comment]
No need to be obfuscated. Bottom line is if a blocker has an effect on a web page, the effect can be detected by whatever javascript code is on a page. It's impossible to hide the presence of a blocker.
