### ISSUE TITLE
Add support for safari.

### ISSUE THREAD

**Issue by TyanColte** [gorhill/uBlock#1006]
I asked for Mac support the other day but I forgot that safari is available on windows. Would it be possible to add support for safari which I think will work on a Mac also.

**Comment by Hrxn** [comment]
No.

The APIs are too different, it's simply not feasible..

Would just be a waste of time. Especially since Apple now has a content blocking system on their own.
Since iOS9 and OS X El Capitan, see [here](https://developer.apple.com/library/safari/documentation/Extensions/Conceptual/ContentBlockingRules/Introduction/Introduction.html).

I have now idea if such implementations or extensions exist already, but I would bet they appear soon..

**Comment by gorhill** [comment]
Safari has been discontinued on Windows, I believe that even the other uBlock would not work on the last available version on Windows.

**Comment by TyanColte** [comment]
Well it was worth an ask at least.

**Comment by lewisje** [comment]
I believe there's an old version of AdBlock (from getadblock.com) that works on Safari 5 for Windows, but you shouldn't use that browser anymore, because support ended about three and a half years ago.

**Comment by anewuser** [comment]
@lewisje  TyanColte is a Mac user (like all other current Safari users). His/her point was that since gorhill doesn't have access to a Mac, he could supposedly use the Windows version to develop it for all Safari platforms.

**Comment by TyanColte** [comment]
@lewisje I don't use safari for windows. If you read the OP I was trying to see if gorhill could port the extension to the mac version of safari using the windows version of safari. Wasn't aware that safari on windows had been discontinued nor did i know that the code bases were so varied that you couldn't develop for one with the other. Now that I know that It's a non-issue.

**Comment by asoksevil** [comment]
@Hrxn considering uBlock is no longer developed, I guess we Safari users can either stick to the current version of uBlock or switch to another browser like Chrome/Firefox to get uBlock Origin.

**Comment by gorhill** [comment]
> or switch to another browser like Chrome/Firefox to get uBlock Origin

If this is the choice one makes, strictly concerning uBO itself (leaving aside the browsers' pros/cons), it may be good to know that the Firefox version of uBO currently performs better than the Chromium version:

- [Inline script tag filters](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering) do not work for Chromium at this point (unclear if it will ever work for Chromium).
- Ability of uBO to block websocket requests (these are not exposed to chrome's `webRequest` API yet). 
- The Firefox version of uBO still can see (and act upon) behind-the-scene requests from other extensions -- something that is no longer possible with Chromium.

**Comment by TyanColte** [comment]
@asoksevil @gorhill the only problem with using Chrome/Firefox on a mac is that neither of them are optimized for OS X and are HUGE battery drains on the system.

**Comment by asoksevil** [comment]
Yes, you are absolutely right @TyanColte I don't want to sacrifice battery life for having uBO.

**Comment by Hrxn** [comment]
As I said, Apple is doing a new turn here..

I haven't heard about promising projects for OS X, so far it's mostly iOS.

Further reading here:

https://webkit.org/blog/3476/content-blockers-first-look/
https://webkit.org/blog/4062/targeting-domains-with-content-blockers/

A project on GitHub that I found:

https://github.com/krishkumar/BlockParty

Otherwise, alternative solution:

https://glimmerblocker.org/

http proxy, I didn't hear about that project before, but at first glance it looks like they know what thery are doing..

**Comment by lewisje** [comment]
FTR GlimmerBlocker does not filter on HTTPS connections, and there are few local proxies that do; I don't even think Privoxy does that.

**Comment by Hrxn** [comment]
Good to know...

You're right, this would kinda defeat the purpose of encrypted transport :wink: 

So let's say it would be the best to just forget about these proxy software.
I don't know when we will see the first viable solution for OS X, guess we just have to wait a bit.

If there is one, I would also be interested

**Comment by neoyoli** [comment]
Maybe you could ask for help from developers, who has OS X. It would be really good to have uBlock Origin for Safari...

**Comment by TyanColte** [comment]
@neoyoli @gorhill That's a splendid idea.

**Comment by lewisje** [comment]
I'm sorely tempted to buy a MacBook with my Christmas bonus and other money I had saved before that, mainly so I could work on a Safari port; I ought to look into finding a used one that's still new enough to run El Capitan.

**Comment by TyanColte** [comment]
@lewisje i was able to get a MacBook Pro Mid 2010 model for $280 from the place I work (An IT Consulting firm which also sells new and used computers) came with 6 GB of ram and a 250 GB hard drive. Ran El Cap perfectly. However, just for the hell of it I upgraded the HDD to an SSD and maxed out the RAM to 8 GB and now it's lightning fast. First Mac I've ever owned and it's the best laptop I've ever had.

**Comment by lewisje** [comment]
I just bought a 2009-era MacBook with El Capitan on it for about $150, and as Domenic Tarr once said, "if you want to write fast software, use a slow computer": https://joreteg.com/blog/viability-of-js-frameworks-on-mobile

I'll try re-partitioning it so I could also try for Safari 6 compatibility (Mountain Lion) and maybe play around with what was available on Snow Leopard (last version to support Rosetta); I was surprised to learn that Safari 9 was available on Mavericks and later, even though, according to Wikipedia, Safari 8 was not available on Mavericks.

I also got a G4 MacBook for about $60, because it's an easier way to play around with old OS X and OS 9 software than PearPC, etc.

I just hope I'm as good at getting the old Safari-specific files up to date as the people who did the porting work were at porting this extension in the first place; I'm thinking I'll just start out doing what Deathamns did, posting up unofficial, non-self-updating builds.
