### ISSUE TITLE
SpyHunter 4 showing snap.do infesting ublock origin

### ISSUE THREAD

**Issue by NeoBlakkrstal** [gorhill/uBlock#1009]
Hello, SpyHunter 4 is detecting snap.do;ublock0@raymondhill.net.xpi, 7 infections, after installing ublock origin on 7 different profiles in Firefox 42.0. If I "fix" this issue using SpyHunter 4, it uninstalls ublock origin from Firefox. I installed ublock origin via about:addons. Any help with this would be appreciated. I have not had any problems with ublock origin up to this point and would like to continue using the product. Thanks.

**Comment by harshanvn** [comment]
False Positive.
Also, you can check it on virustotal.com by uploading your .xpi file.

**Comment by gorhill** [comment]
Yes, false positive. I will add SpyHunter 4 among the malware detector which falsely flag uBO: <https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin>.

There is nothing for uBO to do, the fix is for SpyHunter to stop falsely flagging uBO as infected. I don't know how that software works, maybe you can mark uBO as safe to avoid the fals positive, or you have to report the false positive to SpyHunter maintainers.

**Comment by onestepbeyond** [comment]
SpyHunter is well known for engaging in false advertising, to say the least...
http://www.bleepingcomputer.com/forums/t/550005/spyhunter-vs-malwarebytes-vs-iobit/#entry3491488
