### ISSUE TITLE
dev version has problems when opening _blank target links 

### ISSUE THREAD

**Issue by mausalimi** [gorhill/uBlock#1010]
sorry for the stupid title.

i made a very simple testcase: http://vicebuilds6.bplaced.net

just click the link, the "vicebuilds6 tab" seems to get closed and the new created "imagebam tab" takes its place immediately. 

tested with firefox 42 under windows 7 and ublock 1.3.7b12

**Comment by gorhill** [comment]
Thanks for the report. This is occurring because of the following (very broad) filter -- as per logger:

    |http:$domain=allmyvideos.net|embed.videoweed.es|extreme-board.com|fastspics.net|filepost.com|filmovizija.com|go4up.com|imagebam.com|imagefruit.com|imageporter.com|imgbox.com|imgmade.com|imgshots.com|imgsin.com|imgspice.com|load.to|mofunzone.com|openload.co|promptfile.com|putlocker.is|thevideo.me|twer.info|vidspot.net|watchcartoononline.com|xtshare.com|youwatch.org,third-party,popup

Which means clicking any link to one of the above sites will cause the current tab to be closed...

The only solution I can think of is to create a new filter option `popunder` and to create specific filters for sites known to use popunders.

**Comment by gorhill** [comment]
Closing as per new `popunder` filter option to handle explicitly popunders, i.e. no longer implicitly treating popunder filtering by extending the semantic of the `popup` filter option.

**Comment by mausalimi** [comment]
:+1: 
thanks a lot!

**Comment by gorhill** [comment]
Gave some thought to this.

I could restore the originally implementation -- to use existing `popup` filter option to also block popunders, while making uBO a bit smarter to work around the issue here. The problem here is an overly broad `popup` filter, this is what caused me to introduce the `popunder` filter. However, if uBO took into account the "broadness" of a popup filter, and discarded the ones which are too broad (like the one above), then I think this would allow to restore the implementation I originally intended for popunders.

Summarily: bring back the lookup of existing `popup` filters to also handle popunders, **except** for when the `popup` filter is too broad -- like `|http://`.

**Comment by gorhill** [comment]
I used this test case provided in #1381 to test fix in ff0ccbd803fc63b221d4c2a6e6ab97c0a8a43ed9:

Add `||adf.ly/puopen.php$popup,important` -- `important` is necessary to override exception filter in `Unbreak` list.

Though the site launches a popunder upon clicking the "Skip Ad" button, it is taken care by the above `popup` filter, because it is a non-broad popup filter.

The case here still work fine, because the popup filter which cause the issue here is discarded, because too broad.

The fix should simplify filter set, as oftencase just providing a non-broad `popup` filter will also take care of popunders.
