### ISSUE TITLE
Cosmetic filter fails to hide element

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1015]
Repro steps:

- Go to <https://en.wikipedia.org/wiki/Main_Page>.
- A large notice should appear at the top.
    - If not, clear all cookies for the site, refresh the page.
- In _"My filters"_ pane, manually enter the following cosmetic filter: `en.wikipedia.org###centralNotice`.
- Refresh the above web page.
- Result: the large notice is still visible.

Cause:

The DOM element `#centralNotice` has a style property `display: block !important`, and that CSS rule is part of a style tag which is inserted **after** uBO has inserted its own style which contains site-specific cosmetic filters -- so essentially uBO's CSS rules are overriden by the page's own rules.

Solution: prepend all inserted CSS rules for cosmetic filtering purpose with `html `, to augment one notch the [specificity](http://specificity.keegan.st/) of uBO's CSS rules.

**Comment by epicgirl1998** [comment]
some stuff about the fix in 89f0e8f1a9a66b3c344562a1e68124ae1600f648

issue one:

blindly prefixing the selectors with `:root ` breaks the inserted css rules for filters with otherwise valid selectors that already make use of `:root` or `html`

like how `example.org##:root .ads` turns into `:root :root .ads`

the elements do seem to get hidden later though using the shadow dom thing

issue two:

for filters whose selectors have multiple selectors separated by commas (a css feature), the specificity boost only applies to the first selector

like how `example.org##.ad, .ads` turns into `:root .ad, .ads`

fixing it by blindly replacing commas with `, :root` would still suffer from issue one & it'd also break escaped commas and attribute selectors whose values contain commas

just thought you should know
