### ISSUE TITLE
Redirect Feature

### ISSUE THREAD

**Issue by jd4u** [gorhill/uBlock#1025]
How the new tags can be created and loaded apart from experimental.txt?

- I downloaded dev version 1.3.7 and loaded unpacked in chrome from local drive. ]
- Any change to assets/ublock/experimental.txt is not reflected even after reloading extension  
- Any change to assets/ublock/redirect-resources.txt is not reflected even after reloading extension 

Can we create a tag where a script url is changed to its querystring value?

http://resourcesniffer.com/someurl/?a=123&myUrl=http://mydomain/code.js
to change as 
http://mydomain/code.js

thank you.

**Comment by gorhill** [comment]
Custom filters go into the _"My filters"_ pane in the dashboard.

**Comment by gorhill** [comment]
By the way, what you **could** do for something like:

    http://resourcesniffer.com/someurl/?a=123&myUrl=http://mydomain/code.js

Is to strict-block `resourcesniffer.com` with the a filter like `||resourcesniffer.com^$document`, and then use uBO's [ability to show you the decomposed URL in the block page](https://cloud.githubusercontent.com/assets/585534/9832014/bfb1b8f0-593b-11e5-8a27-fba472a5529a.png) so that you can just click on whatever URL is found in the paramaters.

**Comment by jd4u** [comment]
The problem is the sniffer is just replacing the <script> block url.
