### ISSUE TITLE
B-t-s blocking stops working

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#1047]
uBO 1.4.0rc0 and v1.4.0rc2
Firefox 42.0 stable

1. With everything at default, create the static rule `||*$domain=behind-the-scene`
2. Make a b-t-s request which is now blocked
3. Do anything to static rules (add a rule, change a rule, add nonsense text, whatever)
4. Observe b-t-s requests are now _not_ blocked
5. No such issue occurs in uBO v1.3.7b10

This doesn't appear to affect any other rules (e.g. `||www.google.com$image,domain=www.google.com` which will continue to block images).

**Comment by gorhill** [comment]
`*$domain=behind-the-scene` works though. -- I put in a special test to reject nonsensical filters, and a filter such as `||*` makes no sense because `||` means the match must start within the hostname part of the URL, which can't happen with `*`, because in such case the match always start at the start of the URL.

**Comment by gorhill** [comment]
I verified and ABP enforce `||*` as you expected it -- so I will have to do the same, even though this goes against [the official documentation](https://adblockplus.org/filter-cheatsheet#blocking2):

> **Domain name anchor** The following text must be the domain name of the address.

When using `*`, the "following text" is always `http` or `https` -- so ABP's implementation contradicts its documentation.

**Comment by luxoflux** [comment]
> `*$domain=behind-the-scene` works though.

Oh, of course, that is the correct rule. At least it's foolproof now.

Thanks.
