### ISSUE TITLE
two new rules

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uBlock#1068]
Hello.
Two new rules appeared in Settings Tab "My rules", which wasn't made by me.
And I accidentally have deleted both.
How can I recover them?
And, please, give me a link to commit where you added these new rules. Because I don't know why they exist.
Thank you.

P. S. It's Firefox.

**Comment by 5t3f4n** [comment]
Do you mean these?
`behind-the-scene * 3p noop`
`behind-the-scene * 3p-frame noop`

**Comment by gorhill** [comment]
Those rules appears **if and only if**:

- First installation of uBO; **or**
- One never used dynamic filtering.

The purpose is to avoid [yet another instance](https://github.com/gorhill/uBlock/issues/1027) of someone overestimating their "advanced-userness" and:

- Enables _"advanced user"_ mode; **and**
- Removes `behind-the-scene` from whitelist directives; **and**
- Creates a broad block rule such as `* * 3p block`; **and**
- Complains that important function of the browser or extensions -- including uBO -- is broken when using uBO.

No doubt this will still happen, it's just me trying to lower likelihood of this happening.

Commit is [here](https://github.com/gorhill/uBlock/commit/0c5ef268add45a394b921c0425dee061639c472e).

**Comment by bhabba** [comment]
@gorhill I have a small question regarding your answer: Do I understand it right that when I

1. enable [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode)
2. remove ``behind-the-scene`` from the whitelist
3. add the rules ``behind-the-scene * 3p noop``, ``behind-the-scene * 3p-frame noop`` and ``behind-the-scene * 3p-script noop``

the only difference to hard mode without doing 2. and 3. is that static filter rules (the ones I subscribed to) are applied to behind-the-scene network requests, too (but no dynamic rules)? If this is the case, why do you warn in such a drastic/dramatic tone from doing it (at least it seems to me you do)?

Thank you for a clarification!

**Comment by IDKwhattoputhere** [comment]
I saw you posted it here too: https://www.reddit.com/r/uBlockOrigin/comments/45ge45/unwhitelisting_behindthescene_network_requests/

I also wonder about this. When all those noop rules are in place I don't see what bad results not whtelisting behind-the-scene requests has. Seems like normal site breakage is way more common and the upside (keeping YouTube, GitHub/GA and maybe more sites from tracking the user) seems to outweigh hindering behind-the-scene breakage if it exists at all with noop in place.

**Comment by gorhill** [comment]
> If I'm not mistaken ABP filters behind-the-scene too

Of course not. All blockers I have seen skip behind-the-scene network requests.

> I don't see what bad results not whtelisting behind-the-scene requests has

Until one single unforeseen issue occurs and break whatever browser/other extension functionality -- and for which most users would have no clue how to investigate, let alone fix. Just one single example, if you use an AdGuard filter list, updating the filter list will be broken, because of EasyList's `/adguard.`, and since all behind-the-scene network requests are 3rd-party to the behind-the-scene scope, EasyList's ` ` won't work.

**Comment by bhabba** [comment]
> Just one single example (...)

Ok, thanks! That's what I wanted to know!

@gorhill Do you think it might be worth collecting those issues somewhere in the wiki (under the article [Behind the scene network requests](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests) maybe) so that they might get addressed in the future? Or do you prefer to not even start to consider applying static filtering/filter lists to the ``behind-the-scene`` scope?

**Comment by gorhill** [comment]
> Or do you prefer to not even start to consider applying static filtering/filter lists to the behind-the-scene scope?

This.

Blocking behind-the-scene is possible, but whoever choose to do it is completely on its own if it breaks something in the browser or other extensions. I am not looking to increase my workload, the opposite actually.

**Comment by bhabba** [comment]
> I am not looking to increase my workload, the opposite actually.

Ok, fair enough!

**Comment by IDKwhattoputhere** [comment]
Makes complete sense now. Thank you.
