### ISSUE TITLE
Yavli Advertising

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1079]
Questions:
1. Can I request these filters to be added here? Sorry and disregard if not.
If yes:
2. Will you add filters like ||example.com^ so uBO blocks redirections through them? I don't think EasyList is going to add them since Adblock Plus doesn't have this feature and they call themselves "The Easy Subscriptions for Adblock Plus". They usually use ^$third-party which doesn't cause uBO to block redirections.

If yes:

    ||c8factor.com^
    ||k5zoom.com^

Example: http://www.latinpost.com/articles/101358/20151210/android-m-6-0-marshmallow-update-release-date-motorola-adds-moto-e-droid-turbo-2-maxx-2-moto-x-force-to-rollout-list.htm

Yavli ads is native advertising (see https://easylist.adblockplus.org/blog/2015/08/19/issues-with-yavli-advertising) and they change domains which host their scripts and images often to avoid ablocking but those two domains are used to redirect and track the clicks on a lot of those sites.

**Comment by gorhill** [comment]
> 1. Can I request these filters to be added here?

Why not EasyList? The filters you suggest have nothing to do with uBO's redirection feature. I could block the Yavli ads on the URL you provided by simply using `||vuadiolgy.net^`.

**Comment by gorhill** [comment]
Ok I understand your comment re `third-party` and redirection. Can you give me examples of such filters in EasyList works to block the Yavli ads but uBO interprets those filters differently?

**Comment by gorhill** [comment]
Ok, you were talking about **strict blocking**. In EasyList forum you say "if clicked", you did not mention here you meant "if clicked", so you got my all confused.

So I look at the web sites behind `c8factor.com` and `k5zoom.com`, and there is essentially nothing except a blank page with the message "Hi, I am your new HeroFW app!". Because ofthis, yes, I am open to strict block those hostnames.
