### ISSUE TITLE
one.co.il is broken

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1081]
(Default filter sets with EasyList Hebrew)
On homepage, try to click on videos from ONE VOD.

You need to add to the unbreak list:
`@@||google-analytics.com/ga.js$domain=one.co.il`
`@@||xads.zedo.com/ads2/c?*.one.co.il/Cat/Video/`
The first one is caused by Peter Lowe's list. Second by uBlock Origin blocking method.

**Comment by gorhill** [comment]
> Second by uBlock Origin blocking method.

I don't understand what that means. Can you explain?

**Comment by IsraeliUser** [comment]
uBlock Origin has prevented the following page from loading:

`http://xads.zedo.com/ads2/c?a=`...

Because of the following filter

`||zedo.com^`
Found in: Peter Lowe’s Ad server list 
---
But when I use Peter Lowe’s Ad server list on Adblock Plus I don't have this issue.

**Comment by gorhill** [comment]
With both (ABP or uBO) and _Peter Lowe's_ and:

    @@||google-analytics.com/ga.js$domain=one.co.il
    @@||xads.zedo.com/ads2/c?*.one.co.il/Cat/Video/

I get:

    Error loading playlist:
    Error loading file

> But when I use Peter Lowe’s Ad server list on Adblock Plus I don't have this issue.

I can't make sense of this. `zedo.com` is blocked by _EasyPrivacy_ and _Peter Lowe's_, so the issue should also be present in ABP.

**Comment by IsraeliUser** [comment]
Do you use EasyList Hebrew? Many Israeli sites like this one are broken/blocked if you don't use it.
With ABP (with EasyList Hebrew) on Firefox I've no issue. 
If I use Peter Lowe's list on ABP I need to add only the first filter to watch the videos.
With uBO I need both filter.

**Comment by gorhill** [comment]
> Do you use EasyList Hebrew?

My bad, forgot to check it. So I am now further in having the video play, however it still does not play and nowhere in the log there is an instance of `xads.zedo.com`. Investigating.

**Comment by gorhill** [comment]
Alright, I could get the video to play, with the following steps:

- Disable Flash plug-in -- such that the player falls back on using the HTML5 player.
- Adding your filter `@@||google-analytics.com/ga.js$domain=one.co.il`.

Video plays from here, no need to allow connections to ad servers.

If enabling _uBlock filters -- Experimental_ (which will override the above exception filter for `google-analytics.com/ga.js`, there were exceptions thrown in the console, that is now fixed by adding the missing stuff into the neutered `www.google-analytics.com/ga.js` in [redirection-resources.txt](https://github.com/gorhill/uBlock/blob/master/assets/ublock/redirect-resources.txt).

**Comment by IsraeliUser** [comment]
Problem has not been solved yet.
On the main page, try to click on the videos in the light grey box "ONE VOD". You should get a blocking message. You should add the other filter as well. It won't whilelist any ad.

**Comment by gorhill** [comment]
I see, the link is going through `xads.zdo.com` before serving the expected content. I don't like that kind of 3rd-party tracking. At least users are made aware of this now, and this awareness would go away if I create a filter to bypass the warning -- so I rather no add this exception filter. One can even use the embedded URL in the parsed URL on the block page to skip completely `xads.zdo.com`.
