### ISSUE TITLE
Hide Outbrain and Taboola placeholders

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1083]
`##.outbrain` on mako.co.il homepage on bottom and on many sites
`##.outbrain-wrapper` on articles on haaretz.co.il and themarker.com above user comments
`##.taboola-widget` on articles with video on walla.co.il below video
`##.taboola-video-container` on articles with video on nrg.co.il below video
`##.taboola-center-container` on articles on nrg.co.il above user comments

**Comment by gorhill** [comment]
It would make sense to add these given that `outbrain.com` and `taboola.com` are blocked out of the box through _Peter Lowe's_ list. However, if someone choose to un-select that list, this won't make those filters go away, since they would be in uBlock's own filter list, and this means they would interfere. Ideally these cosmetic filters should be part of _Peter Lowe's_ list but it's of course not possible.

Not sure yet what is the best solution for this.

**Comment by IsraeliUser** [comment]
Add a new filter list with these filters, enabled by default.

**Comment by harshanvn** [comment]
> However, if someone choose to un-select that list, this won't make those filters go away, since they would be in uBlock's own filter list

is it a problem?

**Comment by gorhill** [comment]
> is it a problem?

If `outbrain.com`/`taboola.com` are no longer blocked because the user un-selected _Peter Lowe's_, uBO should no longer cosmetically hide the Outbrain/Taboola placeholders -- since they would now be filled with whatever they are supposed to be filled.

**Comment by IsraeliUser** [comment]
I think Outbrain and Taboola should be blocked by default.
You can add a fliter list called "Block Outbrain and Taboola" (with blocking rules) or a list called "Hide placeholders for Peter Lowe's ad server list".

**Comment by RoxKilly** [comment]
@IsraeliUser These solutions don't seem like they would scale well. Today it's just Taboola and Outbrain, but tomorrow there might be many others. In addition, Peter Lowe's list is one block list, but there are more and in the future there will be even more.  As a result, the user experience may be poor because the UI will have a lot of boxes that are linked in a way that won't be obvious.

Does this really need a fix?  Isn't it for this use-case that uBO allows for user custom filters and even give us the picker (eye-dropper) tool in the panel to select elements and create cosmetic filters on the fly?

**Comment by gorhill** [comment]
Here is an instance of Outbrain being blocked and its placeholder would not be hidden using `###.outbrain` or `###.outbrain-wrapper`:

![a](https://cloud.githubusercontent.com/assets/585534/11914222/232b4582-a648-11e5-80ca-cc4961f83995.png)

So this supports that the best solution is to create filters on a per-site basis, and I see this as someone creating a filter list which purpose may be dedicated to block such annoyances, then it is up to the users to make use of that filter list. This is also best in the spirit of spreading the workload: it does not have to be me, anybody can create and maintain a filter list.

Fanboy’s Annoyance List‎ contains some of the filters in the opening comment.

**Comment by IsraeliUser** [comment]
I don't think it's a good solution because Fanboy’s Annoyance List blocks other things on sites, such as social networks, which many users (like me) do not want to block.

Maybe you can ask Fanboy to organize all Taboola and Outbrain filters under two sections, then they could be added automatically to your default list by a bot.
