### ISSUE TITLE
HTML5 Speedtest.net not possible

### ISSUE THREAD

**Issue by theincogtion** [gorhill/uBlock#1107]
I can not execute the speedtest on http://beta.speedtest.net/# while ublock is running.
The page is loading but a click on "begin test" does not has any effect. I have to deactivate ublock to start the test.
I couldn't find any options to unblock seweral items on this page.

**Comment by zymase** [comment]
beta.speedtest.net doesn't run here either, even with uBlockO deactivated, because of my system-wide HOSTS protection settings. The site is using/calling privacy related data which is naturally blocked, be it by uBlockO's settings, be it by whatever privacy/security application applicable.

There are excellent speed testers free of privacy concerns. Sorry for being off-topic when it appears uBlockO is not concerned, but good html5 speed testers I know:

SpeedOf.Me (HTML5) : http://speedof.me/
Bandwidth Place (HTML5) : http://www.bandwidthplace.com/

No privacy issues with those.

**Comment by gorhill** [comment]
Works fine from here using default filter lists.

Marking as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). If you make the case there is an issue with uBO proper and I will look into it.

**Comment by CrisBRM** [comment]
Works fine here as well, using ALL non-localised lists and all privacy enhancing options enabled on Chromium (mum's profile).
