### ISSUE TITLE
Downloading a file messes up party order in dynamic filter pane

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uBlock#111]
Same steps as https://github.com/gorhill/uMatrix/issues/145.  Not sure if the fix over there would fix this.

1.) Go to http://www.reddit.com/r/PushBullet/
2.) Observe the popup ( reddit.com is 1st party )
3.) Download from the "Pushbullet Windows app" link, you can cancel the download
4.) Observe the popup ( pushbullet.com is now 1st party & reddit.com is 3rd party )

![ublockorigindownloadpartyissue](https://cloud.githubusercontent.com/assets/6408935/7312143/c42025d4-e9fb-11e4-8e7f-2e5739f34949.gif)

```
uBlock Origin 0.9.4.6
Chrome ( stable )
Win XP
```

**Comment by WyohKnott** [comment]
Additional info: it only happens when one clicks on the link directly, not if one does a Right click>Save As.
(Tested on Nightly + latest 0.9.4.6 + Default Deny + No static filter).

I set up a test page on a tumblr with various links to Linux Distros (Fedora/Slack/Gentoo), the colours seem off too: the local cells appear Dark Blue because these domains are not allowed in Default Deny, yet the whole line has a yellow mark saying content is allowed:

![screenshot-ublock0 2015-04-24 09-41-20](https://cloud.githubusercontent.com/assets/6247191/7314597/37c074f2-ea66-11e4-8022-cb67583c73d9.png)

(ps: I'd like to know what software you are using for screen recording).

**Comment by gorhill** [comment]
Currently uBlock detects download operation using the `content-disposition` header. In the current case, there is no such header. The best hint it is a download in the current case is the `content-type` header:

    name: "content-type"
    value: "application/x-msdownload"
