### ISSUE TITLE
Elements being hidden without notice

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1124]
I found that if you open an image which has been blocked by uBO (e.g. https://airvpn.org/images/promotional/banner_641x91.gif from https://ipleak.net/) in a separate tab it will be hidden but uBO will neither show a blocked net request nor a counter for hidden elements. It also doesn't show up in the console or logger.

Edit: Made a video to demonstrate it: https://u.pomf.io/fvexdv.mp4

**Comment by ethus3h** [comment]
I am unable to reproduce with Firefox 43.0.2.

Why anyone would willingly use Chrome/Chromium is beyond me, but perhaps that is the source of the issue?

**Comment by IDKwhattoputhere** [comment]
I'm also no fan of Google and their control over the internet but Chrome runs smoother than Firefox (at least for me).  Take a look at Chrome's and Firefox's market share. Your opinion is irrelevant here. And yes, this is only an issue in Chromium based browsers.

**Comment by gorhill** [comment]
Even though the page URL address is `https://airvpn.org/images/promotional/banner_641x91.gif`, from uBO's content script's point of view, Chromium shows the document as being a standard HTML document, all with normal DOM structure (`<!DOCTYPE ...><html><head>...</head><body>...</body></html>), with only one `<img>` node in its `body` element.

However, from uBO's HTTP observer's point of view, the network request to `https://airvpn.org/images/promotional/banner_641x91.gif` is not blocked, because it is labelled as being a document, not an image.

A similar issue was reported for FF: #260. The fix was made into FF-dependent code only at the time.
