### ISSUE TITLE
Cosmetic filtering should block blank area on spiegel.de home

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#1176]
As you can see on http://www.spiegel.de/wirtschaft/unternehmen/vw-aktie-verliert-massiv-an-wert-a-1070498.html there's a huge blank area above the article which should be blocked by cosmetic filtering.

I'm talking about this area:
![2016-01-05_2055](https://cloud.githubusercontent.com/assets/583169/12125951/ba031e04-b3ee-11e5-8a6d-8aba77c403d4.png)

**Comment by TonyTough** [comment]
report it to easylist Germany forum.

In the meantime you can use:

||imagesrv.adition.com/js/srp.js$script,domain=www.spiegel.de,important

**Comment by tobbi** [comment]
Alright!

**Comment by gorhill** [comment]
This is caused by the exception filters which were added to EasyList Germany to workaround anti-blocker mechanisms on spiegel.de -- and various other sites.

This really sucks for uBO users, as this means they are suffering lowered blocking power because of solutions specific to ABP. I suspect none of the exception filters seen in the commits below are really needed for uBO users:

- <https://hg.adblockplus.org/easylistgermany/rev/c7e3e7daec10>.
- <https://hg.adblockplus.org/easylistgermany/rev/5975490726aa>.
- <https://hg.adblockplus.org/easylistgermany/rev/5da52adc859d>.
- <https://hg.adblockplus.org/easylistgermany/rev/332fa82fc94f>.
- <https://hg.adblockplus.org/easylistgermany/rev/332fa82fc94f>.
- <https://hg.adblockplus.org/easylistgermany/rev/10759d51f71c>.

What would be great is that Germany filter maintainers create filters specific to uBO, and these would include counter exception filters which are of no benefit to uBO users.

**Comment by tobbi** [comment]
In any case, I reported this here: https://forums.lanik.us/viewtopic.php?f=62&t=27628

**Comment by gorhill** [comment]
Another way which work to easily counter unwanted exception filters is for user to take matters in their own hands and to use dynamic filtering: wholesale blocking of `adition.com` server get rid of the empty banner:

![a](https://cloud.githubusercontent.com/assets/585534/12126766/21f58520-b3c1-11e5-9769-de332cb030e3.png)
