### ISSUE TITLE
Duplicate filter lists

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1181]
1. If I add EasyList Germany from https://adblockplus.org/subscriptions uBO will add it in the box under "One URL per line" and ignore it. It would be better if uBO just activated the list in the settings.
2. I'm able to add "EasyList Germany+EasyList" while both EasyList and EasyList Germany are already checked in uBO.
3. I'm able to add EasyPrivacy and uBO will not ignore it but add it under "Custom".

**Comment by IDKwhattoputhere** [comment]
On a similar note: You could rename `Fanboy’s Annoyance List` to `Fanboy’s Annoyance List (includes Social Blocking List‎)` so people don't unnecessarily download both. uBO ignores the duplicate filters but it puts load on the servers. @ryanbr would probably appreciate the change.

**Comment by IDKwhattoputhere** [comment]
uBO should also treat `http://example.com/filterlist.txt` as if it's the same as `https://example.com/filterlist.txt`. To add to that: If the user is subscribed to `http://example.com/filterlist.txt` and adds `https://example.com/filterlist.txt` uBO should simply replace the Non-SSL with the SSL version.

**Comment by bhabba** [comment]
Regarding filter lists that are subsets of other filter lists (currently only ``Fanboy's Social Blocking List`` which is a subset of ``Fanboy’s Annoyance List``): I suggest using [radio buttons](https://en.wikipedia.org/wiki/Radio_button) for them so it's not possible to select both of them together in the first place. Of course some additional comment like what @IDKwhattoputhere [suggested](https://github.com/gorhill/uBlock/issues/1181#issuecomment-172250770) would still be helpful.

**Comment by IDKwhattoputhere** [comment]
I think this also applies to `Malware domains‎` and `Malware domains (long-lived)` like you can see [here](https://cloud.githubusercontent.com/assets/16030872/12932308/7c44926e-cf82-11e5-9b70-efcdd9dd5528.png). The minimal difference of 5 filters could be a result of the mirror used for `Malware domains (long-lived)` not being up to date.

**Comment by TPS** [comment]
Maybe a couple of sub-proposals here to help think this out:  When 1 is`an advanced user`, bias filterlist processing so that:
* `https`lists are processed before`http`1s
* larger lists are processed before smaller 1s

then someway highlight unused, but ☑ed-&-downloaded, lists for further analysis, purging, & un☑ing.

**Comment by gorhill** [comment]
To be clear: the only thing I accept to possibly fix here is 1) and 3).

**Comment by gorhill** [comment]
I will revisit the meaning of the external filter lists area in the _"3rd-party filters"_ pane: it will become a way to _import_ external filter lists -- as oppose currently being a way to _declare_ external filter lists.

When one will click the _Import_ button (which will replace the current _Parse_ one), whatever (valid) filter lists in there will be imported, and the import text field will be reset to an empty text area (because it has been processed). Imported URLs which match those in the stock filter lists will cause the respective stock filter list to be selected.

To remove an imported filter list, there will be a X button aside the list to mark it for removal.

**Comment by gorhill** [comment]
Fixed with 9309df4196cbe1a30b7b8f7cc88dd67aac3c151c.

As stated above, point 2 is _wontfix_ because the list can't be reverse-mapped to a stock list in uBO.
