### ISSUE TITLE
[Request] Block Background Ads

### ISSUE THREAD

**Issue by bkrcrc** [gorhill/uBlock#1202]
How can we block background ads with uBO? Other ads blocked perfectly but I cannot block those background ads even with element picker. Element picker cannot catch it. Please check the following example website.

http://www.bicaps.net/
http://altyazilifilmizle.org/
http://www.eniyifilmizle.com/
http://720pizle.com/

Thanks

**Comment by gorhill** [comment]
I agree, the element picker should extract and present background image-based filters as a choice.

**Comment by bkrcrc** [comment]
Thanks for accepting this.
Can uBO will do this automatically? or should I block them with element picker?

**Comment by gorhill** [comment]
This will have to be done through the element picker -- blocking heuristically will inevitably leads to false positive. Meanwhile the logger can be used to create a static filter once you find which image event in there is the one for the background.

**Comment by bkrcrc** [comment]
OK, thank you gorhill. Waiting for this feature, I will test it when will you release it.

**Comment by SMed79** [comment]
* https://forums.lanik.us/viewtopic.php?f=62&t=27752
* https://forums.lanik.us/viewtopic.php?f=62&t=27753
* https://forums.lanik.us/viewtopic.php?f=62&t=27754
* https://forums.lanik.us/viewtopic.php?f=62&t=27755

**Comment by anewuser** [comment]
@SMed79 The Turkish filter shipped with uBlock Origin points to a different URL: http://forum.adguard.com/forumdisplay.php?51-Filter-Rules

**Comment by bkrcrc** [comment]
@SMed79 , the Easylist author did not accept to add filters from non-english website. I request a list from Adguard for Turkish they accepted. and again thanks to @gorhill , he accepted to add Adguard filters in uBO for my people.

@anewuser , here is the real Turkish list page from adguard : https://adguard.com/en/filter-rules.html?id=13

Thanks

**Comment by SMed79** [comment]
Hi, 

@anewuser @bkrcrc maybe you do not know, but always there are a **Regional Lists** ([Espanol/Portuguese](https://secure.fanboy.co.nz/fanboy-espanol.txt), [Turk](https://secure.fanboy.co.nz/fanboy-turkish.txt), [Polish](https://secure.fanboy.co.nz/fanboy-polish.txt), [Indian](https://secure.fanboy.co.nz/fanboy-indian.txt), [Swedish](https://secure.fanboy.co.nz/fanboy-swedish.txt), [Japanese](https://secure.fanboy.co.nz/fanboy-japanese.txt), [Vietnamese](https://secure.fanboy.co.nz/fanboy-vietnam.txt) and [Korean](https://secure.fanboy.co.nz/fanboy-korean.txt)) managed by fanboy's (Easylist author) found on https://www.fanboy.co.nz/

fanboy turkish list (last changeset/updates): 
https://hg.fanboy.co.nz/rev/5485d2d7e510
https://hg.fanboy.co.nz/rev/3e62ec8242e0
https://hg.fanboy.co.nz/rev/79a61c290deb
https://hg.fanboy.co.nz/rev/276058d758a7

About non-english websites in special cases they will accept generic rules https://hg.adblockplus.org/easylist/rev/2a65b331f8e7

Others Known Adblocker subscriptions found on : 
* https://adblockplus.org/subscriptions
* https://easylist.adblockplus.org/en/
* https://youtube.adblockplus.me/
* https://facebook.adblockplus.me/

Regards,
Med

**Comment by gorhill** [comment]
@Smed79 Your changes are the [first ones since 2.5 years ago](https://hg.fanboy.co.nz/log/5485d2d7e510/firefox-regional/fanboy-adblocklist-tky.txt), it's why I did not include Fanboy's Turkish list, it was no longer maintained.

**Comment by anewuser** [comment]
@bkrcrc  No, that's not the "page". That's a direct link to the list, and the forum link I left before is the one to be used to report issues with it, since they only have Russian and English forums.

@SMed79  as @gorhill has said, Fanboy stopped updating his regional lists when he started working with Easylist. **The Turkish list by Aguard is the continuation of Fanboy's list**: http://forum.adguard.com/showthread.php?7137-Resolved-Turkish-Filter-Rules-Suggest .

**Comment by SMed79** [comment]
Thank you for this information.
Good luck :)

**Comment by bkrcrc** [comment]
I e-mailed to Fanboy about out-dated Turkish list. He updated the Turkish Fanboy list with Adguard's rules because no one interested in regional list as @anewuser said. Adguard Turkish list get updates sometimes daily basis and most of the rules are generic. Adguard filters admin created Adguard Turkish list from Fanboy Turkish list. 
So, we have the correct list in uBO. Fanboy will forget about the Turkish list soon :) He only accepts English page submissions.

**Comment by vgturtle127** [comment]
I thought we weren't suppose to put feature requests and stuff in the issues?

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit

**Comment by anewuser** [comment]
@vgturtle127 As anybody can see, the maintainer and developer of this project has already seen and commented on this issue, and accepted it. Please refrain from commenting on other users' issues and pull requests from now on,

**Comment by vgturtle127** [comment]
@anewuser Sorry, there is a lot of conflicting documentation with this project.

**Comment by anewuser** [comment]
@vgturtle127 This wasn't actually a request for a new feature. The original poster reported a valid issue with an **existing feature** - the element picker -, and @gorhill agreed that blocking background images is **within the scope** of it and worth his time. 

There are guidelines against posting requests because a great majority of posters who suggest changes don't give convincing arguments for that or just base their requests on their own personal preferences or needs. There were so many invalid requests in the past that @gorhill almost gave up working on this project. We need to be grateful for what we have and that he's still willing to fix bugs weekly and add  sensible improvements to current features.

If you have a suggestion for *an improvement within the scope of uBlock Origin features*, you can open an issue with detailed and convincing arguments. However, it's only up to @gorhill to decide on that and he can close it without replying to you. It's his time and charitable work we're talking about. If he marks it as "invalid" or if you see other issues you don't agree with, take it easy and try to fork the extension by yourself or find another developer to work for you. Making comments like [the one you've made here](https://github.com/gorhill/uBlock/issues/1202#issuecomment-172698176) and on [this months-old pull request](https://github.com/gorhill/uBlock/pull/525#issuecomment-172697782) just add noise and animosity to the repository and our email inboxes.

**Comment by vgturtle127** [comment]
@anewuser Sorry, I was trying to tell them so they could close it, to reduce the maintenance stress. I won't comment from now on.
