### ISSUE TITLE
Default dynamic filtering rules for popular CDN's

### ISSUE THREAD

**Issue by zeridon** [gorhill/uBlock#1207]
Hello,

I've looked if this issue was already discussed but could not find it.

I suggest shipping ublock origin with noop dynamic rules for popular CDN's. This of course is prefered to be behind a toggle switch. Benefit for shipping those rules is that this will make quite some sites work out of the box (or at least easier to figure out how to fix some breakage).

in general i am proposing adding rules like:

```
* code.jquery.com * noop
```

For the more popular CDN's (not necessarily all of them, but at least the ones that host widely used libs like jquery, google api's, etc).

**Comment by Goderw** [comment]
No, especially google api's should have been blocked all the time... and should only allowed, if it is really needed. If you are not aware of what kind of connections are really needed for a special website to run, you don't have to wish others to reduce their blocking ability!

**Comment by gorhill** [comment]
Dynamic filtering is entirely under the control of users<sup>[1]</sup>, I do not plan to ship pre-build rules or subscription-based ruleset.

However one can share and publish all the rules he thinks are useful, and users can import them directly from the _My rules_ pane, is such case this is acceptable because this needs user intervention.

[1] Only exception is the two pre-build `behind-the-scene` rules, due to potential unforeseen breakage of basic browser functionality.
