### ISSUE TITLE
Popunder on Stream-Tv

### ISSUE THREAD

**Issue by Aleth08** [gorhill/uBlock#1209]
Getting popunders when playing any videos(generally allmyvideos.net video player) 
Site-http://stream-tv2.ag

**Comment by gorhill** [comment]
Alright, new rule concerning uBO's `popunder` filters -- otherwise my time will be abused: those who want me to add `popunder` filters will have to investigate and craft the filter to add, and provide me with an **exact URL** where I can confirm the suggested filter works fine, along with what I need to do to make the popunder happen. Add this information below when you have it.

**Comment by gorhill** [comment]
Actually, scratch this, someone else will have to step up to maintain a list of filters for uBlock. Anything else does not work, opening the door just a bit to maintain a limited set of (uBO-specific) filters and demands for filter issues will pile up exponentially.

Someone else will have to step up, it does not have to be me, crafting filter is simple, and the logger can be used by everybody to assist in this.

**Comment by IDKwhattoputhere** [comment]
I think I was able to figure out what @Aleth08 is talking about. However this doesn't fit here since it can be blocked using any blocker with EasyList. It's related to the domain areasins.com
@Aleth08 needs to report it here: https://forums.lanik.us/viewforum.php?f=62

About that someone who has to step up: I would do it but I'm afraid I might not be comfortable enough with the syntax.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/e1cb19d9ce25

**Comment by IDKwhattoputhere** [comment]
Much appreciated. :)
