### ISSUE TITLE
window.name

### ISSUE THREAD

**Issue by corvo7** [gorhill/uBlock#1228]
Hello:) Help to make a rule to block/replace the attribute window.name/tab name for all sites.In Adguard works well the rule is that:#%#window.name=null; for Аd Muncher:Windows.name = 'jsID=0';....What is the rule for uBlock?Help please,I did not get him to write.Thank you.

**Comment by gorhill** [comment]
Please describe the issue you are trying to solve -- I will decide what is the solution.

**Comment by corvo7** [comment]
Using the attribute "window.name", a website may give the current tab a name. The attribute "window.name" may get misused for marking your current tab. It remains the same over several websites until a site you visit sets a new value.

How to block "window.name" using uBlock? Above I gave examples of rules ,like I did with the help of Ad Muncher and Adguard. I did not get to write your own filter for uBlock. Don't know how.Thank you.

**Comment by IDKwhattoputhere** [comment]
You mean that it can be abused to track users like demonstrated here(?): http://ip-check.info

And you're looking for a way uBO can prevent that?

**Comment by corvo7** [comment]
Yes. You're right.I'm looking for a filter or a rule.

**Comment by gorhill** [comment]
> Adguard works well the rule is that: `#%#window.name=null;`

AdGuard's `#%#` allows any 3rd-party filter list to inject arbitrary javascript code into any web page. I do not plan on supporting such feature. The only javascript code uBO may inject in web pages is javascript code which is part of the project here, and which is personally vouched for by me.

I could add such resource as ...

    window-name-defuser.js application/javascript
    (function() {
        window.name = '';
    })();

... to the resource library, and then let users create a filter such as `example.com##script:inject(window-name-defuser.js`, but this sort of filter work only for specific filters, not generic ones, i.e. `##script:inject(window-name-defuser.js)` would not work, and also exceptions for such filters are currently not supported either.

If despite these limitations you still would use such specific filter, I will add the resource.

**Comment by RoxKilly** [comment]
@gorhill I'm a bit surprised by your answer. I thought your position vis-a-vis features is that uBO focuses on network request filtering because doing other things, even if they are related to privacy (eg: fingerprint protection) would result in feature creep. Isn't that the criterion you used to accept or reject features in the past?  Do you feel that this window.name feature falls into network request filtering category or has your position changed? (or perhaps I misunderstood your position to begin with)

**Comment by gorhill** [comment]
My answer is that no, I won support AdGuard's `#%#`. How is that feature creep?

**Comment by corvo7** [comment]
I understand you:).... It would be nice if you implemented this feature as written-in the specific filters. Тhank you!

**Comment by RoxKilly** [comment]
@gorhill sorry if I misunderstood. By "your answer" I wasn't referring to the particular implementation -- such as AdGuard's `#%#` -- but rather to the objective -- blocking sites from window.name read/write operations. Specifically:
> If despite these limitations you still would use such specific filter, I will add the resource.

I was surprised at your willingness to put in place the tools to block these operations given that they're not about network request filters. That's why I asked whether your position has changed or whether I misunderstood your position. I'm basically trying to understand what sort of features or improvements you find acceptable for this project, and what would be beyond scope.

**Comment by gorhill** [comment]
I tested <http://ip-check.info/> using the filter `ip-check.info##script:inject(window.name-defuser)`, and the result was ""window.name" has been anonymized". So just use

    example.com##script:inject(window.name-defuser)

To anonymize `window.name`, this will work as long as your prefix with a hostname -- as said as of now `##script:inject(...)` won't work without a specific hostname.
