### ISSUE TITLE
Toolbar icon do not update

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1230]
uBO's Toolbar icon do not update the status for the active tab when I toogle between already opened tabs.

Using GNU IceCat 38.5.2 (based on Firefox ESR 38.5.2)

**Comment by gorhill** [comment]
Unable to reproduce. I will re-open if and only if you make the case -- with all details -- that there is an issue with uBO itself and not something specific you did on your side. Next time please investigate further than provide two lines of text. Investigating means research that the issue is with uBO, look at browser console errors, open the debugger, etc.
