### ISSUE TITLE
Block media by size problems

### ISSUE THREAD

**Issue by zluca** [gorhill/uBlock#1258]
After [that commit](https://github.com/gorhill/uBlock/commit/a7a840500b4d9d474843edc74ba9584388017ff0) "Block media by size" no more works at this site: [tabun.everypony.ru](https://tabun.everypony.ru)
Can u give us an option like --forceParanoidMode or something? To block images when no content-length available.

Another problem is images under spoiler. If I dont open spoiler in first 1-2 sec images became unavailable. Here is screenshot and [url to check](https://tabun.everypony.ru/blog/crafting/147302.html) (U should revert commit that I telling before to see this)
![screenshot](https://cdn.everypony.ru/storage/02/43/83/2016/01/19/f4f6364e18.jpg)

**Comment by gorhill** [comment]
_"Block by size"_ works fine on `tabun.everypony.ru`, as per Network pane in dev console, the images do have a `Content-Length` header. However, even if this were happening, I would not try to fix this -- we have to keep in mind this is purely a convenience feature, and it will have its documented caveats, one of which will be that this won't work for resources for which there is no `Content-Length` response header. In such case, the "worst" is that uBO works as it has always worked, i.e. not blocking by size.

Regarding the other point, there is indeed an issue, which is the way uBO tries to identify correctly which images on the page where blocked due to _"Block by size"_ filtering, and not blocked due to static or dynamic filtering. I have a fix for this.
