### ISSUE TITLE
uBO replica UAdBlocker released on Google Webstore

### ISSUE THREAD

**Issue by theTomaku** [gorhill/uBlock#1267]
https://chrome.google.com/webstore/detail/comodo-uadblocker/hhnkmoijlinhobdagnchdhogdmedamce/reviews?hl=en

![](http://klikr.org/8bab02d260f5a218d2eff150d3e4.jpg)

**Comment by gorhill** [comment]
If people stumble onto such extension and believe it's should be removed, they should just report to the Chrome store, and/or warn other users about it in the _Reviews_ section.

**Comment by kcschan** [comment]
People other than you do not have the copyright (of ublock origin), so they would not be able to file a DMCA request to takedown the extension, since comodo does not show its source code(ublock origin is a GPLv3 licensed extension, so comodo's extension has to be under GPLv3 too):

https://support.google.com/legal/troubleshooter/1114905

**Comment by gorhill** [comment]
> they would not be able to file a DMCA request to takedown the extension

I wasn't thinking about a DMCA, and was just wondering whether there is a Chrome store policy against copycat extensions.

**Comment by anewuser** [comment]
@sowbug Can you clear this up?

**Comment by sowbug** [comment]
No need to escalate. Reporting it should cause the right thing to happen.

**Comment by lewisje** [comment]
The extension has since been removed from the Web Store.
