### ISSUE TITLE
Cosmetic filter exceptions not displayed in network request logger

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#127]
OS: Arch Linux x86_64
Browser: Firefox 37.0.1
uBlock version: 0.9.5.1/git master/3f7225
1. Go to ebay.co.uk
2. Open network request logger
3. Refresh
   As ebay.co.uk#@#.pushdown-ad is in uBlock filters-unbreak, it should be listed in the network request logger.

**Comment by gorhill** [comment]
Ok, I agree with the report -- I figured someone would ask for this..

However, to be clear: not all injected cosmetic filters are reported, only those which have an _actual effect_ on the page. So currently `pushdown-ad` would still not be reported for `ebay.co.uk` because I see they removed the class from their page.

**Comment by gomoku** [comment]
I hope you succeed asap @gorhill , as not seeing cosmetic exception filters in the logger looks not too neatly, I also suggest orange color of the highlight.

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/3573b6b32c3f5721eb606b1e0698ed66497ab080>.
