### ISSUE TITLE
Malwaredomains SSL

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1278]
"Malware domains (long-lived)" seems to be downloaded from `malwaredomains.lehigh.edu` and "Malware domains" from `mirror1.malwaredomains.com`. Both don't properly support SSL.
Does anything speak against changing the first or even both of those domains to `mirror.cedia.org.ec`?
https://www.malwaredomains.com/?p=3997

**Comment by Socialery** [comment]
```
https://mirror.cedia.org.ec/malwaredomains/justdomains
https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
```
for lazyness' sake

**Comment by TPS** [comment]
+1 :+1: @gorhill Especially since you specifically flag http-sourced filters?

**Comment by TPS** [comment]
@IDKwhattoputhere @gorhill Thanks!

**Comment by TPS** [comment]
@gorhill I think https://github.com/gorhill/uBlock/commit/3cc09cf03e9d893f5eebdd7021671d25b86ea22e missed `Malware domains (long-lived)‎ (www.malwaredomains.com): 0 used out of 2,069 [http]` which is https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt above.

**Comment by gorhill** [comment]
This one cannot be changed seemlessly, since the URL is the list key, i.e. changing the key would cause the list to become unselected for whoever is using that list.

The other thing is that I am considering removing that filter list from the list of stock filter lists: when you select it, there is only 3 hostnames used out of the 2000+ in that list -- not worth consuming space in the 3rd-party filters pane.

**Comment by rumorumo** [comment]
On a related note (but also a bit off-topic): since `pgl.yoyo.org` changed over to HTTPS weeks ago, browsers on Windows XP can't update Peter Lowe's Ad server list anymore because of a certification problem (https://community.letsencrypt.org/t/help-needed-windows-xp-support/8756). Until now I've got no answer from they about this.

Maybe a little change on uBlock side can do the trick... Should I open a new issue? Thanks.

**Comment by gorhill** [comment]
> Should I open a new issue? Thanks.

No. The workaround is for XP users to just use non-HTTP URL as custom filter list:
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext

**Comment by rumorumo** [comment]
@gorhill Thank you! I was trying something like that, but hadn't figured out just where to implement it (my bad...).
