### ISSUE TITLE
Regarding: "empirically verified that @brave is faster than Google Chrome with uBlock"

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#1279]
Just a place for me to comment about why I am skeptical of the results someone reported regarding uBlock Origin, in a tweet:

> Just empirically verified that [@brave](https://twitter.com/brave) is faster than Google Chrome with uBlock (fastest adblocker I know): 4s 457ms vs 5s 490ms to load site

Source: <https://twitter.com/maraoz/status/690036772697460739>.

There is no details about anything else than:
- The browser used was "Google Chrome".
    - No settings disclosed.
- The page which was benchmarked: <https://www.washingtonpost.com/news/speaking-of-science/wp/2016/01/20/new-evidence-suggests-a-ninth-planet-lurking-at-the-edge-of-the-solar-system/>.
- A warning by the author: "careful with cache!". This does not tell whether the cache was disabled/enabled.
- The reported result has been [referenced by the founder of Brave Software Inc.](https://twitter.com/BrendanEich/status/690297345271984129) as a pro-argument for the [Brave browser](https://brave.com/) -- so I consider the result is worth scrutinizing.

Following are details of my own benchmark.
- Benchmark tool: <http://www.raymondhill.net/ublock/pageloadspeed.html>.
- Web page benchmarked (same as above): <https://www.washingtonpost.com/news/speaking-of-science/wp/2016/01/20/new-evidence-suggests-a-ninth-planet-lurking-at-the-edge-of-the-solar-system/>.
- Intel Core i5-3570K, 8 GB
- Chromium: 47.0.2526.106 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit).
- No other extension installed. (important: other extensions can add their own overhead).
- No app installed.
- 3rd-party cookies disabled.
- Flash plugin disabled.
- Click-to-play enabled (so that plug-ins do not execute without user intervention).
- uBO 1.6.0b5
    - Fresh new install.
    - No settings changed.
    - Filter lists force-updated following install.
        - Waiting one minute for GC to get out of the way.

Results:
- Cache enabled: Average (valid): 1085.61 ms (11/16 iterations)
- Cache disabled: Average (valid): 1492.59 ms (11/18 iterations)

This is far from close to the results reported in the tweet: 5490 ms. This is why I am skeptical of the reported result -- I would like to understand why the discrepancy.

**Comment by Hrxn** [comment]
That was my initial reaction as well..

But I am generally a very skeptic person ;-)

From their FAQ:
>5. Why aren’t you using Mozilla’s Gecko engine on laptops?

>We were, under a partially sandboxed, multi-process architecture called Graphene. But we did a careful head-to-head comparison and by every measure, Electron/chromium won. We wish Mozilla well, but as a startup, we must use all sound leverage available to us. For web compatibility and in particular Chrome compatibility, this means chromium.

Electron is that Node/Chromium hybrid for cross-platform desktop applications, but it still is Chromium. That means they still use Blink as the rendering engine, the layout system is still the same, the network code is the same, the parsers are the same..

No magic sauce here. I mean, they could surely have improved something, but so far it's just a claim without any backing up. Give us the technical details!

But they are right of course regarding the fundamental problem of the web.
A good first step. Yay for disruption!

**Comment by zummuz** [comment]
empirically verified that Lynx is faster than Google Chrome with any extension.
Every browser on release is fast, like Chrome was, like Edge, plus synthetic tests for PR.
Benchmark should be done when the browser will have settings, bookmarks, history, at least. Download Brave to win a few picoseconds (which could be even not true), to watch its own ads, and being able to hide them after payment, because there will not be content on the internet without ads -  just nonsense.

**Comment by lewisje** [comment]
just another reason to facepalm at Eich

**Comment by gorhill** [comment]
To be clear, I don't have any qualm about the Brave browser, I can't say nothing about it I did not try it. 

My only interest for now is that uBlock Origin was used in a statement which claimed that it adds more than one second to a page load versus the Brave browser.

I've run enough benchmarks to make me skeptical of such claim -- I need to be able to reproduce, and to figure why that would be. But so far, the person who made the statement has been less than forthcoming about the details of his measurement (as in no feedback at all).

The measured overhead added by uBO to each network request is on average less than 200µs last time I measured. Now this does not take into account whatever overhead the browser API incurs by having to transfer code execution forth to and back from extension code, but compared to what uBO has to deal with, I figure that would be a fraction of its own overhead. Just to be safe, let's pretend uBO adds 300µs to each network request.

The measured web page shows about 160 network requests. 160 x 300µs = 48ms to each page load (in reality, keep in mind this "overhead" is completely paid back multiple times more by all the bloat _not_ being pulled by the browser as a result of blocking).

Let's be very safe and assume the worst and say uBO would add 100ms on that Washington Post page, compared to a blocker (built-in the browser) which somehow blocked just the same but assuming the best would add exactly 0ms overhead -- of course impossible but just to use the best case scenario for such browser.

Even with that exaggerated scenario biased in favor of the Brave browser, 100ms is far from the 1,000+ms reported.

**Comment by harshanvn** [comment]
| Test Site | Firefox | Brave |
  --------- ----------  -----
| http://tomshardware.com/ | Average (valid): 3998.62 ms (11/15 iterations)  Last reload: 4974.51 ms | Average (valid): 5146.50 ms (11/15 iterations)  Last reload: 4110.11 ms |
| -----------------------  | -----------------------------------------------------------------------  |  ---------------------------------------------------------------------- |

**Comment by gorhill** [comment]
@harshanvn Thanks for this, I had not yet the opportunity to try Brave for myself -- I don't know whether there are binaries for linux yet. These results makes more sense to me.

Question: is there currently cosmetic filtering in Brave?

If not, it may be better to compare with [cosmetic filtering switched off](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) for the benchmark page (`www.raymondhill.net`), to have more of an apple-to-apple comparison. Cosmetic filtering may add a measurable overhead to page load, depending of the benchmarked page. For example, benchmarking the Washington Post page above, same browser/settings/etc, with only the cosmetic filtering switch differing:
- Cosmetic filtering switched on: Average (valid): 701.77 ms (11/13 iterations)
- Cosmetic filtering switched off: Average (valid): 678.16 ms (11/14 iterations)

The more heavy the page the larger the overhead I expect.

Note: you do not need to include the "Last reload: [...]" part in the result, this part is of no importance.

**Comment by gorhill** [comment]
I am going to mention @bbondy in case he may want offer commentary about what is said here.

**Comment by bbondy** [comment]
Hi Raymond,

Big fan of uBlock, awesome work.

I’ve used your pageloadspeed.html tool a lot and I usually see Brave w/ Adblock only faster than Chrome w/ uBlock installed. But definitely not always.  Since Brave doesn’t have cosmetic filters yet, I disable that in uBlock for the tests.  Brave will get those soon.  I don't see the big difference like in your original post though.

I ran these right now on my OSX El Capitan Mac Book Pro: 10.11.1. 2.8 GHz Intel Core i7 16 GB 1600 MHz DDR3.  All extensions other than uBlock are disabled on Chrome.  Flash also disabled. 
Chrome: Version 48.0.2564.97 (64-bit)
Brave 0.7.11 libchromiumcontent:  47.0.2526.110 (64-bit)

tomshardware.com: (Brave seems consistently faster on my system)
Chrome+uBlock (no cosmetic) Average (valid): 2545.49ms (11/18 iterations)
Brave (no ad replacements) Average (valid): 2217.35ms (11/18 iterations)

washingtonpost.com: (they are equivalent ~50ms diff on each run)
Chrome+uBlock (no cosmetic) Average (valid): 530.09ms (11/14 iterations)
Brave (no ad replacements) Average (valid): 529ms (11/15 iterations)

For the original reported URL https://www.washingtonpost.com/news/speaking-of-science/wp/2016/01/20/new-evidence-suggests-a-ninth-planet-lurking-at-the-edge-of-the-solar-system/ (Brave is faster for me I but haven’t digged into why)
Chrome+uBlock (no cosmetic) Average (valid):  1212.15ms (11/12 iterations)
Brave (no ad replacements) Average (valid):  718ms (11/12 iterations)

Brave is Electron based libchromiumcontent + Node based so comparisons are better done with Chrome I’d assume.

There are some other differences as well, we are not strictly only an ad block plus filter parser library, as we also do disconnect like tracking protection.  The same types of rules can / might be applied already with various lists.

Other differences is with the lists that are applied, we aren’t comparing with the same lists.

I’ve seen reports of some sites being faster on Brave and with a different setup the same being faster on Chrome with uBlock, so not sure what to deduce for that.

When I do see a difference like that, re-running the benchmark does stay true for both parties for the particular site being tested. 

You can build Brave from source here:
https://github.com/brave/browser-laptop
It works on Linux too but I haven’t benchmarked on Linux, only on OSX so far.

Brave’s blocking is in this c++ lib:
https://github.com/bbondy/abp-filter-parser-cpp
and here:
https://github.com/bbondy/tracking-protection
Both are very young libraries though, I’m fairly sure they will get 2x+ faster with some small time with a profiler.

**Comment by bbondy** [comment]
Should have mentioned I tested with https everywhere enabled in Brave and didn't have that extension in Chrome.  There's an extra check in a n sqlite DB for each sub-resource for that.

**Comment by harshanvn** [comment]
> you do not need to include the "Last reload: [...]" part in the result, this part is of no importance

Thank You. I did update my original post, to be more concise. And couple of points to be noted!!

Hello Brain,

Thanks for your input, and Congrats to your entire for a great browser.
Sorry, i do not use Chrome. So, i had to test with my Firefox (default browser). So, this might be the reason, for the difference in results! Not sure though. Can you tell me what are the filter lists you used for uBlock. So, maybe i can test with the same lists.

**Comment by Hrxn** [comment]
@harshanvn you did not mention your OS, that may be relevant as well.

I'd be interested in doing some tests with Brave (on Windows) as well, but I want to know what I am installing beforehand.

@bbondy I guess the requirements listed here (https://github.com/brave/browser-laptop/blob/master/docs/prerequisites.md) are for building Brave, right?
Because I'm not installing Node just for one application..

So what am I getting myself with `BraveSetup.exe` from the [releases page](https://github.com/brave/browser-laptop/releases)? Because a 130 MB installer, that is quite something..

I grew up on the Internet starting with 28.8 modems, I still count bytes in the back of my head ;-)

**Comment by bbondy** [comment]
> So what am I getting myself with BraveSetup.exe from the releases page? Because a 130 MB installer, that is quite something..

Installer is bloated and we're trimming to probably less than half that size, but that's not very relevant to this thread.

You can get installers here:
https://laptop-updates.brave.com/latest/osx
https://laptop-updates.brave.com/latest/winx64

For Linux you have to build from source per above.

> And your results for Brave vary a lot with mine. Wondering what could be the reason behind it. I am behind a 40 mbps connection.

Probably the more important things are the difference in benchmarks on each machine vs across machines. 

> Thanks for your input, and Congrats to your entire team for a great browser. Its, a great initiative.

Thanks, super early but it's definitely interesting.

> Can you tell me what are the filter lists you used for uBlock. So, maybe i can test with the same lists.

It's just using easylist right now for the ABP filter parsing portion, but I think that adding more lists will increase the speed.  This depends on the site being tested though.

**Comment by Hrxn** [comment]
Uh, yes, but I already linked to those installers?

What I was trying to ask: Is this opaque goodness of automatic installation, worth 130 MB, bundled with, well, Node? Because I do not want to get myself a (system-wide) Node installation..

**Comment by bbondy** [comment]
Installer size discussion [here](https://github.com/brave/browser-laptop/issues/371), thanks

**Comment by gorhill** [comment]
Advices for those who want to run their own comparative benchmarks. Stick to these settings for  uBO:

- Default out-of-the-box settings -- **important**.
- Be sure that in the filter lists there are no filter list marked as obsolete (no need to force an update otherwise).
- Do not disable caching -- this introduce more noise (network latency) in the measurements.
- Prevent plug-ins (i.e. Flash) from auto-executing (again, this would add noise in the measurements).
- Best to measure using Chromium, because Brave is also closely related to Chromium.
- Always load the page load speed tool in a new tab (this means new process, cleaner slate).
- Be sure no other extension aside uBO are active -- they add their own overhead.
- Do not open the dev console.
- Do not open any of uBO's auxiliary pages (i.e. no logger, no dashboard).

Ideally I would like to see more results from others reported, I am having a hard time explaining results reported by @bbondy -- I argue that the biggest contributor to page load speed improvement is the amount of stuff blocked, whether this is done natively can't possibly be the top reason. The more people reports results, the better will be able to assess which results are anomalous in the bunch.

**Comment by gwarser** [comment]
Please allow `file://` protocol in benchmark, to minimize network and cache latency and allow proper "first load" benchmarking.

I often visit pages only once (links from reddit-like page) and I thing current benchmark results are bit skewed because they distribute large first load time on all reloads.
For example for now, benchmarking [washingtonpost](https://www.washingtonpost.com/news/speaking-of-science/wp/2016/01/20/new-evidence-suggests-a-ninth-planet-lurking-at-the-edge-of-the-solar-system/) using [my settings](https://github.com/gorhill/uBlock/files/111474/my-ublock-backup_1_31_2016._6_44_44_PM.txt.zip) page load time looks like this:

* with clean cache
* 5s, 1.8, 1.8, ...
* after browser restart 
* 3.5s, 1.8, 1.8, ... (still not all content cached?)
* go to dashboard enable/disable "uBlock filters – Badware risks‎" (trying to invalidate uBlock caches here)
* 2.4s, 1.8, 1.8, ...

**Comment by gorhill** [comment]
> 5s, 1.8, 1.8, ...

This is ok, the page speed load tool will discard "suspicious" values -- in your example 5s would be discarded.

**Comment by gwarser** [comment]
Yes, but uBlock is "special". On first load caches for generic cosmetic filters are generated. Because of this first load is slower. You cannot just discard this.

**Comment by gorhill** [comment]
> On first load caches for generic cosmetic filters are generated. Because of this first load is slower.

But that's just your hypothesis, that is unsubstantiated -- you have a benchmark supporting this? Regardless of what cosmetic filters is injected before `DOMContentLoaded` is fired, uBO will _always_ survey the whole page once `DOMContentLoaded` is fired.

**Comment by gwarser** [comment]
> you have a benchmark supporting this? 

I want to have. 

> Please allow file:// protocol in benchmark, to minimize network and cache latency and allow proper "first load" benchmarking.

It's known that sometimes ads "flashes" on first load. Theoretically even if uBO uses no additional resources, additional page content is visible for a moment and this content may use resources.

**Comment by gorhill** [comment]
> Please allow file:// protocol in benchmark

Done. I don't see the point though, uBO only deals with `http`/`https` network requests, and its content scripts won't be injected on anything else than `http`/`https` pages.

**Comment by Hrxn** [comment]
> It's known that sometimes ads "flashes" on first load

Could you quantify this a bit? How often does it happen? Can it be reliably reproduced?

Because I can't remember that I have experienced this, ever..

**Comment by BrendanEich** [comment]
@lewisje: "facepalm", really? Doesn't that violate the CoC? Oh wait, no CoC. :-|

Seriously, I have Hennessy and Patterson (http://www.amazon.com/Computer-Architecture-Fifth-Edition-Quantitative/dp/012383872X), first edition. Were you born when it came out? I know about hazards of single- and micro-benchmarks better than most, having gone through the JS engine perf wars.

The main point that made @maraoz's test credible and possibly (not demonstrably without more evidence) plausible is that Brave can and does use C++. We are not in the extension prison where only JS and certain APIs are allowed. This can matter, according to our measurements.

@gorhill Huge fan too, your work is inspiring. We try to go further and help the ecosystem, but who knows what will work. Both of us need to grow, to find out. Thanks.

/be

**Comment by Hrxn** [comment]
@lewisje What was that actually about? Dropping a comment without context? Maybe just try to say what you wanted to say, without the guesswork on the recipient's side?

CoC: I had to do more than just one search, because I don't think it's supposed to be 'Clash of Clans', right?
That was surprisingly hard to find, and yes, I definitely don't live under a rock. 
`CoC site:github.com -clans -clash -corruption -cthulhu` led me to something. But I already regret it..

Sorry for straying off-topic..

Regarding Brave: You should team up somehow.

**Comment by lewisje** [comment]
I'm thinking that CoC usually means "Code of Conduct" and although this project lacks a formal CoC (CONTRIBUTING.md gets into a lot of this, including a recently added link to a Discourse thread for discussions), and GitHub doesn't have a sitewide CoC, it does adapt the [OpenCoC](http://todogroup.org/opencodeofconduct/) from the TODO Group for GitHub, Inc., projects, and that might be what @BrendanEich was referring to; my earlier comment in this thread could be interpreted as a violation of **Be careful in the words that we choose** and also **Be respectful** (although, as a then-distant figure, it was just a little stronger than the "Thanks Obama" meme and would have been much ruder, a violation of [Wheaton's Law](http://knowyourmeme.com/memes/wheatons-law), if I had said it expecting Eich to read it, say if he were a collaborator or regularly posted in the Issues like I do).

As an indication of my lack of credentials, I had actually not heard of the textbook that Eich mentioned, and it took a while for me to figure out that the first edition was released in April 1990, a few months before I entered kindergarten; I get the point, however, that I don't have a good understanding of benchmarks that would allow me to provide an intelligent and independent critique.

---
I thought that the context when I made my comment would have been clear, but for the benefit of @Hrxn I'll spell it out: Brave sounded like a stupid idea from the get-go, similar to what Opera tried before version 8.5, only worse because instead of loading ads in a dedicated area of the chrome, it would take the effort to swap out various webpage ads with its own. Brave sounded like a less performant version of Chrome+ABP (because after all, ad content is *still* being downloaded, even if not the original ad content) with a sluggish UI (at least in my experience, Electron apps have been bloated and sluggish, like Atom and Slack, and I haven't even gotten Discord working, while various mainstream and not-so-mainstream browsers, using ordinary native or cross-platform UI toolkits, run just fine, on my five-year-old laptop), and therefore basically no reason for anyone to switch to it.

(On the other hand, I thought BlackBerry would stay dominant in the smartphone space, Maemo would be ascendant, iOS would remain a niche platform, and Firefox OS would become a serious competitor to Android in the developing world, and none of that happened; I also thought in 2004 that this would be the year of Linux on the desktop, that Windows would never seriously get better, that the American people would wake up and dump Dubya...you get the idea.)

When Brave was announced, I had been hoping that Eich would go on to do more great things after leaving Mozilla, and hearing that *this* was his next great project led to a facepalm.

(As for a similar effort, the Acceptable Ads Initiative, I actually think it is a good idea, because it was another hoop that the unwashed masses had to *opt out of* and therefore it might actually stave off the risk of adblockers rendering the ad-supported free-to-end-user Web non-viable; Brave, meanwhile, is something that people would need to make the effort to opt into, and it's more a serious effort than toggling a checkbox, the way the Acceptable Ads opt-out is.)

I believed that the case against the viability of Brave was so obvious that nobody who was neither invested in the company itself nor a member of the sensationalist tech press would take it seriously, so 24 days ago, I thought the notion that Brave was a stupid idea just went without saying.

On that day, after I read @gorhill saying that Chromium+uBlock Origin ran about 4 times as fast in his benchmark, with well-defined criteria, than it ran in the Tweeted ill-defined benchmark, I was thinking "wow, they don't even know how to benchmark" and that was "just another reason to facepalm at Eich"; I was surprised that gorhill, in his next post, didn't similarly dismiss Brave out-of-hand, and the post I was responding to hadn't ruled out the possibility that Brave would be competitive in Gorhill Style™ benchmarks that might also show it running about 4 times as fast as in that Tweet.

A major aspect of Brave's blocking engine that I didn't know about when I made that comment was that it didn't amount to bundling ABP into the browser, the way it was apparently done with Maxthon (or with the Pocket integration in Firefox), and that instead it's done with native code; I don't think knowing that would have changed my opinion, because it relied on my belief that gorhill had a solid benchmarking methodology and found something wrong with the official story, and not on any in-depth technical knowledge or pretension thereof.

---
There's no apology here, just an explanation to show that I wasn't some random shitposter. I think I'll try out Brave now to see whether its UI is as horribly bloated as I thought all Electron apps were, and for all I know, it might stick around in the future; I mean I thought that walled-garden app/extension marketplaces would never catch on, and neither would any complex mobile platform that didn't allow Flash, and yet they did.

**Comment by Hrxn** [comment]
Yes, at least in this context, on this site, CoC = Code of Conduct, I figured that much.

Reeks of unnecessary political BS, hence I said that I regret it already..

On the other hand, thank you for clearing that up, it makes sense now!

**Comment by BrendanEich** [comment]
No worries, a Picard facepalm meme can work now and then, and I've earned a few over the years. But not (yet) on this issue :-).

/be

**Comment by gorhill** [comment]
@lewisje 

> I haven't tried benchmarking it myself

Would you mind trying? The [page load speed tool](http://www.raymondhill.net/ublock/pageloadspeed.html) is quite easy to use. If you do benchmark, I recommend you ensure uBO is benchmarked using default, out-of-the-box settings (with no auxiliary pages opened, i.e. no logger, dashboard, no dev consoles). Front pages of high traffic sites are good pick.

I do not have access to a native Windows installation, so I still can't benchmark Brave myself. One thing I would look as complementary data to the benchmarks is a diff of what is blocked/not-blocked between a default uBO vs. a blocking Brave (like the diffs seen [here](https://github.com/gorhill/uBlock/wiki/Blocking-mode#raw-data)).

**Comment by CrisBRM** [comment]
@gorhill Wouldn't it be better to determine what filter lists Brave is using? Would make for a more apples to apples comparison.

**Comment by gorhill** [comment]
That's how I would test it first. Then according to the result I would investigate further with different benchmarks in order to try to replicate the results reported [here](https://github.com/gorhill/uBlock/issues/1279#issuecomment-177192778). I would also look into the sequence of events in the dev console, like when the `load` event is fired (which the page load speed tool relies on). Bottom line is I would investigate below the surface not just run benchmarks. Unfortunately it sucks a lot that I just can't do all this myself until there is a linux version available.

**Comment by harshanvn** [comment]
hello @gorhill 

while going through the commits  for [brave](https://github.com/brave/browser-laptop), i found an interesting [pull-request (to replace sqlite db with json db)](https://github.com/brave/browser-laptop/issues/673).

Here is the original bug about it in [httpseverywhere](https://github.com/EFForg/https-everywhere/pull/4110)! They say it benefits reading and parsing time a lot with this switching, like 268 ms vs 60ms.

Would you mind taking a peek at it and see if uBlock can also benefit from a similar move?

**Comment by gorhill** [comment]
@harshanvn This has nothing to do with the topic here -- on top of this such proposal is _completely irrelevant_ to uBO.

**Comment by harshanvn** [comment]
Ok Thanks.

**Comment by alexara** [comment]
@gorhill  
> Unfortunately it sucks a lot that I just can't do all this myself until there is a linux version available.

By now there's a Linux version available, which you can build yourself or download as a deb file: https://github.com/brave/browser-laptop

I am excited to finally see your comparable results.

**Comment by gorhill** [comment]
####  Summary

The claim in the first comment:

> empirically verified that @brave is faster than Google Chrome with uBlock

is debunked. Issue can be closed.

#### Benchmarked configurations

- Brave 0.11.1 [Block ads + HTTPS Everywhere disabled]
    - I disabled HTTPS Everywhere because it was not installed in other browsers, and the point of the benchmarks was to measure content blocking specifically.
- Chrome 54.0.2810.2 dev (64-bit) [No 3rd-party cookies + Flash plugin disabled]
    - For Chrome, the only extensions were uBO + uBO-Websocket.
- Nightly 50.0a1 (2016-07-30) [No 3rd-party cookies + All plugins disabled]
    - For Nightly, the only extension was uBO.
- uBO 1.7.7rc0 [default settings]

Only two tabs opened in each browser during benchmark -- the 1st tab being that of the browser settings, the other being the page load speed tool. Each distinct URL was benchmarked in a newly opened tab. Each benchmarked URL was benchmarked for all 3 browsers one after the other -- i.e. close in time so as to ensure the exact same web page as returned by the server.

After benchmarking all the choosen URLs, I closed and restarted all browsers and re-ran the benchmarks to ensure the results did not depart dramatically from the previous results obtained. I did that twice (hence three benchmark runs). If the results were better than the previous ones, I used the better ones. Where one browser got better result for a distinct URL, I observed that this was typically also true for the other browsers with the same URL.

#### Various observations

- The difference in average speed load between the various configurations is quite probably not a primary argument to choose one configuration over another. The point of this benchmark was strictly to address issue raised in the first comment.

- There is no cosmetic filtering in Brave -- hence dealing with cosmetic filtering is an added overhead in uBO which is not present in Brave.

- I wanted to gather some data about what is not blocked for a given browser setup + URL, but the context menu in Brave's dev tools is not available, thus I could not get that information (through _Copy All as HAR_ in _Network_ pane, which is supported in both Chrome and Nightly).

- At first I had in mind that the better performance in uBO versus Brave was related to the fact that uBO probably blocks more stuff with its default settings. However this does not appear to be a good explanation since almost nothing is blocked with the Wikipedia page (there is no ads, trackers, etc.)

- The results in the benchmarks for a specific computer can only be compared to each other, never to the results from other computers. Also. all extensions add overhead, hence why you should disable all other extensions if your goal is to measure a specific content blocking solution.

- If you think something is wrong in the benchmarks, do not ask me to run new benchmarks according to your requirements, run your own benchmarks, and share your own methodology and results -- i.e. do not outsource the burden of validating your ideas onto me.

#### Results

    https://www.washingtonpost.com/news/speaking-of-science/wp/2016/01/20/new-evidence-suggests-a-ninth-planet-lurking-at-the-edge-of-the-solar-system/
            Brave: Average (valid): 606.37 ms (11/12 iterations)
     Chrome + uBO: Average (valid): 416.88 ms (11/12 iterations)
    Nightly + uBO: Average (valid): 781.96 ms (11/18 iterations)

Observations: With Brave, the page's rendering is a bit broken for the above page -- possibly due to the fact that cosmetic filtering is not supported in Brave. If I disable cosmetic filtering in uBO for the page, the rendering becomes broken in exactly the same way.

    http://tomshardware.com/
            Brave: Average (valid): 515.95 ms (11/21 iterations)
     Chrome + uBO: Average (valid): 395.51 ms (11/18 iterations)
    Nightly + uBO: Average (valid): 729.52 ms (11/15 iterations)

    http://arstechnica.com/
            Brave: Average (valid): 514.47 ms (11/18 iterations)
     Chrome + uBO: Average (valid): 407.97 ms (11/12 iterations)
    Nightly + uBO: Average (valid): 597.99 ms (11/12 iterations)

    http://www.newyorker.com/
            Brave: Average (valid): 1377.51 ms (11/14 iterations)
     Chrome + uBO: Average (valid):  951.95 ms (11/13 iterations)
    Nightly + uBO: Average (valid): 1099.14 ms (11/14 iterations)

    https://en.wikipedia.org/wiki/List_of_country_calling_codes
            Brave: Average (valid): 561.21 ms (11/12 iterations)
     Chrome + uBO: Average (valid): 479.24 ms (11/14 iterations)
    Nightly + uBO: Average (valid): 897.16 ms (11/13 iterations)

**Comment by bbondy** [comment]
A few quick notes:
- We optimized some content scripts in 0.11.2 which will make for a lot faster base page load when shields are off (and therefore also when on)
- About box in Brave will show the Chromium version 0.11.1 was Chromium 51 based so it's a better comparison to use a matching Chrome version
- A lot of perf related things not specifically related to adblock (but having an effect on these tests) will be changing by 1.0 so it'd be a good time to retest at Brave 1.0 time (September timeframe).
