### ISSUE TITLE
The button does nothing when clicked on

### ISSUE THREAD

**Issue by ScoreUnder** [gorhill/uBlock#131]
I have placed the button on [the addon bar](https://addons.mozilla.org/en-US/firefox/addon/the-addon-bar/) but clicking it does nothing. Pentadactyl displays "-- MENU --" in the status bar for a split-second and then it returns to normal.

**Comment by WyohKnott** [comment]
Do you hide the navbar with Pentdactyl? If yes, it's a known issue with Australis.
See:
https://github.com/gorhill/uBlock/issues/112
https://github.com/chrisaljoudi/uBlock/issues/1315

I'm about to comment on that in https://github.com/gorhill/uBlock/issues/112 since I've just localized the source of the problem in Firefox code.

**Comment by ScoreUnder** [comment]
> Do you hide the navbar with Pentdactyl?

I do! I'll close this since it's a duplicate, then.
