### ISSUE TITLE
element picker: block with regular expressions

### ISSUE THREAD

**Issue by LawrenceBobrov** [gorhill/uBlock#1314]
I read a website listed below and it shows element based with randomly generated names:
If I use a element picker mode I get:
###ae4e143d4
and 
###a4b62a93
But this changes all the time.
I tried to use: ? and * to block multiple instances but this did not work.
Could you be so kind to help me with that? Is it possible with current version or requires an updated parser?
http://www.cnews.ru/news/top/2016-01-29_xerox_razdelitsya_popolam

**Comment by gorhill** [comment]
> I tried to use: ? and * to block multiple instances but this did not work.

Read carefully [the doc](https://adblockplus.org/filter-cheatsheet#elementhiding) about how to create filters. Cosmetic filters (aka element hiding filters) have to be valid CSS selectors.

Closing because this is not an issue about uBO, see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by aggat** [comment]
Try add to _My filters_ pane this filter
`||club.cnews.ru/templates/base/images/icons/status_offline.png$image,domain=www.cnews.ru`

If  you disable scripts from club.cnews.ru  (with uBO, NoScript etc.) you need one more filter
`||www.cnews.ru/inc/images/logocnews_.gif$image,domain=www.cnews.ru`

About ffilters better  ask [here] (http://forums.lanik.us)

**Comment by IDKwhattoputhere** [comment]
Is it an ad that you are trying to block? Because I don't see any ads with RU AdList.
