### ISSUE TITLE
uBlock not update filters

### ISSUE THREAD

**Issue by MajkiIT** [gorhill/uBlock#132]
I have problem with updating filters. I always see on panel of ublock, that filters Anti-Adblock Killer | Reek or Easylist have new version, but never on filters like this: POL: Adblock polskie reguly‎ or  Malware Domain List‎ . If I click clear cache and later apply then I see that number of filters increase. Where it may be a mistake?

**Comment by gorhill** [comment]
> biut never on filters like this: POL: Adblock polskie reguly‎ or Malware Domain List‎

Maybe because you have auto-update on?

To file a real issue about this -- i.e. to not assume there is a problem because you haven't see the lists marked as obsolete -- is to check when they were last time updated. Hover the mouse over the "purge cache" button and see when they were last updated. If you have auto-update enabled, it should not be higher than ~5-6 days **assuming** you let uBlock run long enough for its auto-update mechanism to kick in.

**Comment by marek45** [comment]
Ok thank you for your reply. I watched the update times.

**Comment by flyingzebras** [comment]
@gorhill I have "Auto-update filter lists." enabled in uBO 1.3.2 but the "Update now" button is not available (yellow), it is however available if I "purge cache" for at least one filter which will say "New version avalible" for other filters automatically.
