### ISSUE TITLE
xHamster filter rule is too generic

### ISSUE THREAD

**Issue by Prilu666** [gorhill/uBlock#1322]
The current filter against xhamster popunder is:
`|http://$popunder,third-party,domain=xhamster.com`

That means any links to `xhamster.com` that is opened in a new tab will close the originating tab if it is from another domain, even if the user **did want** to open that link in a new tab.

Take [that link](http://xhamster.com/xyz) for instance (invalid and SFW) and open it in a new tab (middle button click or right click then "Open in new tab"). It will close the current tab ... okay, it does not work on GitHub because it uses HTTPS, but do that from [here](http://jsbin.com/sasacibodo/edit?html,output).

Please refine that filter or make the popunder implementation aware of user intentions. It would help if the user could tell what to do in case of popunder (close the originating tab or let uBlock blocks its content without closing the tab, which could be a workaround for #1028).

Is there a way to disable a single filter without disabling a whole filter file BTW?

Browser: SRWare Iron 47.0.2500.0 (based on Chromium)
uBlock: uBlock Origin v1.5.6

**Comment by gorhill** [comment]
I removed it.

Someone else will have to maintain a filter list with those new uBO-specific filter options, writing/maintaining the code is already occupying my free time.

**Comment by IDKwhattoputhere** [comment]
Stop using SRWare Iron. It's closed source, gets important security fixes and new features later than other Chromium based browsers and the developer is only in it for the advertising money.

https://en.wikipedia.org/wiki/SRWare_Iron#Criticism
http://neugierig.org/software/chromium/notes/2009/12/iron.html

Google has removed the privacy-invading features like the installation-ID which Iron [claims](https://www.srware.net/en/software_srware_iron_chrome_vs_iron.php) is still present. All Iron does is disable some options in the settings menu.

You seem to be concerned about your privacy since you chose Iron over Chrome. I recommend you instead use Firefox or a Firefox based browser since it's the best option in regards to privacy.

I know it's off-topic, sorry. Just had to get it out there.

**Comment by Prilu666** [comment]
Thanks, let's hope someone will manage to find a less powerful rule.

@IDKwhattoputhere thanks, you're probably right, time to use something else.

**Comment by IDKwhattoputhere** [comment]
I currently don't get a popunder on XHamster. EasyList is blocking the script `/js/p.js` which seems to be the source of it. The filter in EasyList is `||xhcdn.com/js/p.js$domain=xhamster.com`.

> time to use something else

I'm happy that you agree. :)
