### ISSUE TITLE
[Feedback] ability to manually evaluate static filters

### ISSUE THREAD

**Issue by WyohKnott** [gorhill/uBlock#133]
Feedback regarding the last dev version (this is what dev versions are for, right?):
- there is no icon for the µBlock menu:
  ![screenshot-ublock0 2015-04-26 19-50-43](https://cloud.githubusercontent.com/assets/6247191/7338498/f5f1eb0c-ec4d-11e4-8210-5d79314b7ddc.png)
- I'm questioning the localisation of such functionality, the Activity log is already displaying what resources are currently blocked and which rule is blocking them in the second column. At the time of https://github.com/chrisaljoudi/uBlock/issues/10,  you did not have the Request log function, which you added in January 2015, so the bug was making sense. The few bug reports I've seen wanted to know in which 3rd party filter that rule is originating from. (but I think you said it was not trivial to implement).
- https://github.com/chrisaljoudi/uBlock/issues/1294#issuecomment-96375391 is not an advanced user, and the Requests log would not have helped him, because his question was: why is this thing not blocked, and the static filter evaluation would not have given him an answer.
- Thus, as you said originally in https://github.com/chrisaljoudi/uBlock/issues/10, I think such function would be best in the "Your filters" tab, when a user is trying is own filters.
- I'm not sure a popup is a good idea, it wouldn't work well on mobile device, a hidden panel taking the whole width once revealed might be better, especially since some URLs and rules are quite long.

**Comment by gorhill** [comment]
> there is no icon for the µBlock menu

I don't understand what you mean.

> questioning the localisation of such functionality

It's the best place in my opinion. That tool is mostly for advanced users investigating why something is blocked or not for somebody else. Again as another example, yesterday I had to investigate issue #142, however there was no way for me to reproduce the bug, due to geo-blocking. With this new tool, it ended up being a mere cut and paste of the reported URL to validate that something was wrong.

> not sure a popup is a good idea, it wouldn't work well on mobile device

It's a sticky popup: press the button, it stays up until you press the button again. But hidden panel is a good idea, I may take your advice, but not for this release.

**Comment by WyohKnott** [comment]
> I don't understand what you mean.

The icon on the far right, why is it empty?

**Comment by gorhill** [comment]
It's a font awesome icon. I figured if I use the uBlock icon it will be confusing, as it is already in the toolbar. That one button behaves differently than the button in the toolbar, it makes the popup sticky.

**Comment by WyohKnott** [comment]
Oh geez, I feel dumb, I thought it was just an empty div and the icon wasn't showing.

**Comment by lewisje** [comment]
I thought you had switched from FontAwesome to SVG, or maybe that's just a chrisaljoudi thing.
