### ISSUE TITLE
uBlock is blocking Firefox Hello

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#135]
Hi,
When uBlock is activated on Firefox (I'm on v37), Hello conversations is not working.
Even after whitelisted hello.firefox.com.

**Comment by WyohKnott** [comment]
I've played with this yesterday:

```
 * opentok.com * noop
 * tokbox.com * noop
```

**Comment by gorhill** [comment]
`behind-the-scene` scope is whitelisted by default, uBlock should not interfere with these.

Now if someone checked "advanced user" and un-whitelisted the `behind-the-scene` scope, as said in the doc, they are entirely responsible for the consequences.

**Comment by gorhill** [comment]
So I tried and as far as I can tell it seems to work on my side.

I have `behind-the-scene` scope listed in my whitelist pane, this ensures uBlock won't interfere with behind-the-scene network traffic, which I can see Hello uses.

**Comment by WyohKnott** [comment]
I have behind-the-scene whitelisted and still Hello refused to work before whitelisting these. In my config the opentok and tokbox weren't displaying ++ but -- before whitelisting.

**Comment by gorhill** [comment]
@WyohKnott 

> I have behind-the-scene whitelisted

I've never seen uBlock block anything when it is deactivate for a given scope, site, page. If you really think it happened, I will need exact steps to reproduce.

**Comment by WyohKnott** [comment]
Okay, let's do a test then.

Config: Nighttly +  0.9.5.1-dev.3
Test page: https://news.google.com/

Whitelist:
```
behind-the-scene
chrome-extension-scheme
chrome-scheme
opera-scheme
```

Test 1: clicking "Start a conversation" open the chat panel, which promptly displays "Something went wrong."
The request log from https://news.google.com/ does not show any new request while doing this.
"behind-the-scene" log shows https://loop.services.mozilla.com/v0/rooms being allowed.

Test 2:
I add
```
 * opentok.com * noop
 * tokbox.com * noop
```
to my rules.
Now "start a conversation" works fine.
The request log from https://news.google.com/ does not show any new request, but "behind-the-scene" shows connections to opentok and tokbox servers (the Telefonica owned company that provides the service for Mozilla).

So the requests to these servers are only displayed in "behind-the-scene" once I whitelist them in my rules, but not before, maybe that's why it doesn't "automatically" work.

**Comment by gorhill** [comment]
If I tried your steps with FF37 stable:

- `behind-the-scene` whitelisted.
- opened <https://news.google.com/>.
- opened logger, set to observe _Behind the scene_.
- click _Start a conversation_

This is what I observe in logger:

    other 	https://media018-sjc.tokbox.com/rumorwebsocketsv2
    xhr 	https://anvil.opentok.com/session/1_MX40N[...]H4?extended=true
    other 	https://loop.services.mozilla.com/v0/rooms?version=1430140756
    other 	https://loop.services.mozilla.com/v0/rooms/0d[...]m4
    other 	https://loop.services.mozilla.com/v0/rooms/0d[...]m4
    other 	https://loop.services.mozilla.com/v0/rooms?version=1430140755
    other 	https://loop.services.mozilla.com/v0/rooms
    other 	https://loop.services.mozilla.com/v0/rooms?version=1430140747
    other 	https://loop.services.mozilla.com/v0/rooms/45unkTmdoCo
    xhr 	https://hlg.tokbox.com/prod/logging/ClientEvent?_=45[...]e5

And Hello started up with no error.

So it seems the issue can be reproduced with Nightly only?

Given that when you add:

    * opentok.com * noop
    * tokbox.com * noop

This is evidence that uBlock is not evaluating the request in the proper scope, which means it's not looking up the proper whitelist directive which would prevent filtering. Now the next step is to find out which scope uBlock is looking up -- since you say you can't see anything for `news.google.com` or `behind-the-scene`, it does seem uBlock is looking up some other scope.

Stepping through [`onBeforeRequest`](https://github.com/gorhill/uBlock/blob/master/src/js/traffic.js#L48) would probably tell what is happening. I do not have Nightly installed... Are you willing to step through this code to find out in what context network requests are filtered?

**Comment by WyohKnott** [comment]
Well, yeah I've just learnt how to do that last week.

Here's the objects passed to this function during the whole exchange:
```javascript
{
  "hostname": "loop.services.mozilla.com",
  "tabId": "-1",
  "type": "other",
  "url": "https://loop.services.mozilla.com/v0/rooms"
}

{
  "hostname": "loop.services.mozilla.com",
  "tabId": "-1",
  "type": "other",
  "url": "https://loop.services.mozilla.com/v0/rooms?version=1430143616"
}

{
  "hostname": "loop.services.mozilla.com",
  "tabId": "-1",
  "type": "other",
  "url": "https://loop.services.mozilla.com/v0/rooms/GLB5WcwtC9E"
}

{
  "frameId": 0,
  "hostname": "hlg.tokbox.com",
  "parentFrameId": -1,
  "tabId": "79",
  "type": "xmlhttprequest",
  "url": "https://hlg.tokbox.com/prod/logging/ClientEvent?_=78bed4f5-7fb3-44c6-8d17-f574da8dd5b4"
}

{
  "frameId": 0,
  "hostname": "anvil.opentok.com",
  "parentFrameId": -1,
  "tabId": "79",
  "type": "xmlhttprequest",
  "url": "https://anvil.opentok.com/session/1_MX40NDgzNTg5Mn5-MTQzMDE0MzYxNjU3OH5FVG9sTDMySUpWelJ0TXliTmwrZ0duZ2l-UH4?extended=true"
}

{
  "hostname": "loop.services.mozilla.com",
  "tabId": "-1",
  "type": "other",
  "url": "https://loop.services.mozilla.com/v0/rooms/GLB5WcwtC9E"
}

{
  "frameId": 0,
  "hostname": "hlg.tokbox.com",
  "parentFrameId": -1,
  "tabId": "79",
  "type": "xmlhttprequest",
  "url": "https://hlg.tokbox.com/prod/logging/ClientEvent?_=f1d5c47c-a120-4678-b106-ea5eefd16c30"
}

{
  "frameId": 0,
  "hostname": "hlg.tokbox.com",
  "parentFrameId": -1,
  "tabId": "79",
  "type": "xmlhttprequest",
  "url": "https://hlg.tokbox.com/prod/logging/ClientEvent?_=ce6890fe-0bd7-4bc8-bf3c-7e1eee6ed253"
}
```

**Comment by gorhill** [comment]
Thanks, I think I found the issue.

The Hello app is occurring within a window which URL is something `about:loopconversation#[...]`. I do have `about:scheme` whitelisted, and this is probably makes the difference between working or not.

**Comment by WyohKnott** [comment]
Whitelisting ```about-scheme``` does make the trick indeed.

**Comment by bugreport0** [comment]
On stable FF37 with behind-the-scene already whitelisted, whitelisting about-scheme allows Hello to work again. Thanks for your great job!

**Comment by clement-escolano** [comment]
Hello !

I have the same issue with version 1.0.0.0
My whitelist is :

```about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
loopconversation.about-scheme
opera-scheme
```
Am I missing something here ?

**Comment by gorhill** [comment]
Did you check _"Prevent WebRTC from leaking local IP addresses"_? This setting disable WebRTC in Firefox, and unfortunately WebRTC is needed for Firefox Hello to work.

**Comment by clement-escolano** [comment]
Yes it was, I unchecked it and .... Thank you it's working now !
I guess I will have to uncheck this option every time I will use Hello.
Thank you again.
