### ISSUE TITLE
[Firefox Android] When clicking on the 'Restore from file...' button, I only get prompted to choose between camera / image apps

### ISSUE THREAD

**Issue by AmperAndSand** [gorhill/uBlock#1363]
When clicking on the 'Restore from file...' button in Firefox Android to import my uBlock Origin settings, I only get prompted to choose between camera / image apps:

[![screenshot of issue described above][1]][1]

I can't import the text file which contains my settings with those apps. uBlock Origin seems to be looking for an image file instead of a text file.

Details: I have Google Drive and ES File Explorer installed. This is on Android 4.4.2, Firefox for Android 44.0, uBlock Origin 1.5.5.

  [1]: http://i.imgur.com/MEZaSaI.png

**Comment by gorhill** [comment]
I tried with Android 5.1.1 + Firefox for Android 44.0  and on my side the choices for "File Upload" are:
- Camera
- Camcorder
- Documents

uBO uses standard HTML5 code to let the user pick a file:

    <input id="restoreFilePicker" type="file" accept="text/plain" class="hiddenFileInput">

Which is [reportedly supported on Firefox for Android](https://developer.mozilla.org/en/docs/Web/HTML/Element/Input).

Consequently the issue is likely a browser and/or an OS one.

**Comment by gorhill** [comment]
http://android.stackexchange.com/a/136725/150667
