### ISSUE TITLE
Add noop option to static filters

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#1365]
>"For phncdn.com we are only adding specific scripts to whitelist because their sites are know to misuse it for serving ads." - MonztA (EasyList author)

In this [filter] (https://github.com/gorhill/uBlock/issues/1357#issuecomment-182177249) we need to noop pornhub.com (and all domains), and the white list domains (phncdn.com, etc),  so EasyList can take care of them.

In uBO there is option ```important``` for static syntax which is used to override filters, but there are no ```[noop] (https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide)``` (contrary to the dynamic filter syntax) that can be used to make transparent filters.

Can you please add it?

**Comment by flyingzebras** [comment]
@gorhill Why?

**Comment by gorhill** [comment]
Because I don't know what you are trying to accomplish. The first thing to point out is what exactly is the primary, root issue.

**Comment by flyingzebras** [comment]
```
! phncdn.com fully white listed with this added to My filters and EasyList enabled
*$third-party,domain=pornhub.com
@@||phncdn.com
```

I want to phncdn.com to use EasyList rather than being white listed. Because EasyList will block some ads om phncdn.com.

**Comment by flyingzebras** [comment]
@gorhill I made it clear now.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Please have a look on this issue.

**Comment by gorhill** [comment]
> I want

Just use dynamic filtering, that's an excellent case to justify using dynamic filtering.

`noop` makes no sense here, you are assuming custom filters are treated in a different layer than 3rd-party filter lists: it's [not the case](https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock's-network-filtering-engine), statis filters are all handled in the same layer, regardless of whether they are custom or 3rd-party.

**Comment by flyingzebras** [comment]
@gorhill 

>noop makes no sense here, you are assuming custom filters are treated in a different layer than 3rd-party filter lists.

No I do not. I just saying that there are no options to do this with static filters:

```
www.pornhub.com * * block
www.pornhub.com phncdn.com * noop
www.pornhub.com pornhub.com * noop
```

Dynamic filters cannot be used in uBlock filters.

**Comment by gorhill** [comment]
> No I do not.

I can't understand this for you, you need to understand it yourself why it makes no sense. It will probably dawn on you if you try to resolve this riddle, which you raised when you asked

> corresponds to which static filters?

Push your investigation further and make your **full** proposal of how the static filtering engine would work to implement your idea of `noop` option for static filters. "Full proposal" means you actually go through detailing how the static filtering engine will handle such filter option. This is the bird view of how the static filtering engine currently works:

- If a block filter pattern-matches:
    - If an exception filter pattern-matches:
        - return **not-blocked**.
    - return **blocked**.

"Noop" in the dynamic filtering engine means "abort dynamic filtering". So "noop" in the static filtering engine would also be "abort static filtering", which means "do not block the network request", because there is no other filtering layer below static filtering.

**Comment by lewisje** [comment]
For custom filters, that option exists already, and it's called prepending with the `!` character.

**Comment by flyingzebras** [comment]
@gorhill >"Noop" in the dynamic filtering engine means "abort dynamic filtering". So "noop" in the static filtering engine would also be "abort static filtering", which means "do not block the network request", because there is no other filtering layer below static filtering.

Is uBlock filters used before or after other filters (eg EasyList)?


Is this documented in the wiki?

**Comment by lewisje** [comment]
I don't believe order matters: Filters are applied based on priority, and there's no way for filters at the same priority level to override each other (for example, a static blocking filter without `important` cannot keep another static blocking filter without `important` from working; a static whitelist rule *can* do that, but only because static whitelist rules have higher priority).
