### ISSUE TITLE
[Feature] tooltips for global/local columns explaining what clicking will do.

### ISSUE THREAD

**Issue by matthewlenz** [gorhill/uBlock#1391]
there are tooltips at the top but they don't explain what each of the 3 columns under global and local actually do.

**Comment by CrisBRM** [comment]
No.

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

People constantly flood the issues' tracker with feature requests such as this, and historically, the answer has been that the advancer user checkbox comes with a TUTORIAL, which is deemed '[required (reading)](https://github.com/gorhill/uBlock/wiki/Advanced-user-features)'.

**Comment by gorhill** [comment]
There are already tooltips for the top cell of both columns.

**Comment by matthewlenz** [comment]
There are two main columns with 3 sub-columns under each and those contain zero explanation.  Sorry for the feedback.

**Comment by gorhill** [comment]
The documentation for the `allow`, `noop` and `block` rules just can't fit into a tooltip, there is too much to be said about these. The doc can't be skipped.

**Comment by CrisBRM** [comment]
Everything is explained [here](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide). The examples give a clear indication as to what the three cells do (which should be obvious thanks to the colour coding), including noop.

**Comment by gorhill** [comment]
> should be obvious thanks to the colour coding

There is also the positional information: `allow` rules are on same side as the pluses which indicate allowed network requests, while `block` rules are on same side as the minuses which indicate blocked network requests.

**Comment by vanowm** [comment]
> The documentation for the allow, noop and block rules just can't fit into a tooltip, there is too much to be said about these. The doc can't be skipped.

"**Block globally**", "**Block on this website only (198 requests blocked)**"
Ta-da! That's plenty enough explanation that would fit into a tooltip. And no need re-read the documentation the size of "War and Peace" to find the explanation what left vs right column does after not using the extension for 6 month.

And no, ``noop`` is not explained enough. I still don't understand what it's for, and why it's called "noop" because according to [this definition](http://www.urbandictionary.com/define.php?term=noop) uB is not using this term properly ;) :D
If it's related to frames/embed, why not call it as such "frames" or "embed"?

Color coding is good for most people, but there are millions who can't see colors and require in more visual aid (tooltips come to mind).

Also, since this is UI related, a link to dynamic filtering explanation is missing at https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface

Thank you for this great addon and I hope one day it will become more user friendly.

**Comment by Hrxn** [comment]
> And no need re-read the documentation the size of "War and Peace" [...]

Seriously?

**Comment by vanowm** [comment]
Don't be silly, of course not :D
