### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by pablomassa** [gorhill/uBlock#1451]
Why not change the name of the product to not get confused with https://ublock.org? 

The average user can't tell the difference between the two products, this change will be beneficial on the long term, will make the project independent for the average users and will build a brand not carrying this confusing issue.

I think that this product is founded in valuable ethical roots compared to similar products and grow with a confusing name is problematic and should be addressed ASAP.

This is an UX issue, maybe this is not the right place to report it but is the only place that I found to discuss this.

**Comment by mmoura11s** [comment]
That would require a whole lot of work, but I do agree that it can be somewhat confusing to other users. That decision is up to @gorhill, though.

**Comment by Hrxn** [comment]
I don't see how you came to this conclusion.
Could be me, but I don't think it is confusing at all.

We have a name _A_ and a name _B_, and even if one does bear a resemblance to the other, they are clearly distinctive and distinguishable identifiers.

Don't just assume some intrepid and speculative interpretation on the recipients' side, because that is not how language works. We all know how to distinguish between _adjective_ plus _noun_, for identical  nouns but different adjectives.

**Comment by IDKwhattoputhere** [comment]
I've actually read comments of people who were concerned about the drama around uBlock and were considering using another extension because of it. I personally was confused too and went with uBlock Origin because I saw in the change log that more features were being added. Also there's a lot of drama being created on Reddit for example about Chris stealing the extension and other nonsense. That said I can't tell if a name change is worth the work that would come with it.

**Comment by gorhill** [comment]
I won't change the name -- it is too well established now.

It's unfortunate that ublock.org causes confusion, but in the end he is hurting himself more in the long run than he is hurting uBlock Origin, it's a conscious choice he made to scam people,<sup>[1][2]</sup> he will have to deal with whatever consequences there is doing so.

***

[1] "Please donate to help keep uBlock alive" - [source](https://www.ublock.org/)
[2] "Your support keeps uBlock development possible" - [source](https://donorbox.org/ublock)
