### ISSUE TITLE
Redirects on UploadRocket.net using data:text;html base64 popups

### ISSUE THREAD

**Issue by TiberianMagnus** [gorhill/uBlock#1472]
Finding some rather unusual activity on UploadRocket.net - when I go to a page such as:

http://uploadrocket.net/v8042ttbno36.htm

and I click the "Click for Free Download" button I'll get a popup that does three things:

1) It forces a URI into the new window:

data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD53aW5kb3cubG9jYXRpb249J2h0dHA6Ly91cGxvYWRyb2NrZXQubmV0L3Y4MDQydHRibm8zNi5odG0nOzwvc2NyaXB0PjwvYm9keT48L2h0bWw+

2) It reloads the same page again (the original URL) in the new window

3) It closes the tab where I originally loaded the URL from in the first place.

The basic steps are:

- load the UploadRocket.net URL I provided above.
- click the "Click for Free Download" button
- the new window appears with the URI data:text;html base64 redirect and reloads the same URL in the new window
- closes the original tab (because it opened a new instance)

Of course clicking that download button again does it over and over which is damned frustrating, not sure if anything can be done about this but it sure as hell would be nice to put a stop to it.

Firefox 45 ESR
uBlock 1.6.5rc0

Default filter lists + the 3 social ones inclusive

I use the no-popups: * true to cover popups on all sites but damned if this one isn't the worst offender I've encountered so far. Not sure if I just broke something or what but up till Saturday things were fine, not it's all hell breaking loose with just one click.

Any assistance (if possible) is appreciated, thanks.

**Comment by IDKwhattoputhere** [comment]
Oddly the popup  with the uploadrocket.net URL gets closed sometimes. Not sure if bug or not since the logger doesn't show any blocked popups.
Though this works (submit [here](https://forums.lanik.us/viewforum.php?f=62)):

`http$domain=uploadrocket.net,script,third-party`
`@@||api.solvemedia.com^$script,domain=uploadrocket.net`

Maybe try getting into [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering) to do this easier and without needing to ask someone.

**Comment by gorhill** [comment]
> I use the `no-popups: * true` to cover popups on all sites

This switch does not work for popunders -- because it blocks popup unconditionally, and closing popunders unconditionally make no sense..
