### ISSUE TITLE
disable canvas fingerprinting in browser and console error in ublock

### ISSUE THREAD

**Issue by joksik** [gorhill/uBlock#1509]
Hi, i use Opera Developer 37.0.2171.0 and ublock 1.6.6 (release from yesterday) under Ubuntu 16.04 beta2. i check the bug in another stable Opera so it`s not the browser bug. i always run opera with flag: 

--disable-reading-from-canvas

to block canvas fingerprinting i check this solutions on https://www.browserleaks.com/canvas and it works. browserlekas say that canvas is disable (the same solutions is in another chromium browser SlimJet - in settings). when i run browser with this flag i have error in ublock console:

Uncaught securityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-orgin

it`s normal under linux? because before i use Windows and Opera and i run Opera with the same flag and i never seen this error

**Comment by gorhill** [comment]
The issue is not within uBlock Origin, as clearly shown from the error in the console, and as shown with one simple quick test with any other extension. The issue is in `extensions::setIcon`, which code is executed as a result of calling `chrome.browserAction.setIcon()`, which is browser code, not uBO code. 

Report to Chromium developers.

**Comment by slingamn** [comment]
A workaround is to pre-render the browser icons as `ImageData` objects constructed from a literal `Uint8ClampedArray`, as implemented here: slingamn/simpleblock@ac87f3d1d03a4
