### ISSUE TITLE
Estadão Buscapé Ad

### ISSUE THREAD

**Issue by 0x3333** [gorhill/uBlock#1532]
In http://www.estadao.com.br/ website, with uBlock enabled, no ads are shown. But some functionalities from the web site became disabled, like the image carrossel in the bottom of the page.

If you allow the script from their own domain(estadao.com.br) the functionalities starts working again, but an Ad from Buscapé is shown in the bottom of the page.

I added this hostname in my filter list to block it:
http://templates.buscape.com/dynatemplate*

**Comment by lewisje** [comment]
That's not a hostname, it's a URL pattern: A hostname would be like `templates.buscape.com` and that's probably not granular enough for blocking.

**Comment by 0x3333** [comment]
Sorry, I said hostname but I mean URL pattern.
I added:
`http://templates.buscape.com/dynatemplate*`

**Comment by anewuser** [comment]
@0x3333  You've ignored and deleted the template text that appears when you create a new issue.

That text isn't there just for decoration. Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what list has blocked your request, and go talk to the list maintainers instead of creating issues here.

Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
