### ISSUE TITLE
Issue with 1.6.8

### ISSUE THREAD

**Issue by absynteZero** [gorhill/uBlock#1544]
Hello
 i use ublock origin and i love it.

windows 7x64
firefox x64 45.0.1
ublock origin 1.6.8

since last update i've issue with reload button.

so many script are loaded and if i set a script, the button reload appear but , tab continu to load and new script are loaded. the issue is when new script load after setting not saved, the button reload disappear.

Other thing, i dont understant global setting?? and green setting? i use only "all" in red and page by page, grey setting script by script.

<http://www.noelshack.com/2016-14-1460064364-captureublock.png>

^^
[Uploading mes-regles-de-filtrage-dynamique-ublock_03_04_2016_à_23_53_31.txt…]()

!!!! very impossible de not have pub on this page, can you do something? French tv live.

[http://www.d8.tv/pid5323-d8-live.html#](url)

Thanks

**Comment by RoxKilly** [comment]
If you wish to use the advanced options effectively, I recommend you have a look at [the Wiki](https://github.com/gorhill/uBlock/wiki).  To understand the dynamic filtering settings, consider [this page](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide)

You addressed a few different topics in your post. It's typically a good idea to make one specific inquiry when you open a new issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

Filter issues need to be reported at <https://github.com/uBlockOrigin/uAssets/issues>.

**Comment by absynteZero** [comment]
hey!

thanks to answer,

i use and understand without problems the advanced setting but i say that green and global setting. i know what it is but there are no interest to use it, i think that less experienced users have to use simple interface. green setting and global setting are not usefull , never . it's evidently more secured to set tab per tab and script by script or simply use simple interface./

i've just give you a french link to see live french tv where i'ts impossible to set in advanced setting the filters to block vidéo pub.

**Comment by RoxKilly** [comment]
@absynteZero Different people have different needs.  I find global settings useful.  For instance, I don't always deny connections to facebook, so I have set a global red (deny) setting for it.

I also find green settings useful, because there is are a couple of domains that I do not want to interfere with, such as the address of my LAN router.  

The dynamic filters' primary purpose is not to block ads.  It is to control which domains you connect to. For ad-blocking, I use the 3rd party block filters and the element picker tool (the eye dropper icon next to the logger icon in the popup UI).

I don't see any ads on the page you linked, but I am not able to test it fully because the video requires a plugin that I don't have.

**Comment by absynteZero** [comment]
yes, differents people, differents needs.

for the ling i give you, it's in the video that there's pub. so xithout player, you can't see. in France, we don't need any plugin to play this, i've using flashplayer and shockwave. The player is from the TV page and i think it's the problem. 
For you i don't understand why you need plugin...
