### ISSUE TITLE
Unable to play a video when Ublock is enabled

### ISSUE THREAD

**Issue by aabadh** [gorhill/uBlock#1624]
Web browser: Firefox 46.0.1
Operating System: Windows 7 professional 32 bits
Ublock Origin 1.7.0

Steps to reproduce:

1.- Open This link: http://www.azteca7.com/a-quien-corresponda
2.- Go to te section "Programas Anteriores"
3.- Choose a video

Actual results:

1.- The browser opens a new page, but the video doesn't start.

Expected results:

1.- The video should start.

Notes:

If you disble ublock origin, the video starts, but an addon appears without an option to skip the addon.
Same problem with Chrome

**Comment by anewuser** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what list has blocked your request, and go talk to the list maintainers instead of creating issues here.

Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
I can't get the video player to work **even** without uBO installed:

![a](https://cloud.githubusercontent.com/assets/585534/15178973/ed38a062-1746-11e6-8e69-518d24cf318f.png)

So this is unrelated to uBO -- or at least the site should work without any blocker before being able to tell whether uBO is interfering or not.
