### ISSUE TITLE
depositfiles.com

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#1628]
Hi, 

[ads](http://i.imgur.com/xePBQen.png) by inline script an popunder on `http://depositfiles.com/files/4w1qi55mf`
see https://forums.lanik.us/viewtopic.php?f=62&t=28822

Thanks!

**Comment by IDKwhattoputhere** [comment]
Hey @SMed79
Maybe you didn't see it but there's now a repo just for filter issues:
> For **filter-related issues**, report at [uBlockOrigin/uAssets.](https://github.com/uBlockOrigin/uAssets/issues)

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by SMed79** [comment]
Sorry, I did not know.

**Comment by MarkTheFucker** [comment]
This is a filterlist issue.

**Comment by IDKwhattoputhere** [comment]
@MarkTheFucker If the ads and the popunder can in fact only be filtered with uBO but not ABP compatible filters then it's correct that @SMed79 asked them to be added to uBO's filters.

**Comment by gorhill** [comment]
`||dep.gitcdn.pw$subdocument,domain=depositfiles.com`

**Comment by MarkTheFucker** [comment]
uBO supports ABP compatible filters, so that's out of the question.

**Comment by IDKwhattoputhere** [comment]
> uBO supports ABP compatible filters, so that's out of the question.

I didn't say it doesn't.

> No popunders are loaded, only one inline script and no ads are loaded either

Read carefully:
@MarkTheFucker If the ads and the popunder can in fact only be filtered with uBO but not ABP compatible filters then it's correct that @SMed79 asked them to be added to uBO's filters.
### If

> thing is ABP blocks basic ads and stuff, switch to uBO and you wont have such issues

Filters for e.g. popunders still need to be added in some cases if current filters don't match (also see screenshot below).

> and you will have tons of filters to add via 3rd party filters which ABP hardly provides any at all.

Actually you can add a lot of filter lists in ABP too and in the end EasyList is the most important one anyways.

> no ads with uBO - https://i.gyazo.com/cca6d0fb583df3232bbe968349912a80.png

Not blocked in standard configuration which most users will have.
![](https://cloud.githubusercontent.com/assets/16030872/15257338/2c5fe132-1946-11e6-8d54-82b7c8ebd964.png)

**Comment by SMed79** [comment]
> switch to uBO and you wont have such issues, and you will have tons of filters to add ...

@MarkTheFucker You're a clever man, shows us how to block ads on : 
```
http://jeu.info/
http://www.manga-news.com/
http://gum-gum-streaming.com/
```

**Comment by gorhill** [comment]
The issue here is specifically about `depositfiles.com`.

**Comment by SMed79** [comment]
Sorry for off topic, it will not happen again.

**Comment by MarkTheFucker** [comment]
@IDKwhattoputhere well your statement sounded like you did imply that. and no ads are not loaded in my case, not a single one actually because you all are using default config.

I have added and am running all the 3rd party filters including regional filters + 5 custom filters, so there is no chance in hell a single ad would bypass, did you check the pic I linked ? You wont single one pop up or get bypassed, that makes it a filter list obviously.

So in total I have 185,835 network filters ＋ 95,457 cosmetic filters. It's all the same, you add single filters with basic configs, while I activated them all found in the list and addionally added 5 custom ones, so by doing this, I have covered more than 90 % of the websites from passing ads on my system. 

Standard config is standard, it hardly covers notorious websites, you have to know that.

**Comment by MarkTheFucker** [comment]
@SMed79 Thank you for the compliment. I will do it when I feel like it but not now as I only visit English language websites and not the ones you usually mention or post.

**Comment by IDKwhattoputhere** [comment]
> well your statement sounded like you did imply that. 

> that makes it a filter list issue obviously.

You have to distinguish between a filter list issue that can be resolved in EasyList and one that won't because the filters are not compatible with ABP. That's the reason why https://github.com/uBlockOrigin/uAssets exists and why it's no issue to post websites where EasyList won't block those ads (due to lack of ABP's features) there.

>I have added and am running all the 3rd party filters including regional filters + 5 custom filters

> So in total I have 185,835 network filters ＋ 95,457 cosmetic filters. It's all the same, you add single filters with basic configs, while I activated them all found in the list and addionally added 5 custom ones

> Standard config is standard, it hardly covers notorious websites, you have to know that.

I don't see your point. Of course I can subscribe to all filter lists and block 3party frames and scripts. But we're discussing uBO in standard configuration. It's standard because it works in most cases without breaking too much. Most users use it so uBO filters are added when standard configuration isn't enough.

> so there is no chance in hell a single ad would bypass, did you check the pic I linked ? You wont find a single one pop up or get bypassed

Try `gum-gum-streaming.com` for example. Your setup won't block those ads. At least not without blocking inline scripts which breaks the videos.

> not now as I only visit English language based websites

There are also English language websites out there that use Goyavelab's service and similar ways to circumvent adblockers.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/506cf093618d
