### ISSUE TITLE
[Off-Topic] uBlock censorships people?!

### ISSUE THREAD

**Issue by CHEF-KOCH** [gorhill/uBlock#1659]
Hello, 
since you not have any public email I need to open an ticket for this which is pretty sad. Some people contacted me and saying that they are blocked from the Wiki and in general here on the uBlocks project without any reasons. I not want to call names but you can just look at the history and see which guys worked on the Wiki and other parts of this project.

I want to reveal the truth about this because if that is true I not recommend anymore to use this extensions and boycott you. It's nothing against you in person but I not want or can tolerate this - I'm very serious about this. 

I hope this is somehow an mistake or something or maybe an permissions issue from GitHub itself, but I hope you can 'fix' and re-think about this. Sadly I need to write all this now public, but someone must do the first step. I think if people really want to contribute on this fantastic project then let them. Otherwise give them real reasons why they are blocked/banned.

I also hear that some reviews was manipulated or even more worse deleted because they may wrote some criticism or other opinions about this extensions, I can't tell for myself but I never saw this - but I this was coming from people which I normally can trust and there is no reason why they should lie about such things. 

Again I hope we can somehow deal with this so that we fast can close this and may see such behavior as an accident ....

Greetings 
CK

**Comment by IDKwhattoputhere** [comment]
Trolls get banned. Should be obvious why that is.

About the reviews: Seems like Mozilla (I assume that's the store you're talking about) deletes some negative reviews. I have seen this happen with a lot of extensions (legit and shady ones). I contacted one of the Mozilla people that work on AMO about it on Reddit but they couldn't help me.

**Comment by CHEF-KOCH** [comment]
This isn't about trolls or someone which try to destroy the project - it's more about why someone which really wanted to help get's blocked without any reasons - and without any contact details it's impossible or hard to get an answer. 

I'm unsure if the original developer not have such a control if he maybe contacts secretly Mozilla or other pages to ask them to remove it, since this may get consequences. Remember the story someone posted a guide on YouTube to unblock xyz page which AdBlock and he gots an letter from a [youtube adblock](https://www.leetchi.com/c/tobis-tricks) story to remove this video and to pay something for it. 

No matter what I want the answer from the developer or the one which have the ability to maybe do this. It's not against you (thanks anyway for the answer/time!) but I know all of this myself, and I'm long enough here to understand what is okay and what is a no-go for a project.

**Comment by IDKwhattoputhere** [comment]
Obviously there's a reason (right or wrong) why whoever you're talking for got blocked. Maybe it's not obvious to them or maybe it was a misunderstanding.

I would be careful with spreading such conspiracy theories without any backup. That's not something you just say and then expect people to take you seriously and not think you're a troll. My guess is that Mozilla uses a system to automatically moderate reviews and maybe that system has a high rate of false positives when trying to detect malicious reviews. I know that they do have an issue with fake reviews (see early reviews for AdBlocker Ultimate which btw is developed by an advertising company (just do some digging and you'll see)) so maybe they also have an issue with malicious negative reviews so they are aggressive with removing them.
That story about the YouTube video is likely different from this case (I'm German btw). The video was against the law.

**Comment by kintpuash** [comment]
Mozilla deletes reviews that violate their review guidelines. In particular there is one user repeatedly spamming negative reviews for the last year. Nearly all of them violated Mozilla's guidelines. In retaliation the user goes to other extension reviews and copy pastes the same baseless accusations.

Better question is why Mozilla hasn't banned the account yet.

**Comment by gwarser** [comment]
Gitoffthelawn selfpromotion: https://github.com/gorhill/uBlock/wiki/FAQ/_compare/efd0fb85d4e022ddca3361c3e640370484f907a3...30b3e7689ef32185ff5f94d5d2714a8e1eae8d1f

**Comment by CHEF-KOCH** [comment]
@IDKwhattoputhere  I don't know why you come up with Mozilla, I said _on some pages_ this is not only Mozilla. But I know what you want to say!*

*I think that gorhill not answer on this also tells something about him, together that there is no contact information for something important like this.**  Of course spam here and there but that's what we all need to handle.

Selfpromotion really? - because he wrote an good hint about an 'alternative' GUI then some people here have really _problems_, it's not even for another project it's forked and directly designed for uBlock. I think it's worth to mention, of course you can see this in another light but seriously what's wrong just let it stay. It's not that he gets money too from mention this. You say gorhill do all this in his free time, so other peoples too.

Btw in contribute it's not even mentioned that hints to other (for uBlock explicitly designed) stuff is disallowed. 

I searched now a lot of the history, and comments from other people are all mostly good to go, blocking them is seriously the wrong way to get 'friends'.

**Comment by IDKwhattoputhere** [comment]
@kintpuash Now that you mention it I remember from the Reddit thread that some reviews were removed because they violated the guidelines. That would be an explanation for the disappearing negative ones.

@CHEF-KOCH I come up with Mozilla because that's one of the two major stores and they have issues with reviews. Maybe you should be more specific.

What this tells about Gorhill is that he doesn't want to waste his time with groundless conspiracy theories and people he already banned for wasting his time. He doesn't post contact information because he doesn't want to be contacted about drama like this.

We found the reason why the person is banned and it doesn't need to be mentioned in CONTRIBUTING.md. IMO it's just common sense to not advertise your project by just going and editing the wiki. I mean maybe it's a bit harsh to ban them but that's his call after investing countless hours into this project (much more than anyone else). Asking to advertise in the wiki would have been the least thing to do which would have created spam but in the end it did anyways in the form of this thread.

I can't comment on your "friend" part because I don't know what that's supposed to mean and you're being very vague. I mean it looks like you're not here to make friends either with those indicated accusations.

**Comment by CHEF-KOCH** [comment]
I think it's not drama to talk about censorship, as mentioned I not found something which is worth to block people from the project. Wasting time is it if someone like to contribute and his change get's reverted + as an 'thank you' he gots an ban.

I wonder how you can ask something if there is no possibility to contact him. You see you arguments to 'protect' him for no reason makes less sense. I know what you try here, but it not explains anything because I said this is not only 'one single' user issue because he may trolled/spammed or destroy the project, there are several people, if I'm wrong show me the commits which 'deserves' a ban, I not found anything (of course I not watched everything). There is no excuse about this, revert would be okay with an message about possible unloved self-promotion but not an entire exclusion from the project, we all may make mistakes, but it also not changes the fact that it's not mentioned so I see no problem at all. 

I think it's no advertisement to give people alternatives, but you may see this maybe different. It's no conspiracy theory and I'm also not here to protect someone like you, why you talking are you the author here? I doubt. At some point you should accept that there are maybe mistakes done instead of making it more orst to find arguments. You and I not know everything behind the story so the only conspiracy is done by you saying they trolled, no one trolled, it's maybe what you want as an reason but see the commits they are okay.

Again this is not wasting time to talk about possible censorship or guidelines for contributing.

**Comment by IDKwhattoputhere** [comment]
I don't understand all of what you're saying and I think this is true vice versa. I only feel like you're getting more hostile and you're being very vague. Two reasons why there's nothing going to come out of this thread so yes, it is a waste of time.
I'm repeating myself here but obviously going ahead and putting advertisements (which is what advertising something is) into the wiki of all places is not simply "contributing". What else would there be about this story? While a ban might be harsh, and I do feel sorry for who did this might have meant well, it is deserved in this case and, again, there's no need to mention this in CONTRIBUTING.md for it is common sense.
What you're doing is making up conspiracies ("this also tells something about him", "maybe contacts secretly Mozilla") and denying it just makes you look more like a troll and makes everyone take you less serious. More so since you're also making threats and talking about boycotts instead of just raising attention to the issue you see. You're not doing whoever you're talking for a favor.

**Comment by gorhill** [comment]
> no answer from the developer

I marked the issue as invalid -- this means "No" to the question in the issue title.

Please read and respect [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by CHEF-KOCH** [comment]
https://gist.github.com/CHEF-KOCH/63d5744e7f4012d62674bfad32431ef6

**Comment by kintpuash** [comment]
Seems clear from your language Chef-Koch, that you are the same user as firebreathing spamming reviews. Stop the bullying.

**Comment by CHEF-KOCH** [comment]
Nope I'm not this person, even if, we still talking instead of revealing the truth. I would trust the author if I really would get something useful from him but he and the community makes it impossible to talk about such things. 

I'm thinking to report this project since it's unclear if it's true or not then he is forced to answer if he want or not. GitHub, Google and especially Mozilla not supporting such behavior, if someone not want it, then he/she should close it and mention that only xyz in a whitelist get access to the project, this would be smarter as blocking people randomly after they may commit something. 

As said I'm done here, the community protect someone which not want to answer on serious things like this, then I need to rise this on a higher level. It's not my fault. If you not care then you will if this project get's a freeze, just because 10 minutes time to answer on this. I hope this is worth the trouble you get now.

**Comment by lewisje** [comment]
Here I thought the user in question had been blocked for a heated debate I had gotten into, for which I thought *I* would be the one blocked from the repo; as for the problem of self-promotion, was he supposed to instead put that UserStyle enhancement under some neutral username, like "uBlockDeluxe"? It's an interesting enhancement and I regularly use it when I use Firefox (like in the Tor Browser), and I'd adapt it for Chrome if I ever bothered to use the Stylish extension.

I do know at least that blocked users *can* sometimes come back, like @davidhedlund.

**Comment by IDKwhattoputhere** [comment]
@CHEF-KOCH You say this is a serious issue but IMO it's completely ridiculed because of all the reasons I explained above. You're simply making a drama out of this. You say we're making it impossible to talk about it while you're the one ignoring the points I addressed. The points could also explain why you're not getting a response from Gorhill. You're saying the community defends him while it's only a handful of people stating their view. You're talking about revealing the truth without actually providing any example cases which would be the first step.

You honestly think Mozilla, Google or GitHub are going to do anything about this? It's not a violation of their terms to ban people from a project so they aren't going to care. And in case you didn't notice you're already using threats again.

@lewisje The discussion could be the reason, we don't know. Got a link? I don't believe the name was the issue ([look at my repo headline](https://github.com/IDKwhattoputhere/uBlock-Filters-Plus#ublock-filters-plus)).

**Comment by lewisje** [comment]
This is the discussion I referred to, in which he thought I was trolling: https://github.com/chrisaljoudi/uBlock/issues/1445

**Comment by kintpuash** [comment]
@CHEF-KOCH Upon reflection I'm inclined to agree you are not the same user whose reviews are being deleted on AMO. Rather you are driven by similar misconceptions. The extension has over 5 million users. That a handful have made themselves a nuisance is expected. You seem to be unaware of the history of these users. And what you have read is misinterpreted.

The developer's time is valuable and he doesn't owe anyone anything. This extension exists in a sea of similar solutions that attempt to monetize their user bases. That you would seek to damage the reputation of a developer who has given so much of his time  and skill based on half baked interpretations is tragic.

**Comment by harshanvn** [comment]
@gorhill 
Can you please weigh in your thoughts. I think there is lot of mis-interpretation going on here, and he is threatening to shut down the project :(

See below quote (proof that he said it) - pulled from [other thread..](https://gist.github.com/CHEF-KOCH/63d5744e7f4012d62674bfad32431ef6)

> I hope the trouble is it worth, I will not recommend this extension anymore as long it's not clear if that was an accident/mistake or something. And if I found out that this was without any good reason I will report this addon directly over Google, Mozilla and GitHub to shutdown a project which works against people just because the developer may not accept other opinions.

**Comment by IDKwhattoputhere** [comment]
Why wouldn't you let him report it? Banning people isn't against GitHub's (or Mozilla's or Google's AFAIK) terms. He is violating GitHub's terms though.
> Verbal, physical, written or other abuse (including threats of abuse or retribution) of any GitHub customer, employee, member, or officer will result in immediate account termination.

- https://github.com/site/terms

His accusations are a complete joke and he lacks any proof to back himself up. He's a troll, nothing more.

**Comment by harshanvn** [comment]
> Why wouldn't you let him report it? Banning people isn't against GitHub's (or Mozilla's or Google's AFAIK) terms. **He is violating GitHub's terms though.**

Oh i see the terms now. 

However, this should be stopped before he does/posts more accusations. It will just eat everyone time.

**Comment by CHEF-KOCH** [comment]
If the ban was given without any good reason then it's censorship. Even if you project creator because otherwise you simplky can mark it as private repo, mention in readme/contribute an special line or the simplest way, lock the project down and restrict access only to whitelisted users. 

> Copyright and Content Ownership
> F1. We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours. **However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories.** 

This also applies to content someone other provide for the project. 

Tell me how I can prove something if it gets immediately deleted? 

> All of your Content will be immediately deleted from the Service upon cancellation. This information can not be recovered once your account is cancelled.

That#s why anyway need to contact them, because it's unclear if they also clear content from ignored/banned users too.

**Comment by IDKwhattoputhere** [comment]
You're again wrong on all points.
1. Banning someone does obviously not violate rule F.1. The banned person can still view and fork the repository.
2. Rule D.2 (which you misquoted) has nothing to do with this case. It only applies to an account being canceled, not a ban.
3.
a) You didn't even provide any reason for a "sorry" to be needed. If anything you should provide a "sorry" to Gorhill, the community and GitHub and refrain from harming this project.
b) Explain how a developer without contact information for groundless accusations like this is not trustworthy. He's reachable for issues with the software which is all he needs to be reachable for.
c) You did violate the terms. The proof is right there ([e](https://gist.github.com/CHEF-KOCH/63d5744e7f4012d62674bfad32431ef6#file-censorship-of-ublock-L15
).[g](https://gist.github.com/CHEF-KOCH/63d5744e7f4012d62674bfad32431ef6#file-censorship-of-ublock-L28).).

**Comment by CHEF-KOCH** [comment]
1) A banned person can't see/edit his own stuff since you not get the chance to change or react on it. 
2) The ban affects the account because you not have any access, the only chance would be to re-create another account (fake account) I don't think GitHub want this. 
3) You're not the author and you already made your statement, they are wrong, because you're not know anything about the background you're a fanboy which want to useless protect a person you not know. I not longer argue with you because you don't even have any access here so it's not worth to speak against a wall. 
4) the only one which trolls is you, you intercept me and think you#re smart but you ignore the things I've said. Instead of accepting it you making it even more worse, seems you really have to much time. You are a small light here and not any of the main commiter, even if you still can't prove anything, but I do can, if 5 or more people now hitting the thread how it helps? We not need to talk about bans because it's clear that the author is rude. An workaround would be as mentioned, to set a warning, because as i now said several times we may all have 'bad' days. 
5) He is not reachable, as we can see here. The community useless fights for him, I respect this, but also shows intelligence level, instead of let it stay you response and think you're smart with a quite you not understand. 
6) You now can't my own words use against me, it's not about me, I already said this, this is about the wrong behavior and some rude people. 
7) I already explained my motivation, seems you can't read and just pick up what you think it's a 'proove'. 
8) I have a lot to show but why should I involve other peoples in this, that you can troll on them too like you try with me? 
8) I already said I contact now GitHub and others, I wrote in my Gist that I gave gorhill 14 days time to clear this.
9) Of course I need permission if I speak or post stuff from other people, BECAUSE IT'S PUBLIC and as said I normally had never did this public but it's impossible without anything, makes sense or? Someone must do the first steps.
10) I already gave up, I normally had not answered on this but the ignorance here and the tolerance to support this seems higher as I thought.

**Comment by IDKwhattoputhere** [comment]
1) But why does it matter what you say? What matters is if it's against the terms like you claim but it's not.
2) Once again you don't seem to know what you're talking about. There's a difference between being banned from a repository and having your account canceled by GH. Like I said:
> otherwise the ban option couldn't even exist since it would create a conflict with the rules. I can't see how you don't understand that.

3) My posts are not wrong since you don't provide any proof for your accusations. Ad hominem won't get you anywhere either.
4) Sounds like you're talking about yourself here. ;)
Who are the main commiters? I'm quite active here if I say so myself but you probably didn't bother checking that.
Insulting Gorhill won't help you. How is he rude? If anything you're the one being rude (not that it matters who's rude or not).
5) With your English skills you still have the guts to insult me and the rest of the community? You are the one misinterpreting here which I can't really blame you for since there's obviously a language barrier but insulting others for your failure is pathetic.
6) You still don't explain what wrong behavior or what rudeness of which people. And yes, this is more and more becoming about you because the issue itself is getting moved into the background because of you continuing to argue without proof and insult for no good reason.
7) What's your real motivation though? I mean if you wanted to "reveal the truth" then just go ahead and provide proof.
8) The only one who looks like a troll is you. And the reason why to provide proof publicly is transparency which is what you claim you're fighting for. Apparently only if it suits you?
8) (No.2?) GitHub won't care since the only rule violation is you giving an ultimatum.
9) You don't need permission to post something they did in this repository.
10) Of course since you are only making open accusations. What response did you think you'd get?

**Comment by Hrxn** [comment]
To answer the question in the issue title: No.

**Comment by CHEF-KOCH** [comment]
Your're a so shining light that you are not even listed on https://github.com/gorhill/uBlock/graphs/contributors. Thanks I'm done here, useless to talk with fanboys which not get the real point and trying to find useless stuff to waste my time.

**Comment by IDKwhattoputhere** [comment]
I got plenty of issue reports here, I comment plenty and I'm active enough to be a member of https://github.com/uBlockOrigin. You on the other hand... But that doesn't matter at all. The only one wasting time here is you. How about you come back if you have something to back you up?

**Comment by Hrxn** [comment]
> Thanks I'm done here, useless to talk with fanboys which not get the real point and trying to find useless stuff to waste my time and protecting someone even if they not even know any of the background.

You're just indulging in some fantasy...

**Comment by seanrand** [comment]
> I think that gorhill not answer on this also tells something about him, together that there is no contact information for something important like this

There's a simple explanation for this, which is also obvious for people who've been following uBlock development for a while.
Part 1: gorhill doesn't provide contact information because he wants discussion about uBlock to happen in public.
Part 2: the GitHub issue tracker generally isn't the place for discussing policy/meta topics like this. Technical, on-topic bug/feature/development discussions are welcome and get responses from gorhill, but he has every right to block disruptive users from his repository or lock discussions that go nowhere. This isn't censorship, it's community management.
