### ISSUE TITLE
wetteronline.de

### ISSUE THREAD

**Issue by 3ckH4rd** [gorhill/uBlock#1666]
is there any way to block the ads oon wetteronline.de?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by IDKwhattoputhere** [comment]
Why'd you delete the text that was there when you opened the issue? Why didn't you read [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) like you were told to? This is not a uBlock Origin issue. This is a 3rd-party filter list issue. The least you could have done is report it in the [correct repo](https://github.com/uBlockOrigin/uAssets).

Filters:
`||wetteronline.de/*/base64.`
`||cnt.wetteronline.de^`

Report your issue and the filters here so that it can be fixed: https://forums.lanik.us/viewforum.php?f=90
