### ISSUE TITLE
filters that start with || and end with |

### ISSUE THREAD

**Issue by IsraeliUser** [gorhill/uBlock#1669]
uBO ignores the || at the beginning or the | at the end.
For example: let's say you want to block the English Wikipedia logo.
https://en.wikipedia.org/static/images/project-logos/enwiki.png

Use the filter: `||en.wikipedia.org/static/images/project-logos/enwiki.png|`
uBO ignores the || at the beginning.

Use the filter:` ||en.wikipedia.org/static/images/*/enwiki.png|`
uBO ignores the | at the end.

**Use the filter:** ` ||en.wikipedia.org/static/images/*/enwiki.pn|` **(without the _g_ at the end)**
**uBO blocks the logo, although it should not.**

uBlock Origin v1.7.0, Firefox 46.0.1 64 bit,

**Comment by lewisje** [comment]
It turns out that this creative interpretation of ABP syntax also leads these two filters from the [EasyList Adware Filters](https://easylist-downloads.adblockplus.org/adwarefilters.txt) supplementary list to be considered invalid:

    ||*-a.akamaihd.net/a24/gsd.html?$third-party
    ||*-a.akamaihd.net/a24/scripts/gsd.js?$third-party

It ignores both the initial `||` and the `*` after that, even though this should mean "any subdomain of akamaihd.net that ends with -a, and any subdomain of that".

**Comment by gorhill** [comment]
> this creative interpretation of ABP syntax also leads these two filters [...]

It was not an interpretation issue, it was an implementation one. uBO can already deal with these filters, it's just that the wrong code path was taken for that specific case.
