### ISSUE TITLE
Unable to change settings after being redirected

### ISSUE THREAD

**Issue by HitomiTenshi** [gorhill/uBlock#169]
This bug happens to me every time I get redirected to a site that has settings I saved.

Video: http://a.pomf.se/zizsig.webm

It is reproducible with every site that redirects you to sites that contain saved settings. For the sake of simplicity I'll give you the links needed to reproduce what has been shown in the video.

Main site: http://dailyindiegame.com/
Save settings here.

Site where you get redirected: https://bitpay.com/invoice?id=VSx8q7dk7T5XA3C51Gr11M

**Comment by gorhill** [comment]
When you say "change settings", what do you define as "settings"?

**Comment by gorhill** [comment]
Ok, the hostname for the first site is `dailyindiegame.com`. The hostname for the second site is `www.dailyindiegame.com`.

`www.dailyindiegame.com` inherits the rules from `dailyindiegame.com`, it does not have it own rules. You can't _noop_ `www.dailyindiegame.com` because it is already _noop'ed_ by its ancestor hostname `dailyindiegame.com`, thus it is pointless to _noop_ what is already _noop'ed_.

**Comment by HitomiTenshi** [comment]
Shouldn't `dailyindiegame.com` and `www.dailyindiegame.com` be exactly the same thing? My problem was that I couldn't revert `3p-script noop` and `3p-frame noop` after being redirected. Going through the site and refreshing it didn't unlock the buttons.

**Comment by gorhill** [comment]
> Shouldn't dailyindiegame.com and www.dailyindiegame.com be exactly the same thing?

That doesn't work in general. In case of ambiguity, how would uBlock know whether the user wants to _remove_ a rule for a parent hostname (or grand-parent hostname, etc.) or _add_ a rule for the current hostname? Safest bet is that all rules are for the current hostname, never for something else.

> My problem was that I couldn't revert

The proper action is to force a scope change (visit `dailyindiegame.com` instead of `www.dailyindiegame.com`), or go into the rule editor to manually edit the parent hostname's rules.

**Comment by HitomiTenshi** [comment]
Okay, thanks for the help!
