### ISSUE TITLE
Too High CPU Usage

### ISSUE THREAD

**Issue by Aexyn** [gorhill/uBlock#1692]
Not what Expected from uBlock Origin..

Chrome :Version 51.0.2704.79 (64-bit)

![screenshot from 2016-06-06 11 18 01](https://cloud.githubusercontent.com/assets/2553128/15812954/4d743e78-2bd8-11e6-828f-1c11929f9c75.png)

**Comment by Hrxn** [comment]
Too high? What do you mean, or what did you expect?

Could be possible that this stems from the set of extensions you are using..

**Comment by IDKwhattoputhere** [comment]
It says `0` under CPU. :confused: 
Maybe you're talking about memory usage? Because that seems to be quite high but apparently all your extensions consume a lot of RAM for some reason. I usually get less than 75% of the memory consumption you get on Chrome with uBO (using Windows 7) and HTTPS Everywhere uses more even though uBO has over 150.000 network, over 70.000 cosmetic and some dynamic filters.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Anybody who want to make the case there is a memory usage issue will have to do a whole lot more than posting a screenshot. You need at least a very detailed methodology, starting from when you launched the browser, and exactly **all** steps in between, and even better, apply the same steps with another similar blocker for comparison.

Re.: <https://github.com/gorhill/uBlock/wiki/Notes-on-memory-benchmarks,-selfies>.

**Comment by Hrxn** [comment]
HTTPS Everywhere is a bad extension anyway..
