### ISSUE TITLE
Suggestion: Canvas Defender

### ISSUE THREAD

**Issue by lordraiden** [gorhill/uBlock#1696]
Add to ublock the same functionality that canvas defender has

[Important to read] https://multiloginapp.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/

https://multiloginapp.com/canvasdefender-browser-extension/

**Comment by anewuser** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

> ### Before you submit
> 
> 1. Submit **bugs/issues only**.
>     - Bugs occur, I will fix them.
> 1. _One specific_ issue per submission.
> 1. The logger is the tool of choice to use to help diagnose issues.
> 1. Do **NOT**:
>     - Submit pull requests.
>     - Submit design ideas.
>     - Submit feature requests.
>     - Submit "revolutionary ideas".

**Comment by lordraiden** [comment]
Sorry,  Where can I submit ideas? What is the channel

**Comment by anewuser** [comment]
There's a link in the first line of the  https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md you can use to discuss ideas with other users and ask for support.

But the rule of thumb is that, if uBlock Origin doesn't have a feature yet, it's because it's out of its scope or the developer just doesn't have the time to implement it.

He has this policy because otherwise this repository would be filled with all kinds of requests every day, and he already spends too much time working to keep uBlock Origin working for us.

You can always try to convince him to change something by providing solid evidence that it's worth the work, but don't take it personally if requests tickets are closed without further comments, especially when it's something that already can be done with other extensions.

**Comment by gorhill** [comment]
Anti-fingerprinting features are best left to a dedicated separate extension -- which would requires constant work.

**Comment by lordraiden** [comment]
This one doesn't  require constant  work because it works in a different way 

It is explained here https://multiloginapp.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/

**Comment by lordraiden** [comment]
It's not a blocker it just change your fingerprint randomly

**Comment by gorhill** [comment]
Feel free to work on such anti-fingerprinting extension if you think see this as an easy project.

**Comment by lordraiden** [comment]
Ok

**Comment by gorhill** [comment]
https://github.com/ghostwords/chameleon

**Comment by lordraiden** [comment]
Thanks.

I have read about chameleon but I think they took to complex approach which is to block the fingerprinting.
What canvas defender does is "simply" to randomize some parameters every time you click on it (it could be done automatically) so you can only be tracked for a short period of time since your ID is different and changes.

Honestly I don't know how complex is to code this to replicate it, but it sounds much more easier and quick than what Chamaleon addon is trying, since it looks like it just introduce some alteration in the parameters so the fingerprint is different every-time, probably is more complex to know how to do it than actually doing it.

As I said how the app works and why is not a fingerprinting blocker is explained here https://multiloginapp.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/ 

It is just and idea, I don't know how to code it so I posted here in case you find it interesting.

**Comment by gorhill** [comment]
When I said _"require constant work"_, I refer to creating and maintaining a multi-platform extension, not the just the js code to counter one _specific_ fingerprinting technique. There is no point cramming one specific anti-fingerprinting scheme in uBO without cramming all of them, and this assuming I would agree with such [feature creep](https://en.wikipedia.org/wiki/Feature_creep) at all. Anti-fingerprinting is best solved by a dedicated extension, and this requires constant work.
