### ISSUE TITLE
Incognito mode Google Chrome

### ISSUE THREAD

**Issue by caio123** [gorhill/uBlock#172]
start google chrome with  -incognito

and this happen

[link to crappy site removed]

**Comment by gorhill** [comment]
And "this" is...?

See <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include>.

**Comment by caio123** [comment]
![immagine](https://cloud.githubusercontent.com/assets/12250344/7473154/305162e0-f339-11e4-81fc-a238646c0963.png)

ublock origin 0.9.6.0
chrome 42.0.2311.135  and  39 or 40 now, i don't remember exactly the version I have in the office
Windows 8.1 / Windows XP

**Comment by gorhill** [comment]
Yes, by design.

Normal/incognito modes both use a separate instance of uBlock, because uBlock is designed to work in [_split_ mode](https://developer.chrome.com/extensions/manifest/incognito#split).

Not using split mode causes [this issue](https://github.com/chrisaljoudi/uBlock/issues/1225), which only solution is to use split mode.
