### ISSUE TITLE
Add a quick toggle for behind-the-scene requests in Advanced mode

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uBlock#1734]
I think that a quick toggle for behind-the-scene requests could be added to the popup interface in Advanced mode : given that behind-the-scene requests can't be blanket-blocked permanently, or else lots of things won't work, such as browser and extensions updates, and also many downloads will fail, but at the same time lots of stuff can go through that the user has no control on - I'd propose to add a quick one-click toggle exposed in the popup interface, that will basically do the exact same thing as commenting/uncommenting the behind-the-scene line in the Whitelist tab, only quicker and more accessible.

Since this is something that average users won't use, I'd limit it to the Advanced mode just like dynamic filtering.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@acrobat1 i read your other thread. why not just remove the whitelist entry and then add dynamic rules to allow all behind-the-scene requests, and then add a static filter to block favicons?

**Comment by berrythesoftwarecodeprogrammar** [comment]
also firefox has the ability to block favicons through about:config

**Comment by acrobat1** [comment]
@berrythesoftwarecodeprogrammar : thanks for the hint, I must admit I did not know about the about:config preference.

As for your suggestion for letting in only selected behind-the-scene requests using dynamic rules, looks tricky to me : how do I set specific rules for updates, for instance? As gorhill pointed out in the wiki, these requests are kinda unpredictable and un-whitelisting them can (will) break all sorts of things - that's why he decided to whitelist them by default.

@gorhill : with all due respect, I think that such a feature could still make some sense (*at least in Firefox*, given its quirks/bugs in handling favicon requests) : more or less "advanced" users can figure out what is going to break when blocking bts requests, so they could allow them occasionally only when needed and then blacklist again once done.

For instance (please note that I'm not "advanced" in any way..) I know that browser updates and extension updates will fail in Firefox, so I could allow bts requests just in order to update.
I've also noticed that many (all?) downloads go trough bts requests, and  videos won't work either in most cases.

Of course I'm aware that what I'm asking for can be done already in the Whitelist tab, this request was just about making things quicker by exposing that switch in the popup interface and making it a one-click deal.
But if you think it's not worth the time, I understand.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@acrobat1  i used to block behind-the-scene by default and slowly add whitelisting rules for things. but its hard. i ended up allowing all xhrs, images and 'other' from behind-the-scene because it breaks too much browser functionality. 'other' breaks downloading of files. 'xhr' breaks addon updates, addon functionality, rss feeds, OCSP requests and other things. and 'image' is used for favicons etc. but i guess if favicons dont matter to you then you could just 'noop' or 'allow' every behind-the-scene request type except for image just block it.

at one point i did the opposite of what you want because i wanted to block all behind-the-scene image requests but allow favicons. i think i created some rules like this:
```behind-the-scene * image noop
behind-the-scene * xhr noop```
etc. and then static filters like this:
```
*$image,domain=behind-the-scene
@@*favicon*$image,domain=behind-the-scene
@@*logo*$image,domain=behind-the-scene
@@*.ico$image,domain=behind-the-scene
```
that would block all images from behind-the-scene but allow those with 'favicon', 'logo' in them, or the .ico extension (i monitored the logs and found that favicons didnt always have the same filename)

you could flip my rules or experiment. or just tell me what exactly you want re: behind-the-scene. if you want to allow all behind-the-scene but block images then just add `behind-the-scene * image block`. or if you want to allow images based on conditions, use the static rules

this whole post assumes that behind-the-scene is whitelisted
