### ISSUE TITLE
Cosmetic filter for ad in dynamically created iframe

### ISSUE THREAD

**Issue by dhowe** [gorhill/uBlock#1740]
### Describe the issue

uBlock does not block ad in dynamically created iframe
### One or more specific URLs where the issue occurs

http://rednoise.org/dyn-iframe.html  (a test-page for this issue)
### Screenshot in which the issue can be seen

![screen shot 2016-06-20 at 7 11 11 pm](https://cloud.githubusercontent.com/assets/737638/16192453/fc316974-371b-11e6-989e-60fa98efc065.png)
### Steps for anyone to reproduce the issue
1. Visit http://rednoise.org/dyn-iframe.html
2. Notice that the ad inside the iframe (with id="adunit") is visible
3. Right-click on iframe, element picker is not shown in context-menu ([ticket](https://github.com/chrisaljoudi/uBlock/issues/88)) 
### Your settings
- Browser/version:  Version 51.0.2704.84 (64-bit) OS X
- uBlock Origin version: 1.7.2
##### Your filter lists

Default filter lists

**Comment by gorhill** [comment]
I see that uBO's content scripts are not injected in the dynamically created `iframe`. The chrome API does say:

> Content scripts will only be injected on pages when their inherit URL is matched by one of the declared patterns in the matches field. The inherit URL is the URL of the document that created the frame or window.

However, in the current case it appears the `iframe` URL is `about:blank`, as seen from within the iframe, though it appears the empty string from outside. There is an option in the manifest format, `match_about_blank`, to force content scripts to be injected into `about:blank` frames as well.

Adding this option though for uBO's content scripts does not fix the issue: I see uBO's content scripts correctly injected into the `iframe`, but then having the parent document reset the iframe using `document.open`/`document.close` trashes all injected content scripts and runtime data in that frame -- the document is resetted.

I see the issue for other top blockers on Chromium: ABP, AdGuard, AdBlock. In a real world case (this is a proof of concept here), the solution would be to create a filter which targets the `iframe` itself, not its content.

So I will decline trying to find a fix for this -- I do think it's possible to fix, but the amount of code rewrite at hand is way too large for such a trivial case.<sup>[1]</sup>

The test case works correctly however on Firefox -- due to how the API is designed.

***

[1] It's a solution I have considered in the past: to make the content scripts able to inject _themselves_ into anonymous iframes. This is already sort-of done by injected scriptlets, they will propagate to source-less child frames.

**Comment by dhowe** [comment]
Understood, thanks. As this is sort of an important use-case for us (we cannot just block the entire iframe), I will go ahead on an implementation (if you're interested in seeing a PR for ublock, leave a msg below)

**Comment by CapSel** [comment]
I've found that on subpages of joemonster.org a script generates an iframe for youtube and for the aD. I can't block iframes because this would block youtube videos that I'm interested in. Generated iframe contains images with src set to data:base64 (or something like that).
It seems that it's new "revolutionary" technique for "beating" ad blocks.

**Comment by jjohns71** [comment]
I confirm what CapSel is saying, I get an iframe ad load on a random [joemonster.org](http://joemonster.org/filmy/79862/Popatrz_kochanie_jakie_ladne_lwy) link that I clicked. The image that gets loaded in the iframe url was an extremely long (40,169 characters) "URL" that is a `data:image/jpeg:base64` "address".

I did find that if you block the following [script](https://www.google.com/js/bg/JUvzvcxJWTuBJ7HCHjfrN49N2GLUWsjQlRKuvUtSXJQ.js) (hosted on google) from loading it doesn't seem to sneak through however, but that isn't a predictable way of removing it in the future as google seems to regularly change the naming convention of their js libraries and files.

**Comment by CapSel** [comment]
Page doesn't always load ads. In my unreliable experience blocking site's inlined scripts helps. I haven't tried to block google scripts.

**Comment by gorhill** [comment]
joemonster.org##iframe[mysrc]

**Comment by CapSel** [comment]
Work for now. What if they decide to change attribute?

**Comment by gorhill** [comment]
Marking as a "browser bug" (using quotes because could be by design) because of:

> having the parent document reset the iframe using document.open/document.close trashes all injected content scripts and runtime data in that frame -- the document is resetted.
