### ISSUE TITLE
1.7.5概率不在状态栏显示图标，不在右键菜单出现

### ISSUE THREAD

**Issue by blob2015** [gorhill/uBlock#1746]
**系统：**
Win7 32，FF 35.0.1，uBlock 1.7.5＋1.6.1【已经设置“加入右键菜单”】，状态栏依靠 Status 4 Evar 2016.02.06.23.1来显示
**问题：**
一、1.7.5 经常需要重启才能在状态栏显示
二、不在右键菜单显示【图片，链接，文字】

---------------

用回更加古老的版本？插件、扩展、脚本冲突？或者其他解决办法？

**Comment by hairycactus** [comment]
@blob2015 -- 如果可能的话，请用英语发表问题。uBlock Origin developer 及大多数使用者都看不懂华语。
_(Translation: If possible, please submit issues in English, since the developer & most users here do not understand Mandarin.)_

Could you provide a screenshot highlighting where the uBlock Origin icon is missing from your Firefox v35.0.1 _"status bar"_ & _"right-click context menu"_ ?

Or did you mean one or more of the following ?
* uBO icon is not displayed at FF's **toolbar**
* uBO icon is not displayed within FF's **hamburger ☰ menu**
* uBO's **dashboard** is missing

Why do you have 2 versions of uBO (v1.7.5 + v1.6.1) installed in your FF ?

Perhaps you can try backing up your uBO settings, uninstall all versions of uBO, restart FF, & then install the latest version of uBO (v1.7.6, released: 22 June 2016) from: https://addons.mozilla.org/zh-CN/firefox/addon/ublock-origin/versions

English page: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions

**Comment by blob2015** [comment]
thanks for your reply.
uBlock doesn't display on the menu, when i click the right mouse.
there are no 2 versions of uBlock at one time, firstly i update to 1.7.5, and then i notice that the error comes. so i replace the former 1.7.5 with 1.6.1, but the error goes on.

**Comment by hairycactus** [comment]
It seems that when you upgraded uBO from v1.6.1 to v1.7.5, something might have gotten corrupted.

Another possibility is that another add-on is conflicting with uBO. Did you install a new add-on (or manual/ auto-update an existing add-on) any time before you updated uBO to v1.7.5 ? Try disabling your other add-ons & see if it helps. Try disabling & re-enabling uBO too.

Just last week, I installed a new add-on, & my uBO icon disappeared from my FF toolbar. The uBO icon stayed missing even after I restarted FF. Luckily, disabling & re-enabling uBO itself made its icon reappear again.

Whilst waiting for uBO developer to advise, below are other things you could try:-

**Test uBO in clean FF Profile:**
Close FF, [create a new FF profile](http://kb.mozillazine.org/Creating_a_new_Firefox_profile_on_Windows), & install the latest version of uBO. Check that uBO icons exist where they should exist. (This new FF profile can be deleted, if you don't wish to keep it.)

or **Uninstall & Reinstall uBO:**
1) Backup uBO settings (filter lists & custom rules).
2) Uninstall uBO.

3) Load `about:config` at FF's URL bar  ⇒ search: _ublock_
   * delete left-hand side entries containing uBlock references
   * double-click any remaining `about:config` entries ⇒ carefully delete references to uBlock in the corresponding string value(s)

4) Check FF profile folder for uBO files & delete them
eg. `C:\Users\<user-name>\AppData\Roaming\Mozilla\Firefox\Profiles\<profile-name>\extension-data\`
⇒ delete all uBO files here (eg. `ublock.sqlite`)

**Comment by gorhill** [comment]
When the issue occurs, please look in the browser console (ctrl-shift-j) to find out if there are any error message related to uBO. (Admittedly I do not test on older versions of FF, I stick to Nightly, latest stable FF, SeaMonkey, Pale Moon, Android).

**Comment by blob2015** [comment]
@gorhill @hairycactus 
anyway, thanks

**Comment by blob2015** [comment]
@hairycactus @gorhill 
is uBlock using the widget api?
https://bugzilla.mozilla.org/show_bug.cgi?id=994280
https://github.com/olsh/Feedly-Notifier-Firefox/issues/92#issuecomment-50577934

**Comment by gorhill** [comment]
uBO does not use SDK stuff, and uses legacy toolbar button on FF35 and less -- it does not use CustomizableUI. I don't test on FF35 specifically, I test on Pale Moon, SeaMonkey stable, FF stable and Nightly.

**Comment by hairycactus** [comment]
@blob2015
> [2. uBlock doesn't display on the bottom status bar, while it will come back, when i restart the ff. ](https://github.com/gorhill/uBlock/issues/1746#issuecomment-228004266)

In my Firefox, the bottom Status Bar doesn't appear, unless I mouseover an embedded hyperlink (Status Bar then displays the link), or when a webpage is loading (Status Bar shows _"Connecting to/ Waiting for ..."_).  In fact, the permanently-visible Status Bar itself was [removed](https://support.mozilla.org/en-US/kb/what-happened-status-bar) a long time ago (since FF v4.0).

Do you have an addon that restores the Status Bar ?  If yes, perhaps try disabling it or downgrading the version to see if it has any effect on how uBO is displayed in your FF.

> [is uBlock using the widget api? Addon-SDK.](https://github.com/gorhill/uBlock/issues/1746#issuecomment-245357836)

If you meant that the uBO icon/ badge is missing from the toolbar near the _top_ of your FF 35.0.1, see if the below addon can help bring it back. You might want to back up your current FF profile folder first, before testing it.

**[uBlock Legacy Toolbar Button Test Build 2](https://github.com/AlexVallat/uBlock/releases)** (25 Apr 2015):
https://github.com/AlexVallat/uBlock/releases/download/0.9.3.5-dev-av.2/uBlock.firefox.xpi

**Comment by blob2015** [comment]
@hairycactus 
yes, stats-4-ever, addon, it's essential for me.
i've tested ubo on latest version, and the problem has gone.
anyway, thanks for your friendly reply.
