### ISSUE TITLE
uBlock for Firefox Android stops blocking ads suddenly

### ISSUE THREAD

**Issue by joemccall86** [gorhill/uBlock#1768]
### Describe the issue
After several months of regular use, uBlock Origin will fail to block any ads on any website until I manually refresh the filter list. Then I can refresh the page and the ads are blocked.
Quitting firefox and restarting it puts it back into the error state. The only thing that will mitigate the issue is clearing all data in firefox at the app-level and re-installing uBlock origin.

### One or more specific URLs where the issue occurs
http://www.sbnation.com
http://www.msn.com

### Screenshot in which the issue can be seen

Album: http://imgur.com/a/awVtm

### Steps for anyone to reproduce the issue

1. Install firefox for Android
1. Install uBlock origin
1. Use regularly for a period of time

### Your settings

- Browser/version: Android 6.0, Firefox 47.0
- uBlock Origin version: uBlock Origin 1.7.6

##### Your filter lists
Default filter lists

##### Your custom filters (if any)
None

### Other Notes
Due to the nature of the bug I haven't been able to reproduce without any other extensions installed. I can say that for months (not sure exactly how long) uBlock has been playing nicely with my other extensions, and suddenly it stops working. Seems like perhaps it's related to a buffer somewhere becoming full, because once I clear the data from firefox and reinstall uBlock everything works fine. Here is the list of extensions I have installed:

* Decetnraleyes 1.3.5
* HTTPS-Everywhere 5.1.10
* Open Native App 1.1.1-signed.1-signed
* OpenH264 Video Codec provided by Cisco Systems, Inc. 1.5.3
* uBlock Origin 1.7.6

I can also say that uninstalling all of these extensions except uBlock Origin does *not* solve the problem. For the sake of this ticket I'll leave my installation of firefox in this state in case you want me to try something for additional information

Finally, thank you a ton for your hard work putting this extension together. The entitled tone of some of these tickets is appalling, considering you do this in your free time. Know there's more than a few of us out here that recognize and appreciate all you've done for the web.

**Comment by gorhill** [comment]
It's as if uBO is not launching properly, i.e. there are errors occurring at launch. Can you see if the browser console reports any error when the issue occur?

**Comment by gorhill** [comment]
One explanation could be that uBO's SQL database becomes corrupted for whatever reasons. Removing the SQL file should fix the issue if this is the problem. Not sure where it would be on Android though. If removing the SQL file works, then this would confirm this is where the issue is.

**Comment by joemccall86** [comment]
I installed the add-on "Console" to view the error log while loading msn.com. I think you're onto something with the SQL database, as that's where I'm seeing the error. Here are the screenshots: http://imgur.com/a/dzdMr

**Comment by joemccall86** [comment]
I'm using the file manager to search for `ublock0.sqlite`. I'll update the post when I find it and let you know.

**Comment by joemccall86** [comment]
After some preliminary searching I think I need a rooted phone to see that file. So assuming the sqlite db is corrupt, do you have any suggestions to try?

**Comment by gorhill** [comment]
Yes, looks like the SQL file is corrupted. Since uBO is using FF API to deal with the SQL database, this means something is occurring FF API-side or OS-side which corrupts the file.

Now uBO is supposed to deal with this by at least making it look like all the settings are default. But looking at the code I see it's not returning the proper value when an error occurs as a result of trying to read the content of the SQL file. This is why the error reported in `vapi-background.js`.

I will fix the code ASAP, and you can confirm whether uBO still work at least with default settings when such rare occurrence as a corrupted SQL file is the issue.

If the fall back code path works, then I will dig into FF API to find out if uBO can remove the SQL file completely so that it can start to work again. This would of course reset uBO to default settings. In such case, hopefully a user would have a backup from which to restore settings.

Now as to why the SQL become corrupted, it's either a FF or OS issue, which should probably be reported to FF dev team.

For now let's see of the fix helps on your side, i.e. uBO still works without having to reset your profile. I will notify here when the 1.7.7b2 version is available.

**Comment by gorhill** [comment]
[1.7.7b2 available in dev channel on AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=1#version-1.7.7b2).
