### ISSUE TITLE
Settings button nonexistent on Firefox

### ISSUE THREAD

**Issue by origintopleft** [gorhill/uBlock#180]
There is no way to access the extension settings on Firefox versions of uBlock Origin. Its not in about:addons, it's not in the pop up you get when you click the icon, it's just not there. I know the settings page exists, Chrome has one, why has uBlock not included a button in the Firefox extension?

**Comment by Tester798** [comment]
You can open it's settings by clicking on dark title in popup window. But I agree it can be tricky to get there if you don't know about it. First time I tried to get there in Firefox I couldn't find it also (because in Chrome I always open settings using right mouse click on extension button). Maybe small gear icon in the corner of the popup window could solve the issue.

**Comment by gorhill** [comment]
> Its not in about:addons

![a](https://cloud.githubusercontent.com/assets/585534/7487034/5f71b3c4-f37d-11e4-8440-74e9b7ec075d.png)

**Comment by lavacano201014** [comment]
The first time I checked the Preferences button, there wasn't anything there. Apparently that was a problem on my end since it's there now. Will have to investigate that further.
