### ISSUE TITLE
Does uBlock Origin impact performance of slither.io ?

### ISSUE THREAD

**Issue by phrokton** [gorhill/uBlock#1806]
How best can one collect metrics to this end?  

I use:  OSX (32gigs ram, i7), Windows 10 (16gigs ram, i5) [because not all my steam games play nicely in emulation on pOSiX boxes] , Ubuntu LTS (16gigs ram, i3).  For this site I exclusively use 64bit chromium.  For other applications I also use 64bit Community Editions of mozilla (not firefox proper).

### Describe the issue

Playing interweb browser game slither.io with extension TamperMonkey enabled for better zoom via UserScript.  Could uBlock Origin contribute to tab instance freeze?

### One or more specific URLs where the issue occurs

[http://slither.io](http://slither.io)

### Screenshot in which the issue can be seen

![slither_broserbecomesunresponsive](https://cloud.githubusercontent.com/assets/19551366/16754472/df230864-47a7-11e6-84bd-203da6617794.png)

### Steps for anyone to reproduce the issue

0 Using chromium ([not chrome](https://duckduckgo.com/?q=chrome+is+evil)) [[64bit, Nik stable, no sync](http://chromium.woolyss.com/)] [[silent installer](https://github.com/henrypp/chromium/releases/download/v51.0.2704.106-r723-win64/chromium-nosync.exe)] (http://chromium.woolyss.com/)
1 Install TamperMonkey
2 Install [j-c-m 's fork](https://github.com/j-c-m/Slither.io-bot/blob/_followself/bot.user.js) of [khumarahn](https://github.com/khumarahn) 's _coiling_ slither UserScript
2b click the 'raw' button to have TamperMonkey prompt to install UserScript
3a load slither.io
3b enter nickname, start match
3c enable no options in onscreen UserScript controls
4 use mouse wheel to zoom out until a single snake skin patch is half a centimeter.  (ignores various monitor issues)

### Your settings

- Browser/version: 64bit: Chromium [dev] 54.0.2793.0, or Chromium [stable] 51.0.2704.106 
- uBlock Origin version: 1.7.6

##### Your filter lists

![filtersettings](https://cloud.githubusercontent.com/assets/19551366/16754624/16b2b92c-47a9-11e6-9ecb-317d0153127d.png)

**Comment by gorhill** [comment]
I tested 1.7.6 with default settings, and the answer is "no". Blockers will always add overhead, but in the current case it was insignificant compare to the rest of the work the web page had to do. I tested without Tampermonkey, because the project here is about uBO, I won't investigate perf issues from other extensions if any.

I tested with all the filter lists you selected and the browser profiler shows that uBO is just fine -- it contributed for less than 1% of CPU usage for that page. Next time please use the browser dev tools to profile yourself if you wonder.
