### ISSUE TITLE
Blocking url with mixed cases

### ISSUE THREAD

**Issue by gtgvxinf** [gorhill/uBlock#1833]
### Describe the issue
 * Ublock origin can't block urls with mixed uppercase & lowercase letters.
 * It does not support $match-case modifier, which is in [the spec](https://adblockplus.org/filters) of Adblock Plus filter rules.

### One or more specific URLs where the issue occurs

http://goo.gl/F0pE

### Screenshot in which the issue can be seen

http://imgur.com/a/7K5xW

### Steps for anyone to reproduce the issue

 * Add a following rule to "My filters"
```
||goo.gl/F0pE
```
 * Go to http://goo.gl/F0pE to see that it is not blocked.

 * Remove above and add instead
```
||goo.gl/
```
 * Go to http://goo.gl/F0pE to see it is correctly blocked.
 * Remove above and add
```
||goo.gl/F0pE$match-case
```
 * Go to http://goo.gl/F0pE to see it is not blocked.

- Browser/version: Chrome 52.0.2743.82 m
- uBlock Origin version: uBlock Origin v1.7.6

##### Your filter lists
None
##### Your custom filters (if any)
||goo.gl/F0pE

**Comment by gorhill** [comment]
> It does not support `$match-case` modifier

By design. I do not plan to implement this, I haven't seen used anywahere, and proof of concept as shown here is not a good reason enough.

**Comment by gtgvxinf** [comment]
You didn't read my first issue. Provide a way to block the url shown here.

**Comment by sn260591** [comment]
`||goo.gl/F0pE$document` works fine.

**Comment by gorhill** [comment]
> You didn't read my first issue

Your first issue:

> Ublock origin can't block urls with mixed uppercase & lowercase letters.

Your first issue is the same as the second: uBO does not take into account case, by design.

The proof of concept case you provide has nothing to do with case, you are attempting to block a whole page, and the reason this does not work is because of how strict blocking works, not because of a case issue. Your case won't work in ABP either since it does not support strict blocking. @sn260591 has the correct answer: you can block whole page for specific pages on a site if you use the `document` filter option.

**Comment by gtgvxinf** [comment]
>Your first issue is the same as the second
No it isn't, nor does my example is to serve as a proof-of-concept. I see, it was about peculiarity of Ublock on strict blocking.
If you want to see an instance where $match-case is used, check out some Finnish filter lists.

**Comment by lewisje** [comment]
Maybe case-matching is supported in regex filters.
