### ISSUE TITLE
Can ":has()" and ":style()" be used in conjunction?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gorhill/uBlock#1837]
First off, they're both great new features, but I haven't been able to make them work together. 
A random example using torrentfreak.com (top of the page, under input):

torrentfreak.com##.stats-item:has(a[href="https://torrentfreak.com/archives/"])
hides the li containing link with that [href]

torrentfreak.com##.stats-item:style(background:red!important;)
styles all ".stats-item" li

but this doesn't seem to work:

torrentfreak.com##.stats-item:has(a[href="https://torrentfreak.com/archives/"]):style(background:red!important;)

Maybe that's the wrong syntax, or maybe there is no correct syntax for combining the two. I'm hoping there is. Any insight would be appreciated.

**Comment by gorhill** [comment]
You can't, I commented somewhere I can't remember one or two days ago. It may or may not be supported in some future, for now, not supported by design. The most important point to keep in mind: uBO is not Stylish, the only purpose of the new cosmetic filter extensions is to take care of difficult cases which can't be solved otherwise, not to turn uBO into an extension to just re-style stuff.
