### ISSUE TITLE
Tag filters with associated network

### ISSUE THREAD

**Issue by yoshimo** [gorhill/uBlock#1898]
It would be great to have a way to make visibly named groups of filters without having to rely on the order and comments in the file only.
Lets say Adtracking Limited operates
a.adt.com
b.adtracking.com
cd.bellerevenue.org

Ghostery would still show on its tooltip that this network is used and which regexes match on the current domain.
UBO doesn't have that background info stored somewhere and only lists individual domains.
To be able to get rid of Ghostery in my neighbourhood it would be good to have a way to group urls by company behind it.

**Comment by gorhill** [comment]
> To be able to get rid of Ghostery in my neighbourhood it would be good to have a way to group urls by company behind it.

uBO would need a complete and constantly updated database of domains/company pairs. Given this is a completely volunteer-based project, who is going to research and maintain such database?

**Comment by gorhill** [comment]
> to make visibly named groups of filters

Anyways, it not clear what you are talking about exactly. "Visibly" _where_ exactly?

**Comment by yoshimo** [comment]
![sample](https://cloud.githubusercontent.com/assets/17909/17667116/ce887486-6303-11e6-93e9-04339f1672d9.png)

As you can see in this sample picture you have thirdparty elements put in categories and instead of their real url they show the product/company behind it

**Comment by gorhill** [comment]
You're are showing me a screenshot of Ghostery: I won't make uBO into a clone of Ghostery. The closest you will find in uBO is the dynamic filtering panel, and I do not intend to change its UI. At most it would be to provide extra info for whatever company is behind a domain name (tooltip or whatever), but as said, I know of no such open source database which uBO could use.

In any case, I frown upon issue opened to with the rationale _"please clone this other extension into uBO because I want to get rid of the other"_. Just keep using Ghostery if you like it.

**Comment by yoshimo** [comment]
@gorhill i thought it would be a nice addition. Taking inspiration from other tools isn't necessarily a bad idea. 
As far as the data goes it could have been a community effort like any other filterlist out there.

**Comment by gorhill** [comment]
> As far as the data goes it could have been a community effort like any other filterlist out there.

Sure, but unless there is something at all, there is no point changing the code to rely on what does not exist. If something becomes available at some point, I am opened to explore using it in the popup panel, I do see how this could be useful -- but at most that would be to keep the exact same dynamic filtering pane UI in the popup panel, except to list entity names rather than domain names for the domain-based rows (the ones with bolded text).

**Comment by yoshimo** [comment]
@gorhill  how about using https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json ? That would have been the right one i guess ;)
