### ISSUE TITLE
Popup filter closes a page as popunder 

### ISSUE THREAD

**Issue by hant0508** [gorhill/uBlock#1903]
### Describe the issue

On some websites when you click on a link to [example.com](http://example.com) and it opens in a new tab, the first tab is closed by uBO, if you have a filter that disables popups on [example.com](http://example.com). Perhaps, this description isn't very clear, so see the specific example.

### One or more specific URLs where the issue occurs

http://prodota.ru/forum/index.php?showtopic=209638&st=2020#entry18887379

### Screenshot in which the issue can be seen

![screenshot_22](https://cloud.githubusercontent.com/assets/12861787/17697719/809bbdae-63c7-11e6-9993-75e46c703c90.png)

### Steps for anyone to reproduce the issue

1. Follow [this link](http://prodota.ru/forum/index.php?showtopic=209638&st=2020#entry18887379)
2. Click on link to pornhub in the post#2024
3. The new tab with pornhub will be opened, but the previous tab with prodota will be closed because of the filter from Easy List: `http://*?*=$domain=extremetube.com|pornhub.com|redtube.com|spankwire.com|tube8.com|youporn.com|youporngay.com,third-party,popup`

### Your settings

- Browser/version: Mozilla Firefox 50.0a2 on Debian GNU/Linux
- uBlock Origin version: 1.8.5b5
- Default settings and filter lists

**Comment by ZenoNiQ** [comment]
Same.

- Browser/version: Google Chrome 52.0.2743.116 m
- uBlock Origin 1.8.4
- Default settings and filter lists

**Comment by gorhill** [comment]
I could reproduce.

Currently, uBO will not apply `popunder` detection for broad `popup` filters. However the "broadness" test in the current state of the code is negative for `http://*?*=`, because it causes the hostname part to be matched with that filter. A fix would be to consider `http://*?*=` to be broad, and not check for popunder. Not sure how easy this can be fixed. Will investigate.
