### ISSUE TITLE
:xpath doesn't hide this element

### ISSUE THREAD

**Issue by GiftWolf** [gorhill/uBlock#1912]
### Describe the issue
The element is not hidden.
It might have to do with the `display: block;` style. Once I disable it in the style inspector the element is properly hidden.

### One or more specific URLs where the issue occurs

[http://www.spiegel.de/](http://www.spiegel.de/)

### Screenshot in which the issue can be seen

![Screenshot](https://cloud.githubusercontent.com/assets/992940/17792990/883f596a-65a4-11e6-8206-9bc27e53f47a.png)

### Steps for anyone to reproduce the issue
use Firefox
add `spiegel.de##:xpath(//div[div/a[starts-with(@href,'http://www.bento.de')]])` under My filters.
vist http://www.spiegel.de/
to better find the elements enter into console: `$x("//div[div/a[starts-with(@href,'http://www.bento.de')]]");`
see that not all of them are hidden. In my case it is the first one, the one in the screenshot

### Your settings

default uBlock settings

- Browser/version: Firefox 48.0
- uBlock Origin version: 1.8.4

##### Your filter lists
Default filter lists

##### Your custom filters (if any)
`spiegel.de##:xpath(//div[div/a[starts-with(@href,'http://www.bento.de')]])`

**Comment by aggat** [comment]
Strange this works
`spiegel.de##:xpath(//div[@style][div/a[starts-with(@href,'http://www.bento.de')]])`

:has also doesn't work
`spiegel.de##div:has(:scope > div > a[href^="http://www.bento.de"])`
but this works
`spiegel.de##div[style]:has(:scope > div > a[href^="http://www.bento.de"])`

**Comment by gorhill** [comment]
I can reproduce.

Does not occur with Chromium, since the node's `shadowRoot` prevent its rendering -- though borders are left behind.

If enabling `dom.webcomponents.enabled` in Firefox, the node is hidden just like with Chromium-based browsers.

Unlike standard cosmetic filters, `:xpath` are implemented procedurally, there is no `style` tag to enforce them.

I experimented a bit, and it turns out I can create a style tag with one single CSS rule to better enforce the hiding of nodes from procedural filters such as `:xpath`, `:has`, `:matches-css`.

Note: Eventually I plan to offer the ability to remove nodes from the DOM, so styling won't ever be an issue for removed nodes. There are other possibilities.

**Comment by gorhill** [comment]
> Strange this works
> 
>     spiegel.de##:xpath(//div[@style][div/a[starts-with(@href,'http://www.bento.de')]])

Make sense from what I have observed. When uBO hides the node, it finds that the node has no `display` style set, and thus does not try to set its own `display: none !important` directly on the node, the `hidden` attribute is enough in such case.

With your filter above, this causes uBO to match the node only after the page set a `display` property directly on the node, and at that point uBO does see that it must add its own `display: none !important` to override the node's one.
