### ISSUE TITLE
How to unblock YouTube comments, while keeping YouTube ad free?

### ISSUE THREAD

**Issue by jebus197** [gorhill/uBlock#1919]
### Describe the issue

Hi, first thanks so much for Ublock! However unfortunately I'm having a little difficulty reading or posting comments on all the YouTube videos I watch. In essence the comments section isn't visible at all. Which exceptions do I need to add to fix this?

Thanks!

### One or more specific URLs where the issue occurs

https://www.youtube.com/watch?v=Dt_jsSKxrkw

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version:  Chrome Version 52.0.2743.116 m
- uBlock Origin version: 1.8.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Default.

##### Your custom filters (if any)

None

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by lewisje** [comment]
I for one see the comments section and am able to add comments unless I take active steps to disable them, which I do with the following filters:

    ||youtube.com/comment_service_ajax$script,xmlhttprequest
    youtube.com###watch-discussion

Similarly, I keep the share-box from loading with these filters:

    ||youtube.com/share_ajax?action_get_share_box=1&video_id=$xmlhttprequest
    youtube.com##.action-panel-trigger[role="button"][data-trigger-for="action-panel-share"]
    youtube.com##.yt-uix-button[data-trigger-for="action-panel-share"]

Anyway, watch the logger to see what might be keeping the comments section from loading for you.

**Comment by DonChino** [comment]
Just want to let everyone know that I came here looking for a solution to the YouTube Comments problem, because I also thought it was uBlock Origin. After seeing the developer blow his top so many times screaming that it is NOT his Add-On I decided to try and see if it was something else, because we have so many Add-Ons/Extensions loaded in our browsers nowadays. :)

Anyway, it turns out that it was - HTML5 Video Everywhere! - that was causing the problem with YouTube Comments. It never would have crossed my mind, since what does HTML5 VIDEO have to do with YouTube comments, but I disabled and restarted my Firefox browser to suddenly see my YouTube Comments come back. I do not have Flash installed so I MUST have something that forces HTML5 and stops AUTOPLAY, so that add-on works PERFECTLY but it turns out that it breaks YouTube Comments.

I hope someone else finds this useful and that way GORHILL can relax and focus on other "bugs"... :P
