### ISSUE TITLE
Url Blocking Issue

### ISSUE THREAD

**Issue by monolifed** [gorhill/uBlock#192]
I am trying to use a filter to block a page.
Page url is like "https://online.example.com/NKF,192.168.13.5"
Filter is "online.example.com/NKF" which is not working.
I tried placing stars, using regex and using the url itself. Nothing worked.
I am not sure if it is a bug, it feels like I am doing something wrong
ps: version is 0.9.6.0

**Comment by gorhill** [comment]
I supposed you are referring to "strict blocking". Given that strict blocking is based on filter lists which were never intended to block whole page, the heuristic to block whole pages had to be relaxed in order to not depend completely on just a filter match.

The heurstic is as follow: if the match is completely within the hostname part of the URL, the page will be blocked. As soon as the match crosses the path part of a URL, the page won't be blocked. Doing so was creating too many false positives, potentially causing users to not want the feature at all, which would be worst than relaxing the heuristic.

So in your specific case, your filter would need to be `||online.example.com^`.

**Comment by monolifed** [comment]
Yes, I was referring to strict blocking. Thanks

**Comment by gorhill** [comment]
Fixed with fa4e3ca492d2ff4d02e467b538695702e4b0be18.
