### ISSUE TITLE
Dim the 'Ignore generic cosmetic filters' option when appropriate

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#1940]
**Issue Report Synopsis:**

When the _Parse and enforce cosmetic filters_ option is disabled, the _Ignore generic cosmetic filters_ sub-option is not dimmed.

**Test Environment:**

uBlock Origin version: 1.9.0
Firefox version: 48.0.2 (applies to 32-bit and 64-bit)

**Steps To Reproduce:**
1. Disable _Parse and enforce cosmetic filters_
2. Notice that _Ignore generic cosmetic filters_ is not dimmed, even though it has no effect.

**Expected Behavior:**

When _Parse and enforce cosmetic filters_ is disabled (unchecked), the _Ignore generic cosmetic filters_ option should be dimmed.

**Recommendation:**

Dim the _Ignore generic cosmetic filters_ option when _Parse and enforce cosmetic filters_ is disabled (unchecked).

**Comment by gorhill** [comment]
I can't make exceptions for user filters, one single generic cosmetic filter would cause all the expected benefits from using this setting to completely disappear -- it takes only one single generic cosmetic filter to exist for uBO to be forced to survey the DOM of a document. Since the re-factoring of 3rd-party pane, it is no longer displayed as a sub-option.

**Comment by gorhill** [comment]
I just had an idea how uBO could disabling DOM surveying while allowing user's own generic cosmetic filters: to simply just inject them all unconditionally. The worry though is that a user would paste a huge amount of generic filters in their _My filters_ pane. Reopening, to assess more thoroughly this implementation idea.
