### ISSUE TITLE
Thunderbird/Fx: After check the blocked resourse in logger, img is loaded

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1949]
If I check which filter blocks an image like this screenshot here ...

![ubo-1](https://cloud.githubusercontent.com/assets/11355601/18103263/17767a32-6ef6-11e6-8e9d-e23b42a088a0.JPG)

it shows also the blocked picture ...

![ubo-2](https://cloud.githubusercontent.com/assets/11355601/18103289/334212c6-6ef6-11e6-8abe-8000b9dcefc7.JPG)

After closing, Thunderbird loads this picture in email (html view).

Then I have to restart Thunderbird and maybe to clear the cache too to have the image blocked again.

Thunderbird 45.2.0 with uBO 1.9.5b0 on Win 10 x64 1607.

BTW: What is the reason that the logger shows blocked images? It's even the case in "normal" Browsers Firefox/Chrome too. If I want ensure that some content is blocked and I check later with which filter, uBlock loads blocked content always in the filter "panel"/view. Is this really necessary?

**Comment by lewisje** [comment]
If you click the actual rule, it will show you what filter-list did it, without loading the resource; the part of the row you clicked is for showing the blocked resource (if it's an image) and explaining how the filter rule works.

I have not reproduced this behavior in Chrome, but here is a good test case:

1. Add the following custom filter: `||electoral-vote.com/evp2016/Art/VFA.jpg$image`
2. Go to electoral-vote.com with the logger open (if you didn't open the logger first, refresh the page).
3. Check the blocked image lines; you should see one for an image promoting voting from abroad (for US citizens).
4. Refresh the page normally, without a hard-refresh or clearing cache.

I still didn't see the aforementioned image in the upper-right of the page, until I removed the custom filter I just added.

I thought maybe the issue was that uBO wasn't able to block requests for content that is already in the cache (as it is when you preview it in the logger), but I haven't reproduced it on my end.

**Comment by Alpengreis** [comment]
I understand, lewisje, thank you!

I was wrong with "which" filter.

Nevertheless: if I have the uBO media filter activated for a certain size, and then an image is blocked, and I display the blocked resource in logger, Thunderbird should not load the image after in email, except I create a filter for this (for case above for example with: "no-large-media:  microsites.pearl.de/images/* false") or something like that.

Here, after the blocked image was displayed, TB loads it in email. **And this stays, TILL I clear the cache and make a Thunderbird restart.**

Note: I have enabled in Thunderbird the "load remote content" for this email. Nevertheless the active uBlock large-media filter should work ALWAYS.

**Comment by Alpengreis** [comment]
News: in Firefox I have the same behaviour, after show a blocked resource WITHOUT create a filter, after I refresh the page, Fx shows the blocked content.

I assume this is by design because it's in the cache already?!

**Comment by gorhill** [comment]
> I refresh the page, Fx shows the blocked content.

Use hard-refresh -- <kbd>Shift</kbd>-click _Refresh_.

**Comment by lewisje** [comment]
I think the idea is that the browser should be prevented from even looking for the resource in the cache, which appears to be what happens in Chrome for me, 52.0.2743.116 Stable 64-bit on Windows 10 Pro 1607 (I made sure of this by testing with "Collapse placeholders of blocked elements" off).

**Comment by laniakea64** [comment]
> BTW: What is the reason that the logger shows blocked images?

https://github.com/gorhill/uBlock/issues/1999

**Comment by gorhill** [comment]
The browser may not call the webRequest API if the resource is in its short-term memory cache. To work around this is to simply reload a page while pressing the shift key.
