### ISSUE TITLE
Undetected anti-adblocker

### ISSUE THREAD

**Issue by Rikk** [gorhill/uBlock#1950]
Not sure where I should report this, if here or https://github.com/reek/anti-adblock-killer (looks outdated, last updated in July) or somewhere else. Please point me to the correct place. Thanks.

http://economia.uol.com.br/cotacoes/cambio/dolar-turismo-estados-unidos/

Offending script seems to be this one:
http://jsuol.com.br/c/detectadblock/detectadblock.js
(looks like it is a library named "Detect AdBlock" at version 1.4.6)

![uol-anti-adblock](https://cloud.githubusercontent.com/assets/2916485/18107139/1cde14f8-6edd-11e6-89e1-c74690e61858.png)

**Comment by lewisje** [comment]
The AAK issue page is still quite active: https://github.com/reek/anti-adblock-killer/issues

Anyway, this amounts to a filter-list issue, so you might do well reporting this at https://github.com/uBlockOrigin/uAssets if it's something that could be fixed in a built-in uBO list (as opposed to a third-party list that is mirrored in uAssets).

**Comment by gorhill** [comment]
CONTRIBUTING:

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets. [...] Ignorance of the above rules is no excuse: Opening an issue for purpose of support or discussion, or opening a filter-related issue will result in the user being immediately blocked. Given the amount of invalid issues being opened, I have no choice but to resort to such a drastic measure.
