### ISSUE TITLE
Not matching some filters

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#1976]
I've been troubleshooting a complex issue, and found a reproducible way to demonstrate it:

## The Issue
uBlock Origin is not matching some filters with properly formed selectors.  (Alternative issue: I'm not understanding how uBlock Origin is supposed to work, or am staring too long at a silly mistake. :wink: )

## Steps to Reproduce  
  1. Create a fresh Firefox profile in Firefox v48.0.2 (current stable release version)
  2. Install uBlock Origin v1.9.6 (current stable release version)
  3. Disable all third party filters
  4. Open `https://play.google.com/`
  5. Observe that the EU cookie warning is present at the top of the page
  6. Create the following filter:  
  `play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"]`
  7. Apply the filter
  8. Refresh the page openened in step 4
  9. Observe that the EU cookie warning is still present
  10. Using whatever tool you prefer, apply the following CSS, which uses the same selector, to the page opened in step 4:  
  `.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"] { display: none !important; }`
  11. Observe that the EU cookie warning is now hidden

## Additional Test  
The following test will hopefully provide additional insight into the cause of the issue.  

  1. In uBlock Origin, create the filter:  
`play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="b"]`  
  2. Notice that the above works to block the EU cookie warning, even though the following does not:  
`play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"]`

**Comment by gorhill** [comment]
The page is doing this: there is no element matching `.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"]` when using your filter, the cookie notice does not have a style attribute starting with `behavior`. So apparently there is code on the page to generate a different DOM conditional to whether the cookie warning is visible or not.

**Comment by Gitoffthelawn** [comment]
Thanks.  I'm interested in what you have to say, but I think GitHub may have botched the formatting of your post a little or some words just didn't make it into your post.  I'm not quite sure what you mean before "So apparently".  Would you mind editing your post above?

The last sentence you wrote is clear: that the page is changing the DOM depending on whether or not the cookie warning is visible.  I'm seeing that too.

Do you understand why blocking the following within uBlock Origin works:  
`play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="b"]`  
but  
`play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"]`  
does not?

Similarly, do you understand why adding this CSS overlay works:
`.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"] { display: none !important; }`  

but the same selector in uBlock Origin does not?

**Comment by gorhill** [comment]
> Do you understand why blocking the following within uBlock Origin works

Yes, because the `style` attribute starts with `background`, not `behavior`.

> Similarly, do you understand why adding this CSS overlay works.

No. I just observed that the page is generating different `style` attribute when uBO tries to add it with your original filter. I will let somebody else spend time to find out why the page does this, I really do not feel doing this, it's not terribly important to me. You will observe the same behavior in ABP/Chrome. The behavior is not there with ABP/Firefox, but then ABP/Firefox strictly uses user styles, it does not modify the DOM at all, my understanding.

**Comment by Gitoffthelawn** [comment]
>Do you understand why blocking the following within uBlock Origin works

>> Yes, because the style attribute starts with background, not behavior.

Hmmm... the actual code is:
`<div class="gb_2c gb_zc" aria-hidden="true" data-ved="..." style="behavior:url(#default#homePage) url(#default#userData);background-color:#5a5a5a">`

It starts with `behavior`, not `background`.  Are you seeing something different?

**Comment by gorhill** [comment]
> It starts with `behavior`, not `background`.

![a](https://cloud.githubusercontent.com/assets/585534/18420191/b5432312-783a-11e6-8b91-522484e756e0.png)

**Comment by Gitoffthelawn** [comment]
That's not what I see when going to the same page.  Maybe try the English version instead of the German version?

Looking at the same page in English, the code I see is:
`<div class="gb_2c gb_zc" aria-hidden="true" data-ved="0EPxBCAE" style="behavior:url(#default#homePage) url(#default#userData);background-color:#5a5a5a">`

![untitled](https://cloud.githubusercontent.com/assets/7672848/18420550/108d2648-782a-11e6-8d68-6117c1083513.png)

Even though the string starts with `behavior`, it does not get matched by uBlock Origin.

I think you are on to something about the DOM changing.  But since it changes to something without any `style` defined, then `...[style^="b"]` should not match either.

**Comment by gorhill** [comment]
> Even though the string starts with `behavior`, it does not get matched by uBlock Origin

I explained why...

Your filter: `play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="behavior"]`

When you do not use your filter, the element's `style` attribute starts with `behavior ...`.

When you do use filter, the element's `style` attribute starts with `background-color ...` -- so your filter won't match.

Hence why `play.google.com##.keyboard-shortcuts-controller + DIV > DIV:first-child > DIV:first-child[style^="b"]` always work.

Would be useful someone else pitch in.

**Comment by Atavic** [comment]
`<div class="gb_2c gb_zc" aria-hidden="true" data-ved="0EPxBCAE" style="behavior:url(#default#homePage) url(#default#userData);background-color:#5a5a5a">`
That's just the div-class attributes.

Try this:

google.com###epbar, #cnsh, #pushdown, #consent-bump, div[data-ved="0CAEQ_EE"], div[data-ved="0EPxBCAE"], #taw ._pei, #cnsi ~ [jsaction*="dismiss"]

**Comment by jjohns71** [comment]
I've blocked something similar to the cookie notice on google which is the popup box when using their search engine routing through duckduckgo with duckduckgo's "!g bang" functionality. When you get to google through that method, a box is displayed which says "Get to google faster, set your search engine to google" or some crap like that. Previously I was using individual element filters to block these every time I saw the notice but I noticed that google seems to change their div id's (somewhat) randomly from time-to-time. Unfortunately, in the example above I feel like defining the div ID so narrowly to the hex value "0CAEQ_EE" and "0EPxBCAE" above will result in the same issue.

Over time I ended up with a large list of the following manual filters that all accomplished the same task because the div id's in the middle would slightly change over time and just blocking the last id in the chain ('.gb_g.gb_ga') ended up killing functionality on other google sites (gmail stopped working for example) so it had to leave in place all the other div id's to be effective in blocking just that one search related popup that was annoying me.

`google.com###gbw > div > .gb_T.gb_je.gb_R.gb_ke.gb_Ta > .gb_R.gb_ke.gb_Qb > .gb_g.gb_ac.gb_7c.gb_wc > .gb_g.gb_ea
google.com###gbw > div > .gb_T.gb_ke.gb_R.gb_le.gb_La > .gb_R.gb_le.gb_Pb > .gb_g.gb_ac.gb_2c.gb_Rb > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_ne.gb_R.gb_oe.gb_La > .gb_R.gb_oe.gb_Ob > .gb_g.gb_gc.gb_8c.gb_Qb > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_qf.gb_R.gb_rf.gb_db > .gb_R.gb_rf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_qf.gb_R.gb_rf.gb_db > .gb_R.gb_rf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_rf.gb_R.gb_sf.gb_db > .gb_R.gb_sf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_rf.gb_R.gb_sf.gb_db > .gb_R.gb_sf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_sf.gb_R.gb_tf.gb_db > .gb_R.gb_tf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_sf.gb_R.gb_tf.gb_db > .gb_R.gb_tf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga
google.com###gbw > div > .gb_T.gb_uf.gb_R.gb_vf.gb_db > .gb_R.gb_vf.gb_ec > .gb_g.gb_xc.gb_Fc.gb_Ec > .gb_g.gb_ga`

However, after @gorhill implemented the xpath functionality I went out looking for a better method and believe I found one which is to target a specific 'class' within a div that they use on those annoying search popup boxes. I don't know if this will work for you (but looks like it might since the div class is similar in the popup asking to switch to google search as it is for the cookie notice). 

For the google search notice, I ended up finding a filter that seems to block the notice without breaking functionality that _I have noticed_. This is setting up a block at any div level however, so it could be that I am nuking some functionality now, or in the future that I am not aware of.

`google.com##:xpath(/html/body/*//div[@class="gb_ga"])`


Based on all that rambling above, you might try the following filter and see if it kills the cookie notice (On a US IP I noticed it worked for me and while testing, realized the exact same xpath filter to kill the cookie notice as it is the switch search engine notice so my guess is Google is using this class for popup type notices).

`google.com##:xpath(/html/body/*//div[@class="gb_ga"])`

 Forewarning, this method could have unintentional breaking since it will kill any div with this class which may cause you to need to only kill this class at a specific div level similar to my second method below.

Second method which is more targeted and has less chance of breaking other functionalities is below:
`google.com##:xpath(.//*[@id='gbw']/div/div/div[2]//div[3][@aria-label="promo"])
google.com##:xpath(.//*[@id='gbw']/div/div/div[2]/div[3]//div[@class="gb_ga"])`


If google is changing the class name in the cookie notice frequently (unlikely based on my observations over a few months wrestling with the search notice), the first option might not work or you might need a more targeted solution like in my second example, hopefully it points you in the right direction to solving your problem.

Good luck!
