### ISSUE TITLE
Generic cosmetic filters abruptly not applied

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uBlock#2011]
### Describe the issue
Generic cosmetic filters are not applied to topics on phpBB forums after visiting more than 15 topics on which said generic cosmetic filters would have no effect.

### One or more specific URLs where the issue occurs

https://forums.informaction.com/viewtopic.php?f=18&p=84348#p84348

### Steps for anyone to reproduce the issue

1) add custom filter `##[href*="github.com"]`
2) visit more than 15 topics on https://forums.informaction.com/ that do not have links to github
3) visit a topic there which does have a link to github, such as above-mentioned URL

**Expected results:** github link is hidden

**Actual results:** github link is visible, and the cosmetic filter is not reported in the logger.
____

(Related discussion on informaction: https://forums.informaction.com/viewtopic.php?f=18&t=21619&start=30#p84250 )

### Your settings

new profile

- Browser/version: SeaMonkey 2.40
- uBlock Origin version: 1.9.6

##### Your filter lists

default

##### Your custom filters (if any)
see above

**Comment by rjkpa** [comment]
@gorhill 

Generic Filters are not being applied still

Steps

Go to http://the-watch-series.to/

Right click on "Latest Popular Episodes" block and click Block Element

Select and apply Cosmetic Filter "##.block-left-home-title"

Now browse to "chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html"

Remove the website name from the cosmetic filter which will turn it into a generic filter and click Apply Changes.

Refresh the web page, and the "Latest Popular Episodes" block will be back.

Add the website name back as and the cosmetic filter will be applied successfully again.

PS - Ignore generic cosmetic filters is NOT activated and this still happens, so I guess the bug lies somewhere there.

**Comment by gorhill** [comment]
> Refresh the web page, and the "Latest Popular Episodes" block will be back

Completely unrelated to the issue here. See the logger: `@@||the-watch-series.to^$elemhide`. from EasyList.

**Comment by rjkpa** [comment]
Is that why generic filters are not being applied ? because of that $elemhide ?

**Comment by gorhill** [comment]
because the filter applied is really `@@||...$generichide`, not `elemhide`. Historically uBO never supported `elemhide`, it was always implemented as `generichide`, which was something added by ABP afterward. I just need to change all instances of `elemhide` to `generichide`.

**Comment by rjkpa** [comment]
Ah, I understand now. Also there was hardly any documentation on this one, so I had to ask.

With those changes, can we still use elemhide instead of generichide ?

**Comment by gorhill** [comment]
Yes, `elemhide` will always map internally to `generichide`.

**Comment by rjkpa** [comment]
Thanks for that. One more question, like for a cosmetic filter namely, example.com##.blah we can do example.com#@#.blah to disable that cosmetic filter, so is there something for $elemhide/$generichide too ?

**Comment by gorhill** [comment]
Currently you can't override a filter such as `@@||example.com^$generichide` -- looks like I put code in there long time ago to disregard filters such as `||example.com^$generichide`, because such filter is implicit, i.e. not required since cosmetic filtering is always enabled by default according to ABP-filtering semantic.

_However_, since uBO supports the `important` filter option, which means theoretically it should be possible for UBO to override an exception filter such as `@@||example.com^$generichide`. Probably best to open a separate issue for this.

**Comment by rjkpa** [comment]
Hmmm, thought so. I did try `||the-watch-series.to^$elemhide,important`, and nothing happened. I guess I will open a new issue hereon forward.

**Comment by yourduskquibbles** [comment]
Hi @gorhill I run a [' Web Annoyances' filter list](https://github.com/yourduskquibbles/webannoyances/blob/master/ultralist.txt) and have a similar experience with generic filters on all websites that use the 'medium.com' blog platform as well as other sites that use their platform.

Use case can be tested on the link below: https://medium.com/buzzfeed-collections/internets-favorite-congressman-b7002ad4f3fa#.f3upjdryx

When I add the following generic filter with _no domain name_ in front of the ## to 'My Filters' `##.is-maximized.metabar--affixed.is-hiddenWhenMinimized.is-withBottomSection.u-tintSpectrum.u-tintBgColor.u-textColorTransparentWhiteDarker.js-metabar.u-clearfix.metabar` the filter seems to have no impact and ignores the rule.

However, if I use the same cosmetic filter, but include the domain, uBO seems to work as intended (i.e. `**medium.com**##.is-maximized.metabar--affixed.is-hiddenWhenMinimized.is-withBottomSection.u-tintSpectrum.u-tintBgColor.u-textColorTransparentWhiteDarker.js-metabar.u-clearfix.metabar`


You can test the impact of what this filter is attempting to block by scrolling down a little bit on the page and then scrolling up, with _no_ filter set, _or_ the generic filter without a domain. You should see a navbar overlay descend from the top of the page. However, when you use a domain in front of the generic filter, the filter applies and the navbar is no longer visible.

The only sites I have seen uBO work this way are on the medium blog platform, so impacted sites for example would be medium.com, backchannel.com, theringer.com, timeline.com, wearemel.com, howwegettonext.com, etc. 

The other curious thing, is that it **ONLY** seems to impact the top navbar, other generic elements that are shared between medium blog platform sites **can** be blocked without a domain in front of the cosmetic filter so I'm not sure why the navbar cosmetic filter doesn't apply when there is no domain prefix. You can test that other generic elements are being blocked without the domain name by setting the following filter that gets used by all of the domains listed above.

`##.is-visible.js-postActionsBar.postActionsBar`
`##.js-postActionsBarContent.row.postActionsBar-content`
`##.promoCard`

Test articles to show the 3 generic filters above are being applied across multiple domains that use the medium platform could be the following links:
https://theringer.com/chris-mortensen-espn-cancer-f2120a2a35cc#.lrebr1lzb
https://howwegettonext.com/translating-identity-across-the-language-barrier-66a87163a8e1#.i7ve001du
https://medium.com/buzzfeed-collections/internets-favorite-congressman-b7002ad4f3fa#.f3upjdryx

The preceding generic filters will block a couple different 'fly-in' boxes at the end of an article and **WORK** without a domain name prefix for articles on any of the previously listed domains (medium.com, backchannel.com, theringer.com, timeline.com, wearemel.com, howwegettonext.com, etc.) that use the medium blog platform.


Please note, from what I have found, the medium sites use different navbar element names such as the following:
`##.is-maximized.is-transitioning.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--tall.metabar--dark.js-metabar.u-clearfix.metabar
##.is-maximized.is-transitioning.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--tall.metabar--dark.js-metabar.u-clearfix.metabar:style(visibility: collapse)
##.is-maximized.metabar--affixed.is-hiddenWhenMinimized.is-withBottomSection.u-tintSpectrum.u-tintBgColor.u-textColorTransparentWhiteDarker.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.metabar--centered.metabar--top.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.metabar--centered.metabar--top.js-metabar.u-clearfix.metabar:style(visibility: collapse)
##.is-maximized.metabar--affixed.metabar--postArticle.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.metabar--postArticle.js-metabar.u-clearfix.metabar:style(visibility: collapse)
##.is-maximized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--hiddenWhenMinimized.metabar--tall.metabar--dark.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--hiddenWhenMinimized.metabar--tall.metabar--dark.js-metabar.u-clearfix.metabar:style(visibility: collapse)
##.is-maximized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--hiddenWhenMinimized.metabar--tall.metabar--light.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--hiddenWhenMinimized.metabar--tall.metabar--light.js-metabar.u-clearfix.metabar:style(visibility: collapse)
##.is-maximized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--light.js-metabar.u-clearfix.metabar
##.is-maximized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--light.js-metabar.u-clearfix.metabar:style(visibility: collapse)
##.is-minimized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--tall.metabar--dark.js-metabar.u-clearfix.metabar
##.is-minimized.metabar--affixed.u-tintSpectrum.u-tintBgColor.metabar--tall.metabar--dark.js-metabar.u-clearfix.metabar:style(visibility: collapse)`

but none of the navbar filters will work without a domain in front of the cosmetic filter.

Sorry if this is a long post, and I hope I clearly explain what the issue is and how to replicate the generic filters not being applied in certain situations. Please let me know if I can provide further information.

**Comment by gorhill** [comment]
@yourduskquibbles See #1885.

**Comment by gorhill** [comment]
It's always best to use specific cosmetic filters -- the generic ones should be avoided as much as possible. Generic cosmetic filters is what led to ABP et al. to inject 17,000+ (as of writing) into every page and _every_ frame on a page.
