### ISSUE TITLE
No icon in SeaMonkey

### ISSUE THREAD

**Issue by logological** [gorhill/uBlock#2024]
### Describe the issue

I installed uBlock Origin in SeaMonkey 2.40 last week, and everything worked as expected.  Today, however, I noticed that the uBlock Origin icon no longer appears next to my location bar.  I therefore have no easy way of temporarily deactivating uBlock Origin, nor of selecting page elements to block, etc.
### One or more specific URLs where the issue occurs

http://www.example.com/
### Screenshot in which the issue can be seen

![ublock](https://cloud.githubusercontent.com/assets/831326/18810248/a4a396ca-8291-11e6-8d86-881e6fba6f41.png)
### Steps for anyone to reproduce the issue
1. Load a SeaMonkey 2.40 where uBlock has been previously installed.
### Your settings

I am using the default uBlock Origin settings.
- Browser/version: SeaMonkey 2.40
- uBlock Origin version: 1.9.8
##### Your filter lists

Default filter lists + Fanboy’s Annoyance List‎ + DEU

**Comment by gorhill** [comment]
Did you look in Customize Toolbar palette?

**Comment by logological** [comment]
Oh, yes, it's there, and I can add it back.  I'm not sure why it disappeared to begin with.

**Comment by gorhill** [comment]
Did you install other extensions after you installed uBO? I know there has been reports of some other extensions "kicking out" uBO's icon from the toolbar.

**Comment by hairycactus** [comment]
> [I know there has been reports of some other extensions "kicking out" uBO's icon from the toolbar.](https://github.com/gorhill/uBlock/issues/2024#issuecomment-249380464)

Do Firefox & FF-based browsers limit the number of displayed icons on the toolbar ? (Can this be changed via `about:config` ?) In my case,  there are 9 icons (including uBO) on my FF toolbar.

In Jun 2016, the uBO icon silently got expelled from the FF toolbar, after I installed the Stylish addon which added its own icon at the end of the toolbar.  Since I don't need quick access to the Stylish toolbar icon, I removed it via  `☰ > Customize` (menu), but uBO's toolbar icon did not return. Neither was it hiding inside the ☰ menu. Even after restarting FF, uBO's toolbar icon remained totally missing.

Only after I disabled & re-enabled uBO did its icon reappear but at the end of the toolbar — after which I dragged uBO's icon to its usual location in the _middle_ of the toolbar.

I wonder why it was uBO's icon (& not any of the other extant toolbar icons) that got "bullied" & kicked out.

**Comment by logological** [comment]
Yes, I believe I installed Greasemonkey after installing uBlock Origin.  I could try uninstalling and reinstalling it to see if it removes the uBlock Origin icon.

**Comment by logological** [comment]
Just tried uninstalling and reinstalling the [SeaMonkey port of Greasemonkey](https://sourceforge.net/projects/gmport/).  It didn't remove the uBlock Origin icon from the toolbar.  I'm sure I didn't install any other extensions after installing uBlock Origin (though some may have been auto-updated).
