### ISSUE TITLE
cosmetic filter is not enforced on the site [Chromium]

### ISSUE THREAD

**Issue by zummuz** [gorhill/uBlock#2036]
### Describe the issue

There is an overlay on http://www.bucksfreepress.co.uk/ at the bottom, and it reappears after being bloked. On Firefox it stays hidden.

### One or more specific URLs where the issue occurs

http://www.bucksfreepress.co.uk/

### Screenshot in which the issue can be seen

![screenshot from 2016-09-28 19-51-08](https://cloud.githubusercontent.com/assets/13698274/18924703/e5292162-85b9-11e6-98f0-aad797e0e62b.png)
https://imgur.com/gallery/VujKa (original report)

### Steps for anyone to reproduce the issue

Go to http://www.bucksfreepress.co.uk/
Add `bucksfreepress.co.uk###__nq__hh` to block overlay
Reload the page
See the overlay's background presents nevertheless

### Your settings

default
- Browser/version: chromium 52.0.2743.116
- uBlock Origin version: 1.9.10

##### Your filter lists

default

##### Your custom filters (if any)
`bucksfreepress.co.uk###__nq__hh`

**Comment by gorhill** [comment]
Chromium-based browser limitation: there is no concept of "user style", which would override the page's style. uBO uses a few tricks which works partially in the current case (try and see difference with ABP).

For the current case, a better cosmetic filter can be used to alleviate the lack of user style, try:

    bucksfreepress.co.uk###__nq__hh:style(visibility: collapse)

Since the warning is to only demand a visitor to turn off their blocker, I will add filters to uBO's filters to remove it.
