### ISSUE TITLE
EasyList & EasyPrivacy - can't update (from "standard" check-boxes) on Windows XP

### ISSUE THREAD

**Issue by BilBg** [gorhill/uBlock#2037]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Since the links for EasyList & EasyPrivacy were changed to easylist.to they do not update from "standard" check-boxes, i.e. when using easylist.to
(they (the lists) are also one month old (28 Aug 2016) in the packages (crx zip xpi) for uBlock Origin 1.9.10)

### One or more specific URLs where the issue occurs
https://easylist.to/easylist/easylist.txt
https://easylist.to/easylist/easyprivacy.txt
https://easylist.to/

### Steps for anyone to reproduce the issue

1. Use browser based on Chromium 48 or less
2. Open in new tab:
https://easylist.to/easylist/easylist.txt

It gives:
Error code: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

- (and/or) To confirm no extension interferes - open the same link in incognito window Ctrl+Shift+N - the same ERR_SSL_VERSION_OR_CIPHER_MISMATCH

- (and/or) (in uBlock₀ — Dashboard) Check the "standard" check-boxes for EasyList & EasyPrivacy and try to [ Update now ] - they will remain "orange"

### Your settings

- Browser/version: Chromium 48, 40, 35
(IronPortable 48, IronPortable 35, FlashPeak Slimjet Portable 3.1.6.0 (based on Chromium 40.0.2214.93))
- uBlock Origin version: 1.9.10
- Windows XP

##### Your filter lists
N/A - issue is: unable to open/fetch/update from:
https://easylist.to/

All other https lists (e.g. Peter Lowe, 4x "Malware" lists) update OK, including other lists/mirrors which contain EasyList / EasyPrivacy:
Fanboy+Easylist-Merged Ultimate List
https://www.fanboy.co.nz/r/fanboy-ultimate.txt

Custom:
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://secure.fanboy.co.nz/easyprivacy+easylist.txt

P.S.
This "issue" is not problem for me as I now use the above mirrors which cover these two lists 3x times. uBlock₀ — Dashboard shows now:
Fanboy’s Enhanced Tracking List: 0 used out of 1,020
Fanboy’s Annoyance List: 1 used out of 24,387
Fanboy+Easylist-Merged Ultimate List: 105,053 used out of 105,137

Custom (3)
EasyList : 0 used out of 67,721
EasyPrivacy : 0 used out of 12,015
EasyPrivacy+EasyList : 5 used out of 79,736

(links for these "Custom (3)" are posted above)

But this "issue" may be a problem for "casual users" of older Chromium based browsers.

**Comment by gorhill** [comment]
The issue is with Windows XP -- the filter lists were moved to a server which use an encrypted connection not handled by Windows XP.

Workaround is to subscribe to the filter lists from the old (Adblock Plus) server:
- https://easylist-downloads.adblockplus.org/easylist.txt
- https://easylist-downloads.adblockplus.org/easyprivacy.txt

**Comment by BilBg** [comment]
Or you may consider adding some code to uBlock Origin to deal with additional reserve/backup/alternative/mirror homeURLs?
And in filter-lists.json :

	"easylist-downloads.adblockplus.org/easylist.txt": {
		"title": "EasyList",
		"group": "ads",
		"homeURL": "https://easylist.to/easylist/easylist.txt",
		"homeURL1": "https://easylist-downloads.adblockplus.org/easylist.txt",
		"homeURL2": "https://secure.fanboy.co.nz/easylist.txt",
		"supportURL": "https://forums.lanik.us/"
	},

(Some people which just say "It stopped working" on chrome.google.com maybe using Windows XP as me?)

**Comment by gorhill** [comment]
It's not a trivial code change, quite the opposite.

At most I could maybe change the current URL to `https://secure.fanboy.co.nz/easylist.txt` and `https://secure.fanboy.co.nz/easyprivacy.txt`.

**Comment by BilBg** [comment]
Also will be good to update all the lists included in uBlock Origin packages ("assets" directory) to current versions.
From my first post:
(they (the lists) are also one month old (28 Aug 2016) in the packages (crx zip xpi) for uBlock Origin 1.9.10)

**Comment by gorhill** [comment]
> Also will be good to update all the lists included in uBlock Origin packages

Yes, I just did -- so this should allow Windows XP users to get the latest EasyList/EasyPrivacy, uBo falls back onto the GitHub repo in case the mirrored filter lists can't be downloaded for whatever reasons. If I update these 3rd-party filter lists once a week, this will probably take care of the issue here.

**Comment by BilBg** [comment]
OK, they now updated from "standard" check-boxes (low "used" count because I have other mirrors enabled)
EasyList: 6 used out of 67,727
EasyPrivacy: 9 used out of 12,019

**Comment by lewisje** [comment]
Another workaround is to switch to Firefox, which is also a good idea because Mozilla is still supporting Windows XP (the last version to support XP will be ESR 52); relevant to this Issue, Firefox uses its own TLS implementation (NSS) rather than relying on the same TLS stack as the operating system (Schannel in Windows), so Firefox on XP can still support newer ciphers. Below is more detail.

---
I've tested easylist.to here: https://www.digicert.com/help/

I have found that it supports TLS 1.0-1.2 with the following ciphers:

    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA

I have also checked easylist-downloads.adblockplus.org, which also supports TLS 1.0-1.2:

    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_DHE_RSA_WITH_SEED_CBC_SHA
    TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA
    TLS_RSA_WITH_3DES_EDE_CBC_SHA

This is the cipher list for secure.fanboy.co.nz, which supports TLS 1.0-1.2:

    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_RSA_WITH_AES_256_GCM_SHA384
    TLS_RSA_WITH_AES_128_GCM_SHA256
    TLS_RSA_WITH_AES_256_CBC_SHA256
    TLS_RSA_WITH_AES_128_CBC_SHA256
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_RSA_WITH_AES_128_CBC_SHA
    TLS_RSA_WITH_3DES_EDE_CBC_SHA

ECDHE and AES do not exist in Microsoft's TLS implementation for Windows XP: https://github.com/client9/sslassert/wiki/IE-Supported-Cipher-Suites

**Comment by BilBg** [comment]
(I have Firefox for years but use very rarely - don't like the slow scroll ("smooth scroll" is Off I think - if that Setting was in Firefox and not in Opera 12.16), I don't intend to "switch to Firefox")

For Slimjet Portable 3.1.6.0 (Chromium 40) from:
https://www.howsmyssl.com/

The cipher suites your client said it supports, in the order it sent them, are:

TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_RC4_128_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_RC4_128_MD5

While on (I have no problem to view and use that site, it is OK):
https://secure.fanboy.co.nz/
the browser reports (with "free speech" but how to copy text from that popup?) it uses the first:
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

Here on github.com browser reports using the second:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

So your link is maybe only IE related.

**Comment by rjkpa** [comment]
You wont have such issues popping up if you're willing to ditch XP for good and get Windows 7.

**Comment by Hrxn** [comment]
Second that above. I seriously, seriously advise against using Windows XP..

**Comment by BilBg** [comment]
I'm not "willing to ditch XP", I don't have "such issues" (they are not "issues" for me)
In fact the system is multiboot but I'm not prepared to "ditch XP" as I have 100s of programs (mostly small tools) set the way I want. And I like the old driver model which is more "close to the metal".
(system is 3 core CPU, 3 GB DDR2, AMD Radeon HD 6570 1 GB DDR2, motherboard from 2006 - if you now say "buy another" then send me money, I'm on money-- )

And this is not politics thread (use another browser, use another OS (especially the OS!))
If some site owner/admin decides to ban maybe 20% of computers using Windows XP by supporting only a few newest cipher suites (despite many others are still considered strong enough and are in newest browsers) - it's not bothering me, it should bother the site owner.
And in this case why the simple http is not allowed?? This list is not bank info.

**Comment by BilBg** [comment]
I just checked - IronPortable 35 supports the exact same cipher suites as Slimjet Portable 3.1.6.0 (Chromium 40) which I posted above.

**Comment by gorhill** [comment]
I will set a weekly reminder for myself to update the filter lists on a weekly basis. For now that is the chosen solution, as it involves no code change, just launching a script to update the 3rd-party resources. Now that uAssets is split from the main project, the commit related to the 3rd-party assets won't pollute the commit related to uBO's code changes -- this used to be an issue for me, but no longer one with the uAssets spin-off.

**Comment by rjkpa** [comment]
If they're not issues, why bother posting here then ? 

You can argue all you want, but someday, those 100s of programs of yours will ditch the support XP slowly and swiftly and then you will have no choice but to ditch XP once and for all. You can be as stubborn as you want, but the fact of the matter remains, these issues are the ones which slowly erupt with time because XP is one OS which lacks mainstream support for the new features which keep coming up with day and age, and those 100s of programs of yours won't be as stubborn as you and they will update and add features which either won't work or will simply put you to torture with issues which you're not willing to accept. 

Either way, your choice. I only suggested to "change OS" as you put it, because I read Windows XP, nobody is willing to support it anymore except for some developers who take pity and continue until someday they will give up on XP too, that's all.

I would never say "buy another PC", so please don't bother presuming something like that. My own PC is from 2007 and I'm running Windows 10 on it. Politics has nothing to do with you being stubborn. I'm merely stating the FACT while you're not willing to change your OS and move to a well supported and compatible OS available for years, that's on you. Site owners never worry about OS, they only have to worry about browsers compatibility which directly depends on OS, in your case all major browsers are already hanging up on XP as MS itself has ditched it since past 2 years, so site owners have nothing to worry. You will be the one who will face issues, not just this one, but numerous ones which have nothing to do with uBlock. 

"HTTP is not allowed" because it's not considered secure, even though this is a just a filter list, nothing like an earth shattering info, it's obvious to everyone, that's why extensions like HTTPS Everywhere are being encouraged and used in masses, something you seem to have missed. HTTPS is the future, more and more sites are adopting it everyday. In your case, you may use small workarounds for a while, but the bigger issue is with the OS itself, some day you will have to ditch it. You're only delaying the inevitable. Good day.

**Comment by lewisje** [comment]
Some of the "small tools" the OP uses may also be old, or one-off tools, or so grounded in low-level Win32 programming that they even run in Windows 2000 or NT4.0; such tools also tend to still work in Windows Vista and later.

Anyway, I almost forgot, when Firefox drops support, the Pale Moon fork might still be releasing Atom builds; they're optimized for Intel Atom netbook processors, but they run fine in Windows XP on other processors.

Also, the reason for not supporting HTTP is concern that the lists may have been altered in transit: HTTPS provides protection from both eavesdropping on *and* tampering of communications. With the rise of free (but technical-ability required) Let's Encrypt certificates, a large number of sites that were HTTP-only because of cost concerns will first support, then prefer, and finally require HTTPS.

**Comment by Atavic** [comment]
Yes, Palemoon has an Atom/XP optimized build.

**Comment by BilBg** [comment]
> If they're not issues, why bother posting here then ?

They're not issues for *Me* (clear from the first post), "bother posting" for the sake of some 500 000 people (10% of uBlock Origin users) 
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0
... since nobody "bother posting" here for a few months (I posted ~this 2 times in chrome.google.com/webstore/ but this remained unnoticed)

I'm "with computers" since ~1982 (IBM-360, Apple ][+), was using MSDOS actively till ~2005 and still have Windows 98 (by XOSL can boot also to Windows 2000, but most importantly to MSDOS 5.0 + NDOS 7.0 + Stacker) for old games.
(You didn't want or need that "info" - well, I didn't need your posts either)

> and I'm running Windows 10

Now THAT is the OS to be banned (and not talking about how ugly it is, I can't stand looking at this "flatness" on posted screenshots - looking like garbage paper)
Windows 10 is "the best" trojan horse, that's why "they" are pushing it so violently.
22% share is because inexperienced users (>90%) don't know how to stop Zillion number of ways it is pushed to them:
http://blog.ultimateoutsider.com/2015/08/using-gwx-stopper-to-permanently-remove.html

> and then you will have no choice

I don't care if some program just updates for the sake of updating. E.g. I'm still on µTorrent 1.7.7 (01.02.2008) - low CPU usage 1-2%, nice "tight" GUI, still works - so why "update"... (that is not question, no need to answer)
 (µTorrent v3.x 10-15% CPU usage - tested on similar computer with less # of torrent files, need to tweak 5-6 places to stop ads/Annoyances, "sparse" GUI maybe for "mobile", the only advantage - UDP)

Best programmers write small clever programs and don't ban old OSes just for the sake of it, e.g.:
http://www.nirsoft.net/

I like that there are No more updates to Windows XP (any update have potential to "break" OS instead of fixing it), I hate Facebook and mobile devices.
So? You may continue to uselessly convince me to "move to the future", I stated my point. Will not respond.
(you are obviously very young and I'm not)

(I use HTTPS Everywhere but that have nothing to do with the "issues" here)

> You're only delaying the inevitable

Death is inevitable. 
Now just wondering ..... do I delay it for some time ... or, since it is "inevitable", just face it now ,,, hmm

(sorry, gorhill, for this useless bla-bla, no more from me, I'm off to listen some songs by Krisia Todorova)
.

**Comment by gorhill** [comment]
The issue is solved as far as I am concerned, I will update the 3rd-party lists weekly -- which is something good regardless of the issue here. Further discussions about whether one should use Windows XP or not is really not relevant to this issue tracker.

**Comment by rjkpa** [comment]
Wow that post is filled with the most moronic comebacks I have ever read. Mine clearly stated facts while yours are nothing but filled with butthurt, argumentative, stubborn rebuttals coming from a child who just wouldn't budge or try to understand. I suggested something and you took it personally, and yet after all this you call me very young, how ironic!

It's you who has lost all the sense. You would rather use Google, but you would stay with an outdated OSs and then whine here in posting issues and using the excuse for posting for those 500 K people! How utterly moronic ! It's you who's trying so hard to convince me and others that you'r correct in your aspect while you struggle through your issues, not others. Please don't bother! Nobody posted because they didn't face it or they understood the consequences of using an outdated OSs, but you didn't.

People like you should stay off the Internet, just because you despise updates so much, might as well go offline and stay like that for the rest of your life. comparing my "delaying the inevitable" to death which is another topic of it own shows how you truly suck at forming valid arguments and the fact you get so butthurt, just goes to show that there is no point in discussing with you any further. You're the child here, and my change OS argument is the one that 95 % of the people of this planet will tell you whenever you come here to moan around here about issues of some invalidated OS, while the rest of the population enjoys the benefits of the latest OSs. 

You're willing to go as far as ban Windows 10 just because your primitive mind hates it and thinks it's ugly, proves me correct, you're a pathetic baffoon from the beginning. Why I even bother to post a productive argument with you baffles me now. The only reason I still respond here is because github doesn't provide any private messaging feature yet, otherwise, children like you don't even deserve a response, truly pathetic! All you have to offer is nothing more than hate and childish arguments towards a product millions use everyday, make mentions of irrelevant websites which have nothing to do with this issue of yours, you would rather use HTTPS Everywhere, but you wouldn't move from XP to 7 is another ironic and laughable case,.

Btw death can also be delayed with proper medication and treatment, but a simpleton mind of yours had to make that rebuttal to sound cool right ? Well you failed miserably there. Adios.

**Comment by BilBg** [comment]
Just to report what Firefox supports (running on Windows XP if that matters):
https://www.howsmyssl.com/

Firefox 41.0.2
The cipher suites your client said it supports, in the order it sent them, are:

    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA
    TLS_RSA_WITH_AES_128_CBC_SHA
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_RSA_WITH_3DES_EDE_CBC_SHA

It connects OK to https://easylist.to/ using the first `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`
If they decide to support also the second `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` the site will be accessible also by Chromium based browsers on Windows XP

https://forums.lanik.us/ is also inaccessible by Chromium on Windows XP but they allow http (I don't have account there to report this and try to convince them to support more cipher suites)
`lanik.us` support the same cipher suites list as `easylist.to` (maybe they have the same owner/admin)
(used link https://www.digicert.com/help/ posted by lewisje)

    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA

**Comment by gorhill** [comment]
With 3b9fd49c508812dfe2545836c63bd5d8cfd2ead4, update should work (uBO will fallback to use one of the alternative URLs should the primary one fail).

**Comment by BilBg** [comment]
Yes, it updates from the second link in `uBlock0.chromium\assets\assets.json`
info from Logger:

11:32:35				xhr	https://easylist-downloads.adblockplus.org/easylist.txt
11:32:34				xhr	https://easylist.to/easylist/easylist.txt

If you wish you may add yet another link (maybe as No 3) for EasyList and EasyPrivacy
(I suspect "easylist-downloads" may vanish in the future):
https://secure.fanboy.co.nz/easylist.txt
https://secure.fanboy.co.nz/easyprivacy.txt
