### ISSUE TITLE
Chrome's text selection search closes the current tab

### ISSUE THREAD

**Issue by y4mz** [gorhill/uBlock#2043]
On certain pages, when the text selection web search feature is used, a new tab opens with the search as expected, but the current tab closes unexpectedly.

This occurs under Chrome 53.0.2785.143 with uBlock Origin 1.9.10, both with default settings.

To reproduce:
1. Go to http://firstload.com in a new tab.
2. Highlight and then right click on some text on the page.
3. Click 'Search Google for "some text"'.

**Comment by gorhill** [comment]
uBO's logger shows this occur because of the filter `||firstload.com^$popup` found in EasyList.

There is no way for uBO to know how the new tab was opened, just that the new tab was opened by a tab from a site for which there is an existing filter targeting popup specifically. The only solution I can think for this would be to scrap the handling of popunders for filters with the `popup` option, but that is not acceptable, there is way too many sites out there making use of popunders -- scrapping this uBO's feature for the sake of the false positive here.

**Comment by y4mz** [comment]
Fair enough. I suppose if you'd call this a bug it's a Chrome one.

**Comment by uBlock-user** [comment]
Chalk it upto Browser Limitations.

**Comment by Betsy25** [comment]
Opening a new tab from a rightclick option shouldn't be done using popup imho.
as @uBlock-user said, this is merely a Chrome issue.

**Comment by y4mz** [comment]
I noticed the problem doesn't occur when using the Selection Search extension to provide the same functionality.
