### ISSUE TITLE
Ublock origin sometimes crashs with Tampermonkey

### ISSUE THREAD

**Issue by mozkan007** [gorhill/uBlock#2074]
Sometimes Ublock Origin crashs with Tampermonkey. Then when I click the extension error section in Chrome it gives me this error : "This extension failed to modify the response header "Content-Security-Policy" of a network request because the modification conflicted with another extension (uBlock Origin)."

- Tampermonkey version: 4.1.10 
- uBlock Origin version: 1.9.10
- Chrome version : 54 64 bit
- O.S. version: Windows 10 64 bit

I am using default settings and filters.Thanks.

**Comment by Atavic** [comment]
[Related](https://github.com/gorhill/uBlock/issues/1941#issuecomment-242972994) discussion stated that Chrome browser has its own problem, plus Tampermonkey changes include sites who use CSP headers. So, check your browser and update Tampermonkey.

**Comment by gorhill** [comment]
> Ublock Origin crashs

What exactly is "crash"? What are the symptoms?

**Comment by Atavic** [comment]
I interpreted it as 'Software conflict'.

**Comment by uBlock-user** [comment]
Not exactly a crash but more of a warning because both of these extensions are modifying CSP headers for a specific site, lets take github.com for example, which is reproducible. As Atavic mentioned the issue posted by me in the thread, the symptons are same and the cause is Browser Limitation; when it comes to handling two or more extensions performing the same task on a specific site, in this case MODIFYING THE CSP HEADER. 

There is no solution for this at the moment, however, I am using a workaround to stop this from occurring.

You're using 4.1.10 which is the stable version and cannot be stopped from modifying the CSP headers.

I suggest you to uninstall the stable version and install the BETA version 4.2.53xx which has the ability to disable the CSP modification feature.

Click on TM icon in Chrome and click on Dashboard.
Click on Settings Tab
Set Config Mode to Advanced Mode.
Scroll down to Security section and find this feature titled "	
Add Tampermonkey to the site's content security policy (CSP) if there is one"
Click on the drop down menu and select No.
Disable and Reanble TamperMonkey and this will not happen ever again.

**Comment by gorhill** [comment]
Ok, due to lack of answer, I will assume OP meant "warning". By browser design, the browser is informing two extensions are trying to modify the same headers, but only one is allowed to do it.

uBO will modify CSP header when:
- blocking inline script for a site
- blanket-blocking websocket for a site

If the browser refuses uBO's change of CSP header, than uBO will fail to block inline script or websocket connections.

When changing CSP header, uBO **always** make the permissions more restrictive.

The is the opposite of Tampermonkey, which makes the permission more relax by adding the `eval` permission to CSP header.

So given this information, pick according to your prerogative.

**Comment by gorhill** [comment]
Marking this bug as invalid, because it was lacking the specific details required as per CONTRIBUTING -- especially the URL where this happens.
