### ISSUE TITLE
Number literals in selector. 

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#2116]
Hi,

To hide this div
``` html
<div id="1234"></div>
```
uBlock currently expects `###\31 234` would it be possible to allow `###1234`?

Regards

**Comment by gorhill** [comment]
Why? You ask for something without providing any argument whatsoever aside "I would like to have this". `#1234` is not a valid CSS selector, it won't accomplish anything.

**Comment by lewisje** [comment]
I'll go ahead and explain it further for the OP; first, the [CSS Selectors standard](https://www.w3.org/TR/css3-selectors/#id-selectors) (currently Level 3, but earlier versions and the latest draft are similar on this point) says:

> An ID selector contains a "number sign" (U+0023, #) immediately followed by the ID value, which must be an CSS [identifiers](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier). *[sic]*

That page (from CSS2.1, which the later CSS standards build from) says:

> In CSS, *identifiers* (including element names, classes, and IDs in [selectors](https://www.w3.org/TR/CSS21/selector.html)) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

After that, it gives a fuller explanation of character-escapes.

---
Basically, what you're asking gorhill to do is re-format entered filters like `###65` to `###\36 5` (conveniently, the hexadecimal ASCII code for each digit is 3 followed by the digit); it sounds simple enough, but he could well be introducing bugs in the process of trying to figure out what you meant, rather than putting the onus on you to figure out how to write valid CSS selectors.

**Comment by kasper93** [comment]
@lewisje Don't worry. I understood what gorhill have said (after checking css spec). And I'm fine with it, otherwise I would have reply. I simply missed the fact that CSS identifiers cannot start with digit.

**Comment by gorhill** [comment]
> Basically, what you're asking gorhill to do is re-format entered filters like ###65 to ###\36 5 (conveniently, the hexadecimal ASCII code for each digit is 3 followed by the digit); it sounds simple enough, but he could well be introducing bugs in the process of trying to figure out what you meant

Bugs would be introduced for sure, because it is impossible for uBO to know whether something has been escaped already or not. Although `#\36 5` does _look_ already escaped, maybe it is not (maybe user really wants `\#\\36\ 5`), there is just no way to know.

**Comment by kasper93** [comment]
@gorhill I understand. One last thing tho. Maybe uBlock element picker could suggest `##[id="107"]` instead `###\31 07` when escaping is needed? Again it is just me thinking it would be clear for layman to understand what's going on. Feel free to ignore this suggestion if you don't like it. Cheers. :)

**Comment by lewisje** [comment]
Oh, I was thinking you were just putting it into "My filters" and wondering why it wouldn't work: Anyway, ID selectors take precedence over attribute selectors and therefore are preferred for hiding rules; a similar argument applies to class vs. attribute selectors.
