### ISSUE TITLE
Firefox loads pages forever

### ISSUE THREAD

**Issue by cemsbr** [gorhill/uBlock#2123]
### Describe the issue
For example, while writing this issue [1], I see in the status bar "Read assets-cdn.github.com" and there is a spinning icon in the tab. It happens in every tab I have opened so far. Another example is duckduckgo [2], where I see "Transfering data from duckduckgo.com". If I disable uBlock and refresh the page, the page loads completely and the favicon appears very quickly.

### One or more specific URLs where the issue occurs
- [1] https://github.com/gorhill/uBlock/issues/new
- [2] https://duckduckgo.com/
- https://www.google.com/

### Steps for anyone to reproduce the issue

1. Just visit the URLs above
1. Notice the spinning icon in the tab and the status bar message

### Your settings
No uBlock settings changed

- Browser/version: Firefox 49.0.2
- uBlock Origin version: 1.9.16

##### Your filter lists

Default, didn't change any settings.

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
> If I disable uBlock and refresh the page, the page loads completely and the favicon appears very quickly.

Disable how?

**Comment by gorhill** [comment]
> "Read assets-cdn.github.com" and there is a spinning icon in the tab

This is the symptom of a connection issue, not a uBO issue. This doesn't pass the make-the-case bar.

**Comment by cemsbr** [comment]
To be clear, by disabling, I mean clicking in the uBlock icon and, in the pop-up that appears, in the big blue power button and then in the refresh icon. I closed and opened Firefox and the problem persists. In uBlock logs, both github.com and google.com have loaded (not blocked) assets from the same domains as seen in the status bar as being forever downloading. Therefore, I don't think this issue is due to a file being blocked by a list.

**Comment by gorhill** [comment]
The spinning icon means your browser is waiting for the server to send a response to a request, that the server is not responding, or is taking long to respond is outside the control of uBO.

> Therefore, I don't think this issue is due to a file being blocked by a list.

The fact that by disabling uBO for the site solves the issue does point to a filter issue. uBO is still functioning and intercepting network requests, it just no longer filter them. Instead of disabling uBO, unselect filter lists one at a time until the problem disappear. This will tell you what filter list is interfering.

**Comment by cemsbr** [comment]
In case anybody else has this problem, disabling the Hola add-on (just turning off doesn't work), as described [here](https://www.reddit.com/r/firefox/comments/3eg32z/has_anyone_else_noticed_ublock_origin_is_stopping/), also solves the problem. Unfortunately, having both uBlock and Hola add-ons enabled doesn't work in Firefox, but it works in Chromium (probably in Chrome, too).

**Comment by gorhill** [comment]
Maybe related to #2173?

**Comment by m3Lith** [comment]
Don't even look into Hola. [It's pure evil](http://www.pcworld.com/article/2928340/ultra-popular-hola-vpn-extension-sold-your-bandwidth-for-use-in-a-botnet-attack.html). It has been removed from the official Firefox add-ons store ever since and everyone still using it should be advised to uninstall immediately. @cemsbr, see [this](http://adios-hola.org/uninstall/firefox.html).

**Comment by cemsbr** [comment]
@gorhill, as m3Lith said, it can't be found in the official Firefox add-ons store. If you want to install it, it must be done from hola.org. It is the easiest way to listen to Pandora outside U.S.

**Comment by gorhill** [comment]
No need to install, it was just to look at the source code. If the extension used the webextension API + listened to chrome.webRequest.onErrorOccurred events, I could confirm it is related to #2173.
