### ISSUE TITLE
Works even disabled

### ISSUE THREAD

**Issue by roman4e** [gorhill/uBlock#2150]
### Describe the issue
I have disabled the add-on.
But it works even disabled.
Look at the screen-shots below please

### Screenshot in which the issue can be seen
![screenshot_083](https://cloud.githubusercontent.com/assets/10156713/20246032/cb8db5bc-a9b6-11e6-9537-b1de512373d3.png)
![screenshot_084](https://cloud.githubusercontent.com/assets/10156713/20246031/cb8c6b76-a9b6-11e6-918c-6593d6b63fe6.png)
### Steps for anyone to reproduce the issue

1 Open add-ons manager. 
2 Disable the add-on
3 Open any site with adverts. (even there on the Github it works)

### Your settings
- Browser/version: 
Mozilla Firefox 49.0.2 for linux mint
- uBlock Origin version: 
1.9.16

**Comment by gorhill** [comment]
Unable to reproduce. As soon as I disable the extension, it's toolbar icon disappears, and ads appear, for example typing "buy car" in Google Search, or visiting <http://arstechnica.com/security/2016/11/new-attack-reportedly-lets-1-modest-laptop-knock-big-servers-offline/>.

I am skeptical of your screenshot showing uBO disabled but yet having its icon enabled present in the toolbar. You will have to investigate this yourself on your side since I can't reproduce.

**Comment by roman4e** [comment]
I'm sorry I cannot repeat it again after the complete uninstall and install again.
