### ISSUE TITLE
Blocking a DOM element in Javascript rather than entire script

### ISSUE THREAD

**Issue by jtechpro** [gorhill/uBlock#2154]
### Description
The ad bars (top and left side) are showing up on the site mio.to. The site seems to run a javascript called app.js which contains the code `window.zads.push()` which is _periodically_ pushing the ad divs.

### One or more specific URLs where the issue occurs
http://mio.to

### Screenshot in which the issue can be seen
![ad-top](http://imgur.com/CyyEOWul.png "Top ads")
![ad-left](http://i.imgur.com/yV3UKUr.png "Left ads")
Look at the top space (white ad bar). Wait for some time, to show the left side also.

### Steps for anyone to reproduce the issue
Just going to the mio.to site is itself enough to know the issue. The issue is that the DOM element `zads` is not blocked. When I deleted it with Firebug then there arouse errors in the Javascript which lead to the non-functioning of the site, like the autocomplete feature, playing feature since all the features including the ads are written in one javascript file.

### Settings

- Browser/version: Firefox 49.0.2
- uBlock Origin version: 1.9.16

##### Your filter lists
Default uBlock Origin filters + hPHosts' Ad and Tracking Servers + EasyList + EasyPrivacy + Peter lowe's Adserver list + Fanboys Enhanced Tracking list + Malware domains list + Malware domains + Malware domains (longlived) + Fanboys annoyance list + MVPS Hosts + Dan Pallocks Hosts file.

##### Your custom filters (if any)
mio.to##script:contains(ad-top)
mio.to##script:contains(ads-perm-right)
mio.to##script:contains(zads)
mio.to###ad-left
mio.to###ad-left-close
mio.to###ad-top
mio.to###ad-top-close

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by TomPeterison** [comment]
@gorhill Filter list issue has nothing to do with it. Filter lists can block Javascript files or some urls based on dynamic filtering.

The issue here is not of blocking a specific script. It is also not of blocking an inline-script like as you said in the wiki script##contains(). However, it is the case of preventing a part of javascript code from execution not all of the code but only a function call.

Here as per the above, it is something like preventing window.zads.push() function call.

If it is a filter list issue what can you write in order to prevent the ad-left and ad-top?
