### ISSUE TITLE
Ublock does not appear in Search Results on https://addons.mozilla.org/

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#2196]
It's not an issue. Just FYI. Adblock Plus gets most downloads (60.000/day) through the "Manage Addon Section" inside the firefox browser itself. If you search with the most public string "adblock" ublock doesnt appear at all. Ublock generates only 5000 downloads per day through the "Manage Addon Section".  

Perhaps it makes sense get ublock rank higher. 

### One or more specific URLs where the issue occurs

See: https://addons.mozilla.org/de/firefox/addon/ublock-origin/statistics/downloads/sources/?last=30
https://addons.mozilla.org/de/firefox/addon/adblock-plus/statistics/downloads/sources/?last=30

**Comment by gorhill** [comment]
> If you search with the most public string "adblock" ublock doesnt appear at all.

It's in there in the list. In any case, as stated on the front page of the project, uBO is not an "ad blocker", it's a [content blocker](https://github.com/gorhill/uBlock/wiki/Blocking-mode), so it's expected it won't show up when searching "adblock".

**Comment by gwarser** [comment]
"Content blocker" not work https://addons.mozilla.org/en-US/firefox/search/?q=content+blocker

**Comment by gorhill** [comment]
Whatever issue is seen for AMO should be reported to AMO. uBO is just a hobby project, nothing more -- starting to worry about these stats is to spend time/energy on the wrong things. The code/doc/filters is where time/energy is best spent.

**Comment by uBlock-user** [comment]
Jesus Fucking Christ! 

You two sound completely ridiculous. Why the hell would you ever search "adblocker" for uBO on AMO? 

1) Adblock/er is a prominent word on the Internet as all blocking extensions use that unlike uBlock and few others. Secondly, because of this, uBlock, in terms of ranking, is behind because it's not operated as an adblocker neither advertised as an adblocker, hence all search engine rankings would be lower for uBlock and similar addons as they're not keenly associated with adblocking typically unlike Adblock Plus and Adblock itself.

2) Have you bothered to take a peek at the AMO page itself lately? **uBO is listed as the 4th MOST POPULAR addon on FF**[#], so why the hell would bother to search something which is already listed on the front page of AMO, damn it just click on the listed link. # - https://i.gyazo.com/116b4b1c0a45b7643e487acf1ddb3c50.png

3)There's no reason to search for it on AMO, but if you're still hell bent on it. Why not try searching as uBlock or uBlock Origin ? It's common sense. It's a hobby project and is not famous as other adblockers, not to mention, it's never advertised anywhere hence it hardly gains any traction, the only reason it has got famous this far is because of word-of-mouth. Posting an issue here just because for this is simply pointless and insensible.

**Comment by anewuser** [comment]
In case you want to submit actual issues related to the Mozilla site (not the current discussion) in the future, use this repository: https://github.com/mozilla/addons/issues
