### ISSUE TITLE
Unworkable alert page

### ISSUE THREAD

**Issue by ViperCode7** [gorhill/uBlock#2229]
Sometimes, instead of getting a working alert page I get this, see attached image.

The URL of most recent one is:
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html?details=eyJ1cmwiOiJodHRwOi8vYWQuemFub3guY29tL3BwYy8/MjkzNzU2NDhDMTMwMzc1NjQ0OVQmenBhcjQ9W1tzKnNuZWpneTJzeTRzaXprZ3lqem0xcXgtRENTLTNibTFpaTIyNipqeXFzeHAqM3N6XV0iLCJobiI6ImFkLnphbm94LmNvbSIsImRuIjoiemFub3guY29tIiwiZmMiOiIwXHUwMDBiLlx1MDAwYmFkLnphbm94LmNvbSIsImZzIjoifHxhZC56YW5veC5jb21eIn0=

![page](https://cloud.githubusercontent.com/assets/6399179/21014217/d239ccf8-bd65-11e6-9625-3098a3aa7ada.jpg)

I came from https://www.schlaubi.de/internet/drosselung and after each redirect page ( of 3 seconds ) for each offer I get this page,

Settings:
[my-ublock-backup_2016-12-08_16.52.39.txt](https://github.com/gorhill/uBlock/files/639720/my-ublock-backup_2016-12-08_16.52.39.txt)

- Browser/version: Chrome 55 x64
- uBlock Origin version: 1.10.0

**Comment by gorhill** [comment]
Look at the dev console when this happens (Ctrl-i), see if there are error messages. I pasted the link in my address bar, and the page displays just fine. It's as if uBO's page is prevented from using its own secondary resources. Do you have any custom settings for your browser? What OS are you using? Is Chrome 55 a stable version? If not, try whatever version is the stable one (53?).

**Comment by ViperCode7** [comment]
It works... that's the issue. I can't figure out why it doesn't work when it doesn't.
In the console pages, the past times when I've checked it said ERR BLOCKED BY CLIENT and the resource path was that of uBlock (css etc).

I'm on a stable chrome version. My Chrome flags, some are old but nevertheless: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --js-flags="--expose-gc" --process-per-tab --enable-async-dns --cipher-suite-blacklist=0x0033,0x0039,0x009E,0xcc15

**Comment by gorhill** [comment]
Well, that is weird. I just went to check something again and I just reproduced it, and I do have the `ERR_BLOCKED_BY_CLIENT` in the console. If I put a breakpoint in uBO's network handler's code, it is not being called when I force-reload the page. So something is blocking the resource, but I have no clue what (I have no other extensions). Could be a browser issue, I need to investigate more.

**Comment by sxymon** [comment]
Hallo
Prosze abys wytlumaczyl mi co to jest co piszesz do mnie bo dopiero
zaczynam tworzyc repozytorium i jeszcze nie potrafie wszystkiego zrozumiec
bylbym ci wdzieczny
                  H

08.12.2016 4:38 PM "ViperCode7" <notifications@github.com> napisał(a):

It works... that's the issue. I can't figure out why it doesn't work when
it doesn't.
In the console pages, the past times when I've checked it said ERR BLOCKED
BY CLIENT and the resource path was that of uBlock (css etc).

I'm on a stable chrome version. My Chrome flags, some are old but
nevertheless: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
--js-flags="--expose-gc" --process-per-tab --enable-async-dns
--cipher-suite-blacklist=0x0033,0x0039,0x009E,0xcc15

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gorhill/uBlock/issues/2229#issuecomment-265770442>, or mute
the thread

**Comment by gorhill** [comment]
Here is how I can reproduce on my side:

- Activate my local (development) installation of uBO in `chrome://extensions/` (it has its own id).
- Open a new tab.
- Paste the URL `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html?details=eyJ1cmwiOiJodHRwOi8vYWQuemFub3guY29tL3BwYy8/MjkzNzU2NDhDMTMwMzc1NjQ0OVQmenBhcjQ9W1tzKnNuZWpneTJzeTRzaXprZ3lqem0xcXgtRENTLTNibTFpaTIyNipqeXFzeHAqM3N6XV0iLCJobiI6ImFkLnphbm94LmNvbSIsImRuIjoiemFub3guY29tIiwiZmMiOiIwXHUwMDBiLlx1MDAwYmFkLnphbm94LmNvbSIsImZzIjoifHxhZC56YW5veC5jb21eIn0=` in the address bar of that new tab.
- Result: error page "This site can’t be reached" -- because the URL is for the published version of uBO, ids do not match.
- Disable my development version of uBO in `chrome://extensions/`.
- Enable the published version of uBO in `chrome://extensions/`.
- For a refresh of the tab for which there was an error.
- Result: issue reproduced.

However as you can see, it's not a normal situation: I enabled the published version of uBO *after* a tab belonging to it was (tentatively) opened (the `document-blocked.html` one).

**Comment by ViperCode7** [comment]
I was thinking the same.... I went away for 2 months and since then I haven't updated Chrome. Then I've updated it to 55 and these errors started.

**Comment by sxymon** [comment]
Dziekuje sprôbuje zrozumiec co sie dzieje dziekuje za info

08.12.2016 5:04 PM "Raymond Hill" <notifications@github.com> napisał(a):

**Comment by gorhill** [comment]
When the issue occurs, the extension bindings are not there, the list is empty:

![a](https://cloud.githubusercontent.com/assets/585534/21017724/4d747ebe-bd38-11e6-8cc1-e78dc43193fc.png)

![a](https://cloud.githubusercontent.com/assets/585534/21017555/c7b6f4f0-bd37-11e6-8c9b-56390ffb7350.png)

So at this point I believe this needs to be reported to Chromium developers, this is outside of uBO's realm.

**Comment by ViperCode7** [comment]
I don't know anymore...
I've updated to 56 and it got worse. Usually closing the malfunctioning tab and reopening it would allow the resources to pass through, but now every single page, even uBO's options page refuse to work, same thing, net::ERR_BLOCKED_BY_CLIENT

**Comment by ViperCode7** [comment]
Edit, nevermind, I figured it out after disabling every extension and checking every permission setting that I also had program switches and particularly --process-per-tab was causing this issue.

If I remember correctly it was in the late 40's versions that tabs stopped opening each in their own process, and now it seems it caught up completely and that function is now useless. Thanks Google for yet again deciding for us what's (not) best.
