### ISSUE TITLE
Possible bug in 1.10.3b0

### ISSUE THREAD

**Issue by olgon** [gorhill/uBlock#2250]
Changed behavior of :style operator
This filter
`example.com##body:style(background-color: red;)`
worked in 1.10.2 

In 1.10.3b0 filter don't work without  `!important`
`example.com##body:style(background-color: red !important;)`

Browser: Firefox 52

**Comment by gorhill** [comment]
Remove trailing `;` please. See release notes.

**Comment by gorhill** [comment]
Never mind, thought it was about `matches-css`.

Just checked, `example.com##body:style(background-color: red;)` and I can reproduce with Firefox. I see the style properly injected, but overridden by the page style. Need to investigate.

**Comment by gorhill** [comment]
Ok, I just learned the `important` keyword is necessary to enforce that user styles override page styles. If (order matters):

- uBO style: body { background-color: red; }
- Page style: body { background-color: gray; }

Page style wins. If:

- uBO style: body { background-color: red !important; }
- Page style: body { background-color: gray !important; }

uBO wins.

It was working before because of luck: Most likely uBO style was inserted after the page's own style, causing it to win. So it appears using `!important` for user styles guarantee these styles always win, regardless of the order, and regardless of whether the page styles also have `!important`.
