### ISSUE TITLE
dynamic filter popup issue

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#2275]
i have no-popups: * true in my dynamic filters. i go to kisscartoon.me and right click a link and it trys to open then closes because i have popups blocked. 

so i add this: kisscartoon.me http://kisscartoon.me popup allow

still blocked. shouldn't adding the above override the no-popups: * true ?

i am on the latest ublock test in chrome browser

**Comment by gorhill** [comment]
`no-popups: kisscartoon.me false`, or just use the UI to toggle it.

**Comment by harshanvn** [comment]
Not sure, if i should create a separate issue or not. Please let me know if you want -

Allowing a pop-up through the logger (**instead of toggling it through UI**), will actually create a incorrect rule  as shown below -

`github.com https://github.com popup allow`

instead of `no-popups: github.com false`

So, I believe OP here used logger to create a exception rule for `no-popup * true `rule
