### ISSUE TITLE
Fake News Adblock List

### ISSUE THREAD

**Issue by SMed79** [gorhill/uBlock#2286]
Hi, 
@ryanbr (fanboy) just created a new [adblock list](https://github.com/ryanbr/fanboy-adblock/blob/master/fake-news.txt) which is intended to block **fake news sites**.

`Targeting sites with Hoax, propanganda and clickbait (fake sites)`

Could you please add it to the regular uBO subscriptions lists?

source: https://forums.lanik.us/viewtopic.php?p=111302

Best,
M.

**Comment by sdfasdfgawe456h4356** [comment]
I dont think this list should be added. It would be completely unfitting because all the other lists that have been added to the subscriptions list are about trackers/malware/ads and then suddenly a list with websites that someone feels are fake news ? Just doesnt fit.
Also: who can really objectively decide what is fake news and what not ?
If youre not all-knowing you cant.

**Comment by ryanbr** [comment]
Personally I don't care what "sdfasdfgawe456h4356" thinks of it.

` Also: who can really objectively decide what is fake news and what not ?`

! Sources: http://fakenewswatch.com/ 
! https://en.wikipedia.org/wiki/List_of_fake_news_websites
! https://docs.google.com/document/d/10eA5-mCZLSS4MQY5QGb5ewC3VAL6pLkT53V_81ZyitM/preview

thx. come again.

**Comment by gorhill** [comment]
I did not decline because of @sdfasdfgawe456h4356's comment, I declined for my own reasons. There are the obvious nonsense sites, but there is subjectivity involved in adding or _not_ adding some sites to such list<sup>[1]</sup>. There are always been "fake news" (somehow it's a trendy expression now as if it's a new thing). My view is that the cure is critical thinking, not a ready-to-use list in uBO. Whoever still want to use it can just import it as any other list.

[1] Example, why is The Guardian not there? [Here is a citation](https://theintercept.com/2016/12/29/the-guardians-summary-of-julian-assanges-interview-went-viral-and-was-completely-false/).

**Comment by sdfasdfgawe456h4356** [comment]
@ryanbr thank you very much for your input but there is no reason to get upset :)
the links you posted are maintained by humans too... who are (like everyone is) fallible and biased

have a nice day :)

**Comment by Hrxn** [comment]
Is this _fake news_ list officially verified by the Ministry of Truth?
If not, I support the decision to decline this suggestion.

**Comment by Betsy25** [comment]
Exactly, this whole "Only CNN is telling us the truth" thing needs to stop. It's a joke, nobody still trusts them, and they are running wild screaming. We all know we can't trust the mainstream media, thank goodness we still have alternative media.

**Comment by giantslor** [comment]
The main resource I use to evaluate a site for bias and accuracy is [Media Bias / Fact Check](https://mediabiasfactcheck.com). It's the most comprehensive and objective resource, and they have a [very useful extension](https://chrome.google.com/webstore/detail/official-media-bias-fact/hdcpibgmmcnpjmmenengjgkkfohahegk).

Regarding sites like The Guardian and CNN, they lean left but are committed to the facts. One false article does not mean the whole site is fake -- every news organization has had to retract a story at some point in its existence. Conversely, fake news sites are those whose very business model is to run mostly fabricated or highly misleading stories in order to get clicks.
