### ISSUE TITLE
Blocking not working after page refresh 

### ISSUE THREAD

**Issue by moongose** [gorhill/uBlock#230]
Please check this site http://reklama5.mk/

I manually block all the banners on the right side, they disappear, but after refreshing or changing the page they all come back.
How do I make those blocking permanent?

Opera 29 with latest µBlock v0.9.7.5 on win7 x64

**Comment by gorhill** [comment]
I don't see any banner on the sides.

**Comment by gorhill** [comment]
OK, next time, **please be specific**: I should not have to spend time trying to figure what to do to reproduce an issue, especially that you only had to provide an **exact URL** where the problem can be seen.

The issue is present on **other** pages on the site, but **not** on the URL you provided.

The issue is because there is an exception filter in EasyList which applies to all of `reklama5.mk`. So the solution is to override that exception filter using the `important` filter option:

    ||reklama5.mk/GetBanner$important
    ||reklama5.mk/img/banner/$important
    ||reklama5.mk/Search/GetPremiumAds$important

I won't always care to spend my time -- however cheap it appears to be to many -- to guess what is the issue.

**Comment by moongose** [comment]
I apologize for misleading you with the link. Your solution works perfectly.
Thank you for your time and effort

**Comment by gorhill** [comment]
Just going to add a note for future reference that this is a good use case (and demo case) for the [coming URL filtering feature](https://github.com/gorhill/uBlock/releases).

**Comment by gorhill** [comment]
@moongose 

You might want to also add `reklama5.mk###dvBanner2` as custom filter, this will collapse the top area where the banner was sitting.

**Comment by moongose** [comment]
Thx, but didn't notice any difference. The top area was collapsed too with your first solution.
No worries.
