### ISSUE TITLE
site functionality broken even disabling ubo for the site

### ISSUE THREAD

**Issue by mapx-** [gorhill/uBlock#2317]
issue only in chrome, ubo 1.10.4

site:
marketers.coop

steps to reproduce the issue:
https://issues.adblockplus.org/ticket/4808

the site is broken in ABP too (as the issue above)

**the site is working only disabling the extension in the extensions page.
still broken disabling ubo for the site or disabling all the lists in ubo.**

(no issue in firefox at least in ABP)

**Comment by gorhill** [comment]
Same with Adguard.

**Comment by viraladmin** [comment]
Do we have any kind of updates on this?

**Comment by gorhill** [comment]
I read the latest comments at <https://issues.adblockplus.org/ticket/4808>, and I tried [your minimal test case](http://admin.marketers.coop/abptest.php) without any blocker or any extensions installed in Chrome 57. Your POST still failed:

![a](https://cloud.githubusercontent.com/assets/585534/22375291/67493dd2-e477-11e6-96ed-c299ec077c96.png)

So this means your issue is not related to uBO or ABP or whatever else extension, it's a browser issue (it works fine with Firefox).

**Comment by viraladmin** [comment]
So this means your issue is not related to uBO or ABP or whatever else extension, it's a browser behavior

If this is the case, why does chrome add credits on my site, unless uBO or ABP are installed. I am not the one who narrowed it down to that error. I was told by people within ABP that was what was causing the problem, however you are correct, when using my site - that error appears whether the plugin is installed or not, the difference is, when the plugin is install, its blocking the credits from being added to the users account - without the plugin installed it does not - as was in fact tested and shown to be true by others after I reported the ticket, disabling the plugins from the browser extension tab fixes the issue.

**Comment by viraladmin** [comment]
This should not be closed after it has already been verified as a bug by people. If the plugin is not installed my site works perfectly this is NOT a browser issue.
