### ISSUE TITLE
Regular expression does not work in the filter of logger since 0.9.7.0

### ISSUE THREAD

**Issue by g3939434** [gorhill/uBlock#232]
Since the version of [0.9.7.0](https://github.com/gorhill/uBlock/releases/tag/0.9.7.0), which had been imported the Unified logger from uMatrix. Regular expression does not work in the filter of logger anymore.

Quote from wiki - [network request logger](https://github.com/gorhill/uBlock/wiki/The-network-request-logger/9f9c25eb8bd0a1419cd685d476ca98e9209af9c0)

> The filter expression can be a plain regular expression:
> - `/image|css/`: show all requests which type is `image` or `css`
> - `!/image|css/`: show all requests which type is not `image` neither `css`

**Comment by gorhill** [comment]
The new expression parser is different, it's more flexible overall, whereas I chose to support regex with the old parser because of its inherent limitations.

The first case can't be replicated with the new parser however.

The second case can be replicated using simply `!image !css`.

For the first case, if really needed, I may choose to support a custom syntax which less advanced user can use, maybe `||` to _or_ expressions together (default is to _and_ them).

**Comment by gorhill** [comment]
The filter expression parser now supports `||` to be used to _or_ together subexpressions (in the end I chose `||` because this is language-neutral). Regular expressions are still not supported, as the end goal is not to support regexes, but to support a syntax which allows to support _or_'ing expressions together.

So equivalent for `/image|css/` is now `image || css`, and `!/image|css/` is now `!image || css`, or equivalent `!image !css`.
