### ISSUE TITLE
Leverage Firefox's upcoming All-in-One Fingerprint resistance

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2381]
### Describe the issue
Hello Raymond. You made it clear recently (#2378, #1647) that you don't want to go down the rabbit hole of implementing fingerprint protection because it's a wide and deep endeavor that warrants its own add-on.

I understand. How about one all-encompassing option that puts the burden of implementing fingerprint resistance on the browser?  As part of the [Tor Uplift project](https://wiki.mozilla.org/Security/Tor_Uplift), Firefox devs intend to implement a single config that tells the browser to resist fingerprinting.
```
privacy.resistFingerprinting = true
```
The devs will strengthen the effect of this setting over time, a bit like Private Browsing mode. In fact there is [discussion on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1308340#c11) about possibly enabling this by default when in Private Browsing mode (same as Tracking Protection).  Initially, the discussed effects are:

> It does offer some significant protection (including hiding system colors, screen orientation, screen dimensions, device pixel ratio, window position on screen, screen click coordinates, supported mime types and installed plugins) ([source](https://bugzilla.mozilla.org/show_bug.cgi?id=1308340#c5))

This alleviates your concern (no need to continually update uBO to block new fingerprinting vectors) while still providing ever-improving protection to users.

**Comment by uBlock-user** [comment]
Does this include Canvas Fingerprinting too ? Also I suppose this is limited to Firefox only ?

**Comment by gorhill** [comment]
I've been subscribed to this bug since a while to see how it involves and see if I can make use of it in uBO.

**Comment by Atavic** [comment]
@uBlock-user I don't think so.
https://github.com/pyllyukko/user.js/issues/203

**Comment by Thorin-Oakenpants** [comment]
AFAIK WebExtensions cannot change FF internals, so IMO, I think it's better to just forget it. Mozilla plan to add a preference to this to the UI. That said, it should be pretty simple and straight forward to add an option & code to chrome://ublock0/content/dashboard.html#settings.html for the non WebExtension version. But then .. you'd need to add an info button and deal with any fallout from the dozens of pref changes - such as no site specific zooming, no reader view, time-zone issues in gmail etc due to spoofed UTC 0, and heaps more. Although not hard to close tickets, it's still a time waster. I'd rather this was ignored.

**Comment by gorhill** [comment]
> AFAIK WebExtensions cannot change FF internals

I am assuming the setting will be available through the `browser.privacy` API.

**Comment by Thorin-Oakenpants** [comment]
relevant link for people: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/network

**Comment by tumpio** [comment]
There is no All-in-one solution to browser fingerprinting. uBlock can be used as a blocker for fingerprinting hosts or scripts for which there are some filter lists available.

The bug discussed in this topic (bug 1308340) is about enabling the in-build browser fingerprinting countermeasures through a privacy setting option. The comment by Simon provides a valuable information regarding the browser fingerprinting : https://bugzilla.mozilla.org/show_bug.cgi?id=1308340#c20

> AFAIK WebExtensions cannot change FF internals

Yes, as observed in comment by Kris, https://bugzilla.mozilla.org/show_bug.cgi?id=1279371#c6

> Traditional extensions had access to all requests because they ran with the full privileges of the browser. WebExtensions are designed to be sandboxed. **They're not meant to have access to implementation details of the browser**, and they're especially not meant to have access to security-sensitive requests such as update checks and OCSP checks.

**Comment by elypter** [comment]
its kind of a srtetch calling something a countermeasure when the browser actively included the methods in question and knew about its misuse for over a decade. but at least finally something is being done about it. there is currently no way to browse comfortably(without losing all cookies&history) and with the smallest possible fingerprint. and even if you modify the TorBrowser to be be an every day solution by switching on saved passwords, history and cookies(managed with an addon) and install ublock you still have many more safety measures than a default firefox but its worth nothing because you are already unique because of your unique modifications. this could only be stoped if there was a comfortable option that many use of active spoofing by sending different plausible looking information on each request.

**Comment by Atavic** [comment]
Maybe it's off-topic, but various discussions like this do not mention a simple solution: use more than one browser.

Usually internet users deal with two kinds of browsing, a casual one that includes various searches and clicks on RSS feeds and a personal one where the users logs into a site or forum with it's own nickname.

Different browsers for different purposes render this problem easy, IMHO

**Comment by elypter** [comment]
but some people have dozens of identities and it becomes impractical to have everything spread over muötiple browsers or profiles.

**Comment by Atavic** [comment]
I use always the same browser when I log into some site. If I'm on another hardened browser, I use an addon as [Open with](https://addons.mozilla.org/en-US/firefox/addon/open-with/) to start the other browser that I use to log into sites.

**Comment by ublock-user123** [comment]
Hi @gorhill, you've probably already seen it, but since it wasn't mentioned in this thread I thought I would post the link to a different bugzilla relating to this (id=1397611):

https://bugzilla.mozilla.org/show_bug.cgi?id=1397611

Unless I'm misunderstanding, it looks like it's now possible to toggle `privacy.resistFingerprinting` on/off through webextensions.

**Comment by gorhill** [comment]
I prefer to decline for now, it turns out enabling `resistFingerprinting` has a lot of consequences and very often users are unable to understand many apparent malfunctions are directly linked to their use of the settings, and it's the reason the setting is not currently exposed in Firefox's _Preferences_.
