### ISSUE TITLE
FEATURE REQUEST: Website Reporting (malicious sites) 

### ISSUE THREAD

**Issue by bandaid** [gorhill/uBlock#2389]
Looking for an addon to uBlock Origin to report malicious sites, the data collection and implementation to block these sites doesn't necessarily have to be controlled by uBlock Origin developers, but by the script writers for filters and other mainstream developers. The more honest people involved the better. I would suggest the reporting tool provide the user the ability to report a malicious webpage (ie: demanding Flash installation, spoofed Microsoft fatal errors, critical alters about a 'found' virus, etc..) and collect the page URL and data, which will then be anonymously (or not) sent to all the filter writers and uBlock Origin for review. 

In the aspect of review, you can have thousands of users reporting *cnn.com as a malicious site (well... not really, but their journalists are nimble-minded just as many media outlets), versus lets stay a real crap malware site as https://f190211.4privacybrowsing.com ([**].4privacybrowsing.com)... is one of the tens-of-thousands of malware sites and it's one of many that still is not blocked. Get the point? 

Malicious sites are seriously intrusive and very annoying to advanced users, not only, the elderly and inexperienced user will likely fall victim to the scams on these websites by just clicking areas where the site demand's a user to select an affirmative action or download malicious software... whereas causing either a virus, sensitive data being stolen, or even worse ransom-ware. 

***I do not have any type of social media account, nor subscribed to the Mozilla uBlock Origin support page. I will not sign up to them, period. So, I highly doubt this will get noticed here on Git but it's an attempt.

**************
**************
(**PS: If someone could make a tool to redact mainstream media sites from spewing out incoherent nonsense about subjects or 'news' they think they know the answers to, especially in this generation, that would be great. The only concern the Media has today is viewer-ship, not facts about a matter... they rather spew out garbage to attain headlines,  The media use to actually report the news, but today... journalists have to spew their mindless inexperienced ideologies into the mix, which then a bunch of mindless sheep jumping onto a bandwagon begin following journalist nutjobs, including senators, Elon Musk, and other notable individuals. Sad.)

**Comment by uBlock-user** [comment]
Usually malicious websites get reported and get blocked by Malware filterlists which saves the time for review and discussion. I doubt anyone here would bother to undertake the responsibility to review, report and maintain the list which is already being done by the aformentioned Malware filterlists.

**Comment by bandaid** [comment]
You're correct, however, there are tens of thousands malicious sites the Malware filterlist's do not catch, especially pop-ups (*which is why  HOSTS file is important too). But that's the purpose for requesting a website reporting tool within uBlock Origin to help report cheesy-malicious sites. As previously noted uBlock Origin developers don't need to involve themselves other than implement the feature to hand off data regarding a malicious site in the reporting to known Malware filterlist/host developers.  

Of course this feature would require manual reporting of such sites, but all the specific details required (ie: URL and screenshot) would be automatically captured to help the user report, or upload the details to a GIT where all developers can view and make adjustments to their filters.

**Comment by uBlock-user** [comment]
Users interested in reporting such domains on daily basis are hardly existing. Most of them, prefer "install uBO/generic adblocker and forget forever" approach, so to built in a tool would rather be a waste of time for the dev himself. Either, run your own list and add the domain yourself or contact the malware domains lists maintainer(s)  and report. 

There's no one spot/ GIT dump as you mention, where all malware list maintainers meet and greet unfortunately, but if there was, that would save a lot of time though.

**Comment by bandaid** [comment]
Well, the fact that "users interested in reporting such domains on a daily basis are hardly existing" is by far a very naive statement. It's far from a waste of time and wouldn't take a developer no more than a couple hours to to create one. The entire purpose of the request is on the basis of community reporting.... but obviously there are people like you who cannot comprehend the basics of community.

If users were provided the ability to do such things they may indeed report, but they're not provided those options.

**Comment by gorhill** [comment]
> Adblock Plus has a reporting tool, used for both bug tracking and reporting websites

uBO is serverless. If ever EasyList/EasyPrivacy supports reporting, I will consider integrating support in uBO.

**Comment by bandaid** [comment]
gorhill, I understand uBlock is serverless. There shouldn't be no overhead for such request. Perhaps you have a better idea to implement.

**Comment by uBlock-user** [comment]
> is by far a very naive statement. You clearly have no understanding of how people browse the internet, most people are also not aware of tools to report websites, because they are non-existent and tedious.

Instead of calling for a rebuttal, it's you who forgets people don't care and those who want to, have no direct means to do it and no have idea how to do it and teaching them is a pain in the ass. Secondly, most of these suggestions get declined and so did yours, I was only saving you the time. You're welcome.  It won't happen, so don't bother. It's not naive, it is the fact of life. You can live in denial by offering more idiotic rebuttals or accept it and move on. As gorhill mentioned, uBO is serverless and will remain like that, so someone has to be willing to offer a reporting system, which is not gonna happen as ABP will simply tell you to install their adblocker and use it, they don't have any intentions on doing uBO users any favour.

>If users were provided the ability to do such things they may indeed report, but they're not provided those options.

It was gorhill's decision to make it server-less, stop comparing those two or use ABP if you love that feature so much.


> but obviously there are people like you who cannot comprehend the basics of community, which is one reason why malware sites are so rampant.

I could care less about malware personally, as I simply run uMatrix which takes cares of all third party crap and malware and I'm subscribed to all major malware hosts list all of those which get updated periodically and I have yet to face any malware whatsoever, if only everyone started doing that we wouldn't need a reporting tool despite your desperate claims. Lastly, common sense helps, which unfortunately is uncommon. If only people would avoid websites which appear shady, they wouldn't get infect ever, but they don't. They like to experiment. It's you who simply too moronic to comprehend to understand my argument, so keep on living on your fantasy as you would.

**Comment by bandaid** [comment]
@uBlock-user , 

Thank you for proving how naive you are.
