### ISSUE TITLE
1.11.3b1 gives warnings in Chrome while install attempt

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#2435]
The 1.11.3b1 gives the following warnings while install attempt with Chrome current Release x64 on my Win 10 Pro x64 (current Release):

![ubo warnings](https://cloud.githubusercontent.com/assets/11355601/23713582/b2dd29a6-0426-11e7-85e2-c9c759caaae1.PNG)

**Comment by Hrxn** [comment]
Chrome version?

Websocket is only supported in recent Chrome 58.0.x.x builds..

**Comment by Alpengreis** [comment]
I thought it's clear, if I write Chrome RELEASE ... sorry if not. And thank you very much for your answer!

The Chrome is v56.0.2924.87 (64-bit). This explains it then.

Should I go back to older version of uB0 then, or can I leave it so?

**Comment by Hrxn** [comment]
Oh, right. I overlooked that part. Release as in latest official stable release...

Not sure why you would want to use a dev build of uBO with Chrome stable, to be honest. If you don't use the extension from the Chrome Web Store, you'll normally see a warning every time you start Chome on Windows. Or have they changed that yet again?

Personally, I'd just use official uBO release + uBO Extra with the Chrome stable release, and dev version together with other dev versions. I don't know if there are any side-effects when you get this warning because of websocket support, probably not, but only @gorhill can really answer this correctly.

**Comment by Alpengreis** [comment]
Thank you! No problem, I should include version number anyway, my fault!

I used TILL NOW always the latest version, incl. dev, to be really up-to-date ;-)

I thought dev uBlock is not REALLY related to = dev Chrome ...

And yes, I receive always a warning then after Chrome start.

However: to avoid such problems, it would be probably really better to use it from the official store!

**Comment by gorhill** [comment]
I didn't have this warning when I loaded the extension in Chromium 53.


So essentially this means once Chrom[e|ium] 58 is out, there is will be a complicated backward compatibility issue -- I don't see how this can be solved.

Aside the warning, is the extension working properly, i.e. is it blocking what it is supposed to block?

**Comment by Hrxn** [comment]
Why did you test it with version 53?

**Comment by Alpengreis** [comment]
Yes, it seems it works (does block normally) nevertheless.

**Comment by Alpengreis** [comment]
Once again: it was and is for me not clear that a dev version of uBlock Origin is only intended to dev Version of Chrome ... is that really the case?

**Comment by gorhill** [comment]
> Once again: it was and is for me not clear that a dev version of uBlock Origin is only intended to dev Version of Chrome ... is that really the case? 

No. I appreciate that a dev build of uBO is tested in whatever browser it's meant to be installed on.

**Comment by Hrxn** [comment]
No, not necessarily. They are independent of each other, and can be used as such.

The only exception is cases like this here. The latest uBO dev build includes some new changes specific to the Chrome API, making use of functionality that is only included in the Chrome project since some version 58.0.x.x.

**Comment by gorhill** [comment]
I could use the `<all_urls>` permission instead of `http://*/*` and `https://*/*`, that would probably allow websocket requests to be reported to the API when this become available -- and that would be backward compatible.

However, I fear changing that host permission could cause Google Chrome to issue a spurious warning about a "new" permission and automatically disable the extension and warn users, as it happened when I added the _privacy_ permission, it was a mess, people thought that the permission to "read and change all your data on websites that you visit" was new and thought the worst of uBO, while this permission has been there since the beginning and is required for uBO to do its job.

**Comment by Alpengreis** [comment]
Ok, thanks both!

I would say, I close it here ...

**Comment by gorhill** [comment]
I still need to come up with a fix.

**Comment by Hrxn** [comment]
> However, I fear changing that host permission could cause Google Chrome to issue a spurious warning about a "new" permission and automatically disable the extension and warn users [...]

This is definitely the worst possible solution.

But to be honest, I still don't see the real problem here with regard to compatibility. Why not release a new uBO version with these changes only after Chrome 58 has been published, plus maybe some transition period?
Is there any specific reason I don't see yet?

**Comment by uBlock-user** [comment]
Chromium 59 is already in Canary, so 58 will be released April, so you can wait it out for a month or so.
