### ISSUE TITLE
Ublock addon detection on  privacy testing website

### ISSUE THREAD

**Issue by neoatomic** [gorhill/uBlock#2446]
### Describe the issue

Not really an issue, more of an note. :)

Was playing around with some privacy testing websites, and it seems the below site can detect the Ublock addon "through chrome:// URI trickery!". (Al-trough its recognized as the official "abp" adblock addon)
Not sure if something can be done about this, but might be worth checking?

https://thehackerblog.com/addon_scanner/

- Browser/version:  FF 52
- uBlock Origin version: 1.11.2

**Comment by uBlock-user** [comment]
What trickery ? All it's doing is laying down a honeytrap by naming the script `adblock.js` which gets blocked because of a filter from Easylist, so it concludes that adblocker is installed, nothing fancy. Run the logger and see for yourself. There is no way of detecting whether uBlock Origin or any other extension is installed or not via `chrome://URI`. Don't be so gullible.

**Comment by gorhill** [comment]
Duplicate of #1035.
