### ISSUE TITLE
New type of ads not blocked on Facebook.

### ISSUE THREAD

**Issue by mikhoul** [gorhill/uBlock#2449]
Hi @gorhill , 

There is a new type of "video ad" on Facebook that are inserted in the middle of some videos posted on Facebook on the newsfeed.

Those ads seem to be from 15-20 seconds and are targeted for each users. 

Here's a screenshot: of the ad: 
![FB ad](http://i.imgur.com/wdCvoII.png)
 
The ad appear over the video and you can see a countdown ad the bottom on the scrennshot there's four seconds left and you always have a link to the page that is promoting the ad.

I found some information here about the advertisement program: http://marketingland.com/watch-facebooks-ad-breaks-non-live-videos-work-208685

Do you intend to have a mechanism to handle those video ads inserted in the middle of video ? 

**N.B.:**  If you did not see them and want to test it there is lot of those ads in "The DODO" page since it's a very popular page: https://www.facebook.com/thedodosite  Just play few video and you will see for sure one of those annoying ads.  

Regards !  :octocat:

**Comment by bershan2** [comment]
If that type of adds was introduced very recently, then there might not be rules for it yet. The fix is simple: just add those rules. (In that case it should be reported to appropriate list maintainers, not uBlock Origin.)

How many videos do you have to watch to see an add? I played five videos from start to finish and did not see any ads. Maybe, my subscriptions include rules for these ads, but you either have too few subscriptions or you have/had outdated rules? (It's even possible that in the three hours that passed since you opened this issue someone had added the rule to my list.)

Try updating your subscriptions:
Try going to uBlock Origin Settings -> "3rd-party filters" and  pressing "Update now" and check Facebook videos again.

Please report back whether this issue remains.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mikhoul** [comment]
@bershan2 Thanks for the help but sadly the issue remain, do you have another idea to stop those anoying ads ? 

Regards !   :octocat:

**Comment by gorhill** [comment]
Filter list issues must NOT be filed here. I don't know how to make this more clear than it is stated in CONTRIBUTING.
