### ISSUE TITLE
No docs for popup UI

### ISSUE THREAD

**Issue by XuTpuK** [gorhill/uBlock#2467]
When UI is opened by clicking icon on toolbar, right section shows big OFF button, but LEFT side... WHAT IS THIS? I see list of domains and strange ++ -- and what is most annoying - no info about this in the wiki.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> what is most annoying - no info about this in the wiki

What is most annoying is that you checked the setting _"I am an advanced user"_ without going through the _"required reading"_ link just aside that setting.

If I am going to keep maintaining this project going forward, I can't let myself be burdened by such spurious issue reports. Because of this and your history of being a burden on other projects as well, blocked.
