### ISSUE TITLE
[Question] Procedural cosmetic filters

### ISSUE THREAD

**Issue by splattadat** [gorhill/uBlock#2472]
No issue, a question or perhaps a feature request.

> Procedural cosmetic filters can now be chained and recursive  

== the best news causing me to instantly switch to uBO.

uBO version 1.11.4

Background, there are two DIV's at the same DOM level each with fixed height=50px where the total visible height=100px.  If `#div-1` is targeted using a filter, then `#div-2` will visually move up into its place. This **may** be undesirable where an opaque `#div-2` obscures background imagery due to hiding transparent `#div-1`.
```
<div class="background-image">
   <div id="div-1" style="height: 50px; background: transparent"></div>
   <div id="div-2" style="height: 50px; background: blue"></div>
</div>
```
In the case of the above example, I would chain a change so that the DOM layout is no longer affected, that is, I would alter `#div-2` to contain `margin-top: 50px` to counter the removal of `#div-1`.
```
<div class="background-image">
   <div id="div-1" hidden=""></div>
   <div id="div-2" style="height: 50px; background: blue; margin-top:50px"></div>
</div>
```
The question: is it possible to change inline html? If not, please add the ability :)

I hope that makes sense.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#style ?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by splattadat** [comment]
Thank you @gwarser - perfect answer.

**Comment by gorhill** [comment]
There was absolutely no good reason for @splattadat to completely dismiss [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

There will always be some newcomers wanting to open an issue so much at any cost that they will **completely** dismiss what is asked in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). This is rude, disrespectful and a burden on the maintainer(s) of _any_ project.

In order to keep my ability to maintain this project for the foreseeable future, I've come to set quite strict rules in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). I've had **no choice** to come to be that strict. Since the time I started this project, I've come to understand that I had to make the choice: be _very strict_ in enforcing [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), or call it quit.

What is asked in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) ensure that the free time I volunteer on this project is spent productively, and that the time spent does not overtake everything else in my life. It's not a job, it's a _hobby_.

What is spelled out in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) correspond to the _"set clear boundaries on my involvement"_ part in this [blog post](https://danielbachhuber.com/2016/06/26/my-condolences-youre-now-the-maintainer-of-a-popular-open-source-project/).

Unfortunately, the reality is that some people are just unable and will _never_ be able to grasp the meaning of boundaries (see :-1: above), and will happily dismiss [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). The least time-consuming way to deal with these cases is _"Closing and marking as invalid, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)"_.
