### ISSUE TITLE
Fail to chain a filter with style()

### ISSUE THREAD

**Issue by JackTandy** [gorhill/uBlock#2473]
### Describe the issue

In the uBO edit filter box, an unexpected [E] occurs.

### One or more specific URLs where the issue occurs

https://www.google.com

### Screenshot in which the issue can be seen

<img src="http://i.imgur.com/pk1eFDx.png">

### Steps for anyone to reproduce the issue

See screen capture.

Add the text that is highlighted blue and the [E] will appear.

### Your settings

Default settings. 

- Browser/version: Any.  The screen capture was Opera
- uBlock Origin version: 1.11.4.

##### Your filter lists

Default filter.

**Comment by gorhill** [comment]
> In the uBO edit filter box, an unexpected [E] occurs.

The suffix for `:style(...)` can only be a CSS selector, not a procedural one -- so the `E` is expected.

**Comment by gorhill** [comment]
I've modified the documentation from:

> So mainly it's exactly the same syntax of plain cosmetic filters, except that the :style(...) suffix is appended at the end.

To

> So mainly it's exactly the same syntax of plain cosmetic filters (i.e. must be a valid CSS selectors), except that the :style(...) suffix is appended at the end.

To be sure it's clear.

**Comment by JackTandy** [comment]
Does xpath return the same object type as a CSS selector ? So could I use xpath instead ?

**Comment by gorhill** [comment]
all procedural cosmetic filters (meaning `:xpath` included) apply on a collection of HTMLElement as input and generate of collection of HTMLElement as output. The `:style` operator needs a CSS selector because it's injected as a CSS rule in a stylesheet. Making `:style` apply to procedural cosmetic filters is theoritically possible but I rather not go there yet until there is a clear need for this in the real world -- this is potentially require throwing in a lot of complicated code, which I prefer to avoid.
