### ISSUE TITLE
uBlock Origin v1.11.5.103 webextensions not working correctly

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2499]
Just upgraded from the last webextension version and a number of things are broken.

1. Element picker does not work at all.

2. My filters are not working.

3. Sites now have empty boxes where ads were... msn.com

**Comment by aggat** [comment]
Same with non webext version
All cosmetic filters and Element picker dont't work anywhere
Static network filters and dynamic rules seem to work fine

- Browser/version: Firefox 54
- uBlock Origin version: 1.11.5rc3

**Comment by gorhill** [comment]
Yes sorry, fixing asap.

**Comment by gorhill** [comment]
The non-webext is fixed in rc4. For the webext version, I need more time, this is an outcome of fixing <https://bugs.chromium.org/p/project-zero/issues/detail?id=1225&desc=6#c10> for the chromium version of uBO.

**Comment by gorhill** [comment]
Turns out webext's content script sandbox does not have a `self` global variable, unlike chromium's content script sandbox -- and when I fixed <https://bugs.chromium.org/p/project-zero/issues/detail?id=1225&desc=6#c10> this morning, I removed what the small bit of code which I thought was pointless -- because `self` is available as global variable in chromium.

Regarding <https://bugs.chromium.org/p/project-zero/issues/detail?id=1225&desc=6#c10>, I found that uBO was affected by the issue. For uBO specifically, the issue was that uBO could leak its content script `vAPI` variable into the DOM `html` or `head` element if one of these had a `id` attribute set to `vAPI`. [Test case](http://raymondhill.net/ublock/tiles1.html).
