### ISSUE TITLE
ABE vs uBlock issue (ABP deactivated uBlock by itself...)

### ISSUE THREAD

**Issue by Rava77** [gorhill/uBlock#2533]
Hi, first I used Adblock Plus, with Firefox, later I switched to Palemoon. Then I found out about uBlock origin and installed it instead. Now, for some reasons, there always remained some code from ABP in my local settings folder (in the /extenstions sub-folder) and I was not able to get rid of that, even when I not just "disabled" ABP but uninstalled it.
Now, to use my webmail I have to use Firefox also since that webpage is very badly designed and it fails to work with Palemoon. And so I installed uBlock on the Firefox as well, and when I wanted to copy "My Filters" from my Palemoon uBlock setup to the Firefox one, I realized that there is no uBlock icon in my toolbar.
Going to Add-ons/extentions I realized that uBlock was disabled (I sure did not disable it) and instead ABP was installed and running again (again, it was not me who did that, since I prefer uBlock over ABP a hundred times over...)

Now, I wonder... Since ABP did not fully deinstall, could it really be that the programmers of ABP are that nasty that they dare to disable a competitive product, and re-install their own ABP even when the user deinstalled ABP previously...

Issue happens: On every URL...

- OS/version: Slackware based Live Linux (Porteus), x86-64
- Browser/version: Palemoon 27.2.0
- uBlock Origin version: 1.12.0

##### Your filter lists
don't apply here.

I know this it not really a uBlock origins issue, more like a ABE issue, but since it all seems like ABP targets uBlock specifically and tries to deactivate the user's chosen add-on, I want you folks to know about this...

Cheers...

**Comment by gorhill** [comment]
Please, no baseless speculations -- there is no way ABP is disabling uBO. I never ever observed such behavior, and there is no way such a high profile extension like ABP would do this.

If you have an issue with the state of extensions not being respected, your issue is more than likely with the browser, and surely you need to investigate more on your side before throwing out there such baseless, damaging claim ("damaging" because many people out there are eager to believe this rather than question it and will repeat the nonsense).

Did you try to methodically repeat the steps, and taken notes at every step of what you observed? Do this, very _methodically_ and _thoroughly_ and report your notes if you still observe the issue repeatedly, jumping to conclusions without the detailed factual information.

**Comment by Rava77** [comment]
This is the first time I observed this behaviour, and I reported what I did and what happend, without adding anything. I now have deinstalled ABP, and will look into it later if anything remains in the /extensions folder like it did last time. Then I will write an update here and give you the heads up if this behaviour could be repeated, or not. It still could have been a bug, that in a certain older version that bug did hinder ABP to deinstall itself, who knows. So, in a few days I will post the info on the details, and if code of ABP still remains, or if (hopefully) this time it was deinstalled completely.
Also, I use to have several backup versions of my user home directory including the Palemoon, and so ABP and uBlock setup as well, but that also takes some days of looking into every old available setup backup.

Like I said: I will research all the above named details, and post the results here.

**Comment by gorhill** [comment]
> will look into it later if anything remains in the /extensions folder like it did last time

That is not unexpected. uBO also does not remove its `extension-data/ublock0.sqlite` file when you un-install it, because one might want to re-install the extension and all the settings will be back as they were before un-installing.

That the data is left behind is not evidence of an extension enabling/disabling other extensions.

**Comment by Rava77** [comment]
The extensions/ folder and the extension-data/ are not the same. Like I said, I look into it, and also into the old setup backup archives and post the findings here, but due to now own internet access at the moment it will most probably take some days, but I have it higher up on my TODO list, like you said: baseless speculations are not good and should not be done, therefore I will research all I can with the old setup data.

Cheers
