### ISSUE TITLE
Punycode phishing attack detection

### ISSUE THREAD

**Issue by fproulx-pbox** [gorhill/uBlock#2550]
### Describe the issue

Punycode based phishing attacks may become a threat to consider

There are Chrome extensions that detects those - it'd be nice to have it part of UBlock

like 
https://chrome.google.com/webstore/detail/punycode-domain-detection/fkenopinnpinfcjneoanjoimhkmdcjne
or
https://chrome.google.com/webstore/detail/idn-safe/kegeenojcnijgmfgkcokknkbpmjcabdm

**Comment by anewuser** [comment]
> Do **NOT**:
> 
> *    Submit pull requests.
> *    Submit design ideas.
> *    Submit feature requests.
> *    Submit "revolutionary ideas".

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by fproulx-pbox** [comment]
@anewuser ok - but if we have feature request - there's just no way to communicate those?

**Comment by bershan2** [comment]
@fproulx-pbox uBlock is a network blocker (filter), not URL checker. While it can protect you from known (black listed) malware domains, it is not really tasked with verifying URLs.

Also, consider this:
1. You can, and should just install an extension for that -- which is the easiest fix.
2. Punycode phishing is not really an issue (or will be resolved soon) for all up-to-date browsers. Update and you won't need the extension either.
> Apple Safari, Microsoft Edge, and Internet Explorer protect against this attack. A Chrome fix arrives in Version 59 this week, but Firefox developer Mozilla continues weighing whether to release a patch.
Source: https://www.wired.com/2017/04/sneaky-exploit-allows-phishing-attacks-sites-look-secure/

3. Adding any code to the main codebase increases number of potential bugs and complicates the code. As you can see, even the default filters were moved to a separate repo https://github.com/uBlockOrigin/uAssets
4. You could try to make a rule for this (and add it to custom rules list or propose it to malware domain list), but a comprehensive regular expression might be very complicated. (Assuming that regular expression exists.)

**Comment by bershan2** [comment]
@fproulx-pbox Considering what I wrote above, the solution here is simple and does not require any changes in uBlock:
0. If you use outdated browsers... update or use extensions forever.
1. If you use up-to-date Apple Safari, Microsoft Edge, and Internet Explorer, you are all set.
2. If you you use Google Chrome (which probably you do, since you gave links to Chrome store), use extension for now and wait till 59 is released.
3. If you use Mazilla... switch or use extensions until further notice.

**Comment by okiehsch** [comment]
> If you you use Google Chrome (which probably you do, since you gave links to Chrome store), use extension for now and wait till 59 is released.

Actually the issue has been fixed in Chrome 58 released today.
`https://bugs.chromium.org/p/chromium/issues/detail?id=683314`

**Comment by bershan2** [comment]
@okiehsch You are right! Tested just now with Google Chrome 58.0.3029.81 (64-bit) on the original demo domain created by the original bug reporter: [fake Apple.com](https://www.xn--80ak6aa92e.com/).

@fproulx-pbox Thus this bug is fixed.

**Comment by bershan2** [comment]
@fproulx-pbox regarding your question 
>if we have feature request - there's just no way to communicate those?

It's unlikely that you come up with a feature request that would be implemented right away, because:
1. uBlock is already well-established network filter with most functionality a reasonable person would need. If you would like a more customization network filter, try uMatrix (by the same developer).
2. very rarely a the syntax is extended, if the current syntax is proven incomplete. But even then, the new syntax element is born in a debate about existing issue with uBlock, e.g. `badfilter` introduced in major release [1.12.0](https://github.com/gorhill/uBlock/releases/tag/1.12.0), originating from [uBlock Assets issue](https://github.com/uBlockOrigin/uAssets/issues/192).

**Comment by anewuser** [comment]
@fproulx-pbox 

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

**Comment by gorhill** [comment]
I will consider adding a small sign aside hostname entries in the dynamic filtering pane contain Unicode character, and hovering over these hostnames will show the punycode version.

**Comment by Atavic** [comment]
For Firefox, Palemoon, K-meleon:
In about:config set `network.IDN_show_punycode` to True.

**Comment by RoxKilly** [comment]
I'm with @bershan2 here.  This doesn't seem to me to be in uBO's wheelhouse since there is no filtering, so the maintenance overhead that comes with introducing a new capability along with its UI may not make sense.  Besides consider: the suffix `u` @gorhill will consider adding won't mean anything to casual users (and most advanced users) unless it comes with a tooltip that links to more info.

**Comment by gorhill** [comment]
> won't mean anything to casual users 

It will be displayed in the advanced user pane, and only for when there is a mix of ascii and unicode character in the domain name.

**Comment by gorhill** [comment]
Commit: 0b3d1477f245eda143c5b55a57d106001e73d6b9:

> add basic mitigation to potential abuse of IDN

Key word: _mitigation_. There is no magic solution for the whole issue. The choosen (and trivial codewise) change here is to render the base domain name with the label `idn` for when the following condition is met:

- The base domain name minus the public suffix is a mix of ascii and unicode characters.

If this exact condition is not met, there will be no label:
- If a base domain name minus public suffix is all made of unicode characters, there won't be a label.
- If a base domain name minus public suffix is all made of ascii characters, there won't be a label.

When a base domain name minus public suffix is a mix of ascii and unicode characters, it's is not a sign that the server behind the domain name is malicious -- for example `québec.qc.ca` would be labelled with `idn`. The label is strictly informative of the above condition -- the user is responsible to act based on that information.

Addtionally, the punycode version of a base domain name will be provided through a tooltip if there is at least one unicode character in the base domain name minus public suffix.

Demo: <http://raymondhill.net/ublock/idn-tricks.html>.

![a](https://cloud.githubusercontent.com/assets/585534/25306470/a9fc7b9a-275b-11e7-9a11-6aa308606ec8.png)

**Comment by gorhill** [comment]
I did some more reading and modified the condition under which uBO will use the `idn` label. I modified my comment above to reflect these changes.

**Comment by gorhill** [comment]
I'm going to need to revise slightly again, the `idn` label would not being used currently for `québеc.qc.ca` -- the `е` is not ascii, it's the cyrillic character. The logic used in the solution used for Chromium is what really work, I just need to implement it more fully.
