### ISSUE TITLE
[suggestion] Add a note to README for Chrome users about disabling QUIC

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2584]
### Describe the issue

As you know, in Chromium-based browsers, connections that use the [QUIC protocol completely bypass uBO](https://www.reddit.com/r/uBlockOrigin/comments/66k0eh/psa_disable_quic_in_your_chromiumbased_browser/). I suggest that you add a note to the README recommending that users consider disabling QUIC, perhaps right around where you wrote the [advisory on websocket](https://github.com/gorhill/uBlock#chromium):

> Important: Chromium-based browsers do not relay websocket connections to the extension API. This means websites can use websocket connections to bypass uBO (or any other blocker).:

Those who take the time to read up on how to make the most of uBO should probably have this info about QUIC

Reference: Original [Brave browser post](https://blog.brave.com/quic-in-the-wild-for-google-ad-advantage/) discussing the QUIC findings

UPDATE: The issue with QUIC connections bypassing uBO does not seem to be reproducible in Chrome 58: [see this](https://github.com/gorhill/uBlock/issues/2584#issuecomment-299980678)

**Comment by uBlock-user** [comment]
Not on my end, QUIC speeds things up and doesn't make any connections to ad-servers(Google or any other 3rd party ones) in specific. I have been monitoring QUIC live sessions for the past 72 hours, no change in behavior. I have three extensions in total uBO, uMatrix and ViolentMonkey.

**Comment by uBlock-user** [comment]
QUIC Incoming Sessions -

![](https://i.gyazo.com/af22ead96ae9de1763d6da0811477c21.png)

QUIC Live Sessions - 

![](https://i.gyazo.com/d9e9b2f6f784c932c7c62851d9f49eab.png)

**Comment by uBlock-user** [comment]
I performed another test with all extensions disabled and only uBO running Results are below.

QUIC Incoming Sessions -

![](https://i.gyazo.com/db7c61595fcee128a4fa2fce50d23ee4.png)

QUIC Live Sessions -

![](https://i.gyazo.com/edd84ba9379c173a5c829760117a1fe5.png)

**Comment by uBlock-user** [comment]
Same results for Chromium m58 stable. I simply cannot reproduce what Luke did in his test findings.

**Comment by lukemulks** [comment]
Wanted to share an update here. 

We're in the process of updating the post that I released re: QUIC, after some extensive testing in c58. 

It appears that the issue observed and reported from Nov to mid-Feb which resulted expected blocking returning with QUIC disabled (and no additional measures) was a temporary one. 

Both the YT config and Chromium have since been updated, and after forcing the c58 update and re-testing we saw blocking restored to expected levels regardless of whether QUIC was enabled or disabled. 

Note that we did have a window of time where this did make a difference, but that as of now it no longer appears to be the case in c58 (tested with uBO). Apologies for any confusion here. 

As mentioned, we're making an update to the post to reflect, but wanted to let you all know our latest update after running tests to confirm current status here.

FWIW, Google is using QUIC for ad and ad-related domains, but the error on my part was specifically related to QUIC currently bypassing ad blocking. Sorry again for any confusion, it was an honest mistake on my part which I have been in the process of rectifying since. 

With Chrome v58+ uBO passed on our latest tests as well.

**Comment by lewisje** [comment]
I remember that something weird happened a few versions ago and disabling QUIC fixed the issues; I don't think it was related to ad-serving, and I hope that when and if Google removes that flag and forces QUIC to be enabled, it won't cause the problems it once did.
