### ISSUE TITLE
Image being blocked/hidden, shows as behind-the-scene request even when directly navigated to

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#260]
https://a.pomf.se/dyionj.mp4
ABP does not exhibit the same symptom.

Browser: Firefox 38.0.1
OS: Windows 8.1 Professional x64
uBlock version: 0.9.8.2-dev.0

Steps to reproduce:
uBlock:
1. Go to the uBlock dashboard
2. Enable "Fanboy's Annoyance List"
3. Open the logger
4. Navigate to http://i0.kym-cdn.com/photos/images/facebook/000/820/090/0da.png
5. Notice that the image is hidden
![apeyng 1](https://cloud.githubusercontent.com/assets/4343306/7891578/663fb676-0613-11e5-905b-1e4b262f881a.png)
6. Disable uBlock
7. Notice that the image appears
8. Look at the logger, notice how it doesn't report any hidden DOM elements, nor any blocked network requests, also notice how the image shows up as a behind-the-scene request

ABP:
1. Subscribe to Fanboy's Annoyance list (https://www.fanboy.co.nz/)
2. Navigate to http://i0.kym-cdn.com/photos/images/facebook/000/820/090/0da.png
3. Notice that the image appears
4. Disable ABP
5. Notice that the image appears
Reproduced with a clean profile.
All filter lists were disabled except for EasyList and Fanboy's Annoyance. No custom dynamic filtering rules.

**Comment by gorhill** [comment]
I can reproduce, though my logger doesn't show the request as behind-the-scene.

Same issue as https://github.com/gorhill/uMatrix/issues/199.

Upon closer inspection, I can see that `self.document` is not `HTMLDocument`, but `ImageDocument`. Maybe I could use that information to prevent injecting the content scripts. I will look more into this.

As to why ABP does not have the issue it's just because it works differently.
