### ISSUE TITLE
uBlock Origin for Google Chrome and apiBreaker

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBlock#2609]
uBlock Origin 1.12.4
uBlock filters
EasyList
RU AdList
Google Chrome 58.0.3029.110 (64-bit)

http://www.segodnya.ua/culture/stars/emili-blant-i-tom-kruz-vernutsya-v-gran-budushchego-2-1020015.html

**Comment by gorhill** [comment]
Description of what is happening on that page.

The site uses a MutationObserver to detect changes to the `style` attribute of the ad-laden `iframe` tag, to restore the `display: block !important;` style. uBO does the same, except that is to restore the `display: none !important;` style. So both are fighting to have their style enforced, this causes constant mutation events to be fired, and both listeners to be constantly called as a result.

This is not an issue on Firefox because it supports user styles, there is no need for uBO to modify the `style` attributes of the iframe.

I did observe that I could improve uBO's mutation listener code by using a Set() instead of an Array to coalesce the nodes reported in mutation events. When using an array, uBO has to iterate through over a thousand entries, all for the same two nodes, while if using a Set(), there is only two entries to iterate though. However when using a Set(), the page's style wins -- the iframe ends up not being hidden, which means in the end the solution for the not-hidden iframe has to be something else.

**Comment by dimisa-RUAdList** [comment]
https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes/code#n869

**Comment by evenfrost** [comment]
@gorhill Same thing started happening [here](http://allboxing.ru) recently, and that's incessant fight for `display: none !important`.

**Comment by gorhill** [comment]
@evenfrost Fixed, filter added to "uBlock filters".

Another solution is to use Firefox, it supports user styles and these can't be fought.

**Comment by evenfrost** [comment]
Thanks for fast fix! 🎉
