### ISSUE TITLE
How to block an element without blocking ads?

### ISSUE THREAD

**Issue by ayatana** [gorhill/uBlock#2632]
I want to support a site, so I prefer not to run uBlock on that particular site. But the site has a facebook comment plug-in. Now, I don't want to be tracked by facebook, so, I want to block facebook's plug-in without blocking the ads by Google or the site's own advertising. How can I do that? Is it even possible?

**Comment by mapx-** [comment]
if your site is` www.example.com`, add these rules in "my rules"

```
www.example.com * * allow
www.example.com facebook.net * block
```

**Comment by mapx-** [comment]
@gorhill , I noted all the elements are whitelisted but not 
`||cm.g.doubleclick.net^	--	worker	https://cm.g.doubleclick.net/push?client=ca-pub-7670433186403461&srn=gdn`

tested on `https://www.dcnews.ro/livetext-simona-halep-kiki-bertens-roma-2017-semifinale_543387.html`

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Regarding tracking by Facebook and other such sites: <https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-to-easily-reduce-privacy-exposure>.

So if you have that rule beforehand to block `facebook.com` everywhere, than @mapx-  suggestion would become simply:

```
www.example.com * * allow
no-cosmetic-filtering: www.example.com true
```

Since the rule `* facebook.com * block` takes precedence over the rule `www.example.com * * allow`.
