### ISSUE TITLE
Dynamic block error or by design?

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#2654]
Issue & Reproduction

Visit Dropbox
It sends two similar named requests e.g.
(1) dropbox.com/alternate_wtl
(2) dropbox.com/alternate_wtl_browser_performance_info

If I dynamically block request (1) with default context/type via the logger then (2) is also dynamically blocked even though no rule was created for it.

Same thing will happen for URLs like
dropbox.com/track/
dropbox.com/tracking.php

Is this intended? I would think separate dynamic blocks would be better for different URLs but it looks like the way uBlock interprets it doesn't care for the rest of the filename i.e. as long as there is a rule for the request containing start of the filename other similarly named requests will also be blocked.

- Browser/version:  Firefox 53
- uBlock Origin version: 1.12.4
- Default filter lists

**Comment by gorhill** [comment]
So I will assume you are referring to dynamic **URL** filtering.

By design, uBO tests whether a URL starts with the URL specified in the rule -- and this is why there is a list of URLs to pick from when [creating the rule through the logger](https://github.com/gorhill/uBlock/wiki/The-logger#dynamic-url-filtering-rules).

Just create a `noop` rule to override the _block_ one.
