### ISSUE TITLE
[Suggestion] Bigger icon of configuration

### ISSUE THREAD

**Issue by Irbidan** [gorhill/uBlock#2671]
That icon in the drop down menu. It's so small to select it. Sometimes you click somewhere else unintentionally.

![captura](https://cloud.githubusercontent.com/assets/541941/26689697/d2cecb3a-46f6-11e7-87b7-521fd08c0d5c.PNG)

**Comment by SW1FT** [comment]
You don't need to press the icon, you can just press the whole tab (where it says uBlock Origin 1.24.4)

**Comment by gorhill** [comment]
I will just remove it completely -- as I was intending to be it originally.

**Comment by Phyxion** [comment]
I don't think removing the settings icon is a good idea. From my own experience: non-tech users have no idea how to go to the settings otherwise.
What about a bigger icon next to the zapper/picker/logger icon?

**Comment by Hrxn** [comment]
For non-tech users, and tech users alike:
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface

uBo has one of the best wikis from all projects here on Github, as far as I know.

**Comment by Phyxion** [comment]
That's all nice but if they can't find the settings they aren't going to find the readme either as it's in the settings.

**Comment by Hrxn** [comment]
But a hypothetical non-tech user is really aware of the cog wheel symbol?

Besides, no need to find no settings, if you refer uBo to someone, best link to the wiki in the first place.

**Comment by gorhill** [comment]
This is [my conclusion](http://forums.mozillazine.org/viewtopic.php?p=14750683) on the topic:

***

There are so many hints that the bar is interactive, it was never needed in the 1st place (I added it against my will), and it's causing spurious issues to be filed (i.e. the one here) . Considering:

- The mouse cursor turns into a pointer when hovering over it (everywhere in the browser "pointer" means "clickable")
- It has a tooltip which says "Click to open the dashboard".
- There is succinct documentation about it ([here](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-title-bar)).
- Alternatively the dashboard can be accessed from other places also 
    - The browsers exposes there own entry points, sometimes multiple (i.e. Chromium).

I was never for adding it, so it's back to how it used to be, and to emphasize, it's case closed for me.

For anyone who wants to configure uBO beyond the default settings, due diligence dictates: read the documentation about what you just installed, especially considering something as important as a content blocker.

***

**Comment by Rikk** [comment]
I liked when the title ("uBlock Origin <version>") was clickable to open the dashboard.

**Comment by bershan2** [comment]
@Rikk Right not I like the button on the title too, especially how quickly I could get to the dashboard since the title is so wide and so close to the icon itself. However, the separate "three cogs" icon makes much more visual sense (1) as a separate button next to the logger icon, and (2) in context of menus in general. In fact, when I started using uBlock, I did not like the combined button and window title, but then _got used to it_. We just we have to _get used to_ the separate button now.

**Comment by Rikk** [comment]
It was just the removal of a good shortcut without any performance improvement at all. The removal of the `<a>` tag there is insignificant in every kind of optimization perspectives. Unwelcome change, imo.

**Comment by BilBg** [comment]
@gorhill - Maybe people just don't expect the word "dashboard" but Settings / Preferences / Options

**Comment by SW1FT** [comment]
@BilBg Most people won't even see the tooltip anyway (the delay is too big), they will see the "gears" icon and will click on it.

**Comment by Irbidan** [comment]
I think the "rookies" on the Internet need a personal UI (bigger icons, descriptive sections, etc...) to prevent confusions. Could be interesting when you disable "I'm an advanced user" in the settings or adding a "basic theme".

**Comment by bershan2** [comment]
The discussion of the dashboard button had moved to issue 2718.

@Irbidan The existing UI (1.13.4) is great for all since the dashboard link is obvious since has own button (see issue 2718). Now the only button that does not look like a button is dynamic filtering sub-menu button on the "requests blocked" and "domains connected" (two buttons, to be exact). And yes, I write "now" even though 1.13.4 is not yet in Chrome store.
