### ISSUE TITLE
Add Anti-Adblock Killer Continued

### ISSUE THREAD

**Issue by comfyneet** [gorhill/uBlock#2685]
It seems that reek's AAK repo has been discontinued/abandoned for over 7 months (reek/anti-adblock-killer#3272), some features don't work any longer. Fortunately, someone else forks and maintains this repo at [GitLab](https://gitlab.com/xuhaiyang1234/AAK-Cont).

I think you should consider to add this new filter to the "3rd-party filters" tab.

**Comment by gorhill** [comment]
It's in there, it's called uBlock Protector.

**Comment by comfyneet** [comment]
uBlock Protector only works with Chrome, [its owner also recommends to use AAK-Cont](https://jspenguin2017.github.io/uBlockProtector/):
> You must be using Chrome, uBlock Origin, and Violentmonkey to use this project.
> Do not want to switch your setup? Check out [AAK-Cont](https://xuhaiyang1234.gitlab.io/AAK-Cont/)!

I think you should add AAK-Coont to the filter list if the browser is not Chromium-based.

**Comment by Atavic** [comment]
[AAK](https://github.com/reek/anti-adblock-killer/) has an old list that's bigger than the one on [AAK-Continued](https://xuhaiyang1234.gitlab.io/AAK-Cont/).

**Comment by Giwayume** [comment]
@Atavic We're working on converting all that over.

**Comment by BilBg** [comment]
> I think you should add AAK-Coont to the filter list if the browser is not Chromium-based.
I use Chromium, uBlock Origin, but Tampermonkey (not Violentmonkey) so uBlock Protector is not compatible.
**AAK-Cont Filter For uBlock Origin**
https://gitlab.com/xuhaiyang1234/AAK-Cont/raw/master/dist/aak-cont-list-ubo.txt

**Comment by BilBg** [comment]
> I think you should add AAK-Coont to the filter list if the browser is not Chromium-based.

I use Chromium, uBlock Origin, but Tampermonkey (not Violentmonkey) so uBlock Protector is not compatible.
**AAK-Cont Filter For uBlock Origin**
https://gitlab.com/xuhaiyang1234/AAK-Cont/raw/master/dist/aak-cont-list-ubo.txt

**Comment by lewisje** [comment]
Wait, what happened to jspenguin2017 and the AdBlock Protector List?

**Comment by BilBg** [comment]
> Wait, what happened to jspenguin2017 and the AdBlock Protector List?

I think AdBlockProtector was renamed to uBlockProtector
https://github.com/jspenguin2017/uBlockProtector
https://github.com/jspenguin2017/uBlockProtector/commit/2e63db94b255ae4164512f2660783115d88886ea

**Comment by RegexTeste2** [comment]
> I think AdBlockProtector was renamed to uBlockProtector

True.

List is very similar today:  [www.diffchecker.com/47vN5VQU](https://www.diffchecker.com/47vN5VQU 'offline version not support links') / [www.mergely.com/8JHBqTzy/](http://www.mergely.com/8JHBqTzy 'Live / update possible')


```
uBlock Protector List​:	​​		used 2 395 of 2 395 
AAK-Cont Filter For uBlock Origin:​​	    used 6 of 2 400​​
```
difference file:

```diff
1,14c1,11
< ! Title: uBlock Protector List
< ! Redirect: https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt
< !
< ! Description: An anti-adblock defuser for uBlock Origin
< ! Author: jspenguin2017
< ! Homepage: https://jspenguin2017.github.io/uBlockProtector/
< ! Support: https://github.com/jspenguin2017/uBlockProtector/blob/master/CONTRIBUTING.MD
< ! License: GPL-3.0
< !
< ! ===== PLEASE READ =====
< ! This filter list is intended to be used with uBlock Protector Script.
< ! Visite my home page for more information: https://jspenguin2017.github.io/uBlockProtector/
< ! =======================
< jspenguin2017.github.io##script:inject(doubleclick.net/instream/ad_status.js)
---
> [Adblock Plus 2.0]
> ! Title: AAK-Cont Filter For uBlock Origin
> ! Author: AAK-Cont contributors
> ! Version: 1.048
> ! Expires: 1 days
> ! License: GNU GPL v3
> ! Homepage: https://xuhaiyang1234.gitlab.io/AAK-Cont/
> ! Support: https://gitlab.com/xuhaiyang1234/AAK-Cont/issues
> ! WritingRules: https://adblockplus.org/filters
> ! RedundantRules: https://arestwo.org/famlam/redundantRuleChecker.html
> ! RegExpVisualizer http://www.regexper.com/
245,247d241
< ! =====Patched Anti-Adblock Killer List (originally by Reek)=====
< ! Patching logic can be found in List Compiler source code
< ! Anti-Adblock Killer Repository (contains original source code and license): https://github.com/reek/anti-adblock-killer
2166c2160,2165
< 
---
> /wp-content/uploads/$script,domain=altervista.org
> eurogamer.net##script:inject(abort-on-property.read.js, stop)
> @@||cloudvideoplatform.com/advert.jpg$image,domain=nana10.co.il
> transparentcalifornia.com##script:inject(overlay-buster.js)
> ||35.184.169.188^$popup
> @@||fwmrm.net^$xmlhttprequest,domain=vtm.be

```

</details>

**Comment by BilBg** [comment]
`AAK-Cont Filter For uBlock Origin` has new URL:
https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt

**Comment by lewisje** [comment]
I hope they have the decency to add in the redirection line in the filter-list (I forget exactly what the syntax is now).

**Comment by TonyTough** [comment]
ublock Protector List in combination with ublock Protector Script is only for users of
Chrome + uBlock Origin + Violentmonkey

**I guess the amount of users that use exactly that combination is very very small.**

For all other combinations with ublock Origin
AAK-Cont Filter For ublock Origin + AAK-Cont Userscript For uBlock Origin
has to be installed.

**Comment by Hrxn** [comment]
> Violentmonkey

Not Tampermonkey? Why is that?

**Comment by BilBg** [comment]
> Not Tampermonkey? Why is that?

Ask the author of uBlockProtector:
https://jspenguin2017.github.io/uBlockProtector/

"Anti-Adblock Killer Continued" claims to work with Tampermonkey:
https://xuhaiyang1234.gitlab.io/AAK-Cont/
https://gitlab.com/xuhaiyang1234/AAK-Cont#installation-instruction

**Comment by hawkeye116477** [comment]
Author of uBlock Protector told that this script works properly also with Tampermonkey, but Violentmonkey is lighter than Tampermonkey and is open source, so he recommends Violentmonkey.

**Comment by Hrxn** [comment]
Thanks, I wasn't aware that Tampermonkey is not completely open source.
And whatever "significantly lighter" means, for normal usage. I doubt that you can really notice a difference, except some extreme cases maybe.

I always thought UI/UX was especially nice in Tampermonkey, but Violentmonkey doesn't look to bad either. Well, then there is the icon. The Violentmonkey extension icon looks rather, well, ugly. And you can't even hide it. I'd really prefer a much more minimalist icon.

**Comment by kageimposter** [comment]
Hey guys, couldn't find a spot for this so I'll just leave this here. 
This site http://prompt-sys60.info/chrm/ is a new phishing site posing as microsoft support preying on google's site ad service, found it while going to lowes.com. So far non of the filters have blocked it after updating and adding all 3rd party UbO filters. Its really really convincing, so just thought this might help if one of the admins see it.
![capture](https://user-images.githubusercontent.com/10405971/27611020-34226f5e-5b56-11e7-8e37-56f0f7f7c8ea.PNG)

**Comment by bershan2** [comment]
@kageimposter This is not a place for this, please report it to list maintainers. Or better yet, to [Google SafeBrowsing](https://safebrowsing.google.com/), which is built into every major browser except for IE/Edge, and to [PhishTank](https://www.phishtank.com/).

**Comment by bershan2** [comment]
@kageimposter I reported this to PhishTank, and Google Safe Browsing. Please do not remove your comment since I linked to it.

**Comment by RoxKilly** [comment]
Can anyone please shed some light on why Greasemonkey is not supported? I've seen this same limitation on another userscript recently. Tampermonkey in FF seems to be compatible with more userscripts.

**Comment by Hrxn** [comment]
In case of uBlock Protector, Chrome(ium) only, hence no Greasemonkey.

No longer relevant in that case, because the uBlock Protector userscript is already (or is about to be) dropped, in favor of a real browser extension on the Chrome Web Store.

The problem with Greasemonkey in general is its incompatibility with WebExt extensions, so unless Greasemonkey gets updated it won't work anymore starting with Firefox 57.
Tampermonkey and Violentmonkey for Firefox will continue to work.

**Comment by bershan2** [comment]
@kageimposter To followup your report of the phishing website: Google Safe Browsing had blacklisted the entire domain `prompt-sys60.info`. (PhishTank, however, did not). Once again, please report it to Google Safe Browsing next time.

**Comment by Giwayume** [comment]
@Hrxn
The problem is, Greasemonkey is the only extension that runs reliably at document start, and most anti-adblock killer scripts rely on running absolutely first. Tampermonkey and Violentmonkey have race conditions in this case, which is why uBlock Protector was converted to an extension.

**Comment by Atavic** [comment]
@RoxKilly Are you asking if Greasemonkey is supported by uBlock Protector? Not officially.

For a Greasemonkey related project: https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by jspenguin2017** [comment]
The Userscript is now replaced by an extension, there are a lot of things that cannot be done with just a filter list, so an additional script based system is required. Please note that I overrode some whitelists with the filter and I'm not sure what will happen if you don't install the extension. 

AAK-Cont will try to support Greasemonkey, but for technical reasons, that turns out to be a real pain, so the Userscript there is left in a half-working state, and is no longer in sync with uBlock Protector. That project may not go very far without additional help from the community.

**Comment by Atavic** [comment]
@jspenguin2017 I'd like to help, but I'm on an older FF and I sadly have not so much time.
I greatly appreciate your efforts BTW.

**Comment by jspenguin2017** [comment]
@Atavic Don't thank me, @Giwayume is the main developer downstream. 

@TonyTough I knew not many people have Violentmonkey installed, but I think they can just go install it, you can have both Violentmonkey and Tampermonkey installed at the same time. Chrome and Chromium have over 50% of market share. Anyway, that doesn't matter anymore, since the Userscript is changed to an extension, now the supported setup covers over half of total users.

**Comment by TonyTough** [comment]
@jspenguin2017 
Thanks for the info.
Would it be possible to also use a webextension for Firefox, so that ublock Protector List + webextension can be used with Firefox?

**Comment by jspenguin2017** [comment]
@TonyTough I can make the extension run on Firefox, but I don't have time to maintain that version. So no.

**Comment by lain566** [comment]
@jspenguin2017 uBlock Protector Extension works a treat on Firefox, better than AAK Cont Script

![administrador_de_complementos_-_mozilla_firefox_2017-06-29_12-57-12](https://user-images.githubusercontent.com/27441315/27684536-b465eb4e-5cca-11e7-8bde-128ba86acf12.png)

**Comment by jspenguin2017** [comment]
@lain566 You just loaded the unpacked extension? That's weird, I thought Firefox doesn't have the `chrome` namespace... Anyway, if you want to use it I won't stop you, but I won't officially offer Firefox support. 
If you want to offer Firefox support, fork the repository, change links to point to your repository and publish it in the extension store. 
Also, does Firefox extension store support automated publishing from CI server? If not, it's going to be a pain to keep it up to date.

**Comment by lewisje** [comment]
Actually, [it does](https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Working_with_chrome_URLs), and it supported that namespace before the Chrome browser was being developed: "Chrome" was originally a term for the browser's UI, outside the area where the Web page was drawn, and in browsers from the 1990s, it was usually shaded as if it were metallic and shiny; chrome:// URLs in Firefox go to parts of the user interface, although that might be XUL-specific and no longer supported when XUL is dropped in favor of the new extension system.

**Comment by jspenguin2017** [comment]
@lewisje The link is about the `chrome:` scheme, I'm talking about the namespace, like `chrome` in `chrome.runtime.onMessage.addListener()`.

**Comment by lewisje** [comment]
[It does that too](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities), but as a nod to compatibility.

**Comment by lain566** [comment]
@jspenguin2017 I use Chrome as first priority browser, and Firefox to test
I would like to help you develop extension for firefox, but I'm not a developer.

To be able to install  _uBlock Protector extension_ on firefox, I have used this addon

https://addons.mozilla.org/firefox/addon/chrome-store-foxified/

https://github.com/Noitidart/Chrome-Store-Foxified/

**Comment by jspenguin2017** [comment]
@lain566 I think you can register a developer account pretty easily. Although I'm not sure if CI can push to Firefox store, that can add a lot of extra work, maybe Autohotkey can help... 

Also, I'm not offering Firefox support not because it's hard to port the extension over, it's because I don't want to maintain the Firefox version. If you want to forcefully install the extension in a sketchy way, go for it, but don't tell me when it blow up.

**Comment by lain566** [comment]
@jspenguin2017 Do you hate firefox?
don't worry about that, I will not ask you for help

**Comment by jspenguin2017** [comment]
A little bit, it caused me a lot of headaches.

**Comment by lain566** [comment]
@jspenguin2017 Ok,  I understand

**Comment by bershan2** [comment]
@Giwayume So Violentmonkey has a race condition? There is no open issue about that on its issue tracker... Could you report it there?

@Hrxn
> I always thought UI/UX was especially nice in Tampermonkey, but Violentmonkey doesn't look too bad either. Well, then there is the icon. The Violentmonkey extension icon looks rather, well, ugly.

I agree: Violentmonkey has some CSS bugs and on Firefox looks ugly because of default Times New Roman, but that is Times New Roman's fault. But in Firefox you can change the font to anything you like. Also:
1. You can always modify the look in the settings: just paste some CSS in "Custom Style" on Settings pane.
2. Violentmonkey UI is getting an upgrade, e.g. new button icons instead of plain text and more condensed menus. Also, the author is accepting pull requests (I know because he accepted a few from me).

**Comment by jspenguin2017** [comment]
@bershan2 The race condition isn't really fixable since browsers are designed like that... There are a few hacks that sometimes work but... 
Why everyone cares about the UI? You look at that once a blue moon, functionalities are more important. Violentmonkey autocomplete is way better than Tampermonkey.

**Comment by bershan2** [comment]
@jspenguin2017 
> The race condition isn't really fixable since browsers are designed like that...

Does older API used by Greasemonkey allow solutions without race conditions? I guess it does not matter since Greasemonkey will probably die with Firefox 57 release...

I agree that functionality is more important than the visuals, but visuals are a necessary part of UX thus deserve some attention too. Furthermore, (I think) most people fairly rarely write scripts and more often tweak them and use "Installed scripts" pane.

**Comment by jspenguin2017** [comment]
@bershan2 Yea, the old API is fully synchronous so it doesn't have race condition, but on the flip side, one website can lock up your whole browser. 
Tweaking script by changing its code? Or just settings? Settings needs to be handled elsewhere and that UI depends on the script author. I don't know how many scripts do you install, but I have at most 3. I combined all the small scripts I use into a personal extension, so I'm not using a script host right now. 
If you want beautiful animated UI, you can just throw in some Bootstrap or Polymer, it will be nice and shiny in no time. The price is speed, animation is costly, and not every device can afford that.

**Comment by Giwayume** [comment]
@bershan2 

> Does older API used by Greasemonkey allow solutions without race conditions?

Yes. Web Extensions are screwing over a lot of existing Firefox add-ons, since previously they could modify pretty much any code in the browser.

**Comment by jspenguin2017** [comment]
@Giwayume Really? My $800 tablet can't quite handle it... Maybe because I'm doing other stuff when trying to animate the modal... If done right, the animation should be handled by GPU, hopefully soon we can use Bootstrap or Polymer without thinking about performance.

**Comment by bershan2** [comment]
I hope our discussion did not diverge too far from the original topic...
@jspenguin2017 No, there is no animation, just SVG icons and expanding list, and no outside dependencies. There is even no `:hover`. I'm not the author of the extension, but I do not think he will ever put in any animations.

I do not really use userscripts, I just like the idea of simple prototyping... I have jet to find any useful scripts. So far I really use only three extensions: uBO (obviously), HTTPS Everywhere (hope they'll improve memory usage) and Google Input Tools (could be better). Also, sometimes I just [fix minor things](https://github.com/violentmonkey/violentmonkey/pulls?q=is%3Apr+author%3Abershan2) without real reason.

@Giwayume Unfortunately, the computational cost does add up and although my devices cost significantly more than $200, I care about efficiency. As __@__**gorhill** said, [_Wasting_ is not _using_](https://github.com/gorhill/uBlock/wiki/Who-cares-about-efficiency,-I-have-8-GB-and%7Cor-a-quad-core-CPU).

**Comment by jspenguin2017** [comment]
@bershan2 
If you care about speed, then don't worry about how things look. Violentmonkey uses quite a bit less RAM than Tampermonkey, it is a lot lighter. 
Animating beautiful user interface is not wasting. I didn't build my PC to look at UI from the 90s, but I don't care about UI as much when I'm on my tablet as it is significantly slower than my PC and do not have spare computation cycles to handle animation. 
Coding faster in a language you like is not wasting neither, uBlock Origin uses Python for build script, which is 10 to 50 times slower than JavaScript (Node.js). (I think it can use PyPy as runtime to set back the efficiency difference though...)

Now back to topic, AAK-Cont is not really maintained, but it is still better than the original AAK. Adding it to the filters list will probably not cause damage considering the original AAK is kept.

**Comment by TerrakionSmash** [comment]
@jspenguin2017 Can you elaborate further on why AAK-Cont is not really maintained?

**Comment by Giwayume** [comment]
@TerrakionSmash It is, but so far it's only been me. It needs more devs.

**Comment by jspenguin2017** [comment]
@TerrakionSmash Not enough maintainers. Maybe not enough interest as everyone wants the best in the world. 
Also, many people uses AdBlock and Adblock Plus, so AAK-Cont will probably never work as expected.

**Comment by gorhill** [comment]
@bershan2 

> As __@__**gorhill** said, [_Wasting_ is not _using_](https://github.com/gorhill/uBlock/wiki/Who-cares-about-efficiency,-I-have-8-GB-and%7Cor-a-quad-core-CPU)

That statement was specifically in response for those who tried excused ABP's inefficient use of CPU/memory, this is not a statement to be used as an argument without context in other unrelated discussions.

**Comment by bershan2** [comment]
@gorhill Sorry for that, I just meant that UI does not need a lot to look nice (I'm currently adding in some SVGs with tooltips in place of text buttons). I'm not against animations, I'm against unnecessary use of powerful (and thus large) dependencies, responding to the comment right above mine. Also, I mentioned absence of `:hover` as an extreme example of minimalist CSS (but that might be unintentional).

**Comment by stanlane** [comment]
Replace "uBlock Protector List" with "[Anti-Adblock Killer Continued](https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-script-ubo.user.js)" in uBlock Origin for Firefox.

**Comment by stanlane** [comment]
Replace "uBlock Protector List" (Chrome only) and "Anti-Adblock Killer | Reek​​​​​​​​​" (obsolete) with "[Anti-Adblock Killer Continued](https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-script-ubo.user.js)" ("Based on uBlock Protector (by jspenguin2017) and Anti-Adblock Killer (by Reek)") in uBlock Origin for Firefox.

**Comment by Atavic** [comment]
Site is [here](https://gitlab.com/xuhaiyang1234/AAK-Cont).

**Comment by jspenguin2017** [comment]
Cool, sounds good. The build pipeline for AAK-Cont is choked up for now and I haven't got time to fix it, I have more renaming planned for uBlock Protector so I'll fix AAK-Cont build scripts later. It's an old version for now, but hopefully I'll have time to update it soon. The link to the filter is here: `https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt`.

**Comment by Giwayume** [comment]
I'd like to keep it to one filter list. This is pretty much the same situation that the old AAK had, uBO included the AAK filter list as an option upon installation, but there's the caveat that you need to install the script to get the full functionality. Ideally, a filter list should work on its own, but the whole point behind AAK is sometimes they don't. 

My thought with the userscript is to write a node script to detect which filters need to be ported over/updated. The porting would still be a manual process, since you have some functions that only work in extension code.

I don't know when I'll get to that, though, since it's the end of the budget year I'm busy & with overtime at my job. My company likes to wait until last minute to fit all the projects in for the year for some reason.

**Comment by jspenguin2017** [comment]
It's quite rare that I need to use privileged extension API, the main problems are:
* `onbeforescriptexecute` polyfill only works on Chrome and Edge but not Firefox (can't test on Safari, didn't test on Opera but since Chrome works Opera should work too)
* Stuff chokes on CSP from time to time, especially on Firefox that have pretty broken CSP implementation, Greasemonkey 3.x is a pain as well, and `cloneInto` is buggy though the roof
* Race condition that plagued us since the beginning of time

I do have a few solutions that uses `chrome.webRequest` API, probably have to white list in the case of AAK-Cont. Also not sure what to do with IMA SDK surrogate.

**Comment by jspenguin2017** [comment]
@Giwayume I'm not sure why not many people want to help. I think it is because Merge Requests are too much work and it's a bit hard to satisfy my filter and code quality standard. 
I'll relax the rules until at least 20 developers join us. Filter and script rules are accepted if they fixes more than they breaks. Write access is granted if requested in Issues tracker or Merge Request comment. 
Any objection on this?

**Comment by Giwayume** [comment]
From the issues I've seen it's people who aren't confident enough in their Javascript abilities who said they want to help. I'm not sure how to solve the lack of contributor problem. I've certainly seen them trip up on which files to touch. Maybe the contributing guide needs a step by step tutorial.

**Comment by joey04** [comment]
I've not used AAK or uBO protector, but looking at this thread and the [filter link](https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt) for the first time, here's a first impression critique that may be of help in maintaining your project and getting others to help support it:

1) Add whitespace and headers to organize it. When opening it for the first time I see a big wall of uninviting text. Other than the main header there's no section commenting. Something like EasyList may be a helpful guide in that regard, and would help keep it organized. Whitespace '!' or '#' separators here and there could help too (presumably added by your build scripts).

2) Rule consolidation. There's a big block of 40 rules of `||domain/visitScript/$script,third-party` that could be consolidated into a single `/visitScript/*$script,third-party,domain=a|b|c|etc` rule. That's the way EasyList and others do it.

**Comment by jspenguin2017** [comment]
@joey04 You are looking at the compiled and minimized file, white space and comments are intentionally removed. 
There are a lot of rules copied form the original AAK, I didn't combine them in the fear of breaking it.
