### ISSUE TITLE
Add visible placeholders for blocked elements

### ISSUE THREAD

**Issue by Hyundy** [gorhill/uBlock#2688]
Trying to use ublock without umatrix, I miss the visible placeholders for blocked images and frames. 

Was particularly useful to spot an embedded youtube video and copy its url to open in mpv.

**Comment by lewisje** [comment]
You can get most of that effect by unchecking "Parse and enforce cosmetic filters"; anyway, you should use the logger to find blocked resources.

**Comment by OneOfMany07** [comment]
Was going to say the same here 😄 

There are settings and lists for cosmetic fixes, and you'd want to turn them off.  In the main settings page there is a Default behavior section near the bottom.  Add a checkmark to Disable cosmetic filter.

**Comment by gorhill** [comment]
What he is asking is unrelated to cosmetic filtering. He is talking about the placeholders of blocked resources. By default it's collapse, it can be set to not collapse, and in such case the browser's default placeholder is used.

**Comment by Hyundy** [comment]
Correct gorhill. For an embedded youtube video, when using uBO (firefox), there is nothing there, whereas with umatrix, you see the box, the url and clickable arrow. With images, the default browser placeholder (firefox) does not always show in places that the umatrix placeholder does.

For anyone that wants to check the behaviour for themselves, this link has images where the placeholder does not show when using just ublock and it has an embedded youtube video. http://www.wikihow.com/Embed-YouTube-Flash-Videos-in-Your-PowerPoint-Presentations

**Comment by lewisje** [comment]
I had failed to notice the relevant setting in the Settings pane.

**Comment by gitut2007** [comment]
Ok, my post was closed as duplicated, but it was more specific about right-click options, so I'll paste that as a comment here (without the things mentioned already here): 

 for not having to ... exit full-screen to click the uBO icon..., it would be very useful to have right-click options in the placeholder (like in 'Policeman' Addon -which worked in FireFox 47 but not now in FF 54-; it has a 'shield' icon in the placeholder to hint it's right-clickeable) : 

'load this image', 'load all images in this tab', 'load temporarily all images from xxx.com', 'load permanently all images from xxx.com' (this 'permanently' applies only to current page domain) OR 
'load this frame', 'load all frames in this tab', 'load temporarily all frames from xxx.com', 'load permanently all frames from xxx.com'.
... In case of images one chooses exactly which ones to see.

Other than this, great ergonomy in both this and uMatrix, (I'm using both because some security options are only available in one or the other).
Thanks.

**Comment by d0mf1g** [comment]
This would be a great feature. It would make using medium mode much easier for users by allowing them to easily identify the elements that are being blocked.

**Comment by Atavic** [comment]
It could solve #2334

**Comment by gorhill** [comment]
Closing as no longer an issue since uBO supports:

- the no-large-media-elements per-site switch
- the `redirect-rule=click2load` directive
