### ISSUE TITLE
This site is a pain in a**

### ISSUE THREAD

**Issue by BillGatesTheMiser** [gorhill/uBlock#2701]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
The following site add all time ads and uBlock don't block these ads.

### One or more specific URLs where the issue occurs
https://www.zone-telechargement.ws

### Screenshot in which the issue can be seen
Each time we press something on the page.

### Steps for anyone to reproduce the issue
Each time we press something on the page.

### Your settings
Default settings. 

- OS/version: Windows 10 (updated - June 2017)
- Browser/version: 57.0.2987.110 (64-bit)
- uBlock Origin version: 1.12.4

##### Your filter lists
Default

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
I see no ads on this site. There was only a popup if not using Liste FR, I added a filter for this. Otherwise, if you still have issue, open an issue at the right place (uAssets), and provide more clues, screenshots, and be sure you are using uBlock Origin and not a bad imitation, and with the default settings.
