### ISSUE TITLE
Missing button icons on popup menu

### ISSUE THREAD

**Issue by MinIsMin** [gorhill/uBlock#2706]
### Describe the issue

On the current rc some images of buttons on the popup are missing.
The buttons itself are working.
The buttons are correctly shown in the version 1.12.4.

### Screenshot in which the issue can be seen

![Pic](https://user-images.githubusercontent.com/18466226/27222953-b6e5338e-528e-11e7-9e5a-58f6809e25f8.jpg)

See the missing button icons on the top bar (both dashboard icons) and at "requests blocked" and 
"domains connected".

### Steps for anyone to reproduce the issue

Open the popup menu

### Settings

- OS/version: Windows 10 64 Bit
- Browser/version: Firefox 55.0b1 and Tor Browser 7.0 (ESR 52.2.0)
- uBlock Origin version: 1.12.5rc4 (not webext)

All settings and filter lists left at default.

**Comment by gorhill** [comment]
By design.

**Comment by Hrxn** [comment]
Well, the original comment has been deleted...

Is it about this?
![1](https://user-images.githubusercontent.com/12064918/27396419-480054ac-56b3-11e7-8b1d-8ca5c2735dc5.png)

Noticed this as well, came here for issues because it looks broken to me..

Affected: Latest Chrome Stable, Firefox Stable, Firefox Beta if you open the default home page or the new tab page.
It doesn't look like this if you disable uBo / whitelist a specific site, all icons appear.
OS: Windows 10, but this shouldn't be relevant.

**Comment by gorhill** [comment]
> if you open the default home page or the new tab page.

There is no point showing element zapper/picker on non-http[s] pages, since there is no cosmetic filtering possible on these pages, because content scripts are not injected on these pages.

**Comment by Hrxn** [comment]
I realize that..
It's just my initial reaction upon seeing it the first time, somehow rubbed me the wrong way, I don't know, I can only say that my immediate reaction was _"something is broken here"_, before I understood, on a second thought, so to speak, that these elements make no sense here and it could therefore be by design.

I also think that our hypothetical non-technical user, who is not well versed in those things, might reach a similar conclusion, eventually.

I think it would be more intuitive to grey-out the icons (more, or black-out or whatever), similar to how most GUIs handle this. Or strike-through, like text. Or the red symbol with the diagonal strike, etc.

Well, not really a priority issue, obviously, but maybe a bit relevant to weird users like me, who always notice small inconsistencies in any shape or form and freak out easily...

**Comment by bershan2** [comment]
@Hrxn Maybe you were put off by a single button being not in the center? Would this look better?
![center](https://user-images.githubusercontent.com/22861096/27400099-a7bdc5ca-5684-11e7-82b8-943cffd8059d.png)

**Comment by Hrxn** [comment]
This would definitely be a big improvement, yes.

Although I personally would still prefer something like greyed-out button elements, like other user interfaces do this for any relevant clickable element.

**Comment by bershan2** [comment]
@Hrxn Not sure how you could dim an element that already has the color of a dim On/Off button...

**Comment by Hrxn** [comment]
Yeah, good point.

Maybe something like this as an overlay above the normal icon:
![Imgur](http://i.imgur.com/RettJ3k.png)

I think this is something that is universally understood as well..

**Comment by gorhill** [comment]
That's just visual pollution to me, if something is of no use, last thing you want to do is attract more attention to it by adding complexity to the visual. Removing it from view is unambiguous: the tool can't be used on the page.

**Comment by bershan2** [comment]
@gorhill I realize this is a rather big redesign, but maybe, the menu is not needed at all?

Since uBO can not block anything on its dashboard (and probably all non-http(s) pages), then, as far as I understand the following elements are not needed:
* the large on/off button (which is still "active" on Google Chrome 59)
* the counter of blocked requests for *this page*
* domains connected counter
* all four toggle buttons
* the list of domains that opens upon click on "requests blocked" and "domains connected" badges

The only remaining things are:
* the floating menu title `uBlock Origin [version]`
* the logger link
* the overall proportion of blocked requests

These elements are not really needed because:
* the `uBlock Origin` title is already present on the page in the left top corner. How about including version in the left top corner? Or putting uBO logo in the left top corner and `uBlock Origin [version]` in the page footer?
* the logger link probably can appear as a tab link (not sure if it is a god idea)
* instead of just knowing the overall proportion of blocked requests it would be nice to have a more comprehensive statistics tab. That could include the requests type (floating windows, media, cosmetic, fonts), etc.

**Comment by gorhill** [comment]
"Content scripts" is not webRequest API. The webRequest API can still work on other pages than http[s].

**Comment by Hrxn** [comment]
> I realize this is a rather big redesign, but maybe, the menu is not needed at all?

Why do you think it is not needed? I don't get it, to be honest.

**Comment by bershan2** [comment]
@gorhill @Hrxn Sorry, I did not mean to leave the "other pages" note in. I started writing a comment about the Zapper and Picker in general, got distracted and ended up looking into the **Dashboard only**. This might be off-topic, so please tell me if you are not interested in this:

Since the idea is to remove all unnecessary elements, I checked what elements are actually useful on the Dashboard. My observation was (see comment above) -- it is not useful at all (personally for me).

I would rather have it do something different, like switching back to the tab where I was when clicked uBO dashboard link. This is very useful if I have multiple windows and go back and forth between them, without closing uBO dashboard.
