### ISSUE TITLE
uBlock Origin makes YouTube slow

### ISSUE THREAD

**Issue by ChrisLumia** [gorhill/uBlock#2713]
Dear Mr. Gorhill

First of all let me thank you for the wonderful work of uBlock.
As described by other users before me, Youtube page slows with time when using uBlock.
I am sorry not able to give you a full diagnostic, just what I could try out, I am a simple user.

The problem which occurs to me only in Youtube seems to be related to the non-refresh mode
that happens when changing videos.
Changing a video in Youtube only increases the number of blocked elements in uBlock,
which after a while can get to a really high number which seems to slow down performance in that tab.
If you refresh the page (F5) than the uBlock counter returns to normal block elements number.
From what I could try out, performance get slow when uBlock elements get over 400 after switching
few videos (always switching from the right video panel).
Refreshing the tab brings number back to around 15-20 elements bringing normal performance back

I only hope the information is somewhat useful, if there is anything I could send you to help please let me know.
Thank you very much !

One or more specific URLs where the issue occurs
http://youtube.com

**Comment by bershan2** [comment]
Dear @ChrisLumia,

I'm sad that you are experiencing this issue, however this is probably a filter issue and not a uBlock issue. Also, unfortunately the information you provided is not sufficient. Please consult [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) first and then:
1. close this issue, because someone else reported exactly the same problem in #2711, which was closed as _invalid_. (This issue is _invalid_ too, by the way.)
2. read the [Wiki (user guide)](https://github.com/gorhill/uBlock/wiki), especially how to use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) and try finding report of this issue on [uBlock Origin Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746) (as per CONTRIBUTING).
3. the figure out your problem (find the faulty filter) and bring it up with the list maintainer(s) of the filter(s) with that issue/those issues.

I clicked through a few videos and got my counter to over 450, but did not see the problem. In the logger I saw white-list from EasyPrivacy
```
@@||youtube.com/api/stats/watchtime?$image,domain=youtube.com
```
May be, it fixes that issue?.. But I can't say for sure: you did not provide enough information...

P.S. please do close this issue and do go to the proper place -- uBlock Origin Mozilla Discourse. Also, the text you deleted before writing this report was there for a reason :)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> increases the number of blocked elements in uBlock, which after a while can get to a really high number which seems to slow down performance in that tab

No it doesn't. This is just a mere counter, nothing more -- whether uBO blocks 0 or 1000 network requests, the counter is one single `Number` in memory. You are mustering a nonsensical theory based on flawed assumption as to how uBO works.

"Making the case" (as spelled out in CONTRIBUTING) requires actually providing actual evidences(gut feelings are no evidence) for your theory by profiling using the dev tools to carefully investigate and you provide none of this. I benchmark uBO all the time, and if you have a theory that uBO is slow on Youtube over time, **you** will have to do the work to validate **your** theory.

I do regularly use Youtube for hours and never has uBO been an issue. You will have to make the case.
