### ISSUE TITLE
"since install" is now zero

### ISSUE THREAD

**Issue by OmerWow** [gorhill/uBlock#2715]
Hi,

I backed up all of my uBlock 1.12.4 settings, removed it and installed again and now the "since install" counter is 0, I had almost 1.1 MILLION b4...

I can't find the database (chrome 60 beta, win 10), can u help me change it manually?

**Comment by gorhill** [comment]
It's a "since install" value, hence the count was cleared when you uninstalled then reinstalled the extension.

There is no point modifying the count manually, because you would also need the number of requests which were _not_ blocked in order to display properly the percentage of network requests blocked.

**Comment by OmerWow** [comment]
It was 16% and "since install" value was 1,055,XXX
Pretty easy to get the rest of the numbers from these values, can you please tell me how to change that manually?

Thanks for the advice about resetting though.

**Comment by gorhill** [comment]
>  It was 16% and "since install" value was 1,055,XXX

In that case, enter the following line at uBO's dev console:

    chrome.storage.local.set({ blockedRequestCount: 1055000, allowedRequestCount: 5538750 });

**Comment by OmerWow** [comment]
@gorhill Thanks, that worked!

Have an awesome day, I love uBO :)
