### ISSUE TITLE
settings gear not displaying in 1.13

### ISSUE THREAD

**Issue by boneszz** [gorhill/uBlock#2718]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
the gear settings icon is not displaying

### One or more specific URLs where the issue occurs
so far all
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
no ability to take screen shot
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
default
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 1703
- Browser/version: Firefox 52.2 esr
- uBlock Origin version: 1.13

##### Your filter lists
all fanboy and easy lists and https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none

**Comment by adisib** [comment]
This was an intentional change. The release pages shows an image that includes the gear, but it was just accidentally forgotten that it needs to be updated.

You can see the discussion on removing it here:
https://github.com/gorhill/uBlock/issues/2671

**Comment by boneszz** [comment]
I did not see that post I'm sorry I'll try to be more diligent in my
reading, thanks for the quick reply please mark issue as closed

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
I think I found a way that (this time) I like and hopefully that solves the issue for good.

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/27404000-83ebfe44-569a-11e7-92c5-702c567fa7fe.png)

**Comment by Hrxn** [comment]
Functionality of the grey title bar on top still intact?

**Comment by gorhill** [comment]
No, removed. If I just keep adding stuff without ever removing redundant code, it's what leads to bloat.

**Comment by Hrxn** [comment]
Well, okay, but having simply two <a> elements with the same target instead of just one in a bit of HTML is the most harmless type of redundancy I can think of.

Don't get me wrong, I nonetheless think this new design is better, and removing the now redundant title bar link is perfectly fine.

A small suggestion, while we're at it: What do you think about making the big blue 'power button' a bit smaller and increase the size of the four buttons below a bit instead?

**Comment by boneszz** [comment]
I like that idea as well

**Comment by jjohns71** [comment]
I know this issue is closed but was also hoping the Settings access from the title bar of the popup panel would be reinstated and exist side-by-side with the new icon. 

I think the new icon is great from a design perspective and very straight forward especially from the perspective of a new user learning and or discovering things on their own. That being said, here are a few reasons (in no particular order) why  I think it would be nice to have both ways to access the Settings in no particular order.

1. Muscle memory is a bitch - I've simply gotten used to clicking the title bar to access the Settings and now it's an abrupt change to get used to and adjust to. In just the last couple days I have multiple times clicked the title bar trying to get into the Settings.
2. It takes longer to find the settings each time I want to go there. I now have to visually scan the panel, find the appropriate icon that is mixed in side-by-side with the other icons, and now move the mouse further from its initial origin to bring up the Pop-Up panel. I think it honestly delays me by at least a second every time I want to access the settings (which is multiple times per day) just due to now needing to visually scan and find the appropriate icon as well as moving the mouse a further pixel distance.
3. I know uBlock Origin and uMatrix are different projects, but they share a lot of similarities in their design and usability aspects. If a user runs both side-by-side they are now inconsistent with each other in their approach to accessing the Settings and makes the new muscle memory training required for uBlock Origin harder.
4. The argument against code bloat and performance slowdowns is a good one in general but in this instance the duplication would add almost no additional code, and is at most a couple bytes to the total project.

@gorhill I am fine with and respect whatever decision you make as this project you maintain is an amazing piece of work and I'm sure it is not fun to always have any small design decision be critiqued so intensely on a volunteer project.

Cheers and thanks for the continual improvements you are always making!

**Comment by bershan2** [comment]
@jjohns71 Discussion is over now, but I still wanted to address your concerns:
1. I had been using new uBO interface for a week and completely lost the old muscle memory.
2. Not really a problem since you have to find "UO" shield in the first place.
3. I love consistency too, but do not let it drag you behind. How about changing uMatrix instead? There is plenty of space next to the logger icon and options pane does deserve a dedicated button. More importantly, this does seem like an overall **improvement to uMatrix**, even leaving uBlock aside.
4. The old button could confuse people and is really unnecessary. In this case code bloat is more of philosophical argument. Author just does not want it there, and that is for the better.

**Comment by Rikk** [comment]
@jjohns71 +1
More reasons for having both ways:
- It makes no visual difference keeping a link in the title.
- Just a few bytes (only one `<a>` tag) doesn't have any drawback at all.
- Improves usability.
- Makes old and new users happy.
