### ISSUE TITLE
Yandex search

### ISSUE THREAD

**Issue by dimisa-RUAdList** [gorhill/uBlock#2729]
https://yandex.ru/search/?lr=213&msid=1498249709.54674.20939.25960&text=michelin

New rule for yandex.* (search):
`yandex.*##.serp-item:if(:scope > div.organic div.organic__subtitle:matches-css-after(content: реклама))`

**Comment by bershan2** [comment]
New filters (and other filter-related stuff) should not be reported here, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). Therefore the issue will be closed, and marked as _filter issue_ and _invalid_.

Since Yandex is a service popular in Russia, please report this to either of (or a few of them):
 - Adguard Russian Filter​​​​​​​​​
 - BitBlock List
 - RUS: RU AdList

**Comment by gorhill** [comment]
Does this work?

    yandex.*##.serp-item:if(:scope > div.organic div.organic__subtitle:matches-css-after(content: /реклама/i))

There is already a rule for the lowercase `р`, if the above works, I would just have to modify the existing one.

**Comment by dimisa-RUAdList** [comment]
`...(content: /[Рр]еклама/))`
Yes, it works, only the first letter has changed.
