### ISSUE TITLE
How to add Phishtank's phishing url list in uBlock origin? 

### ISSUE THREAD

**Issue by monperrus** [gorhill/uBlock#2731]
uBlock origin does not contain many phishing lists.

[Phishtank's url list](https://www.phishtank.com/developer_info.php) is large and updated regularly.

Would it make sense to add it in uBlock origin?  How to do this?

**Comment by joey04** [comment]
https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

**Comment by bershan2** [comment]
@monperrus Looks like the interface was too confusing for you. Thus it is a User Interface question. Did you know about uBlock Origin dashboard? You can open it from the popup window that appears after clicking on "UO" icon. Specifically, by clicking on [the title of that window "uBlock Origin [version]" in current release](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-title-bar) or on [the little cog icon in the future releases](https://github.com/gorhill/uBlock/issues/2718#issuecomment-310188330)? **Do you think the new cog icon is more clear?** I'm asking because some still argue against it.

Finally, is it obvious that on the dashboard "About" pane "Wiki" means "the user guide"?

**Comment by anewuser** [comment]
@bershan2 Don't waste your time on people who ignore and delete the issues template and guidelines.

@monperrus 

Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by monperrus** [comment]
> For support/discussions, there is Mozilla Discourse.

OK, thanks.

Something that is not documented in CONTRIBUTING.md is how to submit feature requests.

**Comment by monperrus** [comment]
For the record on this topic of Phishtank in Ublock, one required feature would be CSV parsing so as to add http://data.phishtank.com/data/online-valid.csv in Ublock origin.

**Comment by anewuser** [comment]
> Something that is not documented in CONTRIBUTING.md is how to submit feature requests.

See the section "Before you submit". It covers the subject of feature requests.

**Comment by monperrus** [comment]
Yes, it says NOT to submit feature requests here.

It does not say where to submit them alternatively, or whether feature suggestions are simply not
welcome at all for this project.

**Comment by gorhill** [comment]
I'm not going to add code that serves only one custom format out there. Ask the list maintainers to provide you with a lists which can be used by the tens of millions of blockers out there such as uBO, ABP, Adguard, etc.
