### ISSUE TITLE
$object-subrequest filters being applied to objects

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uBlock#2747]
### Describe the issue
Filters using the `$object-subrequest` option are being applied to objects themselves.

### One or more specific URLs where the issue occurs

http://bartbonte.com/factoryballs3/

### Steps for anyone to reproduce the issue
new profile

1) install uBlock Origin, restart browser
2) Dashboard > My filters, add
```
*$object-subrequest
```
3) visit any page with a Flash object

**Expected results:** Flash object loads

**Actual results:** Flash object is blocked.  Logger sometimes reports that it was blocked by `*$object` in "My Filters", and sometimes does not report the resource at all.

Commenting out `*$object-subrequest` and the Flash object loads as expected.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Linux x86_64
- Browser/version: Firefox 52.2.0 ESR and Firefox 54.0
- uBlock Origin version: 1.13.4
- Flash version: 26.0.0.131

##### Your filter lists
default

##### Your custom filters (if any)
```
*$object-subrequest
```

**Comment by lewisje** [comment]
I haven't seen it mentioned in the wiki, but uBO does [treat `$object-subrequest` like `$object`](https://github.com/gorhill/uBlock/blob/6b293dd58b2ce14b59583aeda6c059d194493b90/src/js/static-net-filtering.js#L1326) because [the `webRequest` API does not make a distinction](https://developer.chrome.com/extensions/webRequest#types); fortunately, [the Firefox version of `webRequest` will still make such a distinction](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType), as the old `nsIContentPolicy` does.

**Comment by gorhill** [comment]
There is no Flash plugin in my Firefox 54.

**Comment by laniakea64** [comment]
@gorhill I tested on Xubuntu 16.04, with the Firefox tarballs direct from Mozilla -
https://www.mozilla.org/firefox/all/
https://www.mozilla.org/firefox/organizations/all/

I get Flash from the `adobe-flashplugin` package, from the Canonical Partners repository.

**Comment by gorhill** [comment]
When I try the URL with Chrome, I do not see any subrequest made by the Flash object.

I would like to get real cases where not supporting `object_subrequest` causes an _actual_ issue, as I do not want to spend time working on code which do not have real purpose for majority of users, because:

- It's unlikely filter list maintainers will care about `object_subrequest` given that this would work only for Firefox;
- Flash is on its way out -- it's not available by default in Firefox;
- I would need actual, real cases which make the case that support of `object_subrequest` is important for a large enough number of users.
    - This means that whatever actual cases for which there are such subrequests worth blocking, there would be no other way to do this with existing filter options.

**Comment by laniakea64** [comment]
> Flash is on its way out -- it's not available by default in Firefox;

I didn't do anything special to get Flash available in Firefox.  Just having it installed was enough.

> - I would need actual, real cases which make the case that support of `object_subrequest` is important for a large enough number of users.
>    - This means that whatever actual cases for which there are such subrequests worth blocking, there would be no other way to do this with existing filter options.

What I had in mind was blocking object-subrequests by default (by adding `*$object-subrequest` as a custom filter), and unblocking individual object-subrequests as needed with dynamic filtering.

While this cannot be done with existing filter options, it is probably not something most users would do.  As such, I guess you're saying this can be closed until we have a more "standard" use case.
