### ISSUE TITLE
UI Improvements to Enhance Usability

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#276]
@gorhill I've created a private CSS style sheet to change the uBlock UI to suit personal preferences and address issues that I felt needed improvements.  You previously implemented a couple of changes I suggested, but I didn't want to overwhelm you with more! :-)

Because others might like the style sheet, I was thinking about making it available.

Out of respect for you, I wanted to run it by you first.

Would you be okay with it?

It is only a CSS overlay and does not replace uBlock or modify its functionality in any way.

Based on a small usability study (n=5), I have concluded that it improves usability.

**Comment by SW1FT** [comment]
You could've put a link here so more people could test it out, I'd give it a test at least.

**Comment by gorhill** [comment]
Just a warning that I admit to be a control freak when it comes to code. I am open to small incremental code change as pull requests, but not very open to grand redesign. Some of these were tried in the past and I rather not go through all this again -- especially when subjectivity is involved.

**Comment by CrisBRM** [comment]
Just post a screenshot of them side to side. Curious to know what was changed.

**Comment by Gitoffthelawn** [comment]
@gorhill Actually, I'm not asking you to implement a single idea... I sensed your freakitude :).  That's why I made a separate CSS style sheet overlay for myself.  I'm willing to share it with others, but I don't want to cause any problems for you, so I want to make sure it's okay with you first.

@SW1FT My goal is to ask permission not forgiveness, so I didn't post a link without gorhill's consent.  It's not anywhere online, and won't be until he gives his okay.  I don't want to step on anyone's toes.

**Comment by gorhill** [comment]
> I want to make sure it's okay with you first

Yes, I am curious too like others.

**Comment by Gitoffthelawn** [comment]
@gorhill Sounds good.  I'll find a cozy spot for it... perhaps here on github.

**Comment by Gitoffthelawn** [comment]
@gorhill  @SW1FT  @CrisBRM   @All

So everyone can see it, I set up a repository at https://github.com/Gitoffthelawn/uBlock-Deluxe

At this time, it is designed for uBlock Origin only; I have not tested it with regular uBlock yet.

It was designed for Firefox on Windows and was created for my personal use.  If you like anything in it, you can post an issue in that repository.  The issue tracker in that repository is open to all feedback, questions, and anything else you want.

It's a CSS overlay, so you can add it to userChrome.css in your Firefox profile folder to have it take effect.

It does not modify underlying uBlock functionality in any way.  It is strictly a UI enhancement for increased usability.

Enjoy!  :-)

**Comment by Gitoffthelawn** [comment]
I updated the overlays at https://github.com/Gitoffthelawn/uBlock-Deluxe into a different format that should work for everyone with Firefox.

**Comment by TeddStriker** [comment]
Have you tried using [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/)? I don't see it anywhere on your page, its a lot simpler to editing userchrome files. I have to ask, how difficult was it for you to do this? I'm asking because I would want to try and tweak some of the UI for myself, my HTML&CSS knowledge is pretty rudimentary though.

**Comment by Gitoffthelawn** [comment]
Difficulty is, of course, relative.  Some enhancements are fairly straighforward whereas others use very advanced tricks and techniques that I've learned through experience and experimentation.

The [Mozilla Developer Network CSS Reference](https://developer.mozilla.org/docs/Web/CSS/Reference) is a great place to see all the available functionality for CSS for Firefox.  Similarly their [HTML Reference](https://developer.mozilla.org/docs/Web/HTML) is quite good.

If you are going to use a style manager, I think [User Style Manager](https://addons.mozilla.org/firefox/addon/user-style-manager/) has many advantages over Stylish (although it is need of some non-critical bugfixes).  Both add significant functionality over editing userChrome.css and userContent.css.

**Comment by anewuser** [comment]
@Gitoffthelawn it would be much easier and productive if you posted a screenshot of it for us to know if we're interested in what you've done in first place.

**Comment by Gitoffthelawn** [comment]
@anewuser I'll definitely consider your request to create screenshots, but in the meantime if you click on the link, you will see another user has already posted one screenshot in the issue tracker (the issue is closed but github lets you view closed issues).

uBlock Origin has multiple UI screens.  The enhancements are to 7 different screens (probably 8 soon), so it will take at least 7 screenshots to see all the changes, and then I'll have to maintain all those screenshots every time I make a new version.

If you want, you can try it out by simply copying and pasting text into 2 text files, so it will probably take less time to try it than for me to make and maintain screenshots.  Plus, it will be more of an adventure to try something different without seeing screenshots first.  :-)

**Comment by anewuser** [comment]
I've taken the liberty to crop [that screenshot](https://github.com/Gitoffthelawn/uBlock-Deluxe/issues/1#issuecomment-108090719) to post it here:

![436a1286-096f-11e5-9f32-83ea385b7da2](https://cloud.githubusercontent.com/assets/6733770/7957541/81c3168c-09be-11e5-884f-e5ee07177bf1.png)

**Comment by Gitoffthelawn** [comment]
Thanks.  Rendering is a little bit off in that screenshot, but fairly close.  If a bunch of people start using it, I'll work out any issues (if not, I'll just use it myself).

Also updated https://github.com/Gitoffthelawn/uBlock-Deluxe to include new usability enhancements and accessibility improvements to uBlock request logger.

**Comment by hairycactus** [comment]
**CSS Overlay Test Outcome:**
No discernible change to uBlock Origin  0.9.8.3's UI (screenshot below). Also, the add-on's header in the popup remains as uBlock Origin (not "uBlock Origin Deluxe!").

![ublockorigndeluxe-csstest-03jun15](https://cloud.githubusercontent.com/assets/9943769/7960197/26cdc31c-0a31-11e5-8e89-3c31e55fbad6.png)

This is regardless of whether I use <code>userChrome.css</code> alone, or both <code>userChrome.css</code> & <code> userContent.css</code>. 

I'd placed the CSS file(s) in my Firefox profile folder as follows:
<code>AppData\Roaming\Mozilla\Firefox\Profiles\ [random-chars] \chrome</code>.

Tested using uBlock Origin 0.9.8.3, Firefox 33.1.1 (32x) with NASA Night Launch dark theme (enabled & disabled) in Win 7 SP1 (x64).

**Comment by TeddStriker** [comment]
Hmmm, have you tried using [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/) or [User Style Manager](https://addons.mozilla.org/en-US/firefox/addon/user-style-manager/)? I can't tell for sure what the problem is, since I don't run windows, and haven't used `userChrome.css` in a long time. Have you tried restarting with addons disabled?

**Comment by gorhill** [comment]
> I've taken the liberty to crop that screenshot to post it here:

Ok so I do not intend to convert uBlock's UI to this. The uBlock's UI is stable, and whatever need change if I agree in the first place will be minimally incremental at most, not a redesign of proportion/colors.

**Comment by Gitoffthelawn** [comment]
@hairycactus It looks like your userChrome.css and userContent.css are not taking effect at all, so no enhancements will be shown.  Do you just have one profile, and is it in the right one?

As a test, you can create a basic userContent.css with the lines:
    `@namespace url(http://www.w3.org/1999/xhtml);`
    `* { color: red !important }`

That should turn almost everything red in Firefox.  If it doesn't work, then either you have userContent.css in the wrong folder, or something on your system is preventing it from loading and being applied.

You can create a new profile using Firefox's Profile Manager in order to troubleshoot.

**Comment by hairycactus** [comment]
@Gitoffthelawn, @TeddStriker
I only have 1 profile in my Firefox browser. I'm not using Stylish, User Style Manager, or similar add-ons. Below are are more tests that I carried out, thanks to your suggestions.

Since Test 1 (<code>userContent.css</code> for red text) works, it seems that my Firefox is specifically not reading the uBlock Origin Deluxe! CSS overlay files as it should ?

**Test 1:** Using dummy <code>userContent.css</code> (<code>* { color: red !important }</code>) in my everyday Firefox profile (includes all add-ons & browser customizations)
* **Outcome:** OK, all the text & some icons turn red in my Firefox — both on webpages & also on uBlock Origin's popup (screenshot below):
![firefox-usercontentcss-redtext-04jun15](https://cloud.githubusercontent.com/assets/9943769/7981787/d7faec7a-0ae3-11e5-8db4-2e9859abd040.png)

**Test 2:** Using uBlock Origin Deluxe! CSS overlay (<code>userChrome.css</code> & <code>userContent.css</code>) with all add-ons disabled, except for uBlock Origin; restarted Firefox
* **Outcome:** No change to uBlock Origin's UI.

**Test 3:** Created new empty Firefox profile with zero customization, installed uBlock Origin, using uBlock Origin Deluxe! CSS overlay (<code>userChrome.css</code> & <code> userContent.css</code>); restarted Firefox
* **Outcome:** No change to uBlock Origin's UI.

**Comment by Gitoffthelawn** [comment]
@hairycactus   Thanks.  I'll post a response in https://github.com/Gitoffthelawn/uBlock-Deluxe
