### ISSUE TITLE
Webext-hybrid version of uBO is not in uBO's dev channel on AMO

### ISSUE THREAD

**Issue by Oooooooooooooooooooooooooooooooooooooo** [gorhill/uBlock#2762]
How long until it's there? You promised this 3 days ago!

**Comment by bershan2** [comment]
@Oooooooooooooooooooooooooooooooooooooo 
1. This is not an issue, this is just discussion at best. [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) states:
   > For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

    Thus it will be closed and marked _invalid_.
2. If you post such a question here, you should probably post it in the relevant issue instead of spamming the logger.
3. Did you consider that @gorhill is a **one** (1) person that develops uBO in the leisure time and [does not receive any monetary compensation for this](https://github.com/gorhill/uBlock/wiki/Why-don't-you-accept-donations%3F) and probably has other commitments? Also, 3 days is a really short period of time.
4. If you are so impatient, would you please consider helping with this task yourself? Just post a message in the appropriate place, fork the repository, implement the necessary changes, (test them a bit) and, if your changes are welcome, open a pull request. That simple, right? Should definitely take no more than three days. :)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
> You promised this 3 days ago!

What I said:

> At this point, I am considering pushing the webext-hybrid version of uBO into uBO's dev channel on AMO

"considering" =/= "promised".
