### ISSUE TITLE
The facebook ads (sponsorised links) are backs !!!

### ISSUE THREAD

**Issue by lorka85** [gorhill/uBlock#2785]
Hi all !
I can see with horror, then the facebook ads as "sponsorised links" (who look like a real article on the wall) are show since many days....

With chrome, firefox, the same problem under ublock...
it's a recent modification of facebook and an update of ublock origin will exit ?

or a more tragic reason ? (like adblock who is payed since many years for force the ads of facebook by example)

Thx for all reply and helps,
regards.

**Comment by bershan2** [comment]
@lorka85 This is probably a filter issue, bot uBlock Origin issue, so it should not be reported here. First of all, try updating the filter lists manually (they update automatically only every 5 days). To do it, click on UO shield -> click on either the title of the popup if you have version 1.13.2 or on the gear icon if you have newer version -> go to 3rd-party filters -> click Purge all caches -> click Apply.

I do not see any ads, so that should help... If not, may be, they did not update the filters yet.

This issue probably will be marked _invalid_ and _filter issue_ if you do not provide a proof that this is uBO issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
