### ISSUE TITLE
Word Wrap on "My Filters" tab

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#2792]
I have noticed that the uBO does not incorporate word wrapping for text added to the "**_My Filters_**" tab. This causes long filters to scroll horizontally over the screen. It would be convenient if an option for word wrapping is made available in uBO or maybe even make it default.

**SS:** https://i.imgur.com/q9fHlZM.png

**Error URL:** `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html`

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by anewuser** [comment]
[This repository isn't open to design suggestions](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) , especially when your example is this instead of a an actual filter that would show us that your request is relevant:

![untitled-1](https://user-images.githubusercontent.com/6733770/28280570-94c4518e-6afa-11e7-9355-08f132266c35.png)

**Comment by gotitbro** [comment]
@anewuser This feels more like a functional change than design to me. The example I provided works perfectly for the issue/suggestion at hand, no real use case is needed if it was I would have provided it.

I do not want inundate my issue with images, if someone wants to see the image they can by clicking the direct link.

**Comment by anewuser** [comment]
If you keep posting here thinking that "no real use case is needed", you may be banned for wasting people's time.

**Comment by gotitbro** [comment]
@anewuser I have added personal filters that overscroll horizontally. Here is an example (a filter from EasyList): https://i.imgur.com/2KgecyM.png

**Comment by gorhill** [comment]
That is easy enough to fix, it's just to toggle the `white-space` style on the textarea. The reason I didn't pick autowrap is because is can become difficult to distinguish where a filter begins and ends (for example some EasyList filters are over 4K characters), and less tech-minded people may end up butchering a filter which would cause uBO to apply bad filters, and uBO ends up being blamed rather than the broken filters.

I decline because of this. Workaround is to import text in a text editor which is better equipped for this, then copy result in the textarea.

**Comment by gotitbro** [comment]
@gorhill Thanks for the explanation, makes sense. One question though what do **EasyList** filters have to do with the "My Filters" tab? They "4k character" filters won't be displayed there.

**Comment by lewisje** [comment]
The point is that ordinary people, like you, could well make up super-long filters and put them in My Filters, possibly using the same format that EasyList uses.

**Comment by gorhill** [comment]
It's a actually easy to create long filters when creating cosmetics filters through element picker.

**Comment by gorhill** [comment]
This has been fixed as a consequence of integrating CodeMirror: 61ec088d4342.

The line now wraps, but a gutter with line numbers makes it easy to distinguish one line from another.
