### ISSUE TITLE
uBlock must convert to web extensions for Firefox

### ISSUE THREAD

**Issue by sammcj** [gorhill/uBlock#2794]
uBlock will no longer work in Firefox 57 and beyond as it is a legacy addon and needs to be converted to be a 'Web Extension'.

https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/

For information on porting uBlock to run as a web extension, please see: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on

**Comment by bershan2** [comment]
TL;DR Everything is [OK](https://github.com/gorhill/uBlock/releases/tag/1.13.8).

If you would have looked at the recently closed issues, you would see one titled _"Compatible with Firefox 57+" badge_, link: `https://github.com/gorhill/uBlock/issues/2782`. Furthermore, even that issue is not a proper issue! The release notes (linked above) clearly address this problem!

**Comment by sammcj** [comment]
Sorry for dupe, I did actually search for webextensions and web extensions and Github returned nothing.

--
Sam

**Comment by anewuser** [comment]
@sammcj Open the Github site instead of replying via email and close this issue.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sammcj** [comment]
Thanks Gorhill, @anewuser sorry I was on a train while writing that!
