### ISSUE TITLE
Use user styles to collapse the placeholder of blocked resources

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2848]
Currently, the collapsing of placeholder (DOM counterpart) of blocked resources uses inline `display: none !important;` style on the DOM element to collapse. uBO should use user styles for platforms which support them (Firefox).

Using user styles will make the collapsing more reliable, as it's currently possible for a web page to overwrite uBO's own style used for collapsing purpose.

**Comment by uBlock-user** [comment]
Is this not available in Chromium ? Also is this ![bug](https://bugs.chromium.org/p/chromium/issues/detail?id=632009)

**Comment by jspenguin2017** [comment]
Injected style in Chromium is asynchronous and is low priority, although you can add `!important`, it can still be easily overridden. 

And yes, that bug is related, Chromium devs are thinking of making `chrome.tabs.injectCSS` to be not overriddable. But it is still asynchronous though, probably still need the inline style, and the injected CSS will be the "back up" if the page tries to remove the inline style. 

For now, just remove the node and register an insert blocker, it's not efficient but gets the job done.

**Comment by gorhill** [comment]
Collapsing using inline styles instead of user stylesheet is causing this issue: <https://forums.lanik.us/viewtopic.php?f=64&t=42660>.

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/d97c46ffd3eb9ae1be4cc9dcf22b49abbd14ab1d>.
