### ISSUE TITLE
Firefox 57.0a1 (2017-08-11) (64-bit) disables uBlock Origin

### ISSUE THREAD

**Issue by spdyrel** [gorhill/uBlock#2862]
### Describe the issue

On OSSierra 10.12.6 if that matters. I understand this is on Firefox's side, not yours but I was on the Development Channel and the addon was still removed with the latest Firefox Nightly update (version in title). I had to re-install through Development Channel (uBlock Origin 1.13.9b8) to get it back but all my settings/custom filters are gone. I did not save my settings through uBlock Origin but is there any way to get them back? Just wondering if they are saved in a certain location or if they were completely removed by Firefox. This is also a warning to others!

Hopefully this is enough info/follows the rules but I can provide more if needed. Thanks.

**Comment by gorhill** [comment]
It's all explained in the [Release notes](https://github.com/gorhill/uBlock/releases). I keep closing that kind of issue repeatedly because people do not read the Release notes.

To migrate from 1.13.8 to 1.13.9b8:
- Install [1.13.9b7](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.13.9b7): it's a webext-hybrid from dev channel, able to migrate your 1.13.8 settings.
- Once the migration is complete, install 1.13.9b8 from dev channel, it's a pure webext.

**Comment by spdyrel** [comment]
I apologize then. I tried searching the "issues" page and didn't see any posts. Thanks for the help

**Comment by Hrxn** [comment]
You can also export settings manually, or maybe only export your own 'My filters' list, then remove the extension completely and just install the latest 1.13.9b8

**Comment by gorhill** [comment]
> I am unable to install that version with the latest update so I'm guessing I'm SOL.

Sorry, I forgot about that. There is a config setting you can toggle allow legacy extensions in Nightly, 1.13.9b7 still work fine if the setting is toggled: `extensions.legacy.enabled`.

**Comment by spdyrel** [comment]
I thankfully had most of my settings on another computer so I saved the restore file and transferred it over. Thanks for all the help and hopefully this will help others.

**Comment by Serkan-devel** [comment]
When will the webext version be released as stable? And will it also be pushed to chrome browsers?

**Comment by Hrxn** [comment]
There is no WebExt version for Chrome, because the extension for chrome always has been a WebExt extension, so to speak.
