### ISSUE TITLE
Does `3p-party` in uBlock Origin UI block third party cookies, too?

### ISSUE THREAD

**Issue by crocket** [gorhill/uBlock#2872]
### Describe the issue

I read wiki on uBlock Origin and uMatrix.
I use uBlock Origin for third party filters and uMatrix in its default deny-all mode for matrix-based filtering.

It seems I can use uBlock Origin in hard mode instead of uMatrix if I don't mind allowing everything from specific third party domains. Does `3p-party` block third party cookies, too? I think wiki needs to answer this question.

I am a bit afraid of medium mode because medium mode still leaks my location on http://webkay.robinlinus.com/ via Google Geolocation API by default. The reported location was within 50 meters of my location. My location is the most sensitive information. http://webkay.robinlinus.com/ drove me into paranoia.

**Comment by gorhill** [comment]
Cookies are delivered in a server response's HTTP headers. If there is no request to a remote server (because uBO blocked it), then there is no response. If there is no response, there is no HTTP headers. If there is no HTTP headers, there is no `Set-Cookie` header. If there is no `Set-Cookie` header, there is no cookie.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by crocket** [comment]
Thanks for the details. I will ask more questions on reddit.
