### ISSUE TITLE
Can you reopen 2029?

### ISSUE THREAD

**Issue by corysimmons** [gorhill/uBlock#2874]
https://github.com/gorhill/uBlock/issues/2029

The conversation was productive except for [this single comment](https://github.com/gorhill/uBlock/issues/2029#issuecomment-253375651).

The problem also affects API developers.

![image](https://user-images.githubusercontent.com/224636/29314989-c0dd60a8-818e-11e7-8486-039ae9c3ff65.png)

![image](https://user-images.githubusercontent.com/224636/29315004-d864d42c-818e-11e7-8400-677ac29fc5d6.png)

Really frustrating having to dive into `chrome://extensions` to disable uBlock every time I'm doing API dev.

**Comment by gorhill** [comment]
What is there more to say? The issue is still opened, which means I do intend to do something.

**Comment by corysimmons** [comment]
Okay, I didn't realize you intended to fix it. Thank you.

**Comment by gorhill** [comment]
By the way, what is the type of document which caused the error message in your pic?

**Comment by corysimmons** [comment]
`text/plain`. You can hit it here if you want: https://shielded-hamlet-97718.herokuapp.com/v1/trucks

**Comment by gorhill** [comment]
One idea is to ask the browser devs to add a content type filter to [`content_scripts` declaration](https://developer.chrome.com/extensions/content_scripts#registration) so that the browser injects the scripts if and only if there is a document type match. This would be a better solution since the browser would completely skip injecting the scripts, removing the need to test/abort content script side after they are injected.

**Comment by corysimmons** [comment]
I don't imagine they'd do it, especially not without months of convincing them, but I'm sure you'd have more clout than me in that sales pitch.

What was the problem with the IIFE anyway? I've never heard of an IIFE being a perf hit.
