### ISSUE TITLE
uBlock webext always changes about:config prefs upon launching Firefox to disable pre-fetching, even if "Disable pre-fetching" is unchecked.

### ISSUE THREAD

**Issue by 4i6l** [gorhill/uBlock#2900]
### Describe the issue
While uBlock blocks pre-fetching behavior in Firefox by default, users should have the option to turn this off if they want. This was possible in the legacy version of uBlock but no longer seems to work in the webextension version. Whenever Firefox is launched, uBlock will make changes to about:config prefs to block pre-fetching, even if "Disable pre-fetching" is unchecked in uBlock options.

Furthermore, it seems that the "Disable pre-fetching" checkbox doesn't seem to do anything when toggled. In the legacy version, toggling that option will immediately result in changes in the corresponding about:config prefs but this does not occur in the webextension version.

### One or more specific URLs where the issue occurs

about:config

### Steps for anyone to reproduce the issue

1. Uncheck "Disable pre-fetching" in uBlock options.
2. Go to about:config and right click on the following prefs and click reset to restore them to default values:
 network.prefetch-next
network.dns.disablePrefetch
network.http.speculative-parallel-limit
network.predictor.enabled

3. Close Firefox and reopen it.

4. Go back to about:config and see that those prefs have been modified by uBlock, even though "Disable pre-fetching" remains unchecked in uBlock options.

Method to reproduce how the "disable pre-fetching" option has no effect:

1. Uncheck "Disable pre-fetching" in uBlock options.

2. Go to about:config and right click on the following prefs and click reset to restore them to default values:
 network.prefetch-next
network.dns.disablePrefetch
network.http.speculative-parallel-limit
network.predictor.enabled

3. Go back to uBlock and check "Disable pre-fetching".

4. Go back to about:config and look up the above prefs again. You will see that they remain at their default values, even though you had toggled the "disable pre-fetching" option. 

### Your settings

- OS/version: Windows 8.1
- Browser/version: Firefox 57
- uBlock Origin version: 1.13.11rc0

##### Your filter lists

"Default filter lists"

##### Your custom filters (if any)

**Comment by gorhill** [comment]
Do you have a `user.js` in your profile which override these settings?

**Comment by 4i6l** [comment]
No, I did not have a user.js file in my profile when I noticed these changes. 
To test that out, I just went ahead and created a user.js that only contained the following lines:

user_pref("network.prefetch-next", true);
user_pref("network.dns.disablePrefetch", false);
user_pref("network.http.speculative-parallel-limit", 6);
user_pref("network.predictor.enabled", true);

I was still able to reproduce the above findings, so it seems that uBlock is changing those prefs after Firefox loads the settings from user.js

**Comment by gorhill** [comment]
In trying to reproduce, I am having the opposite issue: I am completely unable to have the preferences toggled back on when check _"Disable pre-fetching"_ in uBO. At this point I suspect there is something wrong in Firefox-side, I am trying to narrow down what is really happening.

**Comment by gorhill** [comment]
Do you have any other extensions enabled that could be playing with the `privacy.network.networkPredictionEnabled` webtext setting?

**Comment by gorhill** [comment]
Also, I do not see that you tried to find out what happens if you disable uBO then restart. Can you try please?

**Comment by gorhill** [comment]
On my side, I've narrowed down the issue to a bug in the browser.

When multiple extensions try to modify the same settings, a precedence order dictates which extension is going to "own" the right to modify the setting. The precedence order is calculated according to whether an extension is enabled/disabled ("enabled" wins of course), and for all enabled extensions, the one with the most recent install date is going to win.

The problem I have observed on my side is that in the precedence list for the `privacy.network.networkPredictionEnabled` settings, there is an extension which no longer exist because it was removed (`uMatrix-webext@raymondhill.net`), and yet it still is in the precedence list, and it's being seen as the owner of the setting, hence uBO can't modify it:

![a](https://user-images.githubusercontent.com/585534/29741383-68e37eb0-8a39-11e7-8347-70cafa81e2ee.png)

The extension `uMatrix-webext@raymondhill.net` being seen in the precedence list, despite that extension no longer being installed:

![a](https://user-images.githubusercontent.com/585534/29741398-e49f7716-8a39-11e7-9a57-187472da2ddb.png)

I need to report this to bugzilla.

Now the question is whether you are suffering the same issue. The only way to find out is that you launch the debugger ("Web Developer => "Browser Toolbox") put a breakpoint at the end of the `addSetting` function inside `ExtensionSettingsStore.jsm` to find out the content of `keyinfo.precedenceList` when you modify the setting in uBO, as seen in 1st screenshot.

**Comment by 4i6l** [comment]
Yes, it seems that something similar is happening to me. I notice that uMatrix is taking precedence over uBlock for these settings. 

I do have uMatrix 1.0.1rc0 (uMatrix@raymondhill.net) installed. When I disable uMatrix and then toggle the setting in uBlock, it is able to change the about:config prefs. However, I was not aware that uMatrix also modifies prefetching settings. I did not see an entry about that in privacy tab of uMatrix settings.

![ublock1](https://user-images.githubusercontent.com/21112923/29742000-d6af9b2e-8a3c-11e7-990d-ca1d69433ab3.png)

**Comment by gorhill** [comment]
> I notice that uMatrix is taking precedence over uBlock for these settings and it persists even if uMatrix is removed.

> When I disable uMatrix and then toggle the setting in uBlock, it is able to change the about:config prefs.

These two statements seem contradictory. In the second one you say you can control the setting with uBO if uMatrix is disabled. In the first one you say you cannot control the setting with uBO if uMatrix is removed. Can you confirm please?

I did find an issue with Firefox, and I narrowed it down to _embedded_ webextensions specifically. But this is not your case, uMatrix 1.0.1rc0 from AMO is a pure webext, not an embedded one.

Yes, uMatrix controls that setting internally with no UI because it is a hard blocker, it would not make sense to have block rules which are not preventing connections to remote servers to be established.

**Comment by 4i6l** [comment]
Sorry for the confusion. What I meant was that I still saw uMatrix appearing in slot 0 in the predecenceList when using the debugger if I disable it and then uninstall it. (2nd pic in previous comment)
However, the "disable prefetching" toggle in uBlock did work this time as long as uMatrix was disabled or removed.

I just tested again by leaving uMatrix enabled before uninstalling and rechecked the debugger. After doing this, uBlock was the only addon listed there. The "disable prefetching" toggle continued to work this time too.

Now I see that it was the hard-coded prefs in uMatrix that were overriding whatever I had chosen in uBlock. This is fine with me if you deem that is intentional design. I just wanted to know what was causing my prefs to be overridden each time I re-started by browser.

**Comment by gorhill** [comment]
In any case, there is an issue after all regarding embedded webextension, filed: <https://bugzilla.mozilla.org/show_bug.cgi?id=1394111>. 

So for the specific issue here, this is just a misunderstanding: uMatrix also toggle the setting.

What is missing in Firefox is a UI for users to find out which extension owns which settings. There is such UI available in Chromium -- well at least there used to be, for some reasons they removed the ability to find out _exactly_ which extension "own" a specific setting.
