### ISSUE TITLE
Webpages not blocking content from custom filters

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#2902]
### Describe the issue

Testing on 2 separate sites with 2 custom filters

`https://www.theatlantic.com/`

`http://www.activistpost.com/`

**Using the following filters** 

@@||theatlantic.com^$generichidehide Doesn't seem to stop the generic elements from being used.

/mwx$image,domain=activistpost.com  Doesn't seem to work on this site either (part of easylist already)

![activ](https://user-images.githubusercontent.com/1659004/29746749-6642445c-8b38-11e7-8d9e-a2615292c9b8.png)
![atlantic](https://user-images.githubusercontent.com/1659004/29746748-662bbf20-8b38-11e7-9777-bfbdc4f017a2.png)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 64bit
- Browser/version: Firefox Nightly 57.0a1 (2017-08-25) (64-bit)
- uBlock Origin version: 1.3.11rc0 webext

##### Your filter lists

Disabled uBlock filters, just enabled "My filters" and Easylist/Easprivacy etc.

**Comment by gorhill** [comment]
`/mwx*$image,domain=activistpost.com` works, see #1065.

**Comment by gorhill** [comment]
`@@||theatlantic.com^$generichidehide` is not a valid filter, you surely meant `@@||theatlantic.com^$generichide`.

**Comment by ryanbr** [comment]
Typo, but still issues.

![atlantic2](https://user-images.githubusercontent.com/1659004/29747286-19f275e8-8b49-11e7-9077-ea40b8062033.png)

/mwx*$image,domain=activistpost.com  but as you see on activistpost.com, the filter isn't working (its not showing its being filtered in the logger and webpages shows the ads.

**Comment by quilloss** [comment]
Your image says `https://www.theatlantic.com/world/` and `/mwx$image,domain=activistpost.com`.
`/mwx*$image,domain=activistpost.com` on `http://www.activistpost.com/` works for me.

**Comment by shellye5** [comment]
@gorhill  could this be related to this major bug? :

https://github.com/gorhill/uBlock/issues/2684#issuecomment-325178595

**Comment by gorhill** [comment]
Both are working fine here. How many filters are reported as loaded from "My filters" list in "3rd-party filters" pane? Also, you still used `/mwx$` instead of `/mwx*$` above.

**Comment by ryanbr** [comment]
/mwx doesn't need a wildcard, its assumed by default due to ABP (unless a | ends the string). Sure not optimised, but it still follows basic regex rules and would be treated the same. Basically the wildcard is superfluous to requirements. (just to note, very few rules are like this)

I am really trying hard to test the extension again over ABP from a list author's perspective. The fact my custom filter additions aren't working do make me think twice in using uBo. I'll probably be using a pre-FF57 browser until things mature more down the road. 

![rules](https://user-images.githubusercontent.com/1659004/29749826-0f40a274-8b89-11e7-99ab-ee8b0c8a5b79.png)

**Comment by gorhill** [comment]
> I'll probably be using a pre-FF57 browser until things mature more down the road.

uBO _is_ mature.

`@@||theatlantic.com^$generichide` works just fine: all the reported selectors in the logger are found in EasyList and Fanboy Annoyance (which you _did not_ disclose using in your opening comment). There is no generic selector applied to the page:

- `theatlantic.com###subscribe` (Fanboy Annoyance)
- `theatlantic.com##.twitter` (Fanboy Annoyance)
- `theatlantic.com##.sponsored` (EasyList)
- `theatlantic.com##.nav-social-links` (Fanboy Annoyance)
- `theatlantic.com##.facebook` (Fanboy Annoyance)
- `theatlantic.com##.ad` (EasyList)
- `theatlantic.com###footer-newsletter-signup` (Fanboy Annoyance)
- `theatlantic.com###action-bar` (Fanboy Annoyance)

You seems to be too eager to find uBO "wrong". How exactly did you come to the conclusion that `@@||theatlantic.com^$generichide` did not work?

If cases such as `/mwx` are rare as you say, then what is the issue of adding a `*` at the end? This will make the filter work for ABP and uBO. Anyways, it's unfortunate for users of EasyList to suffer such an inefficient filter just because there is no other way to fix the ad issue on `activistpost.com` for ABP specifically. This works for uBO, no inefficient filter required:

    activistpost.com##script:inject(abort-current-inline-script.js, setTimeout, MBoxAdMain)

> I am really trying hard to test the extension again over ABP from a list author's perspective.

I actually write the code for uBO **and** create filters to deal with all the cases seen in the wild, so I have _both_ developer and list author perspectives, hence why I created all the extended syntax -- it makes the task of maintaining filter lists easier, and decrease the need to compromise block filters with exception filters to work around anti-blockers:

![a](https://user-images.githubusercontent.com/585534/29750460-e51dc204-8b0d-11e7-8186-a7dd8d3f7f6c.png)

It's your call to make your life easier by using the extended syntax.

**Comment by quilloss** [comment]
`activistpost.com##script:inject(abort-current-inline-script.js, setTimeout, MBoxAdMain)`
Is there a way to specify multiple domains for script injection?
The easylist filters for `/mwx` has around 3kB of domains to specify.

**Comment by mapx-** [comment]
take a look to ublock filters, for example:
`oload.tv,openload.co,streamango.com##script:inject(openload.co.js)`
