### ISSUE TITLE
.dct in behind-the-scene log while searching in Google

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uBlock#291]
I enabled "Disable hyperlink auditing/beacon" in uBlock.
I did a search in Google. Did not click any links from the search.

Saw and entry that ended with https://www.google.com/..../......dct in the ublock behind-the-scene logger.
(I replaced some text in the above request with period to protect my privacy here)

That request was not blocked by ublock. Is that a beacon or a ping?
Aren't it supposed to be blocked?

I can't provide any screenshots right now, but if you want, I can do it a bit later.

uBlock version 0.9.8.4

**Comment by gorhill** [comment]
Give details please, exact URL, I rather avoid guessing in vain how to reproduce.

**Comment by luxoflux** [comment]
You'll have to provide more information. What browser are you on? How have you configured behind-the-scenes filtering? At least provide a screenshot of the logger and the request which is not being blocked. That URL tells us nothing, I'm sure you can show us more and still anonymize it better than that.

**Comment by gorhill** [comment]
I just confirmed that the hyperlink auditing requests are blocked, using the steps outlined in the release notes. There `ping-to` requests did not have `dct` at the end. In uBlock/Chromium, they are reported as `object` because of a Chromium bug which force uBlock to remap all `other` requests into `object` requests.

This can be confirmed using the _Network_ pane in the dev console. Check "Preserve log". The click on a result link to force an hyperlink auditing request, and if hyperlink auditing requests are not disabled in uBlock, it will appear in the _Network_ pane, and this can be confirm from the `Content-Type` header in request headers: `text/ping`.

So you can all check for yourself, reopen if you confirm with exact steps that `text/ping` requests are fired despite hyperlink auditing being disable. I checked that it works and I have no reason to believe it doesn't

**Comment by castor-troy** [comment]
I am not sure whether it's a ping or a web beacon or whatever. It's a behind the scene request. And I am also not sure whether it is supposed to be block. Wanted to know about it. Here are the screen shots attached.

I am on Windows 7 with Chromium 45.0.2421.0. My default search is disconnect.me.

In this case, I opened Google manually and did a search. I did not click on any of the result link.

![pic1](https://cloud.githubusercontent.com/assets/3329844/7999171/7fff104c-0b64-11e5-88e9-e79b37da169b.png)
![pic2](https://cloud.githubusercontent.com/assets/3329844/7999176/87156e12-0b64-11e5-9234-a90be5e42c31.png)
![pic3](https://cloud.githubusercontent.com/assets/3329844/7999177/8ce501f4-0b64-11e5-88a3-3e5d5900bd7c.png)

**Comment by gorhill** [comment]
Only the request headers can tell for sure whether something is an hyperlink auditing. In any case, this just look like a normal request to me, from where it originates I don't know. Could be one of your extension. I don't get this kind of request on my side.

**Comment by seanrand** [comment]
For the record, these requests are probably related to Google Instant (as you type) results.

```
HTTP/1.1 200 OK
Vary: Accept-Encoding
Content-Type: application/x-sdch-dictionary
```

[Shared Dictionary Compression over HTTP](https://lists.w3.org/Archives/Public/ietf-http-wg/2008JulSep/att-0441/Shared_Dictionary_Compression_over_HTTP.pdf)

**Comment by castor-troy** [comment]
Thanks @seanrand But Javascript is blocked using uBlock on Google. Can Google Instant work without Javascript?

**Comment by gorhill** [comment]
> But Javascript is blocked using uBlock on Google

It's a behind-the-scene request, it's the browser making that request, not the page on which javascript is blocked.

**Comment by castor-troy** [comment]
OK. I just checked with Firefox Beta 39 and I can't see any .dct requests. It seems to be happening only on Chromium. May be the browser is sending a behind-the-scene when Google based websites are loaded. And also, I blocked Google on behind-the-scene request in uMatrix, and is promptly blocked. So, all's fine except that I have more doubts about Google protecting my privacy.
