### ISSUE TITLE
No Longer Supporting ESR Versions of Firefox

### ISSUE THREAD

**Issue by aswgxf** [gorhill/uBlock#2924]
We are using the ESR version of Firefox (Version 52.3.0). I noticed that this plugin now only supports versions 54.0 - 56.*. We have this plugin deployed on nearly every machine on campus, and now new installs are reporting that the plugin has been disabled due to being on an unsupported version of Firefox. Looking at the ESR life cycle the next major ESR release will not release until Firefox 59. Would it be possible to re-add support for Version 52.*?

**Comment by gorhill** [comment]
Read the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.10) please.

Firefox 52 is supported, just that you will have to install uBO from elsewhere than AMO, legacy extensions are phased out on AMO, this has been announced since a long time now. Just download `uBlock0.firefox.xpi` directly from the [Releases section](https://github.com/gorhill/uBlock/releases).
