### ISSUE TITLE
"Custom" in 3rd-party filters pane not collapsible

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#295]

**Comment by gwarser** [comment]
?
![worksfine](https://cloud.githubusercontent.com/assets/886325/8003055/6d76ec1e-0b74-11e5-84ec-3a75f94d274c.gif)

**Comment by Betsy25** [comment]
@luxoflux Which browser (and version) ?
Which uBlock Origin version ?

**Comment by gorhill** [comment]
I interpreted this as meaning to also collapse the text area.

**Comment by luxoflux** [comment]
@gorhill Yes, that's what I assumed it would do.

**Comment by Gitoffthelawn** [comment]
I think is would be an improvement if the text area collapsed with the 'Custom' header as well.  I looked into adding this feature into the [uBlock-Deluxe UI overlay](https://github.com/Gitoffthelawn/uBlock-Deluxe), but because `#externalListsDiv` is not a descendent of `#lists`, it's not possible due to how CSS3 currently works.

@gorhill Can you make `#externalListsDiv` a descendent of `#lists`?

**Comment by gorhill** [comment]
No longer an issue with redesigned filter lists pane in b60c06f3c4d8.
