### ISSUE TITLE
Update & Remove non-working stock filter lists from uBo

### ISSUE THREAD

**Issue by MarkCornway** [gorhill/uBlock#2952]
@gorhill 

Add the following to the default filter list of uBO

https://filters.adtidy.org/extension/chromium/filters/11.txt
https://filters.adtidy.org/extension/chromium/filters/12.txt
https://filters.adtidy.org/extension/chromium/filters/14.txt
https://filters.adtidy.org/extension/chromium/filters/15.txt
https://filters.adtidy.org/extension/chromium/filters/2.txt
https://filters.adtidy.org/extension/chromium/filters/3.txt
https://filters.adtidy.org/extension/chromium/filters/4.txt
https://filters.adtidy.org/extension/chromium/filters/5.txt
https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

ADguard Filter list(Fork of easylist/others with lot's of Ubo filters and no white-list for ADs so prefer these over easylist/easyprivacy/etc)
The other is Filter for the popular addon which disables cookie warning(very useful to people like me who delete cookies every time the session closes)

And finally remove list's which require other addons to work, user's might believe that enabling those
uBO will natively block but it's not the CASE
like
Reek's AAK
uBlockProtector

**Comment by gorhill** [comment]
There are already many issues I left open to take care of this. Reviewing/assessing the stock filter lists is something planned. Marking as generic duplicate, having to find them all would be too time consuming, I will let you find them.

**Comment by lewisje** [comment]
@MarkCornway you should know that the only reason EasyList or EasyPrivacy have any whitelist rules is to work around false positives, so that certain sites will still work; it's not like the Acceptable Ads whitelist, which is specifically created to allow certain ads and may be disabled independently in those extensions (like ABP and AdBlock) that have it on by default.

The lists you posted sound as misguided as the old "EasyList-NoMercy" forks, which were also EasyList without the workarounds for false positives.

**Comment by gorhill** [comment]
> you should know that the only reason EasyList or EasyPrivacy have any whitelist rules is to work around false positives

I didn't realize he was complaining about the exception filters in EasyList.

> Fork of easylist/others with lot's of Ubo filters and no white-list for ADs

Adguard English (`2.txt`) is EasyList + Adguard's own filters. Just look inside:

> EasyList + Adguard English filter

Scroll down, see for yourself. They just import EasyList and add their stuff.
