### ISSUE TITLE
Ublock origin causing problem with Kayako helpdesk agent panel in Firefox

### ISSUE THREAD

**Issue by swarnava** [gorhill/uBlock#2961]
**Screenshot**:-

![Screenshot](https://i.imgur.com/EpEdBEO.png "Screenshot")

DM me for credentials for You can signup for a free trial from https://www.kayako.com/free-trial

**Comment by gomoku** [comment]
https://github.com/gorhill/uBlock/issues/2964

**Comment by gorhill** [comment]
@swarnava How did you conclude the issue is with uBO proper and not caused by one or more filters in the filter lists?

**Comment by swarnava** [comment]
1. I have disabled all active subscription to investigate which one is causing the issue. Seems no one.
2. I have disabled ublock addon on Kayako page, still faced the same issue.

-----

Finally when I disabled the extension completely, it worked.

**Comment by mapx-** [comment]
probably
https://bugzilla.mozilla.org/show_bug.cgi?id=1379148
https://bugzilla.mozilla.org/show_bug.cgi?id=1396226

**Comment by gorhill** [comment]
> Finally when I disabled the extension completely, it worked.

See [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.6):

> There are many reports of people experiencing issues with some web sites, or images not loading, etc. Turns out many of these are a result of using some legacy extensions along uBO/webext. For instance, Reek's AAK in GreaseMonkey has been causing issues with images not loading.
> 
> If you experience such issue, you will have to disable all your legacy extensions and see if this fixes your issue. If so, then you will have to re-enable your legacy extension one by one to find the one(s) causing the problem.

You will have to rule out that another legacy extension is interfering. Once ruled out, the most likely issue is what @mapx- posted above, you will have to add your experience to the bugzilla issue. A way to see if this is really your issue is to install another pure webext blocker to see if they also cause the same issue: [AdBlock](https://addons.mozilla.org/en-US/firefox/addon/adblock-for-firefox/), [AdBlocker Ultimate](https://addons.mozilla.org/en-US/firefox/addon/adblocker-ultimate/).

**Comment by swarnava** [comment]
I have tested with Adblock Plus and it's working fine.

**Comment by mapx-** [comment]
Did you use ABP beta (web ext) ?
https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/beta

**Comment by swarnava** [comment]
huh. Indeed it's a webext issue :3 

Thank you guys!
