### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by gomoku** [gorhill/uBlock#2964]
My proposal to add to https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md:

_[THE SHORT VERSION]_:

Please stop placing "**uBO is causing/breaking/doing something bad...**" offensive accusations/slanders in a title of the issue, until you have the proof/evidence that it's uBO causing the issue.

 _[...THE LONG VERSION]_:

...because it might be uBO's causing an issue, but not necessarily, it still can be caused by a browser / a website / a mistake / an addon / a plugin / bad settings at reporter's side / whoever know what else, and there are already many past such titled issues which have ended labeled: invalid, unable to reproduce, external, filter issue etc. Such false titles of the issues spoil reputation of uBO, especially as they are also being indexed by uncle Google, and then read by thousands of people in internet. Instead of a title: "Ublock is causing problem with a box in Firefox" use a more neutral one: "A problem with a box in Firefox". If the issue will be explored/investigated further and turns out to be uBO or something else causing the issue, the title can be edited and changed then.

_Regardless of whether the short or the long version, it can be placed at the beginning or in the middle or in Before you submit section or in any other part of the guide. Also my non-ideal english has to be corrected to real-native-english of course. I've intentionally used so long title as a visually visible statement, feel free to shorten back if bothering (I've done it already), or close the issue, no problem._

**Comment by gorhill** [comment]
> Please stop placing **"uBO is causing/breaking/doing something bad..."** offensive

That would be overly sensitive to ask this. As long as I can correct erroneous claims I don't want to put such rules in place. It could very well happen that one such claim is true at some point, cannot rule it out.

To keep adding to CONTRIBUTING is not working, because basically many just don't read it.

The idea I am currently bouncing is to open an "issue triager" project under [uBlockOrigin](https://github.com/uBlockOrigin), and this is where people would open issues. I would add people who have shown a willingness to contribute triaging/validating/invalidating/reproducing/etc. as members, in order to have the power to close issues.

Only the issues which have been fully worked out as valid and actionable would be imported here (I would make the issue tracker here read-only). So this should take care of lowering significantly the need for me to deal with every single issue, I would be able to focus on the ones which are important, and finally go back to be able to code with more focus.

**Comment by gomoku** [comment]
> @gorhill: It could very well happen that one such claim is true at some point, cannot rule it out.

I have to disagree, because:

> @gomoku: If the issue will be explored/investigated further and turns out to be uBO or something else causing the issue, the title can be edited and changed then.

Isn't that more logical than claiming at the beginning, in the title, what is causing the issue, without even knowing if it is even true?

> @gorhill: To keep adding to CONTRIBUTING is not working, because basically many just don't read it.

So I'm wondering why you just have updated CONTRIBUTING.md by yourself 4 days ago, that's why I've made the proposal, because I've seen your updates four days before, is that you have changed your mind within last 4 days?

As for "issue triager", theoretically not a bad idea, but in the practice the point is whether there will be enough of such people to keep issues importing to issue tracker, because usually single people come, fil an issue, deal with it a few days, and then leave, we'll have to see.

**Comment by Atavic** [comment]
Big repos always have some lazy issuer that doesn't give enough info or is just angered for a problem they can't solve. By pointing them to the issue triager where title and issue are well presented, they have no other choice than update their own report properly.

That could even work for umatrix.

**Comment by gomoku** [comment]
I would expect the answer/ a counter argument before closing/declining
