### ISSUE TITLE
some elements are hidden after it is displayed

### ISSUE THREAD

**Issue by Anoop2609** [gorhill/uBlock#2972]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs
www.youtube.com

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![screenshot 20](https://user-images.githubusercontent.com/23557479/30038291-664f4a54-91e0-11e7-9116-c6beaf32ecde.png)

![screenshot 24](https://user-images.githubusercontent.com/23557479/30038615-54ffe084-91e4-11e7-9b5c-3286c28299a2.png)
![screenshot 26 _li](https://user-images.githubusercontent.com/23557479/30038655-bf4e47a0-91e4-11e7-9690-b4e5121e726f.jpg)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
Just open https://www.youtube.com and you will see. There are other site also where the blank space is displayed sorry because i was not listing all of them. Test this on "Private Window" because store data may change result

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: Nightly FF57
- uBlock Origin version: 1.14.7 rc0

##### Your filter lists
My filters, uBlock filters – Badware risks, uBlock filters – Unbreak​​​​, ​uBlock Protector List, EasyPrivacy, Fanboy’s Enhanced Tracking List, Fanboy’s Annoyance List, Peter Lowe’s Ad and tracking server list

##### Your custom filters (if any)
Anti popads.net, Clickbait Blocklist, Fanboy's Indian, Overlay Blocker, 
Subscription, that block sites with skimming scripts, Adguard English, Adguard Annoyances, Adguard Spyware

**Comment by gwarser** [comment]
By design: https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

I must say is more visible lately.

**Comment by kasper93** [comment]
Yes, after switching to webext pure css filters that were before flicker free now often lags behind and you can see elements before being blocked. I guess we will have to live with it.

**Comment by Anoop2609** [comment]
So ublock should report this on Bugzilla because this is a problem for efficiency.

**Comment by gorhill** [comment]
> By design: 

For Google search page and Youtube, there are specific cosmetic filters, so it's not by design -- it owuld be by design if we were dealing with generic cosmetic filters.

I haven't experience such flickering on my side.

**Comment by gorhill** [comment]
> My filters, uBlock filters – Badware risks, uBlock filters – Unbreak​​​​, ​uBlock Protector List, EasyPrivacy, Fanboy’s Enhanced Tracking List, Fanboy’s Annoyance List, Peter Lowe’s Ad and tracking server list

There is your issue: please do not un-check "uBlock filters", there is absolutely no good reasons to do so, unless you want to sabotage uBO I would say.

**Comment by gwarser** [comment]
@gorhill can you explain this:

On https://www.dobreprogramy.pl/Juz-po-wakacjach-a-WiFi-w-Pendolino-nadal-nie-ma,News,82964.html

UBO reset to default + Fanboy’s Annoyance List + POL,POL + https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

Firefox ESR
UBO 1.14.7rc0 legacy
 - no visual issues

Firefox Nightly
UBO 1.14.7rc0 webext
- cookie message flashes on top
- when autoscrolling (bit faster than you read), just above comments section, social buttons flashes (facebook/twitter)

**Comment by gorhill** [comment]
I'm not saying that what is documented at <https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters> is no longer true -- it's just as relevant now as it was before, webext or legacy.

I am saying that OP's specific issue (Google and Youtube) does not exist if "uBlock filters" are enabled, so I am not going to waste time investigating a non-issue.

Whether you run Firefox 55 or Nightly, it's the same uBO code. If you have specifics which are unrelated to the issue here, open a new issue and I will look into it. The way Firefox is configured may matter (servo? out-of-process? etc.)

**Comment by gorhill** [comment]
gwarser I tried your steps, and I couldn't see a difference on my side, nothing flickered -- not that I was not expecting it given that cookie notices and social buttons are typically generic cosmetic filters, but there was no flicker in both FF55 and FF57 on my side. If course reloading the page to test again is pointless because after the first load the formerly generic cosmetic filters are cached as specific cosmetic filters.

**Comment by gwarser** [comment]
I tested with addons disabled, and only first page load after restart (no caching). Now rechecked with and without servo and no change.

**Comment by kasper93** [comment]
@gorhill I can reproduce the issue, like I said after switching to webext it started to happen. But I don't have clear STR, it happens from time to time. I might try latter to figure out how to reproduce it reliably and report back.

**Comment by gorhill** [comment]
Open a new issue if you want to report STR, the issue here is not valid: in 2014, specific cosmetic filters were created to avoid the issue in OP, so disabling those filters was not a valid case. I can't use the issue here as a reference for code change, so if you want something to be investigated/fixed (if possible at all) because things have worsened relative to legacy, a new issue is required.
