### ISSUE TITLE
[Firefox 52 ESR] Main menu is unusable.

### ISSUE THREAD

**Issue by 794** [gorhill/uBlock#3003]
The main menu (where the power button appears and you can use the element selection tool) is completely bugged for me. [This is what the menu looks like when I click the icon.](http://puu.sh/xwOfI/1bc9c51aaf.png)

- OS/version: Windows 10 1607 64bit
- Browser/version: Firefox 52.3 ESR
- uBlock Origin version: 1.14.0

**Comment by gorhill** [comment]
Can't help, you will have to investigate on your side and report the cause of the issue.

**Comment by 794** [comment]
Wow, what a super helpful dev. What a joke.

**Comment by gorhill** [comment]
I am not here to be everybody's "computer guy". You have only provided extremely scarce information. Your screenshot is absolutely of no help except to show you quite probably have customized your Firefox to the point of the issue arising because of your own doing, so you will have to fix it yourself. The release notes clearly mention that legacy extensions are incompatible with webext extensions -- again it is your responsibility to read them, nobody else can do it for you.
