### ISSUE TITLE
[Feature Request] Auto-save User Filter "My filters"

### ISSUE THREAD

**Issue by gotitbro** [gorhill/uBlock#3007]
Many a times I find that I loose my custom filters in "**_My filters_**" due to mistakenly clearing data or resetting one thing or the another. I have been able to recover most of these filters as I, thankfully, had made a manual backup using the "**Export**" feature.
It would be really helpful and beneficial for all users if a feature which saves the custom user filters from My filters in a pre-designated file can be implemented. We can call this "Auto save user filters/My Filters". It can backup the filters daily or weekly.

It would indeed save the day when user filters are mistakenly cleared.

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by gorhill** [comment]
uBO does not have access to your file system, it requires user interaction to save something through a simulated download operation.

**Comment by gomoku** [comment]
Closing and marking as invalid, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

**Comment by gotitbro** [comment]
@gorhill Thanks for the clarification.

@gomoku Okay, but then where else can one open such discussions?

**Comment by gomoku** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit

> Do NOT: Submit feature requests.

**Comment by uBlock-user** [comment]
[This post](https://github.com/reek/anti-adblock-killer/issues/2752#issuecomment-289281066) perfectly summarises why you make people dislike you and why you keep getting kicked and why I choose to leave my response via reactions on Github for people like you.

**Comment by gotitbro** [comment]
@gorhill What about a sync like functionality for "My Filters"?

**Comment by gomoku** [comment]
> @uBlock-user: This post perfectly summarises why you make people dislike you and why you keep getting kicked and why I choose to leave my response via reactions on Github for people like you.

Please stop your personal emotional attacks on me, stop insulting me, and stop abusing and hijacking another thread whether by your massive child thumbs down emojis not supported by arguments, or by any other personal talking to me, because you already had several chances to reply to me in the past, but you wasted them and spammed me by the thumbs down or smile emojis instead, so now it's too late for you for any explanations here, if you want to continue your personal flame against me, do it on your private blog, stop abusing repos around. The same to your "friends": @Fuj- which also has insulted me by pasting unreasonable links to Wiki here: https://github.com/gorhill/uBlock/issues/3012#issuecomment-329149656 
and @GianniGi which has insulted me by thumbs down emoji here:  https://github.com/gorhill/uBlock/issues/2968#issuecomment-326933928

In such personal situations, reacting by such emojis/links not followed by reasonable counter-arguments is called trolling/hating and lack of counter-arguments:
https://en.wikipedia.org/wiki/Internet_troll
https://en.wikipedia.org/wiki/Hatred

By this behaviour, all 3 of you have been marked and proved be me to be trolls/haters. If you want to prove something, then prove it by reasonable counter-arguments, if you can't do it, just accept losing a discussion.

It's also sad that @gorhill hasn't and doesn't take any actions against your personal attacks on me and against insulting me by thumbs down/laugh emoji/agressive links, but on the other side he takes actions against me, against just a constructive criticism with no agressive emojis or links. It seems some flawed logic here / some double standards allowed here. But not only here, the same standards in some other places I described in the link @uBlock-user has provided above. It seems that none of you can accept a constructive criticism / or you take it as an attack, or can't deal with some unconfortable facts described here: https://www.google.pl/search?q=adblock+acceptable+ads+scandal&gws_rd=cr&dcr=0&ei=-ki5WaTRLumn6AShu6G4DQ .

Also take a look at my answers: walls of strong reasonable arguments, while your answers contains  thumbs down/laugh emojis/ agressive links not followed by a single argument.

Also for example @Photon89 is an example of a mentally healthy person, which doesn't take a constructive criticism as an attack, and even thanks for the hint: https://github.com/gorhill/uBlock/issues/2947#issuecomment-328270164

Consider you all not being mentally healthy persons.

I don't expect any real arguments from any of you, as you have already proved enough to have no arguments at all, instead for example @gorhill just like to close threads like here: https://github.com/gorhill/uBlock/issues/2964 and here: https://github.com/gorhill/uBlock/issues/3012 instead of provide reasonable arguments. So I'll be just sitting and looking at yours continuation of your emotional/personal flames.
