### ISSUE TITLE
request: Temporarily disable for all sites

### ISSUE THREAD

**Issue by majax79** [gorhill/uBlock#301]
I'm hoping for the ability to temporarily disable ublock origin everywhere by left or right clicking the icon. Currently, I have to go into chrome addon and manually disable ublock origin, but this way would make it a lot easier.
This feature is in adblock and adblock plus. It's called "Pause AdBlock" and "Disable Everywhere". I find it really useful.

**Comment by gorhill** [comment]
Give me a very concrete scenario of why this would be useful to you. Something that I can verify myself, not something from a thought experiment, I want a very specific scenario.

**Comment by 5t3f4n** [comment]
This was already [suggested](https://github.com/chrisaljoudi/uBlock/issues/1432) by @majax79 for [uBlock](https://github.com/chrisaljoudi/uBlock) (where I expressed my initial [skepticism](https://github.com/chrisaljoudi/uBlock/issues/1432#issuecomment-109297273)) and it's apparently slated for future release. I suggest you wait and see what how their implementation of this turns out and, if it's something you can get behind, pull most/all of the code from there.

**Comment by hotdogman** [comment]
#167

**Comment by gorhill** [comment]
This has been asked a couple of times, and never there is a convincing concrete scenario offered that is so common that it would be justified for uBlock to replicate what is already provided by the browser. If somebody needs to do it so often to the point of annoyance, my advice is to just pin the _Extensions_/_Addons_ tab.

**Comment by 5t3f4n** [comment]
I don't know what browser you're using @majax79 but if you're using Firefox you can use the <kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>A</kbd> or <kbd>Ctrl</kbd>+<kbd>⇧</kbd>+<kbd>A</kbd> keyboard shortcut to quickly access the Add-ons Manager.

**Comment by majax79** [comment]
@5t3f4n I asked in ublock because I thought ublock was ublock origin. Not really sure why there is two to begin with, but I was just told ublock origin was more actively updated.

As to why I want it, I use GPT websites, say swagbucks. I can disable for swagbucks website, but when you attempt an offer or a survey it has to be disabled or you won't get rewarded. It's impossible to disable for every individual survey or offer. Thus, I would have to manually go into addons and disable it.

To those arguing it's not needed, then why is it a feature of adblock and adblock plus? It's obviously needed by some, but they don't come here and request it. As of now, I just left-click adblock plus and select, disable everywhere. Then I enable it again when I'm done. It saves me time during my day. 

If it's not implemented, then I'll just stay with what I have. I just prefer the less resources being used by ublock origin.

**Comment by gorhill** [comment]
> when you attempt an offer or a survey it has to be disabled or you won't get rewarded

I am certainly not going to make uBlock more user friendly for the benefit of data miners.

**Comment by Gitoffthelawn** [comment]
@gorhill I respect where you are coming from, but to be fair, I don't think majax79 is a data miner or wants to reward them.  He's the one asking for the feature, so the primary benefit would be for him, not a data mining company.  Since majax79 runs uBlock the rest of the time, there probably would be relatively little data available.

By the logic you are employing, uBlock should block all of google by default, since a majority of traffic to google is probably benefiting a data mining mega-corporation.

From the posts in this repo (it's one of the most frequently requested features), plus those on the main uBlock repo, plus functionality available on competing products, it's clear that some people think they want isolated, intentional, and transparent sessions of unfiltered web use,

It's also clear that you think that you are not one of those people.  But categorizing the needs of all these users as somehow wanting to make uBlock or uBlock Origin "more user friendly for the benefits of data miners" is not a fair characterization.

Their needs, if looked at openly, actually present a great opportunity for uBlock that I don't think any competing product can claim.  In another thread, I think you mentioned that you didn't want to copy ABP functionality; instead you wanted to determine what functions the user really needs, and design a product that accomplishes those.  I agree with you completely.  So here's something that ABP can't do that users want to do: perform web functions that require a little bit of data sharing without performing any unnecessary sharing.  Majax79 states that in ABP, he completely turns it off all filtering (momentarily) to get certain functions to work.  I doubt that is what he really wants.  Likely, he actually wants to keep all filtering ENABLED, except the filtering that is preventing him from performing his task.  But the ability to do that is not built into ABP.  To my knowledge, no filtering tool has that ability right out of the box.  It's a great opportunity for uBlock to do something that no other filtering tool can do.

**Comment by gorhill** [comment]
> I don't think majax79 is a data miner 

Of course I know.

> By the logic you are employing, uBlock should block all of google by default

Please, stop this silliness. uBlock can be disabled through the browser. My position is that it's not worth replicating a browser feature for such edge cases.

**Comment by CrisBRM** [comment]
Disabling through the browser: 3 clicks.
Hypotheticaly disabling through the addon: 2 clicks.

... and in your head, programmer time that could be used doing something else is worth that extra click.

**Comment by Gitoffthelawn** [comment]
No need for testy or aggressive posts.  Keep it friendly and happy, okay?  :-)  The idea is just to discuss issues related to uBlock, nothing more.  

I don't think @gorhill or @CrisBRM understood what I was conveying.  I'm talking about functionality that is not currently available via any browser (to my knowledge): the ability to toggle into a mode that allows the user to filter the appropriate amount so they can accomplish common tasks, like the one majax79 describes.  For many tasks, full filtering is appropriate.  For other tasks, less filtering is appropriate.

**Comment by gorhill** [comment]
@Gitoffthelawn 

> No need for testy or aggressive posts

Pointing out that your argument ...

> By the logic you are employing, uBlock should block all of google by default

... is silly does not imply aggressiveness. It is definitely silly, it is _completely_ unrelated to whether or not I should care implementing a "disable everywhere" feature.

**Comment by Gitoffthelawn** [comment]
I apologize if that seemed aggressive to you; it certainly was not intended that way.  If you think something is aggressive, simply talk about it instead of responding in kind.  It keeps the world a happier place.  Sometimes things written on the internet sound different than they were intended.

My reason for mentioning google is that if the point of uBlock is to block any and all data mining operations, then it would probably make sense for it to block almost all of google.  But uBlock doesn't block most of google by default (thus likely allowing data mining), because using google is a task that some users (but not all) may want to perform.  That's identical to the request made by majax79 who started this thread (see his second post above).  I think characterizing his request and possible solutions as silly is not accurate.
