### ISSUE TITLE
Add Popup Blocker

### ISSUE THREAD

**Issue by hawkeye116477** [gorhill/uBlock#3014]
@gorhill Welcome! Chinese and Russian has 3 filters and one of them is annoyance filter. 
So I think that Polish annoyance filter also should be added to uBlock filter lists. 
Can you add Popup Blocker?
`https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt`

**Comment by gorhill** [comment]
There is already two lists for Polish, I don't want to keep adding lists in there, it's a convenience for the lists which it makes sense to use for majority of users.

Otherwise the proper action for a user is to visit https://filterlists.com (linked from the wiki, which is itself linked from the _"3rd-party filters"_ pane) to pick whatever else they want. For the Russian and Chinese, I may chose to remove one for each, I have been revisiting the content of the _"3rd-party filters"_ pane lately to and I will continue to do so.

**Comment by anewuser** [comment]
As a note, there are way many more Chinese and Russian-language sites than Polish ones, so it makes sense to exist multiple lists to cover different subsets of filters. 

You should attempt to make the creators of those Polish filters to work together on one of the already existing lists to avoid the fragmentation of your small community.

**Comment by hawkeye116477** [comment]
@anewuser These filters lists are for different things. Not all wants to have blocked cookies notices, not all wants to have blocked some widgets, not all wants to have blocked social things, etc, so why that we have few filter lists.
