### ISSUE TITLE
Extra extension tab open with Ublock Origin options in Chrome

### ISSUE THREAD

**Issue by NVHT** [gorhill/uBlock#303]
So when I go to Ublock Origin options by right-clicking the icon on Chrome, it always open an extra extension tab.

**Comment by gorhill** [comment]
Not much I can do for this. Related to #237.

It's Chromium forcing extensions to have their options open within the _Extensions_ page. Since all of uBlock settings do not fit in the limited space available in the _Extensions_ page, uBlock has to open it's own page: Chromium opens the _Extensions_ page, and from there uBlock opens it's dashboard page.
