### ISSUE TITLE
Tab Mix Plus conflict? (close tab icon missing)

### ISSUE THREAD

**Issue by Gittyperson** [gorhill/uBlock#3046]
This came up recently. Using Pale Moon 27.4.2 x64, uBO 1.4.10, TMP 0.5.0.4, Windows 10 x64. The close tab button inside the tabs disappears:

![04](https://user-images.githubusercontent.com/7165208/30691327-13a2731a-9ed0-11e7-8077-b34e2b126218.png)
Normal tab bar:

![05](https://user-images.githubusercontent.com/7165208/30691348-1ea8644a-9ed0-11e7-88be-174a01d47e46.png)

Using a light theme (persona) in the screenshots, same with default theme. Problem comes and goes upon browser restarts. I tried isolating the cause by building a clean profile with default settings and gradually installing my other extensions, but the only obvious result I can reach is that when I disable uBO and restart the browser, the problem goes away. Re-enabling uBO (and restarting) brings the issue back.

**Comment by gorhill** [comment]
Any issue specific to Pale Moon will have to be completely investigated by Pale Moon-using volunteers. As I said somewhere, best is to fork uBO and do exactly what is being done for Safari and Edge, where issues specific to these platform are taken care by volunteers using that platform. I am not willing to have more stuff piled onto me. Once the cause of an issue has been pinpointed, then I will decide whether to fix the issue here.

**Comment by mattatobin** [comment]
Can't say I didn't see this coming two years ago. Maybe next time I speak people will listen.

**Comment by gorhill** [comment]
@mattatobin Please stick to providing technical information relevant to the current issue if you have _any_ -- read carefully the first paragraph in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)), this applies to all reported issues, there is no special treatment for Pale Moon.

Nothing changed in uBO's code dealing with the toolbar, hence the most likely issue is that something else is causing it.

I am merely asking people to _contribute_ investigative work to avoid burdening this repo with too many invalid uBO issues.

From my point of view, the real contributions are those where the reporter invested time and effort to find the real cause of an issue. The issue here does not qualify, and neither does your rant.

**Comment by Gittyperson** [comment]
Gorhill was right in that I needed to research a bit more. It's an unusual situation for me because a third extension might be involved in triggering this. Still testing, I'll post again if I find something.
