### ISSUE TITLE
uBlock Origin doesn’t honor noscript tags when blocking JS

### ISSUE THREAD

**Issue by linkmauve** [gorhill/uBlock#308]
In advanced mode, when blocking some or all of the JS scripts on a page, the noscript tag following the script tag is never used.

Here is a simple testcase for this issue, the page should display either “Using &lt;script/>” when using JS, or “Using &lt;noscript/>” when blocking it, but it currently displays nothing when using uBlock Origin.

http://linkmauve.fr/files/ublock.xhtml

**Comment by gorhill** [comment]
There is no good solution for this.

uBlock does not disable javascript in the browser, it prevents it from running using a `Content-Security-Policy` header, and in such case it appears the browser does not fall back on `noscript` tags. Forcing the `noscript` tag to render using some trickery lead to [other issues](https://github.com/gorhill/uMatrix/issues/232).

So there is no good solution. Maybe file an issue with the browser devs to ask them if the `noscript` tags can become active whenever the browser can't execute `script` tags, for whatever reasons, not just just because javascript is disabled in the browser.

**Comment by luxoflux** [comment]
So those annoying `<noscript><meta http-equiv="refresh" content="0" url=...></noscript>` redirects don't function now? I hadn't noticed when that changed, but I'm glad.

**Comment by gitarra** [comment]
Just for the record, e.g. NoScript honours noscript tags. NoScript also has options whether to allow META redirections inside them or to hide them completely.

**Comment by vn971** [comment]
Can we maybe use this technique?: http://kb.mozillazine.org/Allowing_only_certain_sites_to_use_JavaScript

That is, if all javascript is disabled for a site, can we set
`user_pref("capability.policy.nojs.sites", "http://www.example.com http://www.example.net");`
?

This probably has to be carefully thought of as uMatrix can both function as a blacklist and as a whitelist, but still, even supporting the simplest most popular scenario would be awesome!

**Comment by chiraag-nataraj** [comment]
I just ran into this when trying to ensure my site was accessible to users who don't have javascript. Do we know how NoScript manages to deal with the `<noscript>` tag and can we do something similar?

**Comment by bzbarsky** [comment]
Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1392090 will make this work for "script-src 'none'" once fixed.  For cases when some but not all scripts are blocked, the desired behavior of noscript tags is ... unclear at best.

**Comment by gorhill** [comment]
> will make this work for `script-src 'none'` once fixed

Ok thanks. Well, a master javascript switch was an alternative solution, however it could not be implemented in Firefox due to [`browser.contentSettings`](https://developer.chrome.com/extensions/contentSettings) not being present.

Between both solutions, I like the `script-src 'none'` far better, because this matches exactly uBO's way of deciding on the fly as to whether something is blocked or not, while this is not possible with the essentially declarative `chrome.contentSettings` API.
