### ISSUE TITLE
Add uBlock Origin development version to Chrome Webstore

### ISSUE THREAD

**Issue by xaek** [gorhill/uBlock#3082]
I suggest adding the development version of uBlock Origin to Chrome Webstore, so that bugs and regressions could be reported in a timely manner.
There is already Development Channel on AMO, so I think that it is reasonable to add it to webstore too.

Furthermore Adblock Plus and Adguard have development versions on Chrome Webstore. So why doesn't uBlock Origin have dev build there too?

- Adblock Plus development build -- https://chrome.google.com/webstore/detail/adblock-plus-development/ldcecbkkoecffmfljeihcmifjjdoepkn

- Adguard AdBlocker Beta -- https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl

**Comment by gorhill** [comment]
"uBlock Origin dev build" pushed to the Chrome store, marked as "pending review".

**Comment by mikhaelkh** [comment]
@gorhill are you going to set up automatic store upload like in [uBlock Protector](https://github.com/jspenguin2017/uBlockProtector/issues/312). Are you going to upload only relatively stable RC's or every commit? Please share a link here and in Readme.md when it'll be aalible.

**Comment by jspenguin2017** [comment]
I have to say that automated update is HARD to setup, mainly because Google's doc are broken, I mean VERY broken. But once you set it up, it will build and publish a new version every time you push, it also bypass review process (after the first publish). 
I had to write a couple custom tools for make it work. Unfortunately I can't share the tools as I had to hard code my credentials into them. You also need to dig into Travis PRs as their docs are broken as well. 
Also debugging the deploy script is near impossible if you don't have a callback server, as you don't want your script to crash and dump your credentials in the public build log. The callback server is also needed to store the version of your last build.

**Comment by xaek** [comment]
uBlock Origin dev build is already published to Chrome store

https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii

**Comment by gorhill** [comment]
https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii

**Comment by uBlock-user** [comment]
just an FYI, a duplicate clone of the dev build also got in today - https://chrome.google.com/webstore/detail/ublock-origin-dev-build/nfhbjennnadfpfigkpkfdgioeobceieo?hl=en

**Comment by mikhaelkh** [comment]
@gorhill, right now dev version (1.14.25.101) is older than release version (1.15.0) in Chrome Store. I think it's better to update dev version when you update release version so that dev version is never older. For example, usually when [Chrome](https://chromereleases.googleblog.com/) promotes to next major version, beta channel updates too.

**Comment by mikhaelkh** [comment]
@gorhill, right now [dev version](https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii) (1.14.25.101) is older than [release version](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) (1.15.2) in Chrome Store. You should update dev version when you update release version so that dev version is never older, e.g. when [Chrome Stable](https://chromereleases.googleblog.com/) promotes to next major version, beta channel updates too.
