### ISSUE TITLE
Anti-Adblock Killer | Reek 8.1 needs a userscript in order to fully work

### ISSUE THREAD

**Issue by SW1FT** [gorhill/uBlock#312]
I just found this out, I had no clue that it needs to have a userscript to fully work. I suggest warning people that they need it in order for this list to be working properly.

[Check the README on its GitHub.](https://github.com/reek/anti-adblock-killer/blob/master/README.md#instruction)

**Comment by Betsy25** [comment]
That's correct, it's logical also. Simply removing an overlay item does not "unlock" the content of that page to become browsable, there's a set cookie needed, and an accompanying js has to run in order to unlock the page, which only run when you pressed the "I understand" or "Yes, I will" or whatever button.

The AAK list itself does nothing in the user's interest by itself.

**Comment by lewisje** [comment]
That's probably a good idea now that more of uBlock's userbase came to it as their first ad-blocker and therefore probably haven't heard of Reek's anti-Adblock-killer already; normally one would see the UserScript first and then be told to subscribe to the filter-list.

**Comment by gorhill** [comment]
A special "info" icon will appear for when there are special instructions to read:

![c](https://cloud.githubusercontent.com/assets/585534/8086649/703020b2-0f64-11e5-85f3-1a43c8966a02.png)
