### ISSUE TITLE
Fanboy's lists "Home" URL should be updated (?)

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#3135]
Support page for:
- Fanboy's Enhanced Tracking List
- Fanboy’s Anti-Thirdparty Social (Anti-Facebook List)
- SWE: Fanboy's Swedish

should be change to https://github.com/ryanbr/fanboy-adblock/issues

Right now, only "Fanboy's Social Blocking List" and "Fanboy's Annoyance List" have this in header:
```
! Please report any unblocked content or problems by email or in our forums 
...
! Forums: https://forums.lanik.us/
```
Fanboy's Enhanced Tracking List, Fanboy’s Anti-Thirdparty Social (Anti-Facebook List) and Fanboy's Cookiemonster List have:
```
! Reporting Issues: https://github.com/ryanbr/fanboy-adblock/issues
```
This was updated 8 months ago https://github.com/ryanbr/fanboy-adblock/commit/8b01841dfbef57e7be59be4e1f1f12bfb4e06dcc

Fanboy's Swedish have
```
! Homepage: http://www.fanboy.co.nz/
```
and in http://www.fanboy.co.nz/ link on top is pointing to https://github.com/ryanbr/fanboy-adblock/issues

@ryanbr ?

**Comment by gorhill** [comment]
Thanks for reporting. For things like this I would accept a pull request. For changes in `assets.json` specifically, json-linting after the changes in a requirement.

**Comment by Hrxn** [comment]
Recommendation for linting?

**Comment by gorhill** [comment]
https://jsonlint.com/

**Comment by Hrxn** [comment]
Uh, yes, if only it would be so uncomplicated..
[RFC 4627](https://www.ietf.org/rfc/rfc4627.txt)
[RFC 7159](https://tools.ietf.org/rfc/rfc7159.txt)
[ECMA-404](https://www.ecma-international.org/publications/standards/Ecma-404.htm)

:cry::wink:

Personally, I've been using http://jslint.com so far..

What I actually wanted to know was more like what do with your editor, because some of them have linting support etc. right built in.
Not sure what to use there, does ESLint work? I mean with the default settings?
