### ISSUE TITLE
Would you consider skipping already hidden nodes in procedural selector early?

### ISSUE THREAD

**Issue by kasper93** [gorhill/uBlock#3179]
So, nodes hidden with procedural filter are marked with session id. It is not necessary to walk down the tree if the node is already hidden. 

This can be easily achieved with adding `:not(...)` to simple selector part of procedural filter. This will avoid testing full procedural chain for already hidden nodes. This will help with complex procedural filters.

Thanks

**Comment by gorhill** [comment]
Only if the case is made this actually provides measurable gains without being detrimental in the big picture (i.e. if it shows gain, I don't want these to apply to some very specific case).

I will close the issue now because the case is not made, and will reopen if ever the case is made in a thorough manner (i.e. actual and reliable benchmarking data) for real world cases (i.e. not contrived ones.)
