### ISSUE TITLE
A case that a custom RegExp rule doesn't work

### ISSUE THREAD

**Issue by danny0838** [gorhill/uBlock#3208]
### Steps for anyone to reproduce the issue
1. Add a new Chrome user and switch to it.
2. Install UBO.
3. Add a single custom RegExp rule `/^https?://(?:\w+[.])?youtube[.]com/user/julica138(?=[/?#]|$)/`
4. Load this page: `https://www.youtube.com/user/julica138`
5. The page is not blocked by the RegExp rule.

### Your settings
- OS/version: Windows 7 SP1
- Browser/version: Google Chrome x64 62.0.3202.89
- uBlock Origin version: uBlock Origin v1.14.16

**Comment by gorhill** [comment]
> The page is not blocked by the RegExp rule

No blocker will block a whole page with such a filter. Use the `document` option to block a whole page.

**Comment by danny0838** [comment]
I am confused. According to the [documentation](https://github.com/gorhill/uBlock/wiki/Strict-blocking), strict blocking is default. For example, the rules `example.com` and `http://example.com` makes the page `http://example.com` blocked, without the `document` option.

[The documentation for RegExp rules](https://github.com/gorhill/uBlock/wiki/Regular-expression-based-filters) doesn't mention that the default is different to the above rules.

Additionally, using same test method, the rule `/^https?://(?:\w+[.])?youtube[.]com/channel/UCwsAJAMyGad-kFJePW2vtZw(?=[/?#]|$)/` causes the page `https://youtube.com/channel/UCwsAJAMyGad-kFJePW2vtZw` blocked. If a RegExp rule doesn't block the whole page, then this rule is working wrong?

**Comment by gorhill** [comment]
> and `http://example.com` makes the page `http://example.com` blocked, without the document option

Yes, there is a heuristic in place so that filters like those appearing in malware lists are wholly blocked, while filters which match beyond the hostname are not wholly blocked, to avoid tiresome false positives. The current heuristic is the [result of many discussions](https://github.com/chrisaljoudi/uBlock/issues/1128) about the original implementation blocking as soon as there was a match.

**Comment by danny0838** [comment]
You mean that a rule blocking a domain defaults to strict blocking, while a rule that blocks a specific path and all RegExp rules doesn't? Is there a more comprehensive documentation about this?

And the issue of 3F that the RegExp rule /^https?://(?:\w+[.])?youtube[.]com/channel/UCwsAJAMyGad-kFJePW2vtZw(?=[/?#]|$)/ causes the page https://youtube.com/channel/UCwsAJAMyGad-kFJePW2vtZw blocked still seems to have no explanation...

**Comment by gorhill** [comment]
> still seems to have no explanation

That is unexpected, I have to investigate.

**Comment by gorhill** [comment]
Ok, the explanation for the second case is two-fold:

1) There is an old regression that is still left in the code, `false` should be returned [at that line](https://github.com/gorhill/uBlock/blob/02323826950c7d99b65d93f9edb8fa018159973c/src/js/traffic.js#L314).

2) The regex is found not matching in 1) because the URL is converted to lowercase before being matched against the regex, however the regex is not converted to be case insensitive, while it should.

So these two things need to be fixed.

**Comment by lewisje** [comment]
Why should the whole URL be converted to lowercase, rather than just the scheme and domain name? Most parts of a URL are case-sensitive.

**Comment by gorhill** [comment]
Because by default ABP's filter syntax is case-insensitive -- one needs to use `match-case` for case-sensitiveness.
