### ISSUE TITLE
Developer Mode Warning if installed manually

### ISSUE THREAD

**Issue by hrxn** [gorhill/uBlock#322]
Just tried a manual install, for, uh curiosity reasons..

I followed the steps listed here: https://github.com/gorhill/uBlock/tree/master/dist#install

Installation works as suggested, but every time Chrome is launched, the following messages appears:

![1](https://cloud.githubusercontent.com/assets/12064918/8047782/db741dfe-0e49-11e5-9114-e247d62e7816.png)

Some more details (I forgot, am in a hurry):

OS: Windows 7 SP1 x64 , fully patched etc.
Chrome: 43.0.2357.81 m (64-bit)

Fresh install, nothing changed so far. Well, one exception, disabled the new bookmark menu thing via chrome://flags

uBlock Origin 0.9.8.6

I also tried a manual install of https://github.com/chrisaljoudi/uBlock, but with the same result..

**Comment by luxoflux** [comment]
This is just how the Chrome devs treat their users, like idiots. I'm even on the dev channel and still get this warning. Switch to Firefox and all is well (although Mozilla is going in that direction too, just slower).

**Comment by hotdogman** [comment]
As @luxoflux said, switch to Firefox or Linux.
>https://support.google.com/chrome/answer/2811969?hl=en
>Extensions disabled by Chrome
>The information below applies to Windows and Mac users only.

This is not a mistake. Google Chrome disables extensions that aren't from the Chrome Web Store for the security of its users. This is because extensions that are not from the Chrome Store are often malware/adware. Extensions on the Chrome Store have to be reviewed, which greatly reduces chances of malware/adware making it into your browser.
http://chrome.blogspot.com/2014/05/protecting-chrome-users-from-malicious.html
https://blog.chromium.org/2015/05/continuing-to-protect-chrome-users-from.html

**Comment by luxoflux** [comment]
For now the dev edition will not enforce the signature requirement, but it seems more than likely Mozilla would follow Chrome's example sooner or later:
>Unfortunately, we’ve since observed malicious software forcing users into the developer channel in order to install unwanted off-store extensions.

If that happens I'd probably just move away from the official build.

**Comment by gorhill** [comment]
There is nothing I can do, it's a browser feature, out of control of uBlock, or any extension.

I see that 0.9.8.6 has _finally_ been approved in the Chrome store, so install this version, this will eliminate the warning.

**Comment by Hrxn** [comment]
The nanny state is seeping into every niche ;-)

Anyway, thanks for clearing that up!

I will use the version from the Chrome store then, I assume it works just as good :)
