### ISSUE TITLE
Cosmetic filtering not applied properly on some sites after automatic filter updates/manual updates 

### ISSUE THREAD

**Issue by shellye5** [gorhill/uBlock#3223]
### Describe the issue

On sites like reddit cosmetic filtering is not applied sometimes .

### Screenshot in which the issue can be seen

https://imgur.com/a/dan5W

see the second pic

### Steps for anyone to reproduce the issue

1. visit reddit 
2. check the right sidebar, the placeholder is not removed

### Your settings

- OS/version:  wind10
- Browser/version:  FF57
- uBlock Origin version: 1.14.19b3(previous stable too)

##### Your filter lists

Default filter lists
and sometimes
All with cosmetic filtering

To disable the issue just goto filters,
tick ignore generic cosmetic filters and apply
then untick ignore generic cosmetic filters and apply

reload page and the page is filtered properly(first screenshot)

**Comment by gorhill** [comment]
These symptoms is exactly what happens when you disable/restart uBO. I suspect this is what you are seeing.

I can't reproduce and this is an issue I've never seen. I will re-open if you or someone else can narrow to repro steps which cause the issue to happen for sure -- otherwise this issue will never go anywhere.

**Comment by shellye5** [comment]
@gorhill can you try these

start FF
clear data
restart
open ubo
purge update
load pages.

This is exactly how saw this so maybe just maybe you can reproduce
