### ISSUE TITLE
AAK-Cont Is Discontinued

### ISSUE THREAD

**Issue by kah0922** [gorhill/uBlock#3241]
[AAK-Cont has been discontinued.](https://gitlab.com/xuhaiyang1234/AAK-Cont/commit/e7ba251c5853eb541376fd9a393983934b7d0ef1)

The replacement seems to be [AdBlock Protector 2](https://adblockprotector2.github.io/AdBlockProtector2/); however, while the filterlist has been released, the actual extension has not.

**Comment by lewisje** [comment]
At least AAK-Cont will be available for download, for those who still wish to use it (probably people on Pale Moon or Waterfox or a Firefox ESR earlier than 59, who cannot or refuse to use Firefox Quantum).

**Comment by kah0922** [comment]
Actually...
> This repository will be archived 1 month after ABR2 comes out of beta.

**Comment by lewisje** [comment]
Right from the AdBlock Protector 2 page:

> AAK-Cont, although unmaintained, will still be available for download.

**Comment by jspenguin2017** [comment]
@kah0922 
AAK-Cont was last updated in September, it is unmaintained for a while already, I just didn't made it official. 

ABR2 is ready for developer preview, as I need to inject `'unsafe-inline'` for it to work properly, I'm afraid that it will conflict with uBO, and probably ABP too. I wouldn't need to do that for Quantum 58+, so I'll probably wait for it. ABR2 will be released to the extension stores sometimes next year. 

Archived just means daily build script will be turned off, it will still be installable although I wouldn't recommend that. Daily build task will still run for now, the only thing changed since September is that I no longer accept issues in AAK-Cont repository.

**Comment by ericzutter** [comment]
You wrote that AdBlock Protector 2 extension is not available yet. What about using in the meantime <a href="https://jspenguin2017.github.io/uBlockProtector/">uBlock Protector Extension + uBlock Protector List</a> for Chrome/Chromium webbrowsers ?

For Chrome/Chromium web browsers, what is the advantage for using in the future AdBlock Protector 2 extension instead of uBlock Protector Extension ?

**Comment by jspenguin2017** [comment]
If everything goes planned, ABR2 will work with AdBlock, Adblock Plus, and other reasonable adblockers. Also, ABR2 *may* be able to completely take over the task and work alone, block ads and protect itself from detection. There is no other advantage for Chrome (that are planned for now). 

I need at least a network filtering engine to get a minimal prototype working, I plan on experimenting with WebAssembly to see if it will help with CPU and RAM usage, the current prototype is way too inefficient. 

But all that is just plan, the future is unknown.

**Comment by Luckz** [comment]
In other words, nothing you plan on releasing will work for non-Quantum Firefox (and Waterfox, Pale Moon, etc etc)?

**Comment by jspenguin2017** [comment]
ABR2 is canceled.

**Comment by Niftator** [comment]
This has basically left people who refuse to "upgrade" to webextensions/chrome without a viable option for strong anti-adblock
