### ISSUE TITLE
Allow scripts to run globally

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#3305]
### Describe the issue
While not efficient, filters should be allowed to run globally (and not just domain specific);  

In the same way we have site.com##.sample, the global filter ##.sample works.

### Example
Testing on this site: `https://www.asianhobbyist.com/`

**Works:**
asianhobbyist.com##script:inject(bab-defuser.js)

**Doesn't work (and its variances):**
##script:inject(bab-defuser.js)
.com##script:inject(bab-defuser.js)
*.com##script:inject(bab-defuser.js)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.14.20

##### Your filter lists

Easylist + Easyprivacy + Fanboy Annoyances

**Comment by uBlock-user** [comment]
From what I understand, global filters like `##.sample` are inserted after the page loads in uBO which can't be done in the case of scriptlets, otherwise they may or may not win the race.

**Comment by gorhill** [comment]
Declined, we must not underestimate the inefficiency.

Allowing this will lead to obvious performance issues in the future, just as has happened with generic cosmetic filters. Best way to avoid this is to not allow it.

**Comment by gorhill** [comment]
@uBlock-user 

> From what I understand, global filters like ##.sample are inserted after the page loads in uBO which can't be done in the case of scriptlets, otherwise they may not win the race.

This is not the issue at all, there is no DOM surveying necessary with scriptlets injection.

**Comment by uBlock-user** [comment]
@gorhill But would they still win the race ?

**Comment by gorhill** [comment]
They would be injected no later than they would be when injected for a specific site.

**Comment by elypter** [comment]
you can modify my script i use to block annoying sticky headers. it is a python script that generates the required code for the major top level domains because it works with tlds but not globally. your example doesnt even work with tlds but you can still use alexas top 10 thousand or 1 million websites and create a generic rule for each domain. it creates a several mb file and is all but elegant but it works and if that is what gorhill wants then it is the way to go. https://github.com/elypter/generic_annoying_stickybar_filter
