### ISSUE TITLE
feature request- dark theme

### ISSUE THREAD

**Issue by Gnustier** [gorhill/uBlock#3342]
Feature request : 　
　- Optional dark theme for dashboard, logger, popup menu, element selector, 　
　　in order to take care of eyes in dark ambience or at night.
　- Optional theme which inherit colors from browser or OS, 　
　　in order to keep color consistency and visibility when changing the color theme of browser or OS.

- OS/version: Windows 7 sp1 x64
- Browser/version: Firefox 57.0.2 64bit
- uBlock Origin version: 1.14.20

**Comment by Gnustier** [comment]
Someone please tell me why

**Comment by gorhill** [comment]
Because it's not something I will ever feel compelled to work on, so no point leaving the issue open forever. Even if there was only this one issue opened on the tracker, between taking a walk and sitting at the computer to _work_ on this, I would always pick taking a walk.

**Comment by jspenguin2017** [comment]
Oh I like this idea!

**Comment by cubedj** [comment]
I've got even all the needed css that I'm using in my custom version of uBlock... so only thing that would need to be done is a user friendly way of implementing the switching of the theme ;)

**Comment by jspenguin2017** [comment]
I think a "theme store" is better, what if someone wants a green theme? And this also allow the community to customize things better. 
BTW, for dark theme, can't we just copy from https://github.com/dhowe/AdNauseam ?

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl How does uBo/uM look with [ShadowFox](https://github.com/overdodactyl/ShadowFox) ?

**Comment by overdodactyl** [comment]
@Thorin-Oakenpants - I've started a dark theme for uBO but haven't yet put it in the repo.  If their are users interested in that, I can place it is my next top priority :)

**Comment by overdodactyl** [comment]
@Thorin-Oakenpants, sorry it took me a little while to get to this!

What do you think of something like this:

![ublock](https://user-images.githubusercontent.com/33071129/34311884-42067c6c-e758-11e7-9083-b29ab7e01754.png)

**Comment by Thorin-Oakenpants** [comment]
^^ I have no opinion because I'm not using any dark tweaks (well, not yet, just a handful of UI related ones). I only linked to you in here for interested readers. Are the red/green elements semi-transparent? Because they seem way too dark - see pic below (I just pasted some colors into random squares for comparison - these are not my actual settings)

![lightenupbro](https://user-images.githubusercontent.com/16656956/34315825-22e80e66-e7eb-11e7-94bf-021890d4f966.png)

Should create an issue in your repo rather than talk about it here
