### ISSUE TITLE
unblockable ads

### ISSUE THREAD

**Issue by KonoromiHimaries** [gorhill/uBlock#3363]
![2017-12-14 04_36_11-dobreprogramy - portal nie tylko o oprogramowaniu](https://user-images.githubusercontent.com/5884000/33974410-88726548-e088-11e7-9bbb-a03b9e4f5e43.png)
`dobreprogramy.pl`

unblockable ads

https://github.com/NanoAdblocker/NanoFilters/issues/3

Steps to reproduce the issue
* join to this site
* use this filter
```
dobreprogramy.pl##body > *:matches-css(background-image: /data:image\/(gif|jpg|jpeg|png);base64,/):matches-css(position: fixed)
```

my filters
https://gist.github.com/KonoromiHimaries/809ef17633ba86197db6df03d6790f16

uBlock Origin 1.14.22
Nano Defender 13.8
Chrome 63.0.3239.108
win10

**Comment by gorhill** [comment]
I don't see that ad when using both POL filter lists.

**Comment by okiehsch** [comment]
See https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-352157505

**Comment by gorhill** [comment]
Well, with 1.14.22 a costly procedural cosmetic filter can still be disabled if it's really, _really_ expensive. In the end, filter list maintainers are responsible to craft their filters carefully. The filter above is lacking in such carefulness, so this could be an issue on slower CPU.

Instead of:

    dobreprogramy.pl##body > *:matches-css(background-image: /data:image\/(gif|jpg|jpeg|png);base64,/):matches-css(position: fixed)

Try

    dobreprogramy.pl##body > *[class]:matches-css(position: fixed):matches-css(background-image: /^url\(data:image\/(gif|jpg|jpeg|png);base64,/)

Notice:
- be more selective with the prefix selector
- put the least expensive `matches-css` first
- the data: URI is over 11,000 characters, so you want to avoid a regex that will scan the whole URL

**Comment by KonoromiHimaries** [comment]
@gorhill this filter not working for me
```
dobreprogramy.pl##body > *[class]:matches-css(position: fixed):matches-css(background-image: /^url\(data:image\/(gif|jpg|jpeg|png);base64,/)
```

**Comment by gorhill** [comment]
I edited the filter to remvoe the `class`, try again the edited version. But anyways, just modify your filter in your list so that the regex is more efficient (avoid scanning whole URL), and use the cheapest `matches-css` first.

**Comment by gorhill** [comment]
Also, see if at the console your filter is being disabled, uBO reports when this occurs.

**Comment by KonoromiHimaries** [comment]
@gorhill still not working
```
dobreprogramy.pl##body > *:matches-css(position: fixed):matches-css(background-image: /^url\(data:image\/(gif|jpg|jpeg|png);base64,/)
```

**Comment by gorhill** [comment]
Did you investigate whether the element to filter matches anything in the DOM? Please investigate _more_ on your side.

**Comment by KonoromiHimaries** [comment]
@gorhill i don't know
https://gist.github.com/KonoromiHimaries/3ea43a26be11a5824951ebe093eb9f01

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/34274162-62df5f24-e665-11e7-82a2-86096b26181c.png)

**Comment by KonoromiHimaries** [comment]
yes, i off this filter on the test.

**Comment by gorhill** [comment]
Ok, I think the page is changing the class under some conditions, and uBO's mutation observer does not observe class changes.

**Comment by gorhill** [comment]
The page is trapping calls to `getComputedStyle` -- most likely to foil uBO:

    Object.defineProperty(window, 'getComputedStyle', {
        value: function (e, p) {
            return e && e.hasAttribute('YszMpo') ? null : opMzsYopMzsY(e, p);
        },
    });

This could be the issue.

**Comment by jspenguin2017** [comment]
> The page is trapping calls to `getComputedStyle`

Isn't element hiding handled by content script? 

![image](https://user-images.githubusercontent.com/7283682/34274920-1b4a02c0-e658-11e7-85af-8ba93b539ff3.png)
![image](https://user-images.githubusercontent.com/7283682/34274932-31f8c952-e658-11e7-87ff-53caac00f71c.png)

**Comment by gorhill** [comment]
Yes, that's right.

**Comment by gorhill** [comment]
How about:

    dobreprogramy.pl##body > *:matches-css(position: fixed):matches-css(background-image: /^.{0,8}data:image\/(gif|jpg|jpeg|png);base64,/)

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34275185-59dccc7e-e659-11e7-9497-e40015a5ce42.png)
Apparently there is a double-quote there.

**Comment by jspenguin2017** [comment]
This works for me, but it takes like 5 seconds before it gets hidden: 
```
dobreprogramy.pl##body > *:matches-css(position: fixed):matches-css(background-image: /^url\("data:image\/(gif|jpg|jpeg|png);base64,/)
```

**Comment by gorhill** [comment]
There is this:

    dobreprogramy.pl##a[id][href="#"]:xpath(..)

**Comment by gorhill** [comment]
Probably a case that would benefit from a `:remove` operator: removing the style node behind the ad removes the need to chase for the ad in the dom.

**Comment by jspenguin2017** [comment]
I was definitely looking into a remove operator (or selector or however you call that), I was planning on adding it but I'm not really familiar with how the cosmetic engine works so I added a surrogate that works half the time instead (`nano-remove-element-onready.js`). 
The problem is if uBO can easily remove element instead of hiding them, they can easily watch for remove as well, so we'll be back to chasing it around the DOM. It takes a lot of effort to correctly implement `:remove` and once we have it, there is an obvious counter to that.

**Comment by gorhill** [comment]
> they can easily watch for remove as well, so we'll be back to chasing it around the DOM

There is _always_ something they can do in response to what blockers do. If the mindset in the past had been that there is no point doing something because they can always do something to work around, there would be no blockers today.

**Comment by jspenguin2017** [comment]
> This also can be said of every single filter we add, and yet we are here, adding filters. 

It really depend on what we are dealing with, if it's a third-party detection library, I usually craft a generic rule so the time it takes them to overcome my rule is unreasonable compared to the time I need to craft the rule. For example, in the battle against NoAdBlock, my first rule took them 2 days to overcome, my second rule took them 2 weeks, and my third rule took them already a few months and they still haven't be able to get around it. 

I think in this case here we are dealing with a "library" or something third-party, because they need to make sure their code works for all their customers, it is rather hard for them to make changes. So I think it's worth investigating deeper to strike where it hurts, like API interface or other hard-to-change components. 

`:remove` is useful, I'm not saying it's not, it's just not the right tool for this specific job here.

**Comment by gorhill** [comment]
Quick test with HTML filtering, these seems to work:

    dobreprogramy.pl##^script:has-text(DisplayAcceptableAdIfAdblocked)
    dobreprogramy.pl##^style:has-text(/^\[/)

Requires Firefox 57+ and uBO dev build.

Using HTML filtering to fix the issue here would really be the simplest way for uBO users. Are Polish users willing to move to Firefox 57?

**Comment by KonoromiHimaries** [comment]
@gorhill 
> Are Polish users willing to move to Firefox 57 given the behavior of top .pl sites?

I do not think it's going to happen
50% users use at chrome and i know that not changed because 1 ad has be showed
mozilla not be better, mozilla have own ads
```
https://www.reddit.com/r/firefox/comments/7jh9rv/what_is_looking_glass/?st=jbc2pv1c&sh=83a5507d
```

**Comment by gorhill** [comment]
Yes, they fumbled. However that extension was never ever enabled by default, it had to be enabled by the user. I checked the code on GitHub, I can confirm.

If people are not using Firefox and instead pick Chrome because of that one event, this just makes no sense, that would be an irrational decision: there is no way Chrome gives you the same level of [config capability offered by Firefox](https://github.com/ghacksuserjs/ghacks-user.js). In any case, all has been said about that LookingGlass event, I don't want the issue to become more of it.

I am merely pointing out that at some point, uBO can't do magic, it has to deal with the real world with realistic solutions. And so far, Firefox 57 with uBO 1.1.15 will be far better equipped than Chromium to deal with what out-of-control sites are throwing at browsers. In the end users will move to what works.

So in any case, I will add the filters above to uBO's filters when 1.1.15 is published, and I more genrally will add whatever HTML filters benefit Firefox users, while Chrome users will have to accept imperfect solutions with trade-offs (CPU-intensive procedural filters, glitchy rendering because DOM fighting, Chrome's lack of support for user stylesheets, etc.).

Same reasons I advise people to move to Firefox when they suffer Instart Logic's crap.

**Comment by jspenguin2017** [comment]
> there is no way Chrome gives you the same level of config capability offered by Firefox

Chrome comes with a decent amount of flags and more command line options than you need: https://peter.sh/experiments/chromium-command-line-switches/

The Chrome DevTools is definitely better than Firefox's one. You get a warning every single time you open background page console and if you clicked the wrong button, you have to reinstall Firefox. 
And you can only have one background console open at one time, how are you suppose to debug cross extension messaging? 

> uBO can't do magic

It's not magic, it's polyfill. Nano Defender can filter script tags since last year, so can uBO. 

> Chrome's lack of support for user stylesheets

It's almost released, it's in dev or beta.

**Comment by KonoromiHimaries** [comment]
new ads
![2018-01-11 15_57_40-dobreprogramy - portal nie tylko o oprogramowaniu](https://user-images.githubusercontent.com/5884000/34831797-44c868ee-f6e8-11e7-9993-db1542022ec7.png)

**Comment by Martina-Neumayer** [comment]
Yeap.. and new crap.. https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-357144766
