### ISSUE TITLE
[Question] Is there a way for uBlock to protect users from password manager fingerprinting?

### ISSUE THREAD

**Issue by Uricorn** [gorhill/uBlock#3384]
See:
https://www.theverge.com/2017/12/30/16829804/browser-password-manager-adthink-princeton-research

Source:
https://freedom-to-tinker.com/2017/12/27/no-boundaries-for-user-identities-web-trackers-exploit-browser-login-managers/

It is possible for filters to try and identify these scripts and block them one by one, but I wonder if there was anything else that can be done or a more efficient way to go about it, as currently only one of the scripts mentioned in the article is being blocked and there will undoubtedly be more.

For now clearly disabling autofill is the safest thing, but that will not be done by avg. user.

**Comment by gorhill** [comment]
Filter issues. Use default-deny if you to lower the probability of this happening. Firefox has a setting to disable auto-fill. Otherwise, block javascript if you don't even trust 1st parties by default.

**Comment by uBlock-user** [comment]
Don't use third-party password managing extensions.

**Comment by jspenguin2017** [comment]
Wow, hold on, password manager is extremely important, you have to use one, otherwise, one website you use gets hacked will cause all your accounts to be hacked. 
Although I use a native password manager, most people use extension version for convenience, there is nothing wrong with that.

**Comment by gorhill** [comment]
The issue here occurs even with the password manager integrated in the browser.

It's a browser issue. As soon as javascript code is allowed to run on a page, the code can freely interact with the DOM.

**Comment by uBlock-user** [comment]
> one website you use gets hacked will cause all your accounts to be hacked.

Don't use same password for all websites, thought was obvious.

**Comment by gorhill** [comment]
So apparently I understood wrong and the issue is with only 3rd-party password manager?

**Comment by cy7yz2rj** [comment]
No, I think you got it right. The issue is with autofill, 3rd-party or native doesn't matter.

**Comment by gorhill** [comment]
Yes ok, the issue is the user id field, not the password one (well at least with the password manager integrated with the browser).

So anyways, this is really a browser issue. From uBO's point of view, this is a filter issue -- and as reported, there were filters in EasyPrivacy to prevent the invasive scripts.

**Comment by uBlock-user** [comment]
> the issue is with only 3rd-party password managers? 

The issue is with all the password managers, 3rd party or not. My suggestion was a precaution towards using 3rd party password managers in addition to what you said before, as using them you're opening yourself to be vulnerable.

**Comment by GuardianMajor** [comment]
I have done this myself on my own but was wondering perhaps an option that would similar to CSP and RTC blocking that have right now, so that it will simply disable Autofill globally, for those who need it/or want it/and can't do it on their own. Just a thought. It's a bit of a machete but should do the trick for those who find it an acceptable tradeoff. You should never be allowing anything autofill anyway as if you accidentally or intentionally go to a site that is using hidden bait fields, then autofill is giving away your credentials, so it should never be enabled by default anyway, in that sense I agree with @uBlock-user, although not with the general do not use message, as with anything you are trusting to some degree a third party, even using this extension you are trusting that it won't abuse it's extensive access, so that in of itself is not reason to not use it, any developer can go malicious at any point, so by that logic you should never use anything you didn't build yourself. Including your OS.

**Comment by uBlock-user** [comment]
> Although not with the general do not use message, as with anything you are trusting to some degree a third party, even using this extension you are trusting that it won't abuse it's extensive access, so that in of itself is not reason to not use it, any developer can go malicious at any point, so by that logic you should never use anything you didn't build yourself. Including your OS.

I meant it specifically when it comes to dealing with personal information like passwords, that is not something to be shouldered by a 3rd party extension. When it comes to passwords, you can only trust yourself.

**Comment by Hrxn** [comment]
Another suggestion: Use KeePass(XC) with the Auto-Type feature.

And you can still keep the auto-fill functionality enabled, just turn off the option to save passwords in general in the browser.

**Comment by cubedj** [comment]
if you can't live without autofill in Chrome you can at least use the flag [#fill-on-account-select](chrome://flags/#fill-on-account-select)
