### ISSUE TITLE
This extension failed to modify the response header "Content-Security-Policy"

### ISSUE THREAD

**Issue by t33rex** [gorhill/uBlock#3420]
I have been getting this on 2 different computers (running Chromium Version 63.0.3239.108 x64 on Linux with uBO, uMatrix and HTTS everywhere only):

>Warning:
>This extension failed to modify the response header "Content-Security-Policy" of a network request because the modification conflicted with another extension (uMatrix).

I can't figure when it happens but from time to time it does happen.

**Comment by gorhill** [comment]
Only one extension can modify any given header -- it's an extensions API limitation, by design.

So you have another extension modifying the CSP header, you will have to configure your extensions to solve the conflict, or if configuration is not possible, you will have to remove one of the extension conflicting.

**Comment by Tanath** [comment]
I get this all the time, and it says it's because of uBlock Origin. How do you configure them to work together?
