### ISSUE TITLE
Android Firefox corrupted downloads with uBlock on

### ISSUE THREAD

**Issue by LaxrMediumWas** [gorhill/uBlock#3478]
Files downloaded with and without uBlock have different Hash

Install uBlock, update the filters, download something from https://www.apkmirror.com

- OS/version: Android 4.4, 8.0
- Browser/version: Firefox 58.0.1
- uBlock Origin version: 1.15.2

Default filter lists

**Comment by gorhill** [comment]
See <https://github.com/NanoAdblocker/NanoCore/issues/95#issuecomment-359539345>.

Related?

**Comment by gorhill** [comment]
Please be more detailed:

- Provide an exact download page, keep the download small
- Provide the signature with and without

**Comment by gorhill** [comment]
Please try dev build at <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta?page=1#version-1.15.3rc0> and report whether this fixes your issue. This is a "blind" fix since I can't reproduce. However it does look like the same issue as the one reported previously by another user, apparently caused by some custom `about:config` changes. The code change is to not start stream data modification if the response from the server is a redirection.

**Comment by LaxrMediumWas** [comment]
all is fine, thanks
