### ISSUE TITLE
uBlock crashes on Firefox every two weeks

### ISSUE THREAD

**Issue by dmonay** [gorhill/uBlock#3513]
### Describe the issue
I've been using uBlock origin since November 2017, when FF 57 came out. Since then I have observed a pattern of the uBlock addon crashing around every two weeks. It fails silently and simply disappears from the toolbar. Restarting FF restarts the addon, and it's good for another two weeks.

### One or more specific URLs where the issue occurs
None.

### Screenshot in which the issue can be seen
None

### Steps for anyone to reproduce the issue
1. Enable uBlock origin.
2. Use FF normally.
3. Within two weeks (+/- a few days), notice uBlock extension disappearing from toolbar.

### Your settings

- OS/version: MacOS Sierra 10.12.6 (16G1114)
- Browser/version: 58.0.2 (64-bit)
- uBlock Origin version: 1.15.6 and earlier (since FF57 released)

**Comment by gorhill** [comment]
You will have to investigate on your side, there is nothing I can do on my side.

**Comment by dmonay** [comment]
Does uBlock have an auto-update feature? It may fail to reinstall itself after updating.

**Comment by gorhill** [comment]
The browser updates the extension, uBO can't update itself.

**Comment by scottlowe** [comment]
I have just seen this issue, and also saw it a week or two ago. I think it is probably related to Firefox Quantum updating in the background and requiring a restart, because a new version of Firefox had indeed downloaded when I checked the "About" menu. I restarted and issue was fixed.

TBH, I can always tell when FF has downloaded a new version of itself because various subtle things in the UI start to break. Firefox probably puts some new libraries in place on disk which conflict with what's in memory; not much one can do about that. It's just one of those things 🤷‍♂️

**Comment by krboisseau** [comment]
I've also been seeing this issue infrequently. The uBlock icon just disappears and it stops blocking ads or functioning at all. Going to the addon settings screen and trying to disable uBlock and re-enable it does nothing. I have to restart Firefox each time. Previously it would only happen every few weeks or so, but recently it's been happening every couple days. It's been happening ever since Firefox updated to Quantum. 

I don't think it's related to a Firefox update being available as @scottlowe suggested, because it just happened to me 20 minutes ago and when I checked the About page within Firefox, no updates were available/it said I was "Up to date". It also happened two days ago, but Firefox hasn't had an update beyond 58.0.2 in a week.

**Comment by gorhill** [comment]
> recently it's been happening every couple days

I updated uBO twice yesterday.

**Comment by gorhill** [comment]
One approach is to disable auto-update for uBO on Firefox. Firefox will warn you when a new version is available. This is probably the safest way to have uBO update, given that some people have reported strange issue when uBO updated automatically. On my side, when I install a new version (happens all the time, it should be the equivalent of an update, i.e. the extension is stopped and restarted), I have experienced no issue.

**Comment by krboisseau** [comment]
I don't really know much about using the browser console for debugging, but I left it open in the background for a while today, and one message I noticed that stuck out for me that could be related was this one:

14:29:41.503 No WebExtension found with ID uBlock0@raymondhill.net 1 ExtensionParent.jsm:676
	createProxyContext resource://gre/modules/ExtensionParent.jsm:676:13
	receiveMessage resource://gre/modules/ExtensionParent.jsm:644:11

Which was always followed by this one:

14:29:41.506 No matching message handler for the given recipient. 1 MessageChannel.jsm:913
	_handleMessage/</< resource://gre/modules/MessageChannel.jsm:913:11

Does that help at all? Is that related? I had not restarted my browser yet since the most recent uBO crash. I tried disabling/enabling from the addons menu to see if that would show anything in the log (it did not), but then left the log open and kept browsing normally.
