### ISSUE TITLE
HTML filter showing up as cosmetic filter in logger

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#3541]
### Describe the issue

When adding certain HTML filters they show up as cosmetic filters.

### One or more specific URLs where the issue occurs

https://www.reddit.com/

### Screenshot in which the issue can be seen

https://i.imgur.com/dpaRhR2.png

### Steps for anyone to reproduce the issue

1. Add `reddit.com##^.promotedlink` to 'My Filters'
2. Open logger then open https://www.reddit.com/
3. Filter shows up as `reddit.com##promotedlink` in the logger

### Your settings

- OS/version: Windows
- Browser/version: Firefox 58
- uBlock Origin version: 1.15.10

##### Your custom filters (if any)

`reddit.com##^.promotedlink`

**Comment by Ravizz** [comment]
I can reproduce: Win7 & Opera 51.0 & uBO 1.1.5.10 + EasyList
Moreover after I've disabled EasyList, `reddit.com##^.promotedlink` doesn't show up in the logger, which mean EasyList is both triggering/blocking `##.promotedlink` DOM element

**Comment by gorhill** [comment]
Yes, similar to #3494.

The HTML filtering filter does not apply at `https://www.reddit.com/` because nowhere is there an element matching `,promotedlink` in the source code (see `view-source:https://www.reddit.com/` -- use Chromium for this, its output is more friendly). The HTML filter will be reported in the logger only when there is a match in the response data.

Again, a reminder that HTML filtering is _not_ the same thing as cosmetic filtering -- the filters have a different semantic -- HTML filters apply to the response data, whereas cosmetic filters apply to the DOM. The `.promotedlink` elements are added dynamically after the page loads.

**Comment by gorhill** [comment]
I am trying with a class which I see in the source code, and it's not showing up in the logger:

    reddit.com##^.entry

Investigating.

**Comment by gorhill** [comment]
I made a mistake in 1.15.10, this needs fixing asap.

**Comment by grenzor** [comment]
>I see ##.promotedlink in the logger on my side, or reddit.com##.promotedlink when I click on the filter

Sorry, this was a typo in the OP, I had meant `##.promotedlink`. 

I didn't know that elements added dynamically could not be removed with HTML filters so I guess the only issue here is just like #3494.

**Comment by Ravizz** [comment]
OK, you're right about HTML vs cosmetic filtering, so that explains why `reddit.com##^.promotedlink` doesn't show up in the logger, but I'm still wondering why  `##.promotedlink` DOM:

- after enabling EasyList, is found on Twitter (triggered by EasyList) but
- after adding `reddit.com#@#.promotedlink` is no longer found on Twitter (the inspector doesn't find it anymore)

I mean what has `reddit.com#@#.promotedlink` to `##.promotedlink` being triggered or not at Twitter's side?
I mean `reddit.com##.promotedlink` / `reddit.com#@#.promotedlink` just hides / not hides `##.promotedlink`, but it should not prevent `##.promotedlink` from still being triggered by EasyList and generated at Twitter's side?
