### ISSUE TITLE
CodeMirror problem

### ISSUE THREAD

**Issue by okiehsch** [gorhill/uBlock#3567]
### Describe the issue
The browser search function does not work properly in some filter lists.

### Steps for anyone to reproduce the issue

- Install uBlock 1.15.11b6 besides the stable version
- Open the uBlock-filter list in the stable version and search for "Fingerprint2"
![buggg](https://user-images.githubusercontent.com/16838044/36922059-eb91c1b6-1e66-11e8-9d87-d023d11c93a2.PNG)
I get 85 hits.
- Open the uBlock-filter list in the dev version and search for "Fingerprint2"
![bu](https://user-images.githubusercontent.com/16838044/36922116-23b2ec8c-1e67-11e8-8a54-e87c0d33f4aa.PNG)
I get zero hits.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 64

**Comment by jspenguin2017** [comment]
Make sure to focus the text area before pressing `Ctrl+F` so CodeMirror's search bar appears instead of browser one. (Personally I still like Ace better)
CodeMirror will only render lines that are visible because otherwise the performance goes missing. 
![image](https://user-images.githubusercontent.com/7283682/36925808-e439792a-1e31-11e8-80ca-2bd902cd7676.png)

**Comment by okiehsch** [comment]
Thanks, so if you have 85 hits you can use `Ctrl-G`  and `Shift-Ctrl-G` to go through them all, but this is not ideal for the average user in my opinion.

**Comment by jspenguin2017** [comment]
It's even less ideal when EasyList takes 9 seconds to render.

**Comment by okiehsch** [comment]
EasyList renders basically instantly on my end.

**Comment by jspenguin2017** [comment]
In the stable version?

**Comment by okiehsch** [comment]
Yeah, I was about to edit my comment.

**Comment by gorhill** [comment]
I will see what I can do to improve the search widget -- the default one from the library is rather bare.

**Comment by overdodactyl** [comment]
Just wanted to mention this in case anyone runs into this problem:

If you're running macOS, Firefox 58 and and have `privacy.resistFingerprinting` set to `true`, Code Mirror's search widget won't appear even if you focus on the text area.

I assume it's due to the OS getting spoofed and the usage of cmd keys instead of ctrl (same problem that was occurring with GitHub's text editor, Google Docs and others).  Firefox 59 no longer spoofs the operating system, and the search widget works fine there with RFP on.  

https://bugzilla.mozilla.org/show_bug.cgi?id=1404608
https://bugzilla.mozilla.org/show_bug.cgi?id=1405810

**Comment by gorhill** [comment]
I added a sticky search widget at the top of codemirror editor, this way whichever search feature is used should become obvious. The browser's own find-in-page feature is not suitable for codemirror editors. 

Advantages of the codemirror's own search widget:
- supports regex (use `/.../`)
- scrollbar annotations work on both chromium and firefox.

this is a customized version of the stock codemirror search widget, to deal properly with ctrl-f and related shortcuts, and to modify the behavior to better suit the usage in uBO.
