### ISSUE TITLE
uBlock (Chrome only) redirects to another site at tomshardware.com 

### ISSUE THREAD

**Issue by Fizbin99** [gorhill/uBlock#3597]
OS/version: Windows 8.1 Pro 64Bit 
Browser/version: Chrome 64.0.3282.186
uBlock Origin version: 1.15.2 (Also tried newer and older versions)
(Problem happens on a Win 8.1 Pro AMD PC as well)

Lately I've been doing google searches regarding PC parts and from there I would enter tomshardware.com (In other words, I wasn't entering tomshardware from the front door, although I'm sure this issue would still arise) While there, something was causing me to leave tomshardware and I would find myself on a web site called gamiss.com

I downloaded a program called Fiddler, which records every bit of HTTP/HTTPS traffic. and I was getting stuff like:

c-5uwzmx78pmca09x24x78iomil0x2eowwotmagvlqkibqwvx2ekwu.g00.tomshardware.com 
metric-agent.i10c.net:443
(Tunnel to) www.gamiss.com:443

It took me awhile but after a process of elimination and disabling every extension, I discovered that the problem would only go away after disabling uBlock. (And upon doing this, tomshardware was faster too)

I tried older versions of uBlock, as far back as September 2017 and this still occurs, which makes me wonder if Chrome has something to do with it as well, since **the issue does not occur on Firefox**.

One more thing to note (with Chrome)... When LOGGED IN to tomshardware with uBlock ON, the redirect to gamiss.com doesn't seem to happen. But I still get those "c-5uwzmx" entries.

I think the best way for someone to duplicate this is to go to google, type in something like "asus vs asrock". Click "More results from www.tomshardware.com" and then click on a few topic headers (let the page load before you arrow back) until you get find yourself on gamiss.com.

I was able to duplicate this on another Windows 8.1 Pro AMD PC as well.

**Comment by Hrxn** [comment]
Looks like that IL crap again.. oh my.
Yeah, Chrom[e|ium] needs uBlock-Extra for that.

**Comment by gorhill** [comment]
I can't reproduce the redirection to `www.gamiss.com`. However is my guess: you are being served an ad which causes this redirection. On my side I get ads from my local area, about insurances.

The reason you are served ads which bypass uBO is because Tom's Hardware is using Instart Logic's anti-user tech, which purpose is to bypass blockers, **including** bypass browser settings.[1]

The solution against IL's badware is either:

- Install uBO-Extra: <https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco>.
    - See: <https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful#instart-logic>

Or:

Use Firefox, which IL is leaving alone so far.

I can't emphasize enough: sites using IL's tech are inherently hostile to users.

***

[1] Click the (i) icon in the address bar while on `http://www.tomshardware.com`, notice the number of cookies reported: 94 on my side, despite that I have forbidden 3rd-party cookies through my browser settings/

**Comment by Hrxn** [comment]
> I can't emphasize enough: sites using IL's tech are inherently hostile to users.

> When you install uBO-Extra, you should immediately notice how the pages load faster (clear the cookies to be sure, IL tries to remember whether it is proxying or not): IL's code causes noticeable burden on your computer when pages from a site using it are loaded.

Yes, I can only confirm this.
For fun: Try opening such a site with a Chromium-based browser (and only uBO) on some older computer with weak hardware, and be amazed at how dramatic the slowdown really is.

**Comment by Fizbin99** [comment]
Ok, guys, thanks for helping me clear this up. I'm not ready to migrate to FF just yet but uBlock is working out well so far.
