### ISSUE TITLE
Add the CoinBlockerLists to uBlock Origin

### ISSUE THREAD

**Issue by ZeroDot1** [gorhill/uBlock#3600]
Hi, 
I am the author of the [CoinBlockerLists](https://github.com/ZeroDot1/CoinBlockerLists), and I would be very happy if you would add the list to your addon.
I created an extra list to fight and stop Browserminig.
URL: https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser_UBO.txt

Best regards @ZeroDot1

**Comment by BadPackets** [comment]
I second this request. @ZeroDot1 maintains the best blocklist to prevent cryptojacking in the browser. New malicious domains are frequently found and routinely added to the [CoinBlockerLists](https://github.com/ZeroDot1/CoinBlockerLists).

**Comment by uBlock-user** [comment]
Why are you blocking the entire domain such as `kisshentai.net` based on one javascript which can be individually blocked via uBO ?

**Comment by happysurf** [comment]
The web mining is very dangerous for the users and is an increasing practice today.
I suggest to create a new "Resource Abuse "or "Mining" section on 3rd-party filters tab, with CoinBlockerLists and NoCoin Filter List and maybe others.
These two list are very small, for that don't have impact on UBO performance.
I think must be active by default.
For example, the web site www.bigspeeds.com/service is not cured by the Ublock Origin Resource abuse list, but on the contrary, the CoinBlockerLists fix the mining problem.

**Comment by mapx-** [comment]
see easyprivacy (default list in uBo) list, mining section: bigspeeds is already there.

**Comment by okiehsch** [comment]
bigspeeds is also fixed in `uBlock-resource abuse` list, 
https://github.com/uBlockOrigin/uAssets/commit/32032f40acb3b186df2ba6e528d6f38a26b2cc3a#diff-04acddb39c958962e830b71881e4416b

**Comment by happysurf** [comment]
In any case in my opinion is necessary specific (and more efficient) lists for mining.
I don't use Easy Privacy because sometimes break some web sites.

**Comment by gorhill** [comment]
Observation:

Your list has 40 instances related to `coinhive.com`: the domain itself and 39 subdomains: `api.coinhive.com`, `js.coinhive.com`, `w13.coinhive.com`, etc.

`coinhive.com` is already blocked with uBO's default lists. The 39 subdomains are pointless in uBO, as uBO will block all subdomains of `coinhive.com` with a filter such as `||coinhive.com^` (which is what you hostnames in your list translate to) -- unlike how a OS would interpret a hosts file.

Please make the demonstration that your list actually add value, currently I feel like it would add little to what is already blocked by uBO if you take into account the redundancies from uBO's point of view.

**Comment by ZeroDot1** [comment]
@gorhill See: https://github.com/ZeroDot1/CoinBlockerLists/issues/127#issuecomment-373088641

**Comment by anewuser** [comment]
I believe it'd be a better idea for the community to work on a collective Web Workers whitelist instead of trying to keep up with the random domain names abusers buy every day. Here's a sample from my personal filters:
    
    $csp=worker-src 'none',domain=~facebook.com|~globo.com|~google.com|~mega.nz|~protonmail.com|~r7.com|~speedof.me

**Comment by KonoromiHimaries** [comment]
adblock has remove `CoinBlockerLists` and add `NoCoin` filter list
`https://blog.getadblock.com/adblock-for-firefox-3-9-0-f41a7e40c6c5`

i think, that's is better change <3

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/127#issuecomment-374262087

**Comment by zippy5** [comment]
@ZeroDot1, I would tend to agree with @flatfish12.  

Your list seems far from optimized for uBO.

If anything were to be added, it seems [NoCoin](https://github.com/hoshsadiq/adblock-nocoin-list) would be a better alternative.

**Comment by BadPackets** [comment]
![image](https://user-images.githubusercontent.com/32589462/37618966-229ed78c-2b75-11e8-82f7-70208ef3ace3.png)
![image](https://user-images.githubusercontent.com/32589462/37618972-28a8d2fe-2b75-11e8-9223-7d4af575e80a.png)

lol...

Regardless of what the troll accounts say, the [CoinBlockerLists](https://github.com/ZeroDot1/CoinBlockerLists), have always been and always will be the best list to stop cryptojacking. If it's not a good fit for uBO, per the requirements stated by @gorhill, that's understandable. For the average user, minerBlock is a better choice anyway.

**Comment by zippy5** [comment]
Instead of just calling users trolls, perhaps you should address those users concerns.  I can only speak for myself in saying I don't generally participate in these repositories.  I found a topic I cared about and wanted to voice an opinion, so I created an account.

As for your other comments, could you maybe addres why your list has "always been and always will be the best?"  From where I'm standing, it certainly doesn't appear that way (at least in the context of uBO).  That's a pretty bold statement to make if you don't have anything to back it up.

Based on @KonoromiHimaries's statement, I'm also curious why AdBlock would have dropped your list in favor of NoCoin if yours is superior?

I'm not suggesting you don't have a good list or that your work isn't appreciated.  I'm voicing an opinion that your list does not seem to be a good fit for this project, and I'm asking that you support your claims or fight for the belief that your list belongs in this project.

If that makes me a troll, so be it.

**Comment by gorhill** [comment]
I did create a quick script using Firefox scratchpad to remove redundancies from [the list](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser_UBO.txt), and this is what I got as a result: <https://gist.github.com/gorhill/1a4613677b2c36dd53a2a1fd26f16823> -- 567 hostnames.

I then imported the URL into uBO, which discards duplicates, and the number of network filters went from 76,237 to 76,776. This means the list contains 538 unique hostnames not found in uBO.

So these figures make the case that the list would benefit uBO users.

**Comment by zippy5** [comment]
Thanks for looking @gorhill! Is there any chance you could share the scratchpad script you used? (there are some other lists I wouldn't mind looking into further)

538 would definitely suggest some benefit, but I would be curious what those 538 hostnames are. 

As @uBlock-user mentioned in a previous comment, this list blocks entire sites as opposed to specific scripts.  Is that an approach you are ok with/think is the correct way to go?

I don't think the average user should have to (or necessarily even know how to) properly whitelist a domain.  Even after doing so, they would be no more protected from coin mining on that site then they would have been without the list to begin with.  In other words, is it a good idea to advocate for a list that is willing to say, "this site users a miner, you shouldn't access it at all?"

NoCoin seems like a fairly comprehensive list (now used as an AdBlock default), and at a quick glance, I don't see that it does this.

**Comment by gorhill** [comment]
> but I would be curious what those 538 hostnames are.

The link is in my comment.

The Gist for the quick-script: <https://gist.github.com/gorhill/b04bb22db1adcd21136b31b0fb6500d9>. It could be easily improve to deal with URL to hosts resource instead, and spit out a bit more stats about input/output counts.

**Comment by zippy5** [comment]
>The link is in my comment

My apologies, I thought that was the list with redundancies removed, I'll give it a look.  

And thanks for the script, really appreciate it!

**Comment by ZeroDot1** [comment]
@gorhill It is good to add a function to UBO that removes automatic duplicates.

**Comment by zippy5** [comment]
@ZeroDot1, if you don't mind the questions, what's the rationale for entirely blocking some sites?

**Comment by zippy5** [comment]
@ZeroDot1, here are two quick examples to consider:

`kickass.cd` and `thepiratebay.cr`, two popular websites.  The miners on these sites have already been taken care of by default lists (namely, uBlock filters – Resource abuse and EasyList).  

So sure, you have two unique hostnames here, but they provide no added benefit to the user.  Instead, they only create a need for users to workaround your list.

**Comment by ZeroDot1** [comment]
@gorhill Please check the list again, I just uploaded an update. 
https://github.com/ZeroDot1/CoinBlockerLists/commit/8442e1f5239fea1e1e2a54b3e56cf13a8e18b530

**Comment by ZeroDot1** [comment]
@gorhill The UBO list is ready for use with UBO, please check again if you can include the list in UBO.  
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser_UBO.txt

**Comment by zippy5** [comment]
@ZeroDot1, what made you decide to remove `thepiratebay.cr` and `kickass.cd` but leave in so many other domains for websites?

**Comment by gorhill** [comment]
There are still whole sites being blocked in there. I can't have uBO blocks whole sites just because there is a miner somewhere in it, the proper solution is to block the miner only -- most of the time uBO is equipped to do this. The consequence of blocking a whole site is that the user will disable uBO for the site, not something we want.

**Comment by gorhill** [comment]
I consider miners to be already well taken care in uBO with two default filter lists: _Resource abuse_, and _EasyPrivacy_.

**Comment by gorhill** [comment]
Instead of thumb-downs, provide cases which demonstrates that default filter lists of uBO are not sufficient. I can't have uBO's stock filter lists become a repository of all filter lists out there.

The following lists are selected by default -- if you [really care to inform people accurately](https://twitter.com/bad_packets/status/987421371440361472), you should point out that uBO is already blocking miners by default, the only open question is whether CoinBlockerLists add to this:
- [uBlock filters -- Resource abuse](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt)
- [EasyPrivacy](https://github.com/easylist/easylist/blob/9eca6ed32f7e44c50c30251cd1411d7566c6e2c9/easyprivacy/easyprivacy_trackingservers.txt#L2313)
