### ISSUE TITLE
Switchboard sometimes missing

### ISSUE THREAD

**Issue by lnicola** [gorhill/uBlock#3620]
### Describe the issue
Switchboard sometimes goes missing when advanced mode is enabled. This only occurs rarely. I used to disable and re-enable uBlock and this fixed it, but last time it didn't work. I had to disable and then enable the advanced mode.

No screenshot, sorry, but it looks exactly like with the advanced mode disabled.

### Your settings

- OS/version: Linux
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.15.16

**Comment by gwarser** [comment]
This part of interface is foldable - click on "requests blocked" or "domains connected"

**Comment by lnicola** [comment]
Thanks. I would never have guessed that.

There's still a small issue: the panel is rendered on the wrong side for a short while, but whatever.

**Comment by gorhill** [comment]
> guessed

https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel

It's because if such invalid issues I am giving up on the issue tracker -- I will care only about the issue where the case is made and effort made to investigate, I will let pile up all the rest.

**Comment by lnicola** [comment]
I didn't mean to offend you by opening this issue. I don't recall clicking on those, and they don't really look like links either -- although now I see that the cursor changes on hover. At some point I must have read the wiki page to figure out how to use the switchboard, but it's not really obvious that it can be hidden. It's more of an UX thing.

If you'll allow me to make a suggestion, perhaps a tooltip text like "Click to toggle the overview panel" would be useful here. It's not ideal since you still need to hover to read it, but I don't know a good way to show that the label works like a toggle button.

**Comment by gorhill** [comment]
> If you'll allow me to make a suggestion, perhaps a tooltip text like "Click to toggle the overview panel" would be useful here.

I disagree. Default installation of uBO assume mainstream users who have no interest in  detailed technical information such as base domain/hostnames of all remote servers. Hence why I prefer to keep it subtle with only a pointer cursor -- and in any case, it's in the quick-guides documentation.

Ultimately, whatever is thrown at the UI/doc/contributing guidelines won't make a difference (just look at all the issues opened since I gave up the issue tracker) -- the real solution would be a support desk managed by volunteers to keep an issue tracker dedicated to only actual issues -- but there is no such thing in here. Hence I had to give up caring about keeping a clean issue tracker -- this immediately improved things for me.

**Comment by lnicola** [comment]
> I disagree. Default installation of uBO assume mainstream users who have no interest in detailed technical information such as base domain/hostnames of all remote servers.

All right. I just opened a PR for that, but I'll close it. It could still be useful when the advanced mode is enabled, but I don't feel that strongly about it.

> I had to give up caring about keeping a clean issue tracker

I took a look, and uBlock seems to attract more weird issues/PRs than other projects. Sorry for contributing even more to the noise.

**Comment by gorhill** [comment]
Note that I am not really blaming you -- I "blame" the lack of "support desk"-like functionality in GitHub -- I put "blame" in quotes because all of this is free, so I am not complaining, just observing that there is a missing key component for such a popular project.
