### ISSUE TITLE
My filters and Dynamic filtering with globally blocked but locally unblocked scripting

### ISSUE THREAD

**Issue by Jaaap** [gorhill/uBlock#3621]
### Describe the issue
I have a "My filters" rule which works unless i use Dynamic filtering with globally blocked and locally unblocked scripts (inline, 1st & 3rd party)

### One or more specific URLs where the issue occurs
https://www.youtube.com/watch?v=qN-yLTDkAS4
trying to block this script:
https://www.youtube.com/yts/jsbin/player-vflHDhBq1/en_US/endscreen.js

### Your settings
* Dynamic filtering:
    * Globally Blocked:
        * Inline scripts
        * 1st-party scripts
        * 3rd-party scripts
    * Locally Allowed (for www.youtube.com):
        * Inline scripts
        * 1st-party scripts
        * 3rd-party scripts
* My Filters:
    * ||youtube.com/yts/jsbin/*/endscreen.js$important

- OS/version: MacOS 10.13.3
- Browser/version: Firefox Developer Edition 60.0b4
- uBlock Origin version: v1.15.16

##### Your filter lists
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
​​​​​​uBlock filters – Privacy
​​uBlock filters – Resource abuse​​​​​
​​uBlock filters – Unbreak​​​​​
EasyList
EasyPrivacy​​​​​
Malware Domain List​​​​​
​Malware domains
​​Adguard’s Annoyance List​​​​​
​​Fanboy’s Annoyance List​
​​​​Fanboy’s Anti-Thirdparty Social
​​​​Fanboy’s Social Blocking List​
Peter Lowe’s Ad and tracking server list

##### Your custom filters (if any)
||ytimg.com/yts/jsbin/\*/watch_autoplayrenderer.js$script,important
||youtube.com/yts/jsbin/\*/watch_autoplayrenderer.js$script,important
||www.youtube.com/yts/jsbin/\*/endscreen.js$important

**Comment by Blutgang** [comment]
> Locally Allowed (for `www.youtube.com`): 

Are you using `allow` instead of `noop`? I recommend to use `noop` instead of `allow`. 

From the [wiki](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide):
> **Important: Typically, use only narrow allow dynamic filtering rules to un-break sites. As these allow rules override any static filtering, this means if you use a too broad allow dynamic filtering rule you could start to allow in ads/trackers/annoyances.

`Allow` rules ignore the filters in the filter lists and the custom filters you've created for `youtube.com` The `1st-party scripts` & `3rd-party scripts` `allow` rule in this case will override your custom filters and allow ad/tracking...scripts (such as `doubleclick.net`) on `youtube.com`

From the [wiki](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide)
>Important: Remember that noop rules bypass only broader dynamic filtering rules, static filtering is left completely intact, which means you won't see ads in the embedded YouTube videos.

`noop` rules will not ignore the custom filters you have created.

**Comment by Jaaap** [comment]
@Blutgang you are amazing!
It works.
I never understood that middle grey column but this is amazing.
Thank you.
