### ISSUE TITLE
Adblock detection at browserleaks

### ISSUE THREAD

**Issue by Daisenki** [gorhill/uBlock#3626]
On https://browserleaks.com/proxy it always detect uBlock on my Firefox, I did use Nano Defender a long time and that can hide the detection, but I want to drop the addon, that's why I ask now: Did I do something wrong or is hiding the uBlock not possible?

![abd](https://user-images.githubusercontent.com/22057956/37568338-1fd3ad1c-2ad4-11e8-9a32-efae5af99b62.JPG)

**Comment by mapx-** [comment]
just add
`browserleaks.com##script:inject(abort-on-property-write.js, proxy_ab)`

**Comment by Daisenki** [comment]
Okay, this works now for one site, how can I make a filter to make it work on every site? The uBlock should hide on every site.

**Comment by mapx-** [comment]
There is no adblocker / defender which can take care of all the sites in this world. It's all about filters or (in special cases) about bultin implementations to fix trick classes

**Comment by Daisenki** [comment]
So it's "normal" that uBlock get's detected and not a leak or wrong setting on my side?

**Comment by mapx-** [comment]
Exactly.

**Comment by uBlock-user** [comment]
It's not detecting uBO, it's rather detecting Filterlists's filters, you would get the same result with any other content blocker that relies on Filterlists. Also there's no one filter for every website, you can fix them on case by case basis.

**Comment by uBlock-user** [comment]
Blocking `proxy_ab.js` takes care of the filter detection.

**Comment by Daisenki** [comment]
Thank you, not sure if it does anything for privacy, but the filter lists are not detected anymore. Why does uBlock not block proxy_ab.js as default? Isn't that a leak at the addon?

**Comment by okiehsch** [comment]
So after I block `proxy_ab.js` what have I achieved?
I do not "leak" anything, the site assumes that I use an adblocker based on **blocked** network requests.
The users of `https://browserleaks.com/proxy` can say: "Hey, I use an adblocker that `browserleaks` can't detect", which is basically meaningless, because any site can use the same script, rename it and then assume that the user has an ablocker installed.

I find the whole premise of such a test deeply flawed.

**Comment by uBlock-user** [comment]
> Why does uBlock not block proxy_ab.js as default? 

Because it's javascript used by the aformentioned website only and it's more of a POC, than a use-case. 

> Isn't that a leak at the addon?

How is that a "leak" ? Extensions/addons CANNOT be detected by an EXTERNAL javascript, unless there's an exploit existing in the browser which is NOT the case here. The javascript is doing guesswork based on the logic whether a preset amount of network requests being blocked or not, anybody can do that.

**Comment by Daisenki** [comment]
Thanks guys!
