### ISSUE TITLE
How do I get Ublock extension to update in Chrome?

### ISSUE THREAD

**Issue by thinkpad4** [gorhill/uBlock#3628]
### Describe the issue
@gorhill I'm using version 1.15.2 and I see on the store that the version is 1.15.18 but chrome hasn't updated it yet.  I've checked developer mode and clicked update extensions, still nothing.  Short of backing up my settings and removing and reinstalling it what other options are there? 

### Your settings

- OS/version: 
- Browser/version: 
- uBlock Origin version:

**Comment by Hrxn** [comment]
Well, based on past experiences, it will update automatically, sooner or later..

**Comment by thatsprettygood** [comment]
https://github.com/gorhill/uBlock/releases

**Comment by okiehsch** [comment]
gorhill uses a staged rollout, right now I have one computer with 1.15.2 one with 1.15.12  and one with 1.15.18.
If you have no issues with your current version you can wait, it will update eventually.

**Comment by thinkpad4** [comment]
And they are updated though the google store for you @okiehsch ?

**Comment by okiehsch** [comment]
The 1.15.18 I manually updated via developer mode and clicking "update etension".
Right now the one with 1.15.12 does not update even if I try to manually update, probably because, like I said gorhill uses a staged rollout, i.e 10% of the users, then after some time 30% etc.

**Comment by thinkpad4** [comment]
Thank you @okiehsch that is the answer I was looking for

**Comment by uBlock-user** [comment]
I used to have this issue with the stable builds, even after countless force updates it wouldn't update from the store, so I removed it and installed the dev build.

**Comment by gorhill** [comment]
> I used to have this issue

Sigh. This is not helping -- **there is no issue**: I publish when I have the time for, Chrome store review the extension when they have time for, I increase publishing ratio over time (I start at 5%) when I think it's the time for, etc. etc. I already said it in the past (and it's clearly stated in CONTRIBUTING) -- and yet the tracker is used again about this, and will undoubtedly be used again in the future.

**Comment by uBlock-user** [comment]
> there is no issue

There was, for me, as in the sense, Chrome Store used to show version 1.11.2(for example) and my mine was 1.10.0(for example), I forced update and nothing happened. I don't wanna spend my time just to force update an extension every day to get an updated version from the Store which should have update on its own as expected but it didn't, until I was fed up and thoroughly pissed off, so I removed the entire extension and took the dev build and then sometime later I realised you were  **increase publishing ratio over time**, which is unacceptable to me as I don't mind the bugs since I'm willing to report them as and when they occur, but having to wait for my region to get the update while the Store already had the updated version is something I can't accept.

**Comment by gorhill** [comment]
> I don't wanna spend my time just to force update an extension every day

- Stable release created on March 18, 8h28
    - "stable release created" =/= "uploaded to Chrome store"
- Issue opened on March 19, 3h42 -- **less than a day after**.
    - CONTRIBUTING:
      > Do **NOT** ask me to publish the latest version to AMO/Chrome store.

And this is why the issue tracker here is impossible to manage, at least for a single lonely dev, hence why I give up on managing it.

**Comment by uBlock-user** [comment]
> Issue opened on March 19, 3h42 -- less than a day after.

Where does it say that **I** opened the issue ? I'm relating my experience with stable builds which happened months ago, not today or yesterday. No need to take it out on me. I **NEVER** opened any issue for that here.

> hence why I give up on managing it.

Have you ? Because you keep saying it, but I don't feel you have yet.

**Comment by thinkpad4** [comment]
All I was asking was why my version that I installed from the chrome store hadn't updated to the latest listed version on the store, and @okiehsch informed me that @gorhill has the chrome store push the latest version in stages and I just have to be patient.  I'm gonna close this now

**Comment by Hrxn** [comment]
> Where does it say that I opened the issue ? I'm relating my experience with stable builds which happened months ago, not today or yesterday. No need to take it out on me. I NEVER opened any issue for that here.

I think no one here said that..

Please, don't needlessly attack each other.

Of course you're right about the upload to the Chrome Web Store, and that the new version already appeared on there, but that the forced update does not work as it may imply.

But as explained above, that is due to this staged roll-out behaviour of the CWS.
I don't like it either, but for any detailed reasoning someone at Google should explain this.
Google is not what I once used to be...

But that is not even the primary issue with CWS, they have other problems. Like malicious extensions, I think that was all over the news, not long ago..
