### ISSUE TITLE
Some privacy settings grayed out

### ISSUE THREAD

**Issue by tomasz-warniello** [gorhill/uBlock#3632]
### Describe the issue

From the privacy settings only "Block CSP reports" is not grayed out. Is this expected? How can I switch the grayed out options? (In particular "Prevent WebRTC from leaking local IP addresses".)

### Screenshot in which the issue can be seen

![screenshot from 2018-03-21 20-46-01](https://user-images.githubusercontent.com/12538058/37734058-598335f0-2d4a-11e8-9cf5-76bbc4e807d8.png)

### Your settings

- OS/version: 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
- Browser/version: Firefox 52.7.2 (64-bit)
- uBlock Origin version: 1.15.18

**Comment by OpenBSD-Neurotik** [comment]
Hello,

Content Security Protocol reporting is toggled off by default, this is intended, this is for advanced users only because you need to understand what CSP does as it can greatly help website developers and thus the internet ecology as a whole. However there are 2 sides to the coin of CSP. 

CSP allows websites to set 'trusted sources' mostly URLs to load Javascripts on their website, this is suppose to prevent cross site scripting attacks. A trusted ad opens up a script and then begins open mass ads, this is prevent by the CSP. 

Similar such an attack that was very common in the early 2000s was that when you went to your bank website while you had a specific other websites open these websites would load a false 'frame' ontop of your bank login site. You would thin you were logging into your bank account but in actually you were handing over your information to the XSS attacker who then logged into your bank account instead.

**Leaving the feature off by default is recommended for none advanced users.**

In 2015 over 90%~ of the top 1000 sites use the code 'unsafe-inline' this means those website owners are clueless and allow tertiary people to inject javascript within their CSP and use it to initiate a MITM/XSS attack. Thus CSP is largely ineffective against XSS due to cluelessness of website operators, however Banks in the overwhelming majority in part due to their mass fraud payments have listened and learned and have a correct OCSP.


More info:
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports
https://www.ghacks.net/2017/10/19/ublock-criticized-for-blocking-csp/






an also be used to fingerprint users their useragent. 




Browsers (useragents) do not allow CSP reporting to be toggled off in a easy way, there might be a specific configuration option for it in the manual configuration settings that i'm not aware of currently, however qBlock Origin allows the user to turn this browser feature off by blocking the OSCP requests so that CRL validation can not occur.

Most trackers and malicious sites do not adhere to the CSP curtsy and still collect useragent information in a method to finger print visitors. qMatrix allows users to spoof the refferer so that false data is collected.

**Comment by tomasz-warniello** [comment]
@OpenBSD-Neurotik Thanks for your reaction. I didn't ask my question well and have updated it. I'm more about why the other ones are grayed out and how can I unblock them?

**Comment by gwarser** [comment]
Because you use Firefox 52

**Comment by tomasz-warniello** [comment]
I thought this should be allowed, as per this wiki: https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

**Comment by gorhill** [comment]
> Leaving the feature off by default is recommended for none advanced users.

This is absolutely wrong and this needs correction: nowhere do I ever say this.

Again a case of confusion between "CSP" and "CSP _report_". uBO **never** relaxes sites' CSP if any. The setting concerns **only CSP reports**.

**Comment by Blutgang** [comment]
Seems similar to this issues #2806. 

[v1.14.4 release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.4):
> [The pushed out 1.14.0 on Firefox ESR isn't webext compatible](https://github.com/gorhill/uBlock/issues/2944)
> - As per popular demand, I set the minimum version to 52.0. However be warned that some features are not available, like the privacy settings for example.

Is that Firefox ESR (legacy)? If so, please use the legacy version ([v1.13.8](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=1#version-1.13.8)) and disable the auto-update for uBO.
