### ISSUE TITLE
Ublock doesn't update Malware Domain List properly.

### ISSUE THREAD

**Issue by Dinervity** [gorhill/uBlock#3672]
### Describe the issue

I try to update list but it allways stuck at the Malware Domain List section it says "A network error prevented the resource being updated". I push again update button and then MDL updates normaly. Everything else works nice.

### One or more specific URLs where the issue occurs

No

### Screenshot in which the issue can be seen

![mdl list](https://user-images.githubusercontent.com/31162876/38302356-fe3c1862-380a-11e8-9914-c51636f1dd65.png)

### Steps for anyone to reproduce the issue

No

### Your settings

- OS/version: Windows 10 Pro, build 1709
- Browser/version: Firefox Quantum 59.0.2 FIN
- uBlock Origin version: uBlock Origin 1.15.24

##### Your filter lists

FIN: Finnish Addition to Easylist

##### Your custom filters (if any)

opensubtitles.org##script:inject(abort-current-inline-script.js, atob)

**Comment by akks1981** [comment]
I can confirm that

**Comment by WowDude** [comment]
Could you guys open the uBO logger, select "All", and then go back to 3rd-partry pane and try to update the filter lists again, and then go back to the logger and see what the logger says? (errors? blocked requests?).

**Comment by akks1981** [comment]
I do not know why but now it works for me

![filter](https://user-images.githubusercontent.com/12896716/38303595-c34ee7d8-3806-11e8-892c-e6dd29b1e3a3.png)

**Comment by Dinervity** [comment]
How do i get uBo logger?

**Comment by akks1981** [comment]
![logger](https://user-images.githubusercontent.com/12896716/38303930-de56be9c-3807-11e8-9200-30410d88b85b.png)

**Comment by Dinervity** [comment]
![all](https://user-images.githubusercontent.com/31162876/38304175-29018c7a-3811-11e8-8b90-14ed40592cc4.png)

**Comment by gorhill** [comment]
This has been said again and again: uBO is not responsible for a remote server not responding.

**Comment by Dinervity** [comment]
![no it says this](https://user-images.githubusercontent.com/31162876/38305435-852fa992-3815-11e8-9894-5f7bacd4e660.png)

**Comment by Dinervity** [comment]
![error](https://user-images.githubusercontent.com/31162876/38305799-de1605b4-3816-11e8-8b53-69c3e40e7de2.png)

Error

**Comment by uBlock-user** [comment]
MDL's server is terrible, nothing to do with uBlock.

**Comment by Dinervity** [comment]
Okay. So it will always like this?

**Comment by uBlock-user** [comment]
Yes, untill the server admin fixes whatever the cause is behind this situation.

**Comment by Dinervity** [comment]
Thx man.

**Comment by WowDude** [comment]
Well, I've been asking for screenshoots of the uBO logger just because I was experiencing similiar issue 3 days ago, and it was caused by some old/wrong uBO settings at my side in My Rules/Whitelist tab, the logger was showing red blocked requests to some of the filter lists updating, because some filterlists contains filter matching the update url:

This list couldn't update: `https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt`
because:

 [Adversity](https://raw.githubusercontent.com/Hubird-au/Adversity/master/Adversity.txt) contains a filter: `_tracking.` which was mathcing the update url and blocking updating

[Block all well known privacy trackers​](http://gnuzilla.gnu.org/filters/blacklist.txt) contains `||s3.amazonaws.com^$third-party` which was matching the update url and blocking updating

And several more disconnect lists also couldn't update.

The issue that was causing the matching filters to be applied to behind-the-scope update requests was caused by some old weird entries from old backup of uBO in My Rules/ Whitelist Tab like:
`2cb7269e-089a-494c-bb7a-3a5602b2eba5.moz-extension-scheme`. After I removed it the lists begun updating properly.

**Comment by Dinervity** [comment]
Thats good to read. I hope that, this issue is still reparable.

**Comment by WowDude** [comment]
@Dinervity 

Don't get me wrong, I said I had a similiar issue (visually), but it was caused by some old bad weird uBO settings in My Rules / Whitelist panes at my side, while your and @akks1981 's issue was most probably caused by MDL's servers simply not responding, especially that you most probably don't even use neither `Adversity` nor `Block all well known privacy trackers​`.

**Comment by Dinervity** [comment]
Roger that.

**Comment by WowDude** [comment]
Some of my old uBO backup part, perhaps the bolded parts were causing the filter lists not updating.

"hiddenSettings": {
    "streamScriptInjectFilters": true,
  },
 "netWhitelist": 
**"30.wyciwyg-scheme\n
429ac668-7aca-4ac8-9be5-c5162dde131c.moz-extension-scheme\n
behind-the-scene\n
c1a9b183-b26f-48d8-8a21-1d6dd416419c.moz-extension-scheme\n
chrome-extension-scheme\nloopconversation.about-scheme\n**
opera-scheme\n
vivaldi-scheme",
  "dynamicFilteringString": 
**"behind-the-scene * 3p-frame noop\n
behind-the-scene * 3p noop",**
  "urlFilteringString": "",
  "hostnameSwitchesString": "",

**Comment by Dinervity** [comment]
Mayby.

**Comment by Dinervity** [comment]
I did notice somethind. Now ublock it act unstable and i did have to press tre times update button. And in four one it got through. I did take picture. 

![i did notice something](https://user-images.githubusercontent.com/31162876/38335177-275a7f30-3866-11e8-8503-b90407e7804e.png)

Im not sure if this helps anything, but still server did respont properly.

**Comment by gorhill** [comment]
@WowDude Probably same issue as the one reported at #3654 -- fixed in [1.15.22](https://github.com/gorhill/uBlock/releases/tag/1.15.22)

**Comment by WowDude** [comment]
@gorhill 

I've downgraded to 1.15.20 just to reproduce the issue and I've succeeded:

<details>
  <summary>Screenshoot 1:</summary>

![3rd-party-pane2](https://user-images.githubusercontent.com/37474031/38364393-ba9fbdba-38d8-11e8-8cd4-11d6cf58ac86.png)

</details>
.
<details>
  <summary>Screenshoot 2:</summary>

![logger](https://user-images.githubusercontent.com/37474031/38364362-a0595308-38d8-11e8-8b3a-2b9b5b044a77.png)

</details>
.  

[My uBO config backup as minimum as possible to reproduce the issue](https://gist.githubusercontent.com/WowDude/8effb67974ff94770e78c2fb0f6962cd/raw/a7bcd846b7962defc04e45b60462e2a69f8f6ada/uBO%25201.15.20%2520update%2520fails%2520%25233672.txt)

STR: 
1. Load the backup into uBO 1.15.20 
2. Launch the logger 
3. Get back to uBO 3rd-party pane
4. Hit Update button
5. Switch to the logger and notice the blocked requests.

Just a small correction as per [my previous comment](https://github.com/gorhill/uBlock/issues/3672#issuecomment-378579472): - it was not:
 `Adversity` + `Block all well known privacy trackers` but 
`Blockzilla` + `Block all well known privacy trackers`
matching the update urls of malware domains filterlists.

**Comment by Dinervity** [comment]
![i only got these messages](https://user-images.githubusercontent.com/31162876/38382913-cd369fda-3913-11e8-89e3-088e50fc3aeb.png)

I did have these kind of red messages

**Comment by Dinervity** [comment]
![i only got these messages 2](https://user-images.githubusercontent.com/31162876/38383323-e9a7ba04-3914-11e8-80ef-36bd73a390f2.png)

This from oyher website

**Comment by WowDude** [comment]
@Dinervity 

Your red messages are ok, they are related to ad blocking, and not to filter lists updating.

**Comment by Dinervity** [comment]
Ok thanks again =D.
