### ISSUE TITLE
Information icon for: "Regions, languages"

### ISSUE THREAD

**Issue by stanlane** [gorhill/uBlock#3674]
### Describe the issue
uBO enables the region/language-filter that corresponds to the locale of your web browser. Can you please add a "i" icon with a link to a web page that describes this?

### Screenshot in which the issue can be seen
Demonstration:

![image3047](https://user-images.githubusercontent.com/25944158/38304510-0bda60a6-380a-11e8-8c1e-6bb569f299e1.png)

**Comment by gorhill** [comment]
> a link to a web page that describes this?

What do you think needs to be described and why?

You need to be more specific than a generic "describes this". Closing as invalid due to lack of details about what _exactly_ is suggested. So far I have never come across somebody wondering about this. If you still feel strongly about this, open an issue at the new issue tracker and you think something needs to be described, provide the full text of the description you think is needed.
