### ISSUE TITLE
uBlock Origin translation

### ISSUE THREAD

**Issue by FTno** [gorhill/uBlock#3708]
### Describe the issue
In the My rules tab there is a button with the tooltip 'Toggle locked scrolling'.
I could not find this string at Crowdin Project Localization.

In new rc version a heading for uBlocks own internal filter lists are added with the heading 'Local'.
Wouldn't naming the header 'Internal' be a bit more precise, I have my own local lists too in the Custom section.

- OS/version:  Windows 7
- Browser/version: Chrome 65, Palemoon 27.8
- uBlock Origin version: 1.15.24 (and just tested 1.15.25rc1 in Palemoon)

**Comment by gorhill** [comment]
The "Toggle locked scrolling" is from CodeMirror's code, I would have to find out if and how easy it would be to localize by uBO.

I struggled with picking "Local", I couldn't find any better. The idea is more like "Homegrown" filter lists -- as in "these lists are maintained by uBO", and I ended up using "Local" because that's what seemed least worst in synonyms dictionary.

**Comment by gorhill** [comment]
All suggestions are welcome.

**Comment by overdodactyl** [comment]
Personally, I like uAssets (not a new idea, but wanted to isolate my "thumbs up" from joey04's other suggestion).

**Comment by overdodactyl** [comment]
>I rather not create new ones

You could consider moving the other filters to their corresponding spots, then changing "Local" to "Other."

This would keep the same number of sections, but also leave room for any future filters that don't fit well into a category.  For example, I know there have been several issues/pulls regarding adding more anti-mining/coin filters.  If that were to ever happen, they could be placed under "other" and fit naturally in with *Resource abuse*.

**Comment by okiehsch** [comment]
> I know there have been several issues/pulls regarding adding more anti-mining/coin filters


`EasyPrivacy` actually pulls a large portion of it's anti mining filters form those dedicated anti-mining lists.
With both `EasyPrivacy` and `uBO-resource` abuse enabled by default those lists are really rather redundant for uBO users, in my opinion.
The problem is that nobody knows that `EasyPrivacy` also includes a dedicated anti-mining section and so they keep asking for such a dedicated list.

**Comment by okiehsch** [comment]
I did not mean to imply that you did, my reply was meant to answer the question why so many issues are opened concerning the addition of more mining lists and why I think they are really not neccessary.

**Comment by gorhill** [comment]
So far "uAssets" seems to be the favorite. However I worry that it's not translatable: for example, how will "uAssets" be meaningful to a Chinese person not able to parse Latin alphabet or read English?

**Comment by gorhill** [comment]
In the end I went with "Built-in", as suggested by @vlaszlo in [this comment](https://github.com/uBlockOrigin/uBlock-issues/issues/2#issuecomment-382171036), it's the most accurate labeling really.
