### ISSUE TITLE
Please clarify uBlock₀ vs. uBlock

### ISSUE THREAD

**Issue by rusvnc** [gorhill/uBlock#38]
This is confusing. Are you recommending users with the present extension (i.e. uBlock₀) should now install uBlock from the new repository? If so this should be stated clearly somewhere.

**Comment by SW1FT** [comment]
There's nothing to clarify here. If you like Gorhill's version stick with it, if not, go for Chris Aljoudi's.

**Comment by rusvnc** [comment]
I beg to differ. For one thing, if this is going to be actively maintained, it is unclear why gorhill transferred the official repository to chrisaljoudi, rather than chrisaljoudi starting a fork of the extension.  Given that gorhill has previously deprecated extensions in favour of new extensions, some explanation would be useful.

**Comment by gorhill** [comment]
Dup of #12.

**Comment by Betsy25** [comment]
@rusvnc There are only simple rules about this :

* Always backup up your settings before switching between the forks.
* Never run both forks simultaneously.
* You have to total freedom to choose whichever fork you like.

**Comment by gorhill** [comment]
> unclear why gorhill transferred the official repository to chrisaljoudi

These projects are hobby to me, not full time job. It stopped being a hobby when it felt more and more like a tedious job. I will keep maintaining my version (and share with whoever care to use it) because it guarantees the tool will match what I want out of it.

**Comment by alain1978** [comment]
Hello, I understand but why gave up uBlock one day and less tehan one week later, came back to make a fork ? Why don't work with the "official" uBlock" team (it seems they need some help) ? Your last release works very well, congratulations and sorry for my bad english, I'm French.

Alain

Date: Sat, 11 Apr 2015 09:02:54 -0700

**Comment by justinshepard** [comment]
@ghost: By handing over the official repository, he ensures that the "official uBlock" is maintained by a team that is willing/able to handle the "tedious job" aspects of having a popular, useful addon. gorhill maintaining his own fork allows him to actually enjoy working on uBlock without getting burned out and discouraged. It also means he is free to innovate without breaking things or pissing off a bunch of people that may not like a particular feature. This is a win/win/win for all parties involved.

**Comment by dolohow** [comment]
@gorhill If I were you I would just ignore all the created issues and pull requests or even disable the ability of creating the new ones. If someone wants to change the direction of the project then there is always a possibility of creating a new fork as GPLv3 allowing to do that.

**Comment by gorhill** [comment]
@dolohow The project would suffer if people can not file bug reports, uBlock wouldn't be what it is now without the bug reports.

For the feature requests, I have no problem closing them if I want to, at least now it is spelled out [in here](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), so I can use this as reference without further comment if I want to. I keep some feature requests open though because many of them are things I thought about in the past, so I may or may not decide to do something about them.

**Comment by PeteSebeck** [comment]
Enjoy your hobby and enjoy life. Its way to short. Just wanted to stop by and say thank you for this great project and taking the initiative. My browsing experience is better for it :) I'll use the new fork of your product and keep track of your work for future innovations.

**Comment by ticoombs** [comment]
have a coffee for your hard work on me @gorhill @changetip

**Comment by changetip** [comment]
Hi @gorhill, @ticoombs sent you a Bitcoin tip worth a coffee (6,642 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/730000)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by EamonNerbonne** [comment]
By releasing ublock-origin so soon (and naming it so prominently to be the "original" version), you're stealing some of your own transition's thunder. There's a risk users will install your more trusted version, and that the new owner will lose motivation. Good luck with future development, in any case!

**Comment by gorhill** [comment]
@EamonNerbonne 

Main reason I published on AMO is because a feature which I think is important was removed from uBlock (per-site switches). That both versions diverged significantly enough so soon is not in my control.

When ABP added "acceptable ads" in their fork, they also created a demand for a version uncompromised by the "acceptable ads" principle, hence ABE happened. When uBlock removed the 
per-site switches, a demand was created for a version of uBlock with the per-site switches.

This is the reality of GPL: anybody can fork and create their own flavor if they disagree with the pre-fork version. This should not be seen as wrong when it happens, it's expected. In the big picture, users win.

As far as trust is concerned, both versions can be trusted -- that should not be an issue in either case: the development and source code is public in both cases (every single code change can be easily browsed on github).

**Comment by chrcoluk** [comment]
This i feel needs more publicity, my head is a in a twist wondering whats going no and which ublock to use.

Basically if I understand you rightm, ublock got too big, and you got sick of all the support requests, so you forked it off, knowing that ublock will get the vast majority of users and hence the vasy majority of support requests whilst your own fork is a much smaller userbase and hence less pressure.

The issue I have is there really needs to be some kind of page highlighting the differences in features, such as this change of per site switches feature.

**Comment by Gitoffthelawn** [comment]
@chrcoluk wrote: "The issue I have is there really needs to be some kind of page highlighting the differences in features, such as this change of per site switches feature."

+1000
I don't have enough knowledge about the differences to do it myself, but if someone puts together a rough draft, I'm willing to edit it and polish it up.  If the developers support the idea, I'm also willing to ask the right questions to make the differences clear to the average user.  I will also work to ensure it is unbiased and written in a friendly way.  I have no agenda, bias, ego involvement, or financial interest.  Like most people, I just want the tool that best suits my needs.

**Comment by chrcoluk** [comment]
For what its worth I am now on ublock origin, I suspect this will become the better version over time.  Although I hope this version gets the network log firefox ui enhancement the other version has.

On the other version there is also no mention of per site switches been removed in any changelogs, however it does look like they were "silently" removed, which to me isnt good behaviour from a developer, as the other ublock is still on my laptop and I see the 3 buttons underneath "domains connected" are missing.    I will move my laptop over to this version as well soon, I only kept it on there for now to compare the two.

**Comment by gwarser** [comment]
https://en.wikipedia.org/wiki/Ublock#uBlock_Origin

**Comment by chrcoluk** [comment]
ahh ok so the per site switcher was added specifically in this version, thanks.

**Comment by Gitoffthelawn** [comment]
@gorhill wrote: "Main reason I published on AMO is because a feature which I think is important was removed from uBlock (per-site switches)."

Can you provide some detail as to where this feature is located and what function it serves?  Chrcoluk mentioned the three buttons at the bottom of the uBlock popup.  Is that what the functionality to which you are referring?  Did regular uBlock remove the ability to control popups, strict filtering, and cosmetic filtering on a per-site basis?  If so, why?

**Comment by Snapy** [comment]
Yes, the three buttons at the buttom are the per site switches.
Yes, regular uBlock removed them but you can still block popups through filter syntax ($popup) and disabling cosmetic filtering _should_ (not sure) be possible through dynamic filtering ([wiki page] (/gorhill/uBlock/wiki/Dynamic-filtering:-disabling-cosmetic-filtering-for-the-current-site)). Whereas strict filtering (actually strict blocking) is not available [for now] (/chrisaljoudi/uBlock/issues/1431#issuecomment-108622694) (well, only in the 0.9.3.0 release which is the same for both project).

**Comment by SRGOM** [comment]
People, stop acting entitled. Gorhill is charging you exactly 0.00$
