### ISSUE TITLE
[SeaMonkey] uBlock duplicate icon on Context menu 

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#381]
This is a weird error, but I decided to report it anyway.
It can be re-produced as follows:
1. Open the browser with only a blank tab
2. Install uBlock (from scratch, I also removed the ublock0.sqlite from profile's extension-data)
3. Look at the context menu:
   There's no icon.
4. Close the browser
5. Open the browser (with no page, only an empty tab)
6. Look at the context menu:
   There's an icon.
7. Open some url (http://www.seamonkey-project.org/)
8. Look at the context menu:
   There are 2 icons.

uBlock 0.9.9.2
SeaMonkey version 2.33.1
windows 7 x64

Following are errors I got on the Javascript console.
I also got numerous warnings but I will only post them if you need them.

After step 5 I get the following error:
Sat Jun 20 2015 09:53:28
Error: TypeError: getTabBrowser(...) is null
Source file: chrome://ublock0/content/js/vapi-background.js
Line: 901

---

After step 7 I get the following error:
Sat Jun 20 2015 09:53:28
Error: TypeError: vAPI.lastError is not a function
Source file: chrome://ublock0/content/js/assets.js
Line: 130

---

**Comment by MiKiL75** [comment]
This probably is the same bug that appeared in chrisaljoudi's version during coding legacy toolbar button and it was fixed in https://github.com/chrisaljoudi/uBlock/commit/ed6064912e0740a775a4fa9ab765565f1f8afde7
Probably some Seamonkey-specific as mentioned at https://github.com/chrisaljoudi/uBlock/issues/1315#issuecomment-96264019

**Comment by gorhill** [comment]
Fixed with 1d85c16f82dbcc106110898254a6c10de2df66a5.
