### ISSUE TITLE
request: Temporarily disable for all sites

### ISSUE THREAD

**Issue by HenningJW** [gorhill/uBlock#384]
A pause block completely would be really nice for cashback sites. Right now I have to disable either the plugin in the browser settings or open the page of the cashback company, disable it for the page, click on the link to the shop, disable it on the shop page and click the link on the cashback page again. A full disable for the duration of the purchase would be less error prone and more comfortable with such a function.

This is a duplicate of the locked issue #301 were no one was able to give you the requested concrete scenario.

I am sorry for submitting a feature request, but it seems to me as the feature request spawned discussion with your participation that feature request are at least somewhat tolerated, contrary to the guidelines.

Thank you for considering the feature.

**Comment by gorhill** [comment]
> for cashback sites

This was requested before. Same answer, just disable the extension in the browser.

The other uBlock [plans to have this feature](https://github.com/chrisaljoudi/uBlock/issues/1432#issuecomment-109312713).

personally it's not something I plan to ever include -- it's just replicating a browser feature.

I will lock this issue, because people tend to want to argue endlessly about it, while I think at this point it's clear it's [pointless](https://github.com/chrisaljoudi/uBlock/issues/40).
