### ISSUE TITLE
Question: Why The Name Change?

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#39]
Hi gorhill,

Sorry if this is mentioned somewhere, I didn't notice.

So why the change in name to uBlocko?

thank you

**Comment by Unrepentant-Atheist** [comment]
Reading is hard....

>Because now this version is a fork of the previous repo, I needed to also change name for installation >purpose, which means that with this release, uBlock₀ will no longer fetch settings from former uBlock, >so it will install as if it was the first time.

**Comment by meuwe** [comment]
Reading is hard, LOL...

I saw the ```releases``` section but I don't see it come out and say WHY the name change.

Just because something is a fork of a previous repo, what does that have to do with anything?

Isn't this still the same developers, who also maintained the previous repo too?

Hmm

**Comment by Havokdan** [comment]
Hey, how projects had the same name, shared the same settings, because the folder where they were ended up being the same, with the division in the project, with time, there is the possibility of a project to have something that the other does not, eventually trigger incompatibilities, and another for the extensions have many name shop at the chrome browser, opera, firefox and others.

**Comment by jarodsteele** [comment]
I also like to know what about the add-on AMO (https://addons.mozilla.org/en-US/firefox/addon/ublock/).
Will it be updated by the new maintainer? I don't want to manually install new versions, I want to "set and forget" it... (using the Firefox auto updating mechanism).
Thanks.

**Comment by gorhill** [comment]
> Will it be updated by the new maintainer?

Yes.

**Comment by jarodsteele** [comment]
ok, thank you for clarification (also for creating ublock!)

**Comment by meuwe** [comment]
I'm lost, there is a new maintainer, gorhill I thought this was your project?
