### ISSUE TITLE
Additional privacy filters

### ISSUE THREAD

**Issue by metaphoricgiraffe** [gorhill/uBlock#414]
I have a privacy-related filter list for use with uBlock at https://github.com/metaphoricgiraffe/tracking-filters

The filter list expands on the coverage available from EasyPrivacy and other filter lists and blocks additional trackers on popular websites like Github, Tumblr, Yahoo! Answers, Pinterest, Imgur and BuzzFeed.

I'm wondering if you would like to include any of the filters in your list, or make it available as an optional list.

Note: I tried submitting some of the trackers to EasyList last week but I haven't received any replies and I would like to plug in the gaps in EasyPrivacy, particularly those trackers present on popular sites.

**Comment by SMed79** [comment]
Hi, 
Try to bump your topics on easylist forum https://forums.lanik.us/viewtopic.php?f=9&t=20843

**Comment by gorhill** [comment]
> I haven't received any replies

It's probably because of the same reason I don't feel importing all of this myself into `privacy.txt` without first testing each one of them to find out if they break stuff.

Why not just keep building your list, and the more people use it the more it will be put to test.

I will have to take the time to complete that [wiki page](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web) for all those filter lists which people can install at the click of a mouse, I just need to implement the new _subscribe_ mechanism which I think is or soon will be in ABP, which will use a normal `http://` URL instead of `abp:`

**Comment by gorhill** [comment]
I added you list in there (edit as you see fit): https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

With version 0.9.9.3-dev.2, it is possible to click on any list in there to auto-subscribe.

**Comment by metaphoricgiraffe** [comment]
@gorhill  Ok, thanks, I'll keep updating the list then.
