### ISSUE TITLE
[Question] Does Ublock Origin have Cosmetic filtering from Web Inspector mode?

### ISSUE THREAD

**Issue by Corruptinglyneedful** [gorhill/uBlock#422]
This enables the user to block elements they don't want to see on a more direct level and it's highly useful.

I'm wondering if Ublock Origin has it.

**Comment by SARG04** [comment]
Do NOT: Submit feature requests. https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

>I'm wondering if Ublock Origin has it.

https://github.com/gorhill/uBlock/issues/420#issuecomment-116766855

**Comment by Corruptinglyneedful** [comment]
This is not a feature request, it is a question.

  I was also told on Reddit by gorhil himself, that I post it here.

**Comment by gorhill** [comment]
Ability to create cosmetic filter from the DOM will be in next release, not specifically tied to the Inspector, so as to allow the feature to be available on all platforms.

**Comment by Corruptinglyneedful** [comment]
What is the DOM?  Can you explain that for me?  How will that work?

**Comment by gorhill** [comment]
There are resources out there for this.

**Comment by Corruptinglyneedful** [comment]
I am not a developer or a coder.  I do not understand what this stuff means.

Explain it, in a way that I can understand please.

**Comment by gorhill** [comment]
> Explain it, in a way that I can understand please

I am not a teacher.

**Comment by gorhill** [comment]
> I was also told on Reddit by gorhil himself, that I can post it here.

By the way, this is not true.

Please respect [the guideline](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> Do **NOT**: [...] Use issues as replacement for threads on a bulletin board. You can use Reddit for general discussion among users.

**Comment by Corruptinglyneedful** [comment]
Oh yes it was, several weeks ago.  You specifically responded to a comment I made and told me to post it here.  I just now got around to it.

You aren't being very user friendly and I don't like that.

**Comment by alain1965** [comment]
@gorhill is like that, he's a very good developer but not friendly with the peoples who are not, to be honest if ublock0 wasn't a good project an an alternative to adblock plus, I said to him "f....." because he has a little complex of superiority that make me nervous.

**Comment by gorhill** [comment]
> little complex of superiority

Way to miss the point.

Read carefully above: @Corruptinglyneedful is requiring that I volunteer my time to lecture him about "What is the DOM?" -- and he doesn't like that I refuse to do so.

This is just downright rude, this demonstrates a very low regard for other people's time, especially more so that we are talking about _volunteered_ time. This is what I learned with this project, to not waste my time anymore with people who feel completely entitled to my volunteered time -- because typically they are unable to grasp the concept of boundaries and will always end up asking for more.

Anybody can ask me to volunteered something, but if I say no, respect this. Actually apply this rule to [whoever is volunteering time and efforts out there](https://forums.lanik.us/viewtopic.php?f=9&t=20843).

**Comment by harshanvn** [comment]
Raymond has very little time (i.e., his free time). Where he wants to cater it <b>towards development<,b> (i.e, to code the things).
I would hope/request to people to understand it and stop being demanding :(

It would be very frustrating when people fail to realize that, and instead blames, that dev is not friendly and does not explain all kinds of basic things. Instead, OP can chose to research/read little bit on google, on what is meant by DOM. Or else he can chose to ask the question in any forums (like reddit, wilderssecurity). Where one can expect an answer in due diligent manner.

**Comment by alain1965** [comment]
I agree that @gorhill take many of his free time to develop ublock0 and I thank him for that especially when I compare to ublock dev and owner who does nothing and he will do nothing because he don't have time and the level too. But you known in a savage world where a man can have his head cut by a son of bitch like in my country saturday or a redaction of a newspaper, jews can be killed in the name of a so called god a little bit of "politesse and a manière de le dire" (make work your translator thx) sometime it's not too much even with a person you consider like a nerd, try a little tendernes.

**Comment by Hrxn** [comment]
In the end, good dev > friendly dev

:-)

**Comment by ozar** [comment]
I've been following this project for a while now and have always found gorhill to be more than fair and helpful to those posting uBlock-Origin issues when they use a bit of common sense and post the information needed for him to help them.  On the other hand, I'm not at all sure how he maintains his patience and demeanor as well as he does in those cases where a poster quickly demonstrates a need for constant hand-holding.  Of course, that's not to say that anyone posting in this thread fits either category, or anywhere in between.  It's just a personal observation and opinion, to which we are all entitled.  :)
