### ISSUE TITLE
Not really an issue : impressive improvement of Firefox 41 for AdBlock

### ISSUE THREAD

**Issue by Dormann** [gorhill/uBlock#427]
Hello,

Nicholas Nethercote made this news (https://blog.mozilla.org/nnethercote/2015/07/01/firefox-41-will-use-less-memory-when-running-adblock-plus/): it seems they, at long last, patch a very old issue with Firefox, making it lighter in memory usage and also making AdBlock Plus really lighter.
He also said that it would not affect uBlock since it makes things differently.

The questions here are: 
- is there really no gain for uBlock ?
- could you do another benchmark to show the diffrence in memory use and also in CPU use (maybe also, in time needed to display a web page) ?

It is not like I would switch to AdBlock Plus since I cannot stand their policy.
But I just would like to know.

**Comment by SW1FT** [comment]
No gain for uBlock as it doesn't use the same methods to block ads.

**Comment by gorhill** [comment]
> is there really no gain for uBlock

Doubtful, uBlock does not use global stylesheet to enforce cosmetic filtering, and my understanding is that the Firefox fix apply only to global stylesheets.

> could you do another benchmark to show the diffrence in memory use and also in CPU use

I will for memory use. You can also try it yourself meanwhile by following very rigorously the steps of the benchmark: <https://github.com/gorhill/uBlock/wiki/Firefox-version:-benchmarking-memory-footprint>.

However I never performed a benchmark for CPU benchmark on Firefox, because I wrote a [custom benchmark tool](https://github.com/gorhill/sessbench) to automate the benchmarks on Chromium, and this tool is not available for Firefox. Using an automated tool ensure the benchmarks are rigorous. Even then, Chromium makes it further easier to measure CPU usage because one can see CPU use specific to an extension in the browser's task manager.

**Comment by gorhill** [comment]
I can't answer a specific passage on the blog itself, there is no _reply_ button. So here.

@nnethercote

> Sometimes it’s worth thinking outside the tech elite bubble [...] and thinking about ordinary users in the real world

That's actually what motivated me to start uBlock more than one year ago, as my answer to the ["tech elite bubble" misrepresenting](https://bugzilla.mozilla.org/show_bug.cgi?id=988266#c39) a solution worth investigating for the benefit of users.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Firefox-version:-benchmarking-memory-footprint> updated.
