### ISSUE TITLE
Blocking Flash that contains Ads

### ISSUE THREAD

**Issue by blockerhelper** [gorhill/uBlock#438]
In Adblock or Adblock Plus, there is a tab above the flash that allow the user to block the flash that contains ADS. In ublock origin, there is no such option. When selecting element picker, the mouse pointer becomes the "hand" icon and is unable to select the ads. 

Using the logger feature, i still can't seem to pinpoint the location of the ads.

The Flash  ad is on the LEFT hand side.

**Comment by gorhill** [comment]
> The Flash ad is on the LEFT hand side

Can you provide a picture, I can't see any flash.

Also basic information: browser/version, ublock version.

**Comment by hotdogman** [comment]
Appears to be specific to FF. When click-to-play is enabled, and the flash advertisement hasn't played, the advertisement is blockable, but when it has played, the advertisement can't be blocked.
https://jii.moe/Vyxv5akd.webm

**Comment by gorhill** [comment]
>  Adblock or Adblock Plus, there is a tab above the flash

With ABP, I did not see any tab above the flash element. I can't see AdBlock in AMO.

Anyways, as shown by @hotdogman, I believe Flash elements are rendered separately from the document in Firefox, they "float" above the document and mouse events directly go to Flash elements without being propagated the normal way.

The logger was the solution in the current case, just filter the output so that the `swf` of the Flash object become easier to find: `frame || object` or `swf`, then it's a matter of [creating the filter directly from the logger](https://github.com/gorhill/uBlock/wiki/The-logger#creating-filters).

Given that Flash objects are on their way out, given this happens only with Firefox, and if click-to-play is not enabled, and given the logger works around the issue, I really don't feel like putting any effort for such a case to create some custom UI for these edge cases. It's just a matter of using existing tools when such edge case occurs.

THis is what I got using the logger and filtering its output using `frame || object`, then creating a filter:

    ! 7/3/2015, 3:36:40 PM phim3s.net
    ||lib.gamelumi.com/banner/at_01.swf$subdocument,domain=phim3s.net

**Comment by blockerhelper** [comment]
Ty

**Comment by lewisje** [comment]
ABP for Firefox has an option to "Show tabs on Flash and Java" as did its predecessor, the old "Adblock" extension (which was taken off AMO years ago), but the current "AdBlock" (a port from AdBlock for Chrome, which once was on AMO and soon may be again) does not.
