### ISSUE TITLE
Block Popups blocks "Open in New Tab" on some sites.

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#44]
On some sites, disabling popups causes the right click "Open in New Tab" to not function, or the tab to be immediately closed. I'm not sure if all sites should behave this way due to aggressive popup checks, or not, but I would think that me right clicking a browser context menu (I don't know if this is in any way distinguishable in the API or not) would never be a popup.

Some sites are OK, an example is GitHub itself. I can block all popups just fine.

On this site however (http://www.nextgenupdate.com/forums/grand-theft-auto-v/), I can see that the Open in New Tab is detected as a popup and terminated/blocked.

I also tested via the inspector to force a target="_blank" on the link, though I'd see that more exploitable by popups than a browser menu click.

**Comment by gorhill** [comment]
Yes this was reported before: <https://github.com/chrisaljoudi/uBlock/issues/1143>.

Unfortunately, this is caused by a limitation of chrome API: it is not possible for the code to reliably find out whether a tab opened because a user opened the link or because javascript opened the link.

The _block-all-popups_ feature should be seen as a last resort tool for when a site creates nuisance popups and there are no static filters (yet) for these. Workaround is to copy-link-address and paste manually.

**Comment by CODYQX4** [comment]
I was afraid they wouldn't have had a reliable method to detect the click source.

Well I'll just use it site-specific if I ever see popups. I haven't seen bad popups in forever anyway.
