### ISSUE TITLE
Popup not closed sometimes (chrome)

### ISSUE THREAD

**Issue by Dkzn** [gorhill/uBlock#45]
http://efukt.com/
(NSFW)

Block cookies for the site and start clicking anywhere. Every once in a while you get the strict blocking message instead of the window closing.
When you turn off strict blocking it's blocked 100% of the time.

Edit: nvm, I don't know why but it only happens with tampermonkey enabled.

**Comment by gorhill** [comment]
> only happens with tampermonkey enabled

Good, I didn't feel like opening this site anyways.

Popup is not the same as strict blocking. For a popup to close, there needs to be a specific filter to block that popup. Strict blocking kicks in when there is a match for whatever hostname-based filter. So it's possible that a chain of redirections in a popup can't complete because strict blocking kicks in. Preferred workaround in such case is to block unconditionally all popups for the site.
