### ISSUE TITLE
GMail with uBlock Origin slows down after being open for an extended period of time

### ISSUE THREAD

**Issue by utopiafallen** [gorhill/uBlock#453]
I've noticed that once uBlock Origin's little counter thing says ">1k", GMail slows down considerably. Reloading GMail makes the problem go away, but ideally I wouldn't need to do that. I attached a Javascript CPU profile from when I'm trying to type letters into the compose message window in case that might help you, but the slowdown is across the whole webpage, not just message composition.

![image](https://cloud.githubusercontent.com/assets/6111141/8534431/17fcf400-23f1-11e5-8beb-bd6f80695455.png)

**Comment by gorhill** [comment]
When you say "extended period of time", how long would that be roughly?

**Comment by utopiafallen** [comment]
I want to say overnight is enough to start seeing the slowdown, but I'll be able to confirm that tomorrow. Otherwise, my GMail tabs are always open so I've never tracked specifically how long between page reloads before the slowdown starts occurring.

**Comment by gorhill** [comment]
I see something, the performance log looks strange to me, which could be explained one way. But I can't tell for sure whether it's the issue you are specifically experiencing. A few questions:

- What filter lists do you have selected?
- Would you say your Gmail account is a busy one?
    - Meaning are there things happening regularly so that whatever part of the UI is refreshed as a conosequence.
- Did you restart uBlock at any point without the Gmail web page being reloaded?

**Comment by utopiafallen** [comment]
* I use the default filter lists, but I've attached a screenshot in case I accidentally changed them at some point:
![image](https://cloud.githubusercontent.com/assets/6111141/8535452/c04a0e5a-23fa-11e5-99fa-fb838bdeacec.png)
* One GMail account is a bit more busy than the other one because it's my work account. My personal account doesn't receive email too frequently and I leave it on my inbox view most of the time so the UI for that is pretty static.
* I don't know what you mean by "restart uBlock" so I'm going to say no. uBlock is always running and I leave Chrome with my GMail tabs open forever, unless I need to restart my machine.

**Comment by gorhill** [comment]
Ok.. As per performance profile seen above, this suggests that the content script running in the web page lost contact with the main uBlock process: the content script keep asking stuff from the main process, but the main process never answers back, which would cause memory leaks and performance issues over time, because internal data structures content script-side are piling up due to lack of response from the main process -- whereas these data structures are usually freed immediately upon receiving an answer from the main process.

This can happens if uBlock is restarted without refreshing the currently opened web pages, and this will manifest easily for dynamically updated web pages, which is typical of long-lived web pages such as Gmail, Youtube, for examples. For instance, if uBlock is disabled/enabled because the browser updates it, this will occur.

Now the question is whether this can happen _without_ uBlock's main process being restarted.

I've hardened the content script-side message passing code to deal with losing touch with the main process, so that things do not pile up. I put in a console log message to detect when uBlock's content script is no longer able to see the main process: the message appears once in a while (Youtube, Gmail) even without uBlock being restarted, which means that for whatever reasons, the content script can indeed lose contact with the main process under normal circumstances, not just when the extension updates -- and this is the best explanation for the performance profile seen above.
