### ISSUE TITLE
Understand origin 

### ISSUE THREAD

**Issue by Marsfan** [gorhill/uBlock#462]
Gorhill,  
I know that you hate these posts, but I really need your help. 
I have intended to switch to Chris's release, as you say you focus on bug fixing, but you have more releases and seem to still be adding features. What gives am how do I get the most lightweight,  ad blocking,  and feature loaded system.

**Comment by TeddStriker** [comment]
Please refrain from posting non-issues like this, (read [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)) even with this not being a topic that warrants its github issue, there are several similar ones already opened (as far as I'm aware). You can look through those, or better yet, read the wiki where I believe there are entries concerning this. 

* This [article](http://tuxdiary.com/2015/06/14/ublock-origin/) goes over it very briefly.

* This [issue](https://github.com/gorhill/uBlock/issues/38#issuecomment-96618444) provides some insight.

I don't mean to be rude. But it is best that you **close** this issue, and post a thread on [reddit](https://www.reddit.com/r/ublock+ublockorigin), because there are a lot of important technical issues that need to be addressed, that are drowned in philosophical, ethical and other kinds of discussions.

This add-on is practically a one-man show, and as you can see there are a bunch of issues being reported, very little of which actually pertain to uBlock.

**Comment by gorhill** [comment]
@Marsfan I don't tell people what to use, they need to make this decision themselves.

**Comment by Marsfan** [comment]
@TeddStriker @gorhill 
I completely understand everything that you say, but I have read that chris has the more up-to-date, feature loaded version, yet you update yours more often and seem to add features faster. What gives.

**Comment by Krak-n** [comment]
@Marsfan you dont need to sign up for reddit to read subreddits. This question has been asked so many times there that you can just search for the answer and get a handful of hits.

**Comment by gorhill** [comment]
> For the differences in features between uBlock Origin and uBlock, you are more likely than anywhere else to find an unbiased explanation in [this Wikipedia article](http://en.wikipedia.org/wiki/UBlock).

Bottom line: does your blocker does what you want it to do? Yes = stick with it, no = find what suits your need.

**Comment by TeddStriker** [comment]
@Marsfan 
I don't want to go into detail about the versions and their differences, but you need to consider that:

* Gorhill is the original developer, and wrote the code from scratch (Don't be confused by the "forked from Chris/uBlock)

* Chris has had a very small contribution to the original project

* Go over to both extensions and view their commit history and decide for yourself which one has more additions, and which of those are features (as opposed to cosmetics and readme changes)

With that, make the decision yourself, technically, the forks are very, very similar. I personally switched to this "fork", because this is where the main developer is, and because I don't like some of the practices Chris is doing with uBlock.
