### ISSUE TITLE
Portuguese and Spanish

### ISSUE THREAD

**Issue by ruy-benton** [gorhill/uBlock#496]
I love your work since HTTP Switchboard and now is even better.

Please add https://secure.fanboy.co.nz/fanboy-espanol.txt to the International list.
Portuguese - Spanish.

It's amazing your work.
I tested  the extension with 
https://www.fanboy.co.nz/r/fanboy-ultimate.txt
http://hosts-file.net/download/hosts.txt        	 349.132 Hosts
http://rlwpx.free.fr/WPFF/hmis.7z                     521.790 sites divers bloqués

and it works!!!!!

BTW any user know any "host manager" for Linux like
this one for W$n?
http://www.abelhadigital.com/hostsman

Thanks in advance for your wonderful software.

Ruy B.

**Comment by gorhill** [comment]
> Please add https://secure.fanboy.co.nz/fanboy-espanol.txt to the International list.

The was updated last in August 2013. I do not want to include obsolete filter list. I actually need to remove some already in there, because they are no longer maintained.

You may add it to [this wiki page](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web) if you think it's worth it.

**Comment by ruy-benton** [comment]
Thank you for your comments.
OK
