### ISSUE TITLE
Blocking specific javascripts per site?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [gorhill/uBlock#506]
How do I block just a specific javascript per site? Say randomanimation.js is incorporated in www.somesite.com

**Comment by Mikey1993** [comment]
You can use Dynamic URL filtering feature (from within the logger).
Check the Wiki page: https://github.com/gorhill/uBlock/wiki/Dynamic-URL-filtering

**Comment by Unrepentant-Atheist** [comment]
Ah, thank you! Got it. Now is there a way to block a specific function within a .js?

**Comment by Mikey1993** [comment]
Nope, there is no such ability currently.

**Comment by lewisje** [comment]
If you're able to get a reference to that function from global code (as in a UserScript) and the function isn't used somewhere where it has been dereferenced (like in a timer or an event handler), you should be able to do something like this:

`badFunction = function empty(){'use strict';};`

If you need to do this to several functions, it's more efficient to cache a reference to this no-op function or chain your assignments.

`worseFunction = badFunction = function empty(){'use strict';};`

It produces fewer JS errors than just setting them all to `null` although you could *also* try nulling-out or otherwise neutering any globally accessible configuration parameters for the script: for example, something like `displayDelay = Infinity;` or `adDiv.parent.removeChild(adDiv); adDiv = null;`.
