### ISSUE TITLE
[Enhancement] Automatically select the tab it was opened from when opening the Logger.

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#507]
I find myself most of the times looking for the particular tab that I opened the logger from to check the requests that came from it for an analysis.
But going over the 200+ tabs that I have opened consistently makes this task very frustrating at times.

Also, most of users, I believe, want to analyze a particular page rather than all the tabs (because the uBlock popup is per site/page),
so I think It's more logical to open the logger for the tab that it was opened from instead of the "All" selection.

*If the user just opened the logger manually (by say entering the full path), just revert to the current behavior.

**Comment by gorhill** [comment]
Please, I rather not have feature requests for the DOM inspector. I _obviously_ have thought of many of the suggestion you have submitted, and as spelled out in [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), do not submit feature requests.

**Comment by Mikey1993** [comment]
Sure thing, just wanted to open them for tracking purposes and to discuss them with you.
I'm not a mind reader :)

**Comment by seanrand** [comment]
Sorry to hijack the issue, but while we're on the topic of the logger and I don't want to open another non-issue - please consider ordering the tabs in the logger drop down like the tabs in the browser's tab bar, instead of sorting them alphabetically. I think that would be more intuitive as you could just look for the "2nd tab from the right" instead of finding the tab title in the alphabetically sorted drop down.

gorhill, feel free to ignore this comment, I just wanted it to be seen by you. The sorting is down to personal preference and for Mikey1993's use case with 200+ tabs, alphabetical sorting is probably better.

**Comment by gorhill** [comment]
Actually, I didn't realize this one is not about the DOM inspector, so my comment above should have been made in one of the DOM inspector issues opened, not this one.

In general, when a feature is new, there is an implicit warning to not file feature requests -- an implicit warning which I made explicitly once, so I thought it was understood.

That said, I can see how the current feature here is useful if one has 200 tabs opened.
