### ISSUE TITLE
Undo option for blocked elements

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#515]
Sometimes blocking an element breaks the webpage and I have to go to uBlock settings to manually remove the filter. As far as I'm aware there's no quick option to "undo" changes.
Either a hotkey or a context menu item would be greatly appreciated.

**Comment by gorhill** [comment]
_Preview_ was added in <https://github.com/gorhill/uBlock/releases/tag/1.7.0>, this should help preventing the creation of filters which break page.

In any case, this would need much better detailing about how exactly this works -- asking _"Add undo button"_ without in-depth analyzing how this would work in actual world without self-adversiarial thinking is not the way to go. Whoever wants such feature will have to provide a complete analysis of how exactly that would work in reality -- otherwise I will close such issues as _incomplete_.
