### ISSUE TITLE
Speed and Dynamic-filtering:-precedence

### ISSUE THREAD

**Issue by ruy-benton** [gorhill/uBlock#527]
In wiki, you describe for better security - enable:
3rd-party scripts and frames, inline and 1st-party scripts.

And there is another Benefit / Advantage - IT'S SPEED.
If uBlock (Dynamic-filter) blocks all that scripts and frames ... he don't search in static filters.
<br>
<br>

I analysed https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence

If I block 3rd-party frames and scripts - red in "My rules",
why the local "www.example.com   *    *    noop" don't disable this 3rd-party?

and this disable:
"www.example.com * 3p-script noop"
"www.example.com * 3p-frame noop"

Thank you in advance for your comments

**Comment by gorhill** [comment]
> why the local "www.example.com * * noop" don't disable this 3rd-party?

I don't understand the issue report. What do you mean by "disable this 3rd-party"? `www.example.com * * noop` means to disable dynamic filtering for `www.example.com`.

**Comment by RoxKilly** [comment]
@ruy-benton `noop` means `allow this request unless a static filter blocks it` where static filters come from block lists in the `3rd Party Filters` tab of UBlock's settings (`EasyList` and `EasyPrivacy` for example).
 
In dynamic filtering, site-specific rules will take precedence over more general rules.  So even if you block 3rd party scripts generally, the site-specific rule `www.example.com * * noop` will override the block and allow 3rd party scripts made from `www.example.com` (except those scripts blocked by static filters)

**Comment by ruy-benton** [comment]
RoxKilly 
1) I want that procedure ... correct 
And  "Fanboy+Easylist-Merged Ultimate List‎",  "Malware domains‎" ...

2) "... site-specific rules will take precedence over more general rules ..." correct.

But ... for example     http://www.ic.ac.uk

I block 3rd-party frames and scripts - red in "My rules",



In Logger:

....
10:11:04	image	http://www.ic.ac.uk/NewsEvents/image/featurenews2012/28511.jpg
10:11:04	image	http://www.ic.ac.uk/NewsEvents/image/featurenews2012/28512.jpg
10:11:04	* * 3p-script block	--	script	http://www.google-analytics.com/ga.js



Insert:         www.ic.ac.uk    *      *         noop

10:24:31	image	http://www.ic.ac.uk/NewsEvents/image/featurenews2012/28511.jpg
10:24:31	image	http://www.ic.ac.uk/NewsEvents/image/featurenews2012/28512.jpg
10:24:31	* * 3p-script block	--	script	http://www.google-analytics.com/ga.js

No change ...


Insert:         www.ic.ac.uk     *        3p-script         noop

10:28:06	image	http://www.ic.ac.uk/NewsEvents/image/featurenews2012/28511.jpg
10:28:06	image	http://www.ic.ac.uk/NewsEvents/image/featurenews2012/28512.jpg
10:28:06	.com/ga.js	--	script	http://www.google-analytics.com/ga.js

Static filter in action




"... the site-specific rule www.example.com * * noop will override the block and allow 3rd party scripts made from www.example.com ..."

Nooooooooooo        " ... 3rd-party scripts - red in "My rules"        wins


This is correct if I insert
 www.ic.ac.uk     *        3p-script         noop

Thank you for your work and comments,
Ruy

**Comment by gorhill** [comment]
> "... the site-specific rule www.example.com * * noop will override the block and allow 3rd party scripts made from www.example.com ..."

Put in words, `www.ic.ac.uk * * noop` means you are noop'ing the `all` cell for site `www.ic.ac.uk`, which is usually pointless unless you have a `block` or `allow` rule for the global `all` cell.

The `3p-script` cell has precedence over the `all` cell, hence the result.

**Comment by ruy-benton** [comment]
I don't' understand why you close the issue ...

I give one example

Another one:

seanrand 
...
"Edit: Just tried countering the * * 3p block with behind-the-scene * * noop, but it seems that 3p block takes precedence. Hmm.

Edit: behind-the-scene * 3p noop did the trick. Might be worth adding to the wiki."


And another one:
http://www.massimodutti.com

**Comment by gorhill** [comment]
> I don't' understand why you close the issue

Because there is no issue, what you says is exactly how the [precedence is documented](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence).

**Comment by seanrand** [comment]
Trying to understand why I'm being quoted here, my comment was just me figuring out the precedences (which gorhill explained in this issue before closing it), sorry if that caused any confusion.

**Comment by ruy-benton** [comment]
It's very simple ...    if you post or I can insert some images in WIKI.

When  I change  "www.ic.ac.uk * 3p-script noop" in "3rd-party scripts" right
to  "www.ic.ac.uk * * noop" 
uBlock move to all cells ( local ).

**Comment by seanrand** [comment]
@ruy-benton, I don't want to derail #528 any further, so I'm commenting here. I *think* I see where the confusion might stem from.

Let's take this page as an example. We are using default-deny (```* * 3p-frame block``` and ```* * 3p-script block```) and apply ```github.com * * noop```:

![screenshot-20150726t013907](https://cloud.githubusercontent.com/assets/929479/8891802/d22c5da2-3337-11e5-9ea7-c3a032378979.png)

When you look at the matrix, you could think that ```github * * noop``` overrides the ```* * 3p-frame block``` and ```* * 3p-script block``` rules because all hosts are greyed out. But, as we learnt earlier, that actually isn't the case! With this setup, ```github * * noop``` does *not* noop third-party scripts and frames.

A better representation of the situation would be this:

![screenshot-20150726t013907_y](https://cloud.githubusercontent.com/assets/929479/8891813/75bb38bc-3338-11e5-851b-81f285648be9.png)

*Some* third party assets such as images and css are allowed (because there is no ```github * 3p deny``` rule) while others (scripts, frames) are blocked.

---
Similarly, nooping thirdparty scripts locally on a default-deny setup is currently represented like this in the matrix:

![screenshot-20150726t011623](https://cloud.githubusercontent.com/assets/929479/8891837/55e9d5a6-3339-11e5-9398-b0f0eeb79c63.png)

It's not immediately obvious that some thirdparty requests are *still* being blocked (frames). This could be represented more accurately like this:

![screenshot-20150726t011623_y](https://cloud.githubusercontent.com/assets/929479/8891862/8c904e96-3339-11e5-8659-e3cbec475f4d.png)

---

@gorhill, are you following? You're already using a yellow indicator for "mixed" (some requests blocked, some allowed) in the matrix, so applying it to the second and third column would be intuitive and more accurately represent the state of dynamic filtering for a host.

**Comment by ruy-benton** [comment]
@seanrand  translate my text -> images !!!!! Wowwwwwwwwwwwwwwwwwwww

I understand @gorhill in 2 comment and write:
_________________________________________________________________
When I change "www.ic.ac.uk * 3p-script noop" local ( in "3rd-party scripts" right ) -> "www.ic.ac.uk * * noop"
uBlock move to "all" ( local ).
__________________________________________________________________

and try to help you in #528 

Please update WIKI with images and this will help other users.

Thank you very much for your great software
