### ISSUE TITLE
Google Contributor whitelist?

### ISSUE THREAD

**Issue by sircod** [gorhill/uBlock#541]
Google has a Contributor program which allows you to pay a monthly subscription to remove some ads, giving part of your subscription fee to the site instead. ( https://contributor.google.com/ )

uBlock currently stops this from happening since it blocks the ads before Contributor can get to them. Is there some way to let Contributor support the sites you visit while still blocking the rest of the ads?

**Comment by gorhill** [comment]
That's a job for a filter list maintainer -- I myself do not have the time to become a filter list maintainer, writing code/doc is already occupying most of my free time.

**Comment by sircod** [comment]
OK, thanks for the response.

**Comment by olloff** [comment]
> Is it possible to whitelist ad sources (like let through all google ads)?

Not sure if it helps, but you can test some rules from AdBlock "acceptable ads" list: https://easylist-downloads.adblockplus.org/exceptionrules.txt
Add to uBlock new list with all entries starting with:

    @@||google.com
    @@||g.doubleclick.net
    @@||ad.doubleclick.net
    @@||pagead2.googlesyndication.com
    @@||partner.googleadservices.com

**Comment by sircod** [comment]
Thanks, I will try that.

**Comment by White-Tiger** [comment]
since it's kind of related and the "acceptable ads" list was mentioned, I would really like such a feature that allows acceptable ads to be shown (such as Google text ads)
So it must be a filter that can overwrite other filters and basically "white-list" on a per rule basis...

Can I assume that uBlock doesn't support this yet as there's no such list or setting to be found?
It might be uneasy to add the Adblock list to our integrated list, since they are paid for it and you not.. but the possibility should at least allow people to maintain such a list (preferably on Github)

**Comment by sircod** [comment]
As olloff mentioned it is possible to add the ABP acceptable ads list to uBlock, but it doesn't seem to work. When using EasyList I had a hard time whitelisting anything, and with Peter Lowe's I could whitelist some. But I still don't have ads on Google's search results page even with the acceptable ads whitelist.

The solution might just be to make an adlist that doesn't include the acceptable sources in the first place. I would like to see a list that just blocks the worst offenders, and maybe something like that already exists.

**Comment by gorhill** [comment]
> I still don't have ads on Google's search results page even with the acceptable ads whitelist

Just [toggle off cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-cosmetic-filtering) on Google search page.

**Comment by gorhill** [comment]
> it is possible to add the ABP acceptable ads list to uBlock, but it doesn't seem to work

Most of the "acceptable ads" filter list is made of exception filters using the `document` option. The `document` option for exception filters is not supported by uBlock, by design. So far, this way of using the `document` option is pretty much strictly for Adblock Plus' "acceptable ads" purpose, and [as stated a long time ago](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md), uBlock does not cater to the specific business model of any specific business entity (which is what "acceptable ads" is).

**Comment by White-Tiger** [comment]
@gorhill what you basically say means to NOT let the user control what's blocked and what not... if you make it as much complicated as possible, users will not do it (or won't even be able to). It needs to be simple to be used.

Disabling uBlock for specific websites takes a high amount of time and configuration, it also doesn't allow to share them with everyone so they can enable it with just a simple click of a button, nor does it actually work.
When I disable uBlock, I'll likely have to "accept" some non-acceptable ads. That is: one page might have ads that are acceptable and perfectly fine, but also popups and other annoying stuff so you can't just disable it..
There needs to be a way to strictly allow some ads that got higher priority than blocking them. (so that those "basic" lists can be used which block most stuff, and lists that allow "good" stuff again)

Publishing an adblocker takes some high responsibility, because there are a lot of sites out there that don't really annoy you, yet won't have their ads showed because "everyone" uses an adblocker. Why is this a problem? Because some users are recommended to use a blocking tool by friends, yet those might not really know what they are doing. This results in them not allowing any ads and rarely to never disabling the blocker.
I'm not even happy with ABP because it's already blocking way too much. We have to change the ad industry (like Google tried with text ads) by not blocking non-annoying ads by default. So that they start to use less crap and provide high quality ads. Ads by definition aren't evil, just most ad companies (easy way to make money, the shadier your ads, the more money.. that's why it attracts a lot of idiots)
I don't have a website yet that is supported by ads. Though I wouldn't deny to have one at some point (given that I find a good ad service or that Google text ads still exist)
But mainly I'm talking about a user. Those sites have costs and I don't want to pay for them. (well not directly. Actually I'm a bad guy anyway because ads have almost no chance to make me buying something^^ So I just leech and never give :P)

I define "good ads" like this:
- doesn't annoy with flickery stuff
- no sounds
- doesn't increase the load times (much). Basically try to make them as small and "perfect" as possible (using image optimization tools such as RIOT and other stuff)
- doesn't delay or otherwise reduce the experience with any given site
- might be disabled for mobile users or for regions that are known to have volume based internet traffic (that is you pay for every MB received. No one should PAY just to be able to view an ad...)
- no popups/popunder (basically they tend to freeze my browser.. so I cannot live without adblocking as it would be much much slower and annoying)
- no fake "download now" stuff that is willingly placed on download pages, just to make people install your fake / infected program (mainly never pretend to be something you're not)
- for Video on demand systems: don't repeat your ads all the time, don't show them for the very first seconds to take a peek (that is if one just wants to find out what it is.. doesn't make sense to view 30 seconds of ads to just be able to seek stuff for about 10 seconds)

**Comment by gorhill** [comment]
> It needs to be simple to be used.

Big blue power button:

[![The large power button](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1b.png)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button)

> I define "good ads" like this

> I

"I"

**Comment by White-Tiger** [comment]
How do you define "good ads" then? What's missing or to which points do you not agree?

And I've mentioned the reasons why the power button doesn't cut it. At least not for most sites.. it might work for Google, but not other sites and yet, you've got to do it / try it for every single page.
I've given up to do that. Basically I'm just blocking everything except the "acceptable ads" that Adblock added.. which I also almost never see... (and might be a reason to go back to Adblock, I don't want to block everything, yet don't want to waste my time (which is wasted because I do it just for me and no one else benefits from it. I might help to maintain a public list, but won't configure stuff just for myself)
Seriously, if you allow ads at all, do you really try that with every single site you visit? If at all, you would consider to try it after visiting a site for at least a year.. but those small pages you visit by random chance are simply out of luck.
The only possible way I can currently think of, would be a proxy server for filter subscriptions that removes rules of acceptable ads.. but if you want a flexible, user chosen way to control their lists, it needs to be dynamically generated and requires yet again quite high effort and server resources.
So a way to just have "allow" rules ans subscriptions is simpler... maybe not for uBlock as it needs to compile the filters (but it needs to do that anyway, doesn't it ;))

**Comment by gorhill** [comment]
> How do you define "good ads" then?

I don't, it's for everybody to decide for themselves. If there is such a need for a "good ads" filter list, then it will happen, somebody will create one. ABP's "acceptable ads" is EyeO's business plan, it's not a community-maintained filter list (of course it's marketed as being in the users' interests, that's how good marketing campaign are designed).

It's not uBlock's purpose to decide what is a "good ad", and even whether ads are the business model of choice for sites to support themselves. If sites chose to fund themselves through 3rd-parties which have no real genuine interests in both content creators or users, they have to accept the consequences of such choice, it's not uBlock's purpose to support their specific choice.

**Comment by White-Tiger** [comment]
Well.. uBlock should have meaningful defaults. Which work even for the most "incompetent" user in existence. (one reason why Apple had this much success.. it just "works")
Though it's a rather hard challenge for uBlock.. because if there are ads shown, some users might think uBlock doesn't really work... so it should ask the user whether to allow non-intrusive ads or not (with a very short explanation what it means)

Though it would be the best way if uBlock would support it directly (including a WoT mechanism to rate ads shown on a page to "allow" them and ways to report annoying ads, maybe even by granting the site owner informations about their rating, such as ad X isn't acceptable and thus they were all blocked)

I'm merely asking for a way to allow them by subscriptions (which should be a dedicated category as they need to be "independent" and overwrite other rules)
No one will create a list if there's no programs to use them. We could also try to allow ad companies to define their own "tolerable" list which can be automatically applied to uBlock after user intervention. Will likely not work for most companies, but we'll know which ones really suck this way :P
Yet this isn't really about ideas how this all could be done, but about enhancing uBlock to allow it in first place.

Anyway, you said uBlock doesn't allow exceptions using the "document" option, but what does it mean? That it can't unblock specific ads? (basically the inverse of any given filter) Or that it can't un-hide hidden elements? Understanding how filters are done and how they work takes some time, that's why I have to ask as a mere user (which this is all about)

P.S. I'm bad at writing "short" stuff.. but I try to describe what I mean and to make it as easily understandable as possible.. that's why it often tends to be a lot of text.. Would likely help if English was my mother tongue, except not.
P.P.S. I'm not just asking for myself, friends of mine that I've recently informed about uBlock as a "better" alternative to ABP would also allow non-intrusive ads... though they might not "waste" their time to find out how to do it.. but use it if they knew how to.

**Comment by gorhill** [comment]
> That it can't unblock specific ads? (basically the inverse of any given filter)

You do not need the `document` option to create exception filters (`@@`).

**Comment by sircod** [comment]
Just turning off all ads for a specific site isn't a very good solution as even good sites can have some ridiculous ads. Manually whitelisting sources is a pain in the ass and unreliable in my experience so far.

If we had a "good ads allowed" filter then everything would be fine without making any more work for gorhill.  But I do not know of any such filter and the closest thing we have right now is the ABP acceptable ads option. It doesn't seem like there is a good solution at this time.
