### ISSUE TITLE
[Palemoon] Cosmetic filter weirdness on AMO

### ISSUE THREAD

**Issue by Tharn** [gorhill/uBlock#545]
Using uBlock 1.0.0.0 and Palemoon 25.6, if I add mozilla.org###site-welcome to My Filters and go to https://addons.mozilla.org/en-US/firefox/, I see the little welcome bubble appear for a fraction of a second every time I refresh the page. Interestingly, if I enable Palemoon's 'Firefox Compatibility Mode', this doesn't happen. Compatibility Mode is nothing but a User Agent override for certain popular sites like Google and AMO.

However, if I also add mozilla.org###site-nonfx to the list (which is a different pop-up), this seems to include the welcome bubble and fixes the issue. Is this a case of one bit of CSS bleeding into another, or how does it work? I'm working off the assumption that stuff in the filter lists does not get loaded. It shouldn't even use bandwidth or come through the network, right?

To be clear: It's an insignificant issue for sure. I'm posting this just in case it constitutes a 'leak'.

**Comment by gorhill** [comment]
Using Pale Moon with compatibility mode turned off, I don't see any welcome bubble, custom filter or not. Where should I look for it?

I do see an unexpected behavior though: if I use `mozilla.org###site-welcome`, the DOM inspector appears broken in Pale Moon -- regardless of selected compatibility mode. Looking more into this, it appears it's because Pale Moon does not support [`Element.matches`](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches), which is used by uBlock. Unrelated to the current issue though, and probably easily fixed using the prefixed version of the function.

**Comment by Tharn** [comment]
Something very weird was going on. I tried to get the bubble to show up again, and disabling uBlock didn't fix it. Not even disabling it & restarting the browser. It even still showed the same behaviour as before re. Compatibility Mode. What fixed it, finally, was cutting the filters out of My Filters by hand and putting them somewhere else temporarily. Sorry if this issue turned out to be a bag full of quirks. ;)

http://i.imgur.com/MkGqAmM.png This is the item in question.
