### ISSUE TITLE
request dynamic filtering window have "global" and "local" added to column headers

### ISSUE THREAD

**Issue by jawz101** [gorhill/uBlock#559]
I prefer apps that label things, have hover over descriptions, etc.  Then it doesn't take as much documentation to know what to do.

**Comment by gorhill** [comment]
Once you know what the columns do, these headers become pointless, taking up limited space in the popup UI. Only reading is required, and even then, simply clicking on one cell provides enough visual feedback to understand which one is global or local: visual of global rules will "leak" onto the corresponding local one.

**Comment by dpmccabe** [comment]
This is idiotic. How are you supposed to learn what the columns mean **in the first place** without the UI telling you? Good UI is about following convention and not breaking expectations.

**Comment by gorhill** [comment]
> How are you supposed to learn what the columns mean in the first place without the UI telling you?

![a](https://cloud.githubusercontent.com/assets/585534/11580262/68ba4162-9a03-11e5-9703-ddf06a61af81.png)

And the UI **is** telling you: the cells with the pluses/minuses are the local scope cells.

**Comment by dpmccabe** [comment]
So I have to comb through multiple pages of a wiki instead of just reading a column header? And why does checking "advanced user" turn off tooltips? Does checking that box also imbue users with the gift of infinite and infallible memory? Sure, I read the wiki once. Then six months later when I need to whitelist a resource I'm expected to remember everything in it?

Reading through the many issues here regarding tooltips and other failings of the UI, it seems like you expect users to be as familiar with the extension as you, the developer, are. What *you* find intuitive and obvious is hardly intuitive and obvious to, seemingly, *everyone else*. It's bad UI/UX. It's also a naive and hostile attitude to have to your users. Good luck with that!
