### ISSUE TITLE
UBock Origin no longer being installed in latest Firefox nightly?

### ISSUE THREAD

**Issue by gofirst2220** [gorhill/uBlock#565]
I was formed that it can't be installed because it's unsigned. Can the latest Firefox version be signed?

**Comment by the-nothingman** [comment]
Mozilla is testing addon signing before it moves to release, set xpinstall.signatures.required to false in about:config

**Comment by gofirst2220** [comment]
Ah. No idea why Mozilla patched that now in latest hotfix for Firefox Nightly. Got it installed.

**Comment by gorhill** [comment]
uBlock Origin is signed. All extensions in AMO are signed.

**Comment by slx7R4GDZM** [comment]
I just got this too when trying to upgrade from 1.0.0.0. Had to modify the about:config option that the-nothingman mentioned for it to allow me to upgrade.

**Comment by gorhill** [comment]
To re-cap:

When installing uBlock Origin from AMO, all should be fine, because everything on AMO is signed.

When installing uBlock Origin from GitHub, this will not work starting with Firefox 40 if `xpinstall.signatures.required` is set to `true` in `about:config`.

Hence two possible solutions:

- Install uBlock Origin from AMO;
- Install uBlock Origin from GitHub, but only after ensuring `xpinstall.signatures.required` is set to `false` in `about:config`.
