### ISSUE TITLE
cosmetic issue

### ISSUE THREAD

**Issue by zummuz** [gorhill/uBlock#579]
Hi. There is cosmetic issue: ublock doesn't show requests for domain (colour signs and +/- signs) on some sites. 
For example 2 sites:
https://www.reddit.com/
http://www.avclub.com/
![ublock](https://cloud.githubusercontent.com/assets/13698274/9143587/00ff069e-3d50-11e5-8b11-3d3d9de34e15.png)
I have noticed that sites with the issue have in common one script request from main domain (picture below). But I can't find with logger which script specifically.
![umatrix](https://cloud.githubusercontent.com/assets/13698274/9143776/009506bc-3d51-11e5-9f4a-44bb94fabd99.png)
Chromium 46
Windows 7

**Comment by g3939434** [comment]
>But I can't find with logger which script specifically.

The script is inline-script, which doesn't count as requests blocked.

**Comment by zummuz** [comment]
> The script is inline-script, which doesn't count as requests blocked.

But the script request from 1st party domain was counted (allowed one) in umatrix. I thought there could be green sign and + sign in ublocks field (reddit.com).
Its not significant issue, if it is an issue at all. I'd like gorhill to see these posts to be sure its ok.

**Comment by gorhill** [comment]
uBlock and uMatrix work differently.

In uMatrix, the inline script tags, if present, are globally counted as one 1st-party script resource, because the user must be informed if there are script tags present, in order to be able to decide whether to block or allow 1st-party scripts.

In uBlock, the same inline script tags are not counted as a separate resource, as there is one cell dedicated for inline script tags specifically.

**Comment by zummuz** [comment]
Ok, its not an issue but a feature then. Thanks
