### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by polilla** [gorhill/uBlock#59]
I'm using uBlock 0.9.3.0 with only my own filter-list.

First: 
In this list i'm using such words like adserv, advert or affiliate to block.
In Adblock this works. Block all words that contains for example affiliate.
But uBlock dont't do this.
For first solution i changed this words for example from "affiliate" to "/affiliate".

Second:
The filter /ad/\* matching very well. But when you click on the eye normaly all the filter are marked. 'But not the /ad/ in the correct way.

![ublock](https://cloud.githubusercontent.com/assets/11969556/7171967/44f30ea0-e3e0-11e4-876a-7feca8f0853c.png)

Edit: Missed Example-URL: http://extreme.pcgameshardware.de/

**Comment by gorhill** [comment]
For 1., by design: you need to to add something to the filter so that uBlock can tell it's not a hostname -- because can also read hosts file. So if you enter just `affiliate`, uBlock doesn't know if it's a hostname, or a keyword to match at any position in a URL. So you found the proper solution, to use `/affiliate` instead.

For 2., I am going to say by design to: uBlock will match the first occurrence, whatever follow is of no importance, because it is the first occurrenc which triggered the match.

**Comment by my-password-is-password** [comment]
It thinks the filter is regex because it starts with '/' and ends with '/'. So it matched 'ad'.

Using `//ad/.*/` matches "/ad/*"...  Do you really have to use it like this?

I tested `//ad/.*/$important` and it matched '/ad/'.   The "$important"  was used just for testing so uBlock uses my filter instead of another filter it was using to block it.

**Comment by my-password-is-password** [comment]
@gorhill 

On that same page he provided

Try `/adj/*$important`  , this just matches 'adj'

Then try //adj/.*/$important , this matches 'adj/......'

**Comment by gorhill** [comment]
@my-password-is-password `//adj/.*/` should matches `/adj/`. What am I missing?

**Comment by my-password-is-password** [comment]
In the request log it.  the filter `/adj/*$important` just highlights 'adj'

//adj/.*/$important works fine, I know.   Is `/ad/*` suppose to highlight "/ad/.........."  in the request log?

**Comment by gorhill** [comment]
@my-password-is-password 

Ok I see, you meant _your_ request log, I kept trying to find what you were talking about in the posted screenshot in OP.

Yes, it is wrong. Looks like a rendering issue in the logger, as the match is the right one.

**Comment by gorhill** [comment]
@my-password-is-password 

Can you open a new issue for this please? I do not want to mix up everything. There were no issue in OP, so I want that part cleared. You found a very specific issue, I want it separate rather than piled on inside another issue. This allow me to accurately match code changes with very specific issues.

I thought this could be a quick fix but it is not despite appearing trivial. It is definitely a rendering issue (internal pattern matching works as expected), but it finds it's root cause far from where the rendering is done in the dev log.

**Comment by my-password-is-password** [comment]
@gorhill 

His issue is the same, I think.  Look at his screenshot where `ad` is highlighted instead of '/ad/'.  I just used the example '/adj/*' becuase nothing followed `/ad/` to make it more visible to see in the request log.

**Comment by gorhill** [comment]
@my-password-is-password 

That right, I see it now. Sorry about this.

**Comment by my-password-is-password** [comment]
@gorhill 

Does ABP filter syntax consider '/ad/' as regex or is that just uBlock?  To match just '/ad/' in uBLock you have to use '//ad//'?  I don't know if it suppose to be like..

**Comment by gorhill** [comment]
@my-password-is-password 

It's just a rendering thing. Internally, the filter is really evaluated as `/ad/*`, i.e. not as a regex.

**Comment by my-password-is-password** [comment]
Oh ok. Thanks

**Comment by polilla** [comment]
Thanks for re-opening and investigation.
/ad/*  or /ads/* are "/ad/" or "/ads/"
This is the syntax from Adblock Plus.

**Comment by polilla** [comment]
Ah, ok, gorhill said that this is only a rendering thing, because internaly this filter block how it must.

**Comment by polilla** [comment]
This is what i learned. When its starts with a Slash "/" and ended with a Slash "/" you must mark it with a "*".

**Comment by lewisje** [comment]
yes, because if ABP or AdBlock or uBlock *can* recognize a blocking filter as a regex, it *will*

**Comment by polilla** [comment]
And i use this moment for say that uBlock is confused for the people.
Firefox AMO is now 0.9.1.0. You has Version 0.9.3.0 and more.
My Chromium-Browser under Linux updated from uBlock to uBlockO.
This is a totally chaos in my opinion.

**Comment by polilla** [comment]
I can understand Google. You put your uBlock with same code, same pictures, all is the same in Google. And now your are wondering why they kicked you?

**Comment by polilla** [comment]
All as is tu comunicate with the people befor you do anything. Not after.

**Comment by harshanvn** [comment]
@polilla Please try to stay on the topic.


> Firefox AMO is now 0.9.1.0. You has Version 0.9.3.0 and more.

This is nothing a uBlock Dev can do. It is the AMO process too slow.

> I can understand Google. You put your uBlock with same code, same pictures, all is the same in Google. And now your are wondering why they kicked you?

there is thread reg. this. Don't mix up the other things here.
https://github.com/gorhill/uBlock/issues/50

**Comment by polilla** [comment]
Sorry you are right. But AMO-process is now completed since yesterday.

**Comment by RandomAcronym** [comment]
>I can understand Google. You put your uBlock with same code, same pictures, all is the same in Google. And now your are wondering why they kicked you?

@polilla Google took the original uBlock off the CWS, not the one "put" up this month.

**Comment by older7** [comment]
Sorry for the off-topic, Lithuanian news portal blocks viewers with adblockers from their videos http://www.lrytas.lt/ Maybe there is a the solution for this problem or what? Thank you.

**Comment by lewisje** [comment]
For questions about issues with third-party lists (including "anti-adblock" because all it does is check whether certain stuff was loaded or hidden, websites can't directly detect ad-blocking extensions), go here, because we use the same filter lists that ABP does: https://adblockplus.org/forum/viewforum.php?f=2&sid=40a7bda4087df46e76988d185b384b7a

**Comment by older7** [comment]
So far helps me solve problems reek/anti-adblock-killer filter.

**Comment by lewisje** [comment]
Yes, that and the Adblock Warning Removal List should cover your bases well.

If you use Reek's filters, be sure to also install the associated UserScript, which makes sophisticated changes to certain anti-Adblock tools that filter-lists alone cannot: https://github.com/reek/anti-adblock-killer#step-3-userscript
