### ISSUE TITLE
Firefox: Icons in uBlock menu are broken by setting gfx.downloadable_fonts.enabled -> false

### ISSUE THREAD

**Issue by arni2033** [gorhill/uBlock#605]
![ublock](https://cloud.githubusercontent.com/assets/9205283/9306617/294c1db2-4502-11e5-9462-f93dc1528d39.png)

**Comment by gorhill** [comment]
uBlock uses font-based icons (part of the package), and setting `gfx.downloadable_fonts.enabled` to false will prevent uBlock from loading its own fonts, even though they are "downloaded" from the file system, not from a remote server.

This is why uBlock allows the blocking of all fonts, so you can let uBlock blocks font download rather than tell to browser to do it. One immediate advantage for letting uBlock blocks fonts is that this is done through a per-site switch, so one could chose to allow fonts from one site, even though fonts are blocked globally.

So I advise:

- Add the rule `no-remote-fonts: * true` in the _My rules_ pane in the dashboard.
    - This will globally block the downloading of remote fonts.
- Set `gfx.downloadable_fonts.enabled` to `true`.

You will get the same behavior as before, but uBlock's popup UI will display properly, and you now have the ability to allow fonts for specific web sites.

**Comment by CrisBRM** [comment]
@gorhill meant the other way around. 

````no-remote-fonts: * false````
````gfx.downloadable_fonts.enabled```` to ````true````

**Comment by gorhill** [comment]
Yes I meant `gfx.downloadable_fonts.enabled` to `true`, but `no-remote-fonts: * true` is the right way to block all fonts by default.

**Comment by CrisBRM** [comment]
OOps!

**Comment by RoxKilly** [comment]
@CrisBRM 
Just a heads up.  If you had `gfx.downloadable_fonts.enabled=false` to enhance your privacy (prevent font-based fingerprinting), you should be aware that this setting does not prevent that. Adding `no-remote-fonts: * true` to uBlock.O's settings doesn't either.  They both enhance your security since they block fonts downloading and execution, but they allow fingerprinting if JavaScript is enabled.  

To prevent font-based fingerprinting **even on sites that require JavaScript**, set `browser.display.use_document_fonts=0`.  Once you do this, sites will be unable to know which fonts you have on your system.  If you want to choose for yourself which font the browser will use, go to `about:preferences#content`, click `Advanced...` and on the popup, uncheck `Allow pages to choose their own fonts, instead of my selection above` (this will set `browser.display.use_document_fonts=0`).  

To test whether you're vulnerable to font fingerprinting, go to [Browser Leak's font test](http://www.browserleaks.com/fonts) and look under `Fonts via CSS + Javascript`.  If your fonts are listed, you're vulnerable (JavaScript required).

Note that even if you protect yourself this way, plugins such as Flash, Silverlight or Java could give away your fonts.

**Comment by kirill9000** [comment]
@RoxKilly
@gorhill 
But setting `browser.display.use_document_fonts=0` also breaks uBlock buttons. Why not just use images instead of font glyphs for controls?

**Comment by RoxKilly** [comment]
You're right. It's too bad.  I am concerned enough about fonts fingerprinting that I have `browser.display.use_document_fonts=0` and I use uBlock with broken fonts.  I set the variable temporarily to `1` when I just have to see the icons.

Maybe @gorhill opted for font-based icons to keep the package size small, or to make icon re-scaling work better (no pixelation issues).  It's really inconvenient to not see icons but the privacy gain is worth it in my opinion.  It would be helpful if at least tooltips showed what the buttons do when you hover the mouse over them, so that the add-on would be usable even when the icons do not display.

**Comment by gorhill** [comment]
In Firefox 41 `browser.display.use_document_fonts=0` [won't break font-based icons](http://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/).

**Comment by RoxKilly** [comment]
Thanks that's good news.

**Comment by kirill9000** [comment]
@gorhill But disabling gfx.downloadable_fonts.enabled will. Yes, we can use the dynamic filtering rule you've mentioned above, but could you please explain why you don't want to use PNG or SVG icons?

**Comment by gorhill** [comment]
http://www.leemunroe.com/icon-fonts/

**Comment by kirill9000** [comment]
I take it that fonts are easier to work with. Still, the developers of the fork have already converted font icons to SVG, so no extra work is required. You could just merge their changes: chrisaljoudi/uBlock#1181

**Comment by gorhill** [comment]
Except that each time you want to add/modify an icon, you are back to having to do dev work for this, which gnaw away at the advantages of using font-based icons.
