### ISSUE TITLE
Problem on Yahoo Search Pages

### ISSUE THREAD

**Issue by sfaisal2005** [gorhill/uBlock#621]
I've been facing this problem on Yahoo search pages. There are two issues -

1. <i>Anytime</i> menu below the search box doesn't function with uBlock Origin active. Unchecking EasyList makes it work. However it works fine with ABP+EasyList enabled. On Chrome, clicking on 'Anytime' opens a duplicate tab with a '#' added at the bottom of the URL.

2. Ad placeholders aren't properly hidden on Yahoo search pages and leaves empty space at the top of the page (see screenshot below). 

![2015-08-21 2](https://cloud.githubusercontent.com/assets/13907697/9415483/8b22e892-4861-11e5-89f1-fe63370f365b.png)

**Comment by lewisje** [comment]
My guess is that these problems are related to uBlock's support for strict blocking, which ABP intentionally does not do, and its method of hiding elements (something other than injecting a massive stylesheet, which is what ABP does).

**Comment by hotdogman** [comment]
In your picture, the advertisements aren't hidden at all with ABP enabled.
Try comparing again after updating your filters.

**Comment by sfaisal2005** [comment]
All filters were updated in both ABP and uBlock Origin. There were 4 ads. ABP blocked and hid 3 of them fully. One ad was being shown but that's ABP's issue. On the other hand, all 4 ads were partially hidden by uBlock Origin. The mentions of 'ad' and the star rating of the 4th ad weren't hidden. Besides, there was empty white space at the top which wasn't supposed to be there if the ads were properly hidden.

**Comment by gorhill** [comment]
> ABP blocked and hid 3 of them fully. One ad was being shown but that's ABP's issue.

I see many more not being blocked by ABP on my side -- abp left, uBlockO right:

![a](https://cloud.githubusercontent.com/assets/585534/9419956/7f2b3aea-482e-11e5-88bb-678b87ffc6bc.png)

In any case, I could reproduce your issue with uBlock, I will investigate.

**Comment by hotdogman** [comment]
I tried with a fresh profile, installed ABP/uBlock, looked at the logger, and I noticed this:
![dxb12k2pfu8y 1](https://cloud.githubusercontent.com/assets/4343306/9420129/df8c1ee2-4827-11e5-9a0a-25e8cc7cff02.png)
In EasyList, the only filters for `||yimg.com/zz/combo?` are exception filters.
`@@||l.yimg.com/zz/combo?*/advertising.$stylesheet
@@||yimg.com/zz/combo?*&*.js$domain=~search.yahoo.com`
In the screenshot, I saw `$domain=search.yahoo.com,important`, but it's weird that `,important` is listed, because it's a uBlock specific-extension, and it's listed nowhere in EasyList.

**Comment by sfaisal2005** [comment]
@gorhill You're right. There were more ads not blocked/hidden by ABP. uBlock Origin was able to block them but couldn't hide them properly. It's a minor annoyance but an annoyance nonetheless. I hope you'll be able to come up with a fix or workaround.

By the way, could you get the '<b>Anytime</b>' menu to work with uBlock Origin enabled (more specifically EasyList enabled)? That's the bigger issue for me. Coz without that I cannot trim the search result based on time (for now, I've whitelisted yahoo.com).

**Comment by gorhill** [comment]
> it's weird that `important` is listed, because it's a uBlock specific-extension

`important` is also used internally by uBlock, to decompose such filter as...

    @@||yimg.com/zz/combo?*&*.js$domain=~search.yahoo.com

into smaller filter units. It translates into:

"Do no block requests which URL matches `yimg.com/zz/combo?*&*.js` when **not** on `search.yahoo.com`, which is functionally equivalent to:

    ||yimg.com/zz/combo?*&*.js$domain=search.yahoo.com,important
    @@||yimg.com/zz/combo?*&*.js

**Comment by gorhill** [comment]
@sfaisal2005 I have come up with this cosmetic filter meanwhile, but I can't tell if it has bad side effect:

    search.yahoo.com###main > div > style + ol

For the _Anytime_ popup, I found out that ABP does **not** block the script from `https://s.yimg.com/zz/combo?pv/static/lib/srp-universal-header-uh3_201311011448...`. So I am going to have to research the filters to see other occurrences of using "negated" hostnames to understand how they are interpreted by ABP. So far it seems I extended the blocking realm to far for negated hostname.

Meanwhile as a work around, use this dynamic URL rule (it does **not** require to enable advanced user):

    search.yahoo.com https://s.yimg.com/zz/combo script allow

Cut and paste into the _My rules_ pane: click _Edit_ then paste, then _Save_, then _Commit_ if you want the rule to stick.

**Comment by gorhill** [comment]
I think EasyList manitainers should remove `@@||yimg.com/zz/combo?*&*.js$domain=~search.yahoo.com`, because this filter accomplishes nothing. It actually means

> do not block URLs matching `yimg.com/zz/combo?*&*.js`, except when on `search.yahoo.com`

Except that it's not blocked on `search.yahoo.com`, it appears that whatever block filter there were, it's gone, so there is no need to have an exception for `search.yahoo.com`.

**Comment by gorhill** [comment]
Related: <https://github.com/chrisaljoudi/uBlock/issues/191#issuecomment-53654024>.

**Comment by sfaisal2005** [comment]
@gorhill Thanks! Things are working fine now.

**Comment by gorhill** [comment]
Need to revise the code change here, the fix will need to be better thought than what I did here.

**Comment by ronjouch** [comment]
`<maybe off-topic>`
@gorhill, I just read the release notes and am not sure this fix is the source for the performance improvement, it just looked like a possible reason for it. Anyway, just wanted to report that `feedly.com` is much, much, faster after upgrading to 1.1.0.0 (stable, AMO). It used to be extremely sluggish on initial load and when refreshing my feeds, now it's smooth.
`</maybe off-topic>`

**Comment by gorhill** [comment]
@ronjouch 

I modified the description in the release notes:

>  I expect this is a marginal improvement (i.e. unnoticeable by any user)

If I execute the modified code in my head, I can picture the new code is quite probably **marginally better** performing than the old code, for the **very specific case** of filters with a long list of domain entities. In other word, unlikely that any user will ever notice any difference in performance. For the last benchmark I ran to time `onBeforeRequest` (pre-1.1.0.0), I got `< 180us` avg per `onBeforeRequest`, which means there was never an issue there. The comment in the release notes must be read strictly from a developer perspective, not from a "marketing" perspective.

So that you had performance issue with `feedly.com` is certainly completely unrelated to the fix here. You can confirm this by installing a pre-1.1.0.0 version of uBlock Origin and checking again.

**Comment by ronjouch** [comment]
@gorhill true! Sorry for the false report, must simply have been an improvement from feedly.com. Thanks again for your continued work on uBlock :)

**Comment by gorhill** [comment]
In any case I am running my `onBeforeRequest` benchmark, I will dump result in here for the record. From memory, last one I ran I got 178us per onBeforeRequest call -- can't remember if I dump the result somewhere.

**Comment by gorhill** [comment]
Further dev notes.

- uBlock Origin 1.1.0.0.
- Default settings (filter lists force-updated).
- Reference benchmark (1 cycle).

Result of time per onBeforeRequest call:

    µBlock> onBeforeRequest: 0.159 ms (8223 samples)
    µBlock> onBeforeRequest: 0.159 ms (8313 samples)
    µBlock> onBeforeRequest: 0.159 ms (8393 samples)
    µBlock> onBeforeRequest: 0.158 ms (8436 samples)
    µBlock> onBeforeRequest: 0.158 ms (8524 samples)
    µBlock> onBeforeRequest: 0.158 ms (8574 samples)
    µBlock> onBeforeRequest: 0.158 ms (8663 samples)
    µBlock> onBeforeRequest: 0.158 ms (8708 samples)
    µBlock> onBeforeRequest: 0.158 ms (8873 samples)
    µBlock> onBeforeRequest: 0.158 ms (8883 samples)
    µBlock> onBeforeRequest: 0.157 ms (8990 samples)

Looking in EasyList, the fix here affects 365 filter entries, out of ~48,000 entries -- everything else stays the same. An example of a web site for which there are filters with a `domain=` option with multiple hostnames: <http://alfonzorachel.com/> (see logger to see these filters being reported).
