### ISSUE TITLE
Custom filter: help please

### ISSUE THREAD

**Issue by lencc** [gorhill/uBlock#631]
I would like to add two universal cookie notification filter rules for Google in my custom list.
1.) Here is one for Google Translate: <code>###gb > .gb_[id]</code>
2.) And here is one for Google Maps: <code>###pushdown > .gb_[id]</code>

It looks like the first 4 characters are always the same (<code>.gb_</code>). Others change, for example:
<code>translate.google.com###gb > .gb_<strong>X.gb_wa.gb_Jb</strong></code> (for Google Translate)
<code>translate.google.com###gb > .gb_<strong>d.gb_2b.gb_Dc</strong></code>
<code>www.google.com###pushdown > .gb_<strong>g.gb_8b.gb_Nc</strong></code> (for Google Maps)

Problem: the upper two universal rules do not work. Cookie notifications are still appearing.
I have also tried <code>###gb > [id^=".gb"]</code> and <code>###pushdown > [id^=".gb"]</code> but they don't seem to work neither. Did I write something wrong?

**Comment by gorhill** [comment]
> the upper two universal rules do not work

Because `.gb_[id]` matches nothing, your CSS rule is improperly crafted given what you want to accomplish.

Try `#gb > [class^="gb_"]`.

Also, take note that the issue tracker here is **only** for issues with uBlock Origin, it should not be used as a help desk. I will have to become more hardcore if my goodwill to help keep being abused through the opening of non-issues on GitHub -- each time I help someone with such non-issue, it sends the message to others that they can also do so. There are other places for such help, try Reddit, Wilders Security, anywhere else really.

**Comment by lencc** [comment]
Thank you for information. I didn't know for Wilders Securtiy forum. I will contact them (or Reddit) in the future.

**Comment by gorhill** [comment]
Another trick useful in your case: use the element picker to validate whether a cosmetic filter works or not: uBlock will highlight whatever on the page matches the filter in the text field. So if you cut and paste `#gb > .gb_[id]` in the text field of the element picker while on the page <https://translate.google.com>, uBlock would have highlighted nothing, meaning your cosmetic filter was not working. Entering `#gb > [class^="gb_"]` would have highlighted the element you were trying to remove (and maybe other things on the page -- I did not try it).

**Comment by lencc** [comment]
Great! I thought the text field didn't have option to manually enter and test different rule variations. Very useful indeed.

**Comment by gorhill** [comment]
Just in case, do not enter the prefix for the site when you test for a filter (i.e. `translate.google.com`), uBlock will always use the current site internally. In short:

- `###gb > [class^="gb_"]` = good
- `translate.google.com###gb > [class^="gb_"]` = bad, will be rejected as not a valid filter
