### ISSUE TITLE
Questions about dynamic filtering whitelisting

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#632]
I have dynamic filtering turned on with these rules:
```
* * 3p block
* * 3p-frame block
* * 3p-script block
```
Let's say I go to https://jsfiddle.net/ (or any site really) that can requests a lot of different let's say images from different places. Is there a way to whitelist this site to noop all images from any destination?
I tried the obvious: `jsfiddle.net * image noop` and `fiddle.jshell.net * image noop` but ublock doesn't seem to accept these as a valid rules. Is there any way to noop all images per specified site.

Second question I have has to do with its converse `* code.jquery.com 3p-script noop`, this is to allow any site from accesing third party scripts from code.jquery.com but that also doesn't work. Is there any way to add these type of whitelist rules?

**Comment by Piter432** [comment]
There was a `3rd-party passive` option called in uBlock Origin `3rd-party css/images` but @gorhill removed it, because it can be done by setting `noop` rule to 3p, but on `local` (current site/domain) instead of `global` (all sites and domains). Looks like that removing this option was crappy idea, ha, ha :)

**Comment by gorhill** [comment]
> Is there a way to whitelist this site to noop all images from any destination?

Why not just `jsfiddle.net * * noop`?

uBlock does not support rules such as `fiddle.jshell.net * image noop` or `* code.jquery.com 3p-script noop` -- see [rules precedence](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence) and
[rule syntax](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax).

For anything with higher granularity, there is [uMatrix](https://github.com/gorhill/uMatrix).

@Piter432 `3p-passive` would make absolutely no difference here.

**Comment by Piter432** [comment]
@gorhill `3p-passive` makes HUGE difference when setting this rule especially as `allow` in `global` instead of `local` (I think setting as `noop` in `global` not always will display some pages properly, because of some filters list if someone has many of them) or `allow`/`noop` domain/website in `local` or `global`..

**Comment by vzjrz** [comment]
From what I'm seeing of umatrix, ublock's dynamic filtering would need to be turned off if I want to use them in conjunction or am I wrong? It would be ublock for list blocking and umatrix for dynamic per site filtering right? Now I just need to wrap my head around this umatrix interface.

**Comment by gorhill** [comment]
Corrected: `jsfiddle.net * 3p noop`, not `jsfiddle.net * * noop`. This will let images from anywhere thru when on `jsfiddle.net`.

**Comment by vzjrz** [comment]
Wow umatrix is amazing! Absolutely what I was looking for thanks!
