### ISSUE TITLE
Not displaying all gui

### ISSUE THREAD

**Issue by vasili111** [gorhill/uBlock#648]
I am using Chrome version.
When I press on the icon of uBlock Origin I dont have the part of GUI that is in red square on the image below:
![](http://i.imgur.com/yHoyZqf.png)

How to enable that part of GUI?

**Comment by harshanvn** [comment]
have you checked "i am an advanced user" option in uBlock settings?

A quick guide about dynamic filtering..https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by luxoflux** [comment]
Click on the black bar that says uBlock Origin + version info, then tick _I am an advanced user_ (and check out _Required reading_ next to that). Since you appear to be new to this, I would also suggest studying the [Wiki](https://github.com/gorhill/uBlock/wiki), especially on dynamic filtering, which is what you are trying to enable.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki>.
