### ISSUE TITLE
feature request: click to load domains

### ISSUE THREAD

**Issue by atomGit** [gorhill/uBlock#65]
please consider adding the ability to open URIs in the list by clicking (or middle clicking) them, similar to the NoScript functionality - this would be helpful when one does not know what a 3rd party domain is being used for

**Comment by gorhill** [comment]
Use the request log, that's what it's there for.

**Comment by atomGit** [comment]
where is the request log?

**Comment by tlu1024** [comment]
@atomGit 

Just have a look in the [wiki](https://github.com/gorhill/uBlock/wiki/The-network-request-logger).

**Comment by tlu1024** [comment]
@gorhill 
In the wiki the name of the icon should be updated. (I have no write permission.)

**Comment by tlu1024** [comment]
@gorhill 

BTW, I think that @atomGit was talking about something like [this](https://github.com/gorhill/httpswitchboard/issues/106) issue.

**Comment by gorhill** [comment]
> something like this issue

I removed that feature from uMatrix. I put this feature in HTTPSB more because of pressure to do so than because I agreed with it. I regretted to have put it in, so it's not back in uMatrix.

I don't want uBlock/uMatrix to relay some third-party says about a web site. Web of Trust has it's own extension to do so, and uBlock/uMatrix should not cater to Web of Trust specifically. When you install Web of Trust's own extension, you are leaking to them your browsing history. Maybe they can completely be trusted etc., but regardless, this goes counter to what I want uBlock/uMatrix to be.

**Comment by tlu1024** [comment]
Completely understood. I was just trying to clarify @atomGit 's request.

**Comment by gorhill** [comment]
You're right, I read too quickly (again).

**Comment by atomGit** [comment]
"I don't want uBlock/uMatrix to relay what some third-party says about a web site. Web of Trust has it's own extension ..."

i absolutely agree -- and in my opinion WoT is garbage as most average surfers are in no position to rate the security of a site (plus i see good sites which get down-voted because some group has a problem with the content)

what i was suggesting is more simple, and that is to simply to load the actual sites in the list by clicking on them

**Comment by gorhill** [comment]
Well with the Chromium version of uBlock, it's simply a matter of selecting the hostname and opening it in a new tab using the context menu. This doesn't work on Firefox, maybe this will change eventually.
