### ISSUE TITLE
Instagram "Click to Remove Ads" javascript bypassing filters

### ISSUE THREAD

**Issue by FrenchCuff** [gorhill/uBlock#651]
There is a first-party JavaScript element on Instagram (ink361.com) which bypasses UBO filters. ABP was successful in blocking this element: javascript:ui.removeAds()

See here for example: http://ink361.com/app/users/ig-374366141/lunathetoona/photos

Browser: Firefox 40.0.2
Plugin version: uBlock Origin 1.0.0.1
OS: Windows 10

You can "cosmetically" block these elements, but the element continues to appear throughout the page. You can only hide the element by playing whack-a-mole, one at a time. Again, ABP was successful in fully blocking this first-party script without breaking the page.

**Comment by gorhill** [comment]
I will use this test case to validate some longer term fix I wrote locally that I plan to maybe release for the next version.

Meanwhile, try this custom filter:

    ink361.com##.getridofAdsBlock[href^="javascript:"]

I will add it to uBlock filters until the longer term fix become part of uBlock.

**Comment by FrenchCuff** [comment]
Thank you, that custom filter successfully blocked the elements across the page. Very glad to hear that the fix will likely make it into the next release.

**Comment by gorhill** [comment]
On second thought, not sure the experimental code will be added (efficiency is top priority). The filter solution here is good enough really, and is necessary in the current case because filters in EasyList are created with ABP in mind, and in some cases they are not optimal for uBlock -- ABP and uBlock works differently. The reverse is also true, there are filters which work best in uBlock than ABP.

This is such a case here, easily fixed with a filter optimized for uBlock -- it was just a matter of augmenting the specificity of the CSS rule.

**Comment by gorhill** [comment]
Fixed with 3dd19b7708f4b4c8889e34891fc10e81bf429a92.
