### ISSUE TITLE
Injected CSS selectors are getting saved along with pages

### ISSUE THREAD

**Issue by asl97** [gorhill/uBlock#660]
1. open https://github.com/gorhill/uBlock/issues/315 in a tab in chrome
2. click the `Customize and control Google Chrome` button (the one that look like three bar)
3. click `Save page as...`
4. click `Save`
5. open the downloaded file which should be named `Easy List Inserting Ad and Porn Links · Issue #315 · gorhill_uBlock.html` (by clicking the download bar button thing or through a file browser) in a text editor.
6. see those `CSS selectors` in the file

iirc, stuff in the shadow DOM doesn't get save with the pages so those CSS selectors and other stuff should go in there.

if i am wrong about the shadow DOM or if this is already fix in DEV, just say it instead of [locking without saying anything, it is just plain old rude](https://github.com/gorhill/uBlock/issues/315).

____

quote in reply to `why not put the style in a shadow root?` from https://github.com/chrisaljoudi/uBlock/issues/161#issuecomment-58558623:
`Open an issue, I will look into this in more details, I would want to check first cost or benefit mem and cpu-wise, if any.` from https://github.com/chrisaljoudi/uBlock/issues/161#issuecomment-58559190 by @gorhill

related:
https://github.com/gorhill/uBlock/issues/315

____

uBlock v1.0.0.1
Chrome 42.0.2311.135 (64-bit)
Linux Fedora 21 LXDE spin with XFCE Desktop Manager + Gnome and KDE Service running

list of extension:
User-Agent Switcher for Chrome 1.0.43
Unlimited Free VPN - betternet 2.2.1 (not running/connected)
Search by Image (by Google) 1.5.1
Image Size Info 1.7.7
Hyperlink Text Selector 1.3

^ those should be more than enough to comply with the CONTRIBUTING.md

ps: i have waited for more than an hour with no reply on the locked issue so i am making this.

**Comment by gorhill** [comment]
> instead of locking without saying anything, it is just plain old rude.

At this point I consider keeping bringing up the issue is noise, this won't be debated endlessly.

Now regarding your specific repro steps: I cannot reproduce. Inspecting the DOM, I see that uBlock inserted exactly **zero** CSS rules in the page you refer to.

But then, even if you come up with a scenario which I can reproduce, this is expected: any extension -- be it uBlock Origin or any other (try [Hacker News Collapsible Comments](https://chrome.google.com/webstore/detail/hacker-news-collapsible-c/hockhafcdegocajmjhafgjncjpodihkd)) --  which tampers with the DOM will obviously **cause the DOM to be tampered**: uBlock Origin does not make any claim anywhere that it won't tamper with the DOM to accomplish its purpose -- so there is no issue.

In case you feel like using ABP as reference, even Adblock Plus will modify the DOM and causes these modifications to be part of a locally saved HTML page -- collapsed placeholders will all have the `display: none !important;` style, something not in the original source.

**Comment by asl97** [comment]
it was there when i posted the comment, it must have been the cache or something....
____
at least you stated your reason for locking it.
even if i don't agree that it isn't an issue, i will respect your decision.
i just have to look else where.

i am going to unsubscribe from this issue, CC me using @asl97 if you need me.
____
ps: injecting `display: none !important;` doesn't matter much for most people while injecting `porn` is another story.
i highly doubt ABP or other blocker which tampers with the DOM would inject the word `porn` though.

**Comment by gorhill** [comment]
> i highly doubt ABP or other blocker which tampers with the DOM would inject the word porn though

Of course ABP injects "porn" in the DOM, it injects **all** CSS rules found in EasyList and whatever other lists is enabled.
