### ISSUE TITLE
Ublock blocking comment-sections

### ISSUE THREAD

**Issue by GoodTimesAhead** [gorhill/uBlock#661]
I'm having problems with ublock blocking the comments on some pages. Some are discuss some are facebook. I'm using EasyList, EasyPrivacy, Malware domains, Fanboy's Annoyance and social blocking list. Here are two examples of ublock blocking comments.

http://robhasawebsite.com/big-brother-2015-august-28-bb17-live-feed-highlights/
http://www.huffingtonpost.gr/2015/08/29/politiki-symfonia-diapragmatefsi-_n_8057976.html?utm_hp_ref=greece#comments

**Comment by gorhill** [comment]
3rd-party filter list issue, bring the issue to the maintainers of these 3rd-party filter lists. For exmaple, 1st link, the comments are hidden because of EasyList's cosmetic filter `##.ad_container`. Toggle [cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-cosmetic-filtering) for the site and the comments will appear.
