### ISSUE TITLE
Add custom rules in question

### ISSUE THREAD

**Issue by potkeys2** [gorhill/uBlock#668]
Custom rules can not add https://easylist-downloads.adblockplus.org/fanboy-social.txt rules add no response. There is hope from the rule definition can be automatically updated to add

**Comment by gorhill** [comment]
You do not need to import `https://easylist-downloads.adblockplus.org/fanboy-social.txt`, it is already present in the stock filter lists:

![a](https://cloud.githubusercontent.com/assets/585534/9581052/1e9e81f6-4fcb-11e5-99b1-2238203ab3bb.png)

Just select it, click _Apply changes_.

**Comment by gorhill** [comment]
> But I do not want to use the built-in rules

They are not built-in rules, they are built-in filter lists. Their content is downloaded just like if they were custom filter lists.

> the first three rules can be customized

- `https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt` and `https://easylist-downloads.adblockplus.org/malwaredomains_full.txt ` are not part of stock filter lists, so yes you can import as custom filter lists.
- `https://easylist-downloads.adblockplus.org/easyprivacy.txt` is part of stock filter lists, so it's completely pointless to import as custom filter list. The fact that you can import it is because this particular filter list is shipped with the package. Nonetheless, it will be downloaded from the remote server, so you will always have an up to date version.

**Comment by gorhill** [comment]
The fix might be a bit too late, but it is still useful if ever an older backup is restored.

**Comment by yuan18** [comment]
Custom rules can not add 

https://easylist-downloads.adblockplus.org/easylistchina.txt
https://easylist-downloads.adblockplus.org/fanboy-social.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

**Comment by IDKwhattoputhere** [comment]
First of all those are filter lists, not rules. Secondly they can be selected in the settings. There's no need to add them as custom filter lists.
![](https://cloud.githubusercontent.com/assets/16030872/13524239/565ec45e-e1fa-11e5-897b-a4eb63fe7612.png)
