### ISSUE TITLE
Allow rules based on Base64-decoded urls

### ISSUE THREAD

**Issue by Baldrs** [gorhill/uBlock#679]
Having the following url: http://n25.filecdn.to/ff/fHx8fDR8fHx8fHx8fDc1MTM4MDk4OTMyNTF8fGh0dHA6Ly91YTJjZG4uYWRtaXhlci5uZXQvdGVzdDEvZjUyZTI1YmEtZmJmMy00Y2Q3LTk1ZjUtODczMjljZDBlY2U2LzI2ZDdkMTc3LTk1NzgtNDczYS1iOTY5LWE0ZmNlMTM5Nzk1NS5tcDQ,/play_9iore9pckk8lorzez7h0ny21b.5.7156427754.5538140077.3774421348.mp4

It contanins that long base64-encoded part, that has some AD identifiers and uris that possibly can be used to block such urls:
||||4||||||||7513809893251||http://ua2cdn.admixer.net/test1/f52e25ba-fbf3-4cd7-95f5-87329cd0ece6/26d7d177-9578-473a-b969-a4fce1397955.mp4

This video uris are just an example, as they are using this technique to display ads via player.js param too.

Can you please add some feature to define decoding rules of such urls and allow to block whose that match?

**Comment by gorhill** [comment]
The request here is a huge threat to efficiency. The overhead of scanning a URL, then to scan again to detect and decode base64 -- with possibly a lot of false positives (base64 is just a bunch of alphanum characters), would be way too much, and for possibly no real benefit.

Consider that if a site care to work around a blocker (in the current case using base64 encoding), then they will care to further work around using whatever custom encoding they can muster once their base64 encoding is defeated. All this at the cost of crippling significantly the efficiency of a pattern-based filtering engine.

I don't want to be given a URL without any context and be asked to implement something -- that is not how this work. Give me a **real** case withing its whole context, and I will give you my opinion about what is the best approach.

**Comment by RoxKilly** [comment]
This is tangential, but how does the browser know where to go fetch the resource?  In other words, if my video is at url1 and the browser and filter see url2, how will the browser know to go to url1 for the video?

If there is a redirection happening on the server side, then blocking url2 becomes a waste of time because there will be a url3, 4... that can be developed just as easily. The server side script will know how to decipher all these urls and return the original video.  This is why we can see seemingly randomly generated URLs for the same resources.

**Comment by Baldrs** [comment]
Nope, no redirection on server, they just load the ads inside their CDN, and the advertisement origin is inside the encoded parameter.

**Comment by gorhill** [comment]
You keep **not** providing a real case.
