### ISSUE TITLE
advanced window no where to be found

### ISSUE THREAD

**Issue by silat** [gorhill/uBlock#685]
When I click the uB icon (chrome) the advanced window does not appear anymore. Also the tab 3rd party filters is empty except for the custom box being visible.  
I did a complete clean reinstall of Chrome and reinstalled uB v1.1.
And yes advanced is checked in options. 
Any suggestions?

**Comment by gorhill** [comment]
It's as if javascript is not running for the extension. When you open the dashboard/3rd-party filters, are there any error at the developer console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>i</kbd>)?

**Comment by JeffBuckles** [comment]
I have the same problem since I upgraded to firefox from 40.0.3 to 41.0.1 and did a "Firefox reset".   (Windows 7, ublock origin v1.1.1).   No errors in the console.  I confirmed in ublock0.sqlite that 'advancedUserEnabled' is 'true', and the tooltips stop appearing.   Only the dynamic filtering pane does not appear.

Just discovered that  'dynamicFilteringEnabled' is 'false' in ublock0.sqlite settings.    I cannot find anything in the dashboard or popup that obviously changes this setting.   Any suggestions (other than forcibly changing it with something like SQlite Manager)?  

Thanks and Best Regards,
--

**Comment by gorhill** [comment]
The `dynamicFilteringEnabled` setting is toggled when you click the "expanders" (see below) in the popup UI. Are you saying these "expanders" do not work anymore?

![a](https://cloud.githubusercontent.com/assets/585534/10293394/3eb25aee-6b82-11e5-855f-60aef7d00ec2.png)

**Comment by JeffBuckles** [comment]
Aha!   That works.   I did not see anything about the "expanders" in the "required reading".  The illustrations show it already expanded.   Of course now I notice the "+" appears when Advanced mode is enabled.
Thanks for the help!

**Comment by JeffBuckles** [comment]
Regarding this:
"Dynamic filtering engine is completely turned off when you un-check the setting "I am an advanced user". Your dynamic filtering rules are kept intact though, in case you re-enable advanced user mode again."

While "Advanced user" remains enabled, does the state of the pop-up expansion have any effect on the dynamic filtering engine?

**Comment by gorhill** [comment]
> does the state of the pop-up expansion have any effect on the dynamic filtering engine?

No.

**Comment by JeffBuckles** [comment]
Thanks for the quick replies!

**Comment by dungsaga** [comment]
I updated the wiki (https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) to mention that the dynamic filtering pane can be toggle by clicking on `requests blocked` or `domains connected`.
