### ISSUE TITLE
[Non-Issue/Info] Adblock Edge to be discontinued, dev directs users to uBlock.

### ISSUE THREAD

**Issue by RandomAcronym** [gorhill/uBlock#70]
[Link to AMO.](https://addons.mozilla.org/en-US/firefox/addon/adblock-edge/)

> This addon will be discontinued on June 2015
> Reason: Discontinued in favor of uBlock, a general purpose blocker, that not only outperforms Adblock Edge but is also available on other browsers and, of course, without "Acceptable Ads Whitelist".

Just FYI.

**Comment by mewblock** [comment]
You forgot to add related links.

https://bitbucket.org/adstomper/adblockedge/issue/197
https://bitbucket.org/adstomper/adblockedge/issue/78#comment-16982117

**Comment by gorhill** [comment]
I was looking at that [NoMercy's Guide for uBlock](http://pie.estiva.org:1223/data/proj/sw/nomercy_ublock.html), and for that kind of level of blocking, it would be much simpler to just advise users to turn on _"I am an advanced user"_, then globally block 3rd-party requests (aka default-deny for all 3rd-parties).

This would result in an even more merciless configuration, users would be able to un-break through point-and-clicking if they care to un-break, and even when un-breaking, the page would still have to go through static filtering (default filter lists is stricter than ABP + EasyLIst + EasyPrivacy).

**Comment by lewisje** [comment]
I can't get that guide to load, and it has only been 22 minutes.

**Comment by mewblock** [comment]
@lewisje
NoMercy also providing Hidden service; this should work for ya.
http://ny44ts3j7jkd5gqf.onion:1223/data/proj/sw/adblock.html

**Comment by RandomAcronym** [comment]
@lewisje that link only works with Tor

**Comment by lewisje** [comment]
"pie.estiva.org" is a clearnet domain and that's the domain that the link posted by @gorhill uses; I'll try the link posted by @mewblock when I load the Tor Browser Bundle.

**Comment by gwarser** [comment]
https://archive.today/zOuvg

**Comment by lewisje** [comment]
I almost forgot, those are the idiots who think any and all whitelists are "unnecessary" instead of being workarounds for false positives (especially in gorhill's case, for false positives *in other lists*, which he does not directly control); I hold the "NoMercy" forks of EasyList and some other lists in almost as much contempt as the "Adblock Edge" wankers, and I agree that gorhill's solution is better for those who really want to get rid of third-party whitelists *and know what they're doing*.

Now I'm not sure why that site was refusing to send anything to me; surely it can't be because I run a non-exit Tor node, because I would think the operator of a Hidden Service would be friendlier to node operators than that.
