### ISSUE TITLE
uBlock makes Firefox crash on ubuntu

### ISSUE THREAD

**Issue by l3v147h4n113** [gorhill/uBlock#704]
Hi,
Earlier this week my Firefox 40.0.3 on Ubuntu 14.04.3 started crashing very frequently, (every 3-4 mins). I reported to Mozilla and uBlock was found to be the problem, it's says so in the crash report.

Firefox 40.0.3 Crash Report [@ libxul.so@0x21ea133 | uBlock0@raymondhill.net.xpi@0x55883 .

The weird thing is it will still crash even in safe mode with all extensions ( including uBlock ) disabled.
I had to completely uninstall uBlock to solve the problem.

You can see the full report here https://crash-stats.mozilla.com/report/index/42821458-a2b2-4b8d-8f28-72a622150911

Thanks.

**Comment by gorhill** [comment]
uBlock is written in javascript, javascript does not crash. If the browser crashes while interpreting javascript, there is an issue with the browser.

**Comment by l3v147h4n113** [comment]
Thank you for your answer.

**Comment by gitarra** [comment]
Based on that crash report you are the only one experiencing this crash. Its probably a problem with your installation but you can always file a bug on Bugzilla.mozilla.org if you think its an issue with Firefox.

**Comment by gorhill** [comment]
From where did you install your FF 40.0.3?

**Comment by l3v147h4n113** [comment]
Directely from ubuntu repos.
Reinstalled twice still same problem.

**Comment by gorhill** [comment]
I've spotted a couple of [instances of Firefox crashing on Ubuntu](https://www.google.com/search?q=firefox+ubuntu+crash+libxul&tbs=qdr:y). Maybe you can find better help there.

I saw the moderator responding to you that this is a uBlock issue. That's a pretty crappy answer: uBlock is an extension, written in pure javascript, and to dismiss a full browser crash because supposedly a javascript extension is the cause is irresponsible -- browser crash should always be investigated, not dismissed like it was done in your case.

**Comment by l3v147h4n113** [comment]
After giving it a though, it's true. What I saw precisely is that the cause of the crash is the libxul.so library. Maybe Firefox makes use of it to interpret UBlock or something. I don't have that deep knowledge to go deeper in the cause of the crash. 
I was just trying to be helpful.
Thanks for your answer, I'll get back to Mozilla for further investigation.

**Comment by gorhill** [comment]
Meanwhile you could always add your own crash lniks to <https://bugzilla.mozilla.org/show_bug.cgi?id=1198805> I suppose.
