### ISSUE TITLE
What is your guideline for whitelisting?

### ISSUE THREAD

**Issue by mewblock** [gorhill/uBlock#71]
I want you to unblock my ads.

Where is this text file? I will make a pull request.
chrome://ublock/content/asset-viewer.html?url=assets/ublock/filters.txt

**Comment by crisalis** [comment]
The way you put it, it's like you think those filters serve as some kind of whitelist for "acceptable ads". That's not their purpose. They're there to unbreak sites that don't work otherwise.

When I encounter any such site which is negligently or deliberately making itself break if ads aren't show, I do not visit it anymore. This is just my opinion and it isn't related to the uBlock project.
