### ISSUE TITLE
Default Window Size Tor Browser Bundle

### ISSUE THREAD

**Issue by BobBBob** [gorhill/uBlock#714]
When I install uBlock Origin and uMatrix, the default window size of the Tor Browser Bundle is changed. I am using Linux Mint on the latest TBB version on uBlock 1.1.0.1. This is a problem because your screen resolution can be used to track you if it is not the default. I know, I know, I'm not supposed to Install addons to Tor, but I couldn't help myself.

**Comment by one23** [comment]
This is likely because uMatrix uses a 19px icon (as opposed to 16px default in Firefox) which then increases the entire toolbar height.  Perhaps a issue should be filed for this for uMatrix?

**Comment by gorhill** [comment]
With Tor 5.0.4, I don't see uBlock/uMatrix affecting the window size.

**Comment by bendover22** [comment]
Sorry - this is a year old (I can file new issue, if want).
In last few Tor Browser - TBB - versions, still in TBB 6.0.6, 6.0.7 - uBlocko is definitely affecting the default screen size on startup.  Disable uBo and the issue goes away.  Re-enable it & issue returns.  Haven't used uBo that long in TBB.  Issue began immediately on installing uBo 1.9.16, updated to 1.10. 

Also disabled all other default extensions except uBo - same issue.  uBlocko is the only non-standard addon installed.

Perhaps this depends on specific user prefs choices - ones generally accepted as OK to change?
Like the security level slider setting - under Tor Button (green onion) > Privacy & Security Settings.
Or whether NoScript is set to block all scripts, instead of the default to allow all scripts?

When 1st start TBB, the overall height is much taller than the standard size set by TBB.  Probably a couple inches or more taller.  Screen Width seems the same.  I did check dimensions w/ screen capture prgm, & at a couple of fingerprinting test sites.
After opening TBB, if select "New Identity" from the TBB onion button, it restarts at the correct default screen size - every time.  Which is really odd.
