### ISSUE TITLE
uBlock Origin blocking 3D Secure/Verified by Visa/Mastercard Securecode

### ISSUE THREAD

**Issue by alabrand** [gorhill/uBlock#720]
uBlock Origin Safetycopy: http://pastebin.com/6zawnP29

Hey, uBlock Origin is blocking the information displayed in the square that shows up when trying to pay with 3D Secure/Verified by Visa/Mastercard Securecode. At first I thought something was up with my bank account but it turns out disabling uBlock Origin solves this issue. Do you know what is causing this? Is it a filter? Is it a blocking function built into uBlock Origin?

**Comment by gorhill** [comment]
> Do you know what is causing this?

Use the [logger](https://github.com/gorhill/uBlock/wiki/The-logger), it will tell you what is causing this. It's obviously not something I can reproduce, that would require me to buy something with a VISA card. Just use the logger and report your findings. Disabling uBlock for such specific case is a proper workaround, that's why whitelisting exist in the first place.
