### ISSUE TITLE
Loading mahakala.is host file.

### ISSUE THREAD

**Issue by Zegnat** [gorhill/uBlock#724]
I tried to load in the host files used by [Pi-Hole](http://pi-hole.net/), this includes `adblock.mahakala.is`. After a long time loading uBlock₀ just reports it as “0 used out of 0” and “out of date”. Would there be any way to load this (frankly, huge) hosts list into uBlock Origin?

**Comment by hotdogman** [comment]
```
$ wget adblock.mahakala.is -U Mozilla
--2015-09-19 19:27:53--  http://adblock.mahakala.is/
Resolving adblock.mahakala.is (adblock.mahakala.is)... 93.95.225.235
Connecting to adblock.mahakala.is (adblock.mahakala.is)|93.95.225.235|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47453390 (45M) [application/octet-stream]
Saving to: ‘index.html’

index.html                                       100%[=========================================================================================================>]  45.25M   372KB/s   in 76s    

2015-09-19 19:29:09 (609 KB/s) - ‘index.html’ saved [47453390/47453390]
```
https://github.com/gorhill/uBlock/blob/master/src/js/assets.js#L285-L330

xhr.timeout = 30000 is set to 30000 ms, or 30s

It takes longer than 30s to download the entire file, unless you have a fast internet connection.

**Comment by Zegnat** [comment]
Cheers, now I know! Didn’t think to check for a build in time-out, that’s on me.

For whatever reason it seems that uBlock (for Firefox) doesn’t report on this happening though. It happily put a checked the box in front of the entry and displayed “0 used out of 0” rather than the expected “out of ?” for unloaded lists. Possible bug (or lack of implementation) on the error reporting to the user there?

**Comment by gorhill** [comment]
It's reported in the extension console (Chromium) or browser console (Firefox). There is an open issue somewhere for uBlock related to this, the error needs to propagate to the user. In any case, having uuMatrix/uBlock download huge file is discouraged. Somewhere in the wiki I advise to download through other mean locally, and supply uMatrix/uBlock a URL to that local location. Firefox accepts `file://` URL last time I checked. Otherwise a local HTTP server for just this purpose should work fine.

What I could do is to have a local config setting to tamper with the timeout value, so that users could set their own value. Not something I would expose through the UI though, that would be too risky to have novice users play with this, could easily break uMatrix/uBlock.

**Comment by Zegnat** [comment]
> It's reported in the extension console (Chromium) or browser console (Firefox). There is an open issue somewhere for uBlock related to this, the error needs to propagate to the user.

If there already is an issue, then we’ll close this.

> Somewhere in the wiki I advise to download through other mean locally, and supply uMatrix/uBlock a URL to that local location.

Yep, [it is here](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web#large-lists-too-large-for-remote-subscription), and I have no idea how I missed it.

My apologies for the oversight.
