### ISSUE TITLE
Minimize page startup cost

### ISSUE THREAD

**Issue by paulirish** [gorhill/uBlock#728]
The content script injection at document_start has some fairly sizable cost associated. 50ms on my modern MacBook Air.

![image](https://cloud.githubusercontent.com/assets/39191/10000467/1f873c98-6051-11e5-9682-0ea19512044c.png)

To be fair, it appears the cost is actually all the extension subsystem.  Nearly all cost is once `chrome.runtime.connect({name: vAPI.sessionId})` is called. 

Is there any opportunity to 1) avoid the content script injection or 2) avoid this runtime.connect call under certain circumstances?

**Comment by gorhill** [comment]
> Is there any opportunity to 1) avoid the content script injection

The content scripts are injected declaratively through `manifest.json`. The only time I can think content scripts are not needed is when a site is whitelisted, otherwise the content scripts are needed to find out if and what cosmetic filtering needs to apply + whether the DOM counterpart of whatever network request needs to be collapsed.

On my desktop i5 I get under 20 ms for `vAPI.messaging.setup`. My understanding from reading the [API doc](https://developer.chrome.com/extensions/content_scripts#host-page-communication) is that ports (`chrome.runtime.connect`) should be used whenever there is a chance for a lot of back-and-forth messaging.

**Comment by gorhill** [comment]
I stepped into Chrome API code, specifically `Binding.generate`, and I see `forEach` being used a lot (including `forEach` within `forEach`), and my understanding of `forEach` is that it is quite sub-optimal. I would be curious to see this code profiled against just using plain vanilla loops.

**Comment by gorhill** [comment]
Marking as browser bug: <https://bugs.chromium.org/p/chromium/issues/detail?id=653596>.
