### ISSUE TITLE
Problem with cloud storage

### ISSUE THREAD

**Issue by Krysisx** [gorhill/uBlock#729]
Hi,

I have installed ublock on both my 2 computers.
I have logged in my firefox sync account on both computer.
From the first one (device name `A`) I have export to cloud storage all my ublock settings (filter, rules etc...), from the other one (device name `B`) I have tried to import the settings I have exported from `A`, but it does not work.
I have taken a look to console while trying to import and it says (I have translated it from my browser language): 
`Security Error: Content at moz-nullprincipal: {.......} may not load or link to chrome://ublock0/content/1p-filters.html.`

Am I doing anything wrong?
Do I have to enable anything from firefox sync? Like preferences or addons sync?
I have Firefox 40.0.3 and Linux Mint x64 on both my computers.

**Comment by gorhill** [comment]
You need to check "Add-ons" in Sync preferences.

**Comment by Krysisx** [comment]
Ok I tried that. I have checked "Add-ons" in Sync and I have exported again from computer `A`, after that I went to computer `B`, checked "Add-ons" and tried to import, but it did not import anything.
Do I have to have the same device name or Sync account name?

**Comment by gorhill** [comment]
> Sync account name

I am pretty sure this is necessary. Once you send something to the cloud, you have first to be sure that Firefox actually did actually send it to its servers, and one the other side, you have to be sure Firefox did actually pull from the cloud first. You can force Sync up to date by clicking the Sync button on both side, after you export on one side, and before you import on the other side. Normally the Sync operation is performed by Firefox at launch time, otherwise I am not sure what triggers it.

**Comment by Krysisx** [comment]
Sorry I actually have the same `Sync account` on both computers. What is different is the `Device name` but I think that it's not necessary to have it the same on the 2 machines.
I'll try the steps you said and I'll tell you the result.

**Comment by Krysisx** [comment]
> You can force Sync up to date by clicking the Sync button on both side, after you export on one side, > and before you import on the other side.
Ok, it still does not work.

**Comment by gorhill** [comment]
Are you blocking `behind-the-scene` network requests? I verified and it works fine here.

**Comment by Krysisx** [comment]
I don't think I am. How can I verify whether I'm blocking network requests?

**Comment by gorhill** [comment]
> How can I verify whether I'm blocking network requests?

Logger.

**Comment by Krysisx** [comment]
Ok I opened uMatrix and uBlock logger while exporting to cloud, but I saw nothing.

**Comment by Krysisx** [comment]
Could you please try to install `uMatrix`, `uBlock` and `random-agent-spoofer` (https://github.com/dillbyrne/random-agent-spoofer) and then try the Sync again?
I have these settings in uMatrix: https://i.imgur.com/TeOJsXy.png and `matrix-off: behind-the-scene true` and these settings in `random-agent-spoofer`: 
http://s7.postimg.org/wwbpqed7f/Istantanea_2015_09_29_08_40_46.png
http://s7.postimg.org/nptf347yz/Istantanea_2015_09_29_08_41_11.png
http://s7.postimg.org/azts3rpej/Istantanea_2015_09_29_08_41_25.png

**Comment by vanowm** [comment]
I'm also unable sync between two computers. Add-ons and preferences enabled in Firefox sync, but uBlock doesn't see cloud saves from computer A on computer B and vise versa.
Setting up the same device name on both computers is not acceptable, because it's defeating the whole concept of device name.
uBlock 1.3.6
FF 42

**Comment by gorhill** [comment]
> Setting up the same device name on both computers is not acceptable

Nowhere do I see you have to do this. The device name is just a convenience so that you know from which device originates whatever is in the cloud storage.

You need to provide more details:

- which pane are you trying to export to the cloud?
- did you click Firefox Sync icon after you exported to the cloud?
- any error message on the browser console?

I just tried and I confirm it works fine from here. There might be delay after you sace to the cloud storage, this is dependent on Firefox infrastructure. also, refresh the pane of the destination computer, the content of the cloud storage is looked at when the pane is rendered.

**Comment by vanowm** [comment]
Oh, it's working now, probably I banned myself for a while when was doing sync every 3 seconds...

Anyhow, the Firefox sync options that require for uBlock sync is "preferences" no need "add-ons". Would be nice if this was mentioned in wiki documentation.
I wonder if there is a way make it independent from "preferences" sync? Not every device need the same browser settings.
