### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Saad1988** [gorhill/uBlock#73]
Hi
the most popups in Persian websites are as new window(s). ublock just blocks popup window and doesn't block new complete window.
and i want if it blocks a popup, show notification to maybe i allow popup.
thanks.

**Comment by volia2** [comment]
Found this on google 
http://ideone.com/K452p
Somewhat different with arab's list.

**Comment by gorhill** [comment]
> ublock just blocks popup window and doesn't block new complete window

It does block new complete windows, it's what popups are. Please, give me a URL where I can reproduce what you are talking about.

**Comment by Saad1988** [comment]
for example:
http://www.p30world.com/
go and select text in page. it just opens one window. some websites open few new ad web pages.

**Comment by harshanvn** [comment]
@Saad1988 It is also better to give little more info, like uBlock Version, Browser Version, OS..

This helps dev to manage his time efficiently...

**Comment by gorhill** [comment]
Thanks for the URL. Yes, I got a popup.

Popups are block when there is a filter to block them, otherwise they are not blocked. In the current case, the popup was a page from `p30world.com`. There is no filter to block popups for `p30world.com`. So it's just a matter of creating that filter to you custom rules: `||p30world.com^$popup`, or even easier, to block all popups for that site using the [per-site switch to block popups](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-popups).
