### ISSUE TITLE
I couldn't get the specific inline script blocker working.

### ISSUE THREAD

**Issue by enomat** [gorhill/uBlock#756]
This site has an example for a javascript redirect method.

http://www.tizag.com/javascriptT/javascriptredirect.php

On that page scroll down and click this link: "Time Delay Redirect"
That page has the redirect script, delayed with 5 seconds.

I've tried to block that script with filters like these with no success:

tizag.com##script:contains(/delayer/)
||tizag.com##script:contains(/^function delayer()/)

The page still redirects me. Why?

**Comment by gorhill** [comment]
Because the page is so simple that the the script tag has already been executed before the `beforescriptexecute` listener had a chance to install itself.

**Comment by Betsy25** [comment]
Do the user defined filters have precedence over the filter lists, since those are (and will probably remain) based on the capabilities of ABP ? It's because there are quite a lot of ``@@.....$script`` items in there (take a lot at Easylist for example), which could be corrected by the users of uBlockO for a better outcome.

**Comment by gorhill** [comment]
> there are quite a lot of `@@.....$script` items in there 

The new script tag filter syntax is that of cosmetic filtering. `@@.....$script` is network filtering.

**Comment by lewisje** [comment]
To make it clearer, the only potential conflict would be with `@@.....$inline-script` rules, which are uO-specific anyway: ABP has no way to keep inline scripts from loading or running.
