### ISSUE TITLE
[Chrome]  Impossible to block ad

### ISSUE THREAD

**Issue by rosolko** [gorhill/uBlock#762]
It is impossible to block ads on site [4pda.ru](http://4pda.ru) when using Chrome.
The problem:
![1](https://cloud.githubusercontent.com/assets/11458319/10141994/63f127fa-6618-11e5-8c81-50f45563c949.png)

Locate element:
![2](https://cloud.githubusercontent.com/assets/11458319/10141997/6aed4a20-6618-11e5-89f7-f8273bf4d862.png)

Create rule for links:
```4pda.ru###main > .no-hidden.holder > a```
Result: Ad still show

Create rule for blocks:
```4pda.ru###main > .no-hidden.holder > .main.brand-page```
```4pda.ru###main > .no-hidden.holder > .left.brand-page```
```4pda.ru###main > .no-hidden.holder > .right.brand-page```
Result: Ad still show

Current chrome version: 45.0.2454.99 m (64-bit)
Note: This rules work in latest FF and hide this ad

**Comment by gorhill** [comment]
For the development record, the shadow root did help here because:

- The element was already invisible, by web site author design, so having a shadow root -- which purpose is to render invisible an element -- accomplished nothing;
- Its size was set using element style, which can't be overridden (shadow root included);

The fix is to keep overwriting element style, whether a shadow root is used or not.

**Comment by gorhill** [comment]
The fix here probably cause issue #435 to be back.
