### ISSUE TITLE
ABP issue 3143: "polyfill for `:has()` CSS4 pseudo-selector to element hiding filters"

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#769]
This entry is to keep track of  [Adblock Plus issue 3143](https://issues.adblockplus.org/ticket/3143): If cosmetic filters using `:has` starts to appear in filter lists, I want uBlock to be ready to handle these.

As a matter of fact, the work is already done for uBlock Origin, I have stashed code which already supports for this, and it does work -- but results are unconvincing (hence why the code is stashed): the DOM elements to remove via `:has` are visible shortly before they are removed (because DOM mutation event handling is asynchronous). There is not much to be done to resolve this, until `:has` is supported natively by browser vendors.

**Comment by Halibut80** [comment]
@gorhill 
With dom.webcomponents.enabled;true I see some bugs with new :has operators implemented in new uBlock builds. I'm not sure, should I open issue or not, because shadow dom still experimental in Firefox and disabled by default even in Nightly builds.

Clean new profile with default settings for browser (Win 8.1, FF Nightly 50.0a1 x64 BuildID:20160630030207) and uBlock 1.7.7b6. With enabled/disabled e10s.

Create, for example, custom filter <code>yande.re##ul#post-list-posts > li:has(.preview:-moz-any([alt*="Questionable"],[alt*="Explicit"]))</code>

Visit <a href="https://yande.re/post">https://yande.re/post</a>

Without filter:
<a href="https://lh3.googleusercontent.com/-SZvwJ2ekQH0/V3YUVGBf4rI/AAAAAAAAdAs/0rixbTzaOso/s0/screenshot%2525202016-07-01%252520002.png"><img src="https://lh3.googleusercontent.com/-xahKK8MTv7k/V3YUVYvc0wI/AAAAAAAAdAw/dMVPV3uigIs/s0/thumb_8dbe17f17e2b85d1f1e540a34eb0c54d.jpg" border=0></a>
With filter and dom.webcomponents.enabled;false:
<a href="https://lh3.googleusercontent.com/-1SsDgR4j7Vw/V3YUXmkdEyI/AAAAAAAAdA0/rQhWE0jWVDU/s0/screenshot%2525202016-07-01%252520003.png"><img src="https://lh3.googleusercontent.com/-a4wwdwHHOzM/V3YUX7Oqc-I/AAAAAAAAdA4/_Muzz37316Q/s0/thumb_5c5702dad136c354fbb7ecc4978605cd.jpg" border=0></a>
With filter and dom.webcomponents.enabled;true:
<a href="https://lh3.googleusercontent.com/-XUPnLxTTjts/V3YUcaGBwZI/AAAAAAAAdA8/gGu0CBkVE1k/s0/screenshot%2525202016-07-01%252520004.png"><img src="https://lh3.googleusercontent.com/-qv8ucOLzop8/V3YUcyuWXzI/AAAAAAAAdBA/ggPpgXktGKc/s0/thumb_d61b199388039d0ebe88d1f2bb306343.jpg" border=0></a>

**Comment by gorhill** [comment]
Probably an issue with the current implementation of `:has`. I see you are using a complex selector before the `:has` part, and I figured this could lead to some issues, like the wrong DOM elements being hidden -- unrelated to `dom.webcomponents.enabled`. I need to add a bit of code to deal with this. By the way, I could not repro the case since my DOM is different than yours, there is no "Questionable" or "Explicit" keywords on my side, it's all "Safe".

**Comment by Halibut80** [comment]
> By the way, I could not repro the case since my DOM is different than yours

Uhm, sorry, bad example. 
Filter: github.com##ul.Box-body > li:has(a.label)
URL: <a href="https://github.com/gorhill/uBlock/issues">https://github.com/gorhill/uBlock/issues</a>
With disabled/enabled dom.webcomponents.enabled:
<a href="https://lh3.googleusercontent.com/-5bg8zKTntMk/V3Y93nVgBGI/AAAAAAAAdBU/YWCSNSxhs0k/s0/screenshot%2525202016-07-01%252520002.png"><img src="https://lh3.googleusercontent.com/--tniH0pxi6I/V3Y95jt_dWI/AAAAAAAAdBY/Xw8NV84GQ7o/s0/thumb_126a8980ee6b52267ddc96361bb028c5.jpg" border=0></a> <a href="https://lh3.googleusercontent.com/-2eEFNTddleU/V3Y98cI3ymI/AAAAAAAAdBc/0TSCnJdIHf4/s0/screenshot%2525202016-07-01%252520003.png"><img src="https://lh3.googleusercontent.com/-0WO_FDeq4n8/V3Y99KOQpfI/AAAAAAAAdBg/jjNOqAgL5QQ/s0/thumb_ea1f125c3651bd12738243ecc4e56105.jpg" border=0></a>
And you are right: this garbage attribute appears in both cases. But, with enabled dom.webcomponents.enabled, target elements empty, but still visible.

**Comment by gorhill** [comment]
Ok I see. So the issue is not what I first thought it was since I wasn't able to reproduce the first case.

It's specific to using shadow DOM when available. When shadow DOM is available, uBO does not use `display: none !important;`. In general this works but if the element to hide uses padding or border, this may leave a mark behind. Solution would be to use `display: none !important;` even when shadow DOM is available (note to self: see if there is regression with #435). THis also means the issue is not specific to the beta build, it was always present.

**Comment by Betsy25** [comment]
Off-topic : Just chiming in to say my appreciation for the wonderful work you're doing @gorhill .
