### ISSUE TITLE
[0.9.4.4-dev.1] New gnuzilla filterlist not available

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#77]
I can't see the new [filterlist](https://github.com/gorhill/uBlock/commit/c6cb4345f2b2696784ad89faf911416560f91df0). 

After unpacking ublock0.chromium.zip there is no appropriate subfolder in ...assets/thirdparties. Even after manually adding the `gnuzilla.gnu.org` subfolder from the zip file and restarting Chrome that filterlist doesn't show up.

**Comment by gorhill** [comment]
The filter list is definitely in there, what is missing is an updated `filter-lists.json`. There are many changes in `filter-lists.json`, to fix a handful of old issues about obsolete or moved filter lists, and I want to wait for the week-end for these changes -- maybe tonight, as this will test code paths which has never been really tested yet -- the seamless migration from one filter list to a new version at a different location.

**Comment by tlu1024** [comment]
I see. FWIW, `gnuzilla.gnu.org` seems to be offline right now.

**Comment by anewuser** [comment]
@gorhill maybe you already know this, but that list is actually [an automatically parsed and edited mix](https://lists.gnu.org/archive/html/bug-gnuzilla/2015-04/msg00032.html) of other filters already included in uBlock preferences. Maybe it's not a good idea to keep it in uBlock, at least not with the current description of being just a list of "privacy trackers".

For example, it currently includes this rule, which breaks a lot of websites, like [Instapaper](https://www.instapaper.com/text?u=gnu.org):

> ||amazonaws.com^$script,third-party

I've already reported this to the script author, but this filter may continue to be problematic since it uses  automatic rules.

**Comment by gorhill** [comment]
Removing would be problematic, many people may use it already. I can add a note though, like "high breakage", or whatever concise expression is better to indicate that it has a higher likelihood to cause web pages to break.

**Comment by anewuser** [comment]
@gorhill Thank you for adding the warning. It also is blocking **||imgur.com^$image,third-party**, which is one of the most popular image hosting sites today.  If you decided to remove it from the filters officially endorsed by you, couldn't you move it to the "custom filters" of users who are using it already, along with a comment about it?

**Comment by gorhill** [comment]
> It is also blocking `||imgur.com^$image,third-party`

Yeah, that's problematic. I had assumed this was a well groomed filter lists given the name and origin.

Given the content of this list, for someone who would want to use such list, best option is instead to turn on default-deny in dynamic filtering, at least this way one can easily un-break whatever sites end up broken, which is not the case when using a static filter list.

However I cannot make a clean transition like you propose, because the available filter lists are updated dynamically, this means there won't be special code path in existing uBlock installations to take care of moving it to custom filters.

I will have to remove it and just document why, the sooner the better.
