### ISSUE TITLE
Some icons not displayed when using with Document Font Toggle

### ISSUE THREAD

**Issue by alanbur** [gorhill/uBlock#770]
I'm using another plugin (Document Font Toggle) which controls if pages are allowed to specify their own fonts. When that is enabled, the 'Power' icon on the popup as well as icons in other places don't display. This doesn't happen with the 'other' uBlock.

**Comment by gorhill** [comment]
[Browser/browser version](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)?

**Comment by alanbur** [comment]
Sorry - firefox 31.8.0 ESR

**Comment by gorhill** [comment]
Firefox 41 fixes the issue. I do not intend to no longer rely on icon-based fonts, see #605.

**Comment by alanbur** [comment]
Unfortunately I'm stuck on ESR 31 due to corporate policy so I can't upgrade. When you say "I do not intend to no longer rely on icon-based fonts" does this mean you intend to fix this in uBlock itself? If so, I'll just wait.

**Comment by RoxKilly** [comment]
@alanbur The problem you run into is that prior to FF 41, when document fonts are OFF, font-icons are broken. @gorhill is saying that he will not make a change in uBlock.0 to change this (the change would be to use image-icons which would not be affected rather than font-icons).  In other words he is sticking to his decision to use font-icons despite this disadvantage.
