### ISSUE TITLE
Block 'suggested tiles' on Firefox new tab page

### ISSUE THREAD

**Issue by brson** [gorhill/uBlock#789]
I run uBlock origin on Firefox, and generally expect all adds to be blocked. When I open the 'new tab' page on Firefox nightly in the default configuration, I see prominent 'suggested tiles'. Currently, I have to know to click the new tab 'settings' icon and disable this feature, but since uBlock is my ad-block tool, I'd expect it to take care of this for me, providing a better experience.

#426 is related.

**Comment by 5t3f4n** [comment]
Does adding `matrix-off: newtab.about-scheme false` to your rules help?

I don't know how much it would help for uMatrix to add a specific feature to block tiles as they are included with Firefox and thus loaded before you get a chance to even install uMatrix. I guess Firefox downloads more over time, but you can edit the relevant URLs out from about:config to prevent that.

**Comment by gorhill** [comment]
> Does adding `matrix-off: newtab.about-scheme false` to your rules help?

This means nothing to uBlock Origin, this is a uMatrix rule.

@brson By default uBlock Origin does not mess with `about`-based pages. So disable the setting in Firefox (I've never seen any ads on my side in the _New Tab_ page). You may want to use the logger to see if there are network requests related to these ad tiles -- don't forget to check the [behind-the-scene network requests](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests).

By default uBlock Origin is disabled uBlock on browser-specific pages (`about:`, `chrome://`, etc.) in order to ensure it does not interfere with the functioning of the browser, I don't intend to change this.

**Comment by jruderman** [comment]
You could set browser.newtabpage.enhanced to false. This wouldn't be likely to break other add-ons, since it's the same pref that the built-in gear checkbox flips. Dunno if users would consider that "interfering with the functioning of the browser" or consistently disabling ads.

**Comment by gorhill** [comment]
I did post this a while ago: <https://github.com/gorhill/uBlock/wiki/Tips-and-tricks-waterfall#techcrunch-firefox-will-soon-get-sponsored-suggested-tiles-based-on-your-browsing-history>.

Can't tell if this works though (for some reasons no ads here).

**Comment by brson** [comment]
Thanks for the link @gorhill.
