### ISSUE TITLE
First time with ublock

### ISSUE THREAD

**Issue by delicacy1** [gorhill/uBlock#803]
ublock uses a function called "element picker" that doesn't function & reloads
a page when i require the function, & the page being reloated, only virtual frames appear 
on a unicolor page that gets rid of every html content, 
so you don't know what you're gonna hide, & even worse,
reloading the page can make you lose the track of a particular warning..

+ the log aka "open blockable items-on abp" is opened on a new tab,
and not live at the bottom of loaded content .. .

It would be great if those two issues were fixed.
& make it work like element hiding helper

**Comment by zummuz** [comment]
I guess you should read wiki at first https://github.com/gorhill/uBlock/wiki.
Then https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md :
What browser do you use?
What version of uBlock?
What settings and filters activated?
Provide link to a specific site where element picker doesn't work, for example.
And maybe a screenshot to help understand how those issues looks since they are visiual?

**Comment by gorhill** [comment]
I do not plan to turn uBlock Origin into a clone of ABP.

**Comment by harshanvn** [comment]
> the log aka "open blockable items-on abp" is opened on a new tab, and not live at the bottom of loaded content

Please read the wiki, to fully understand the functionalities..(as suggested by zummuz)
Coming to uBlock's Logger, opening in the new Tab, it is quite different and powerful in its usage -
 - It is universal <a href="https://github.com/gorhill/uBlock/wiki/The-logger">logger</a> (i.e., you can observe the requests of all the pages at once, even other extensions and browser made requests too)

**Comment by harshanvn** [comment]
> on a unicolor page that gets rid of every html content

@gorhill 

here if i understand him correctly, i think you may review this case one more time -

the problem here, when you enter into element picker mode, the remaining portion of the screen (the unselected part) is dimmed and almost invisible to the eye, if one configures his monitor to very little <b>brightness</b>

![element picker](https://cloud.githubusercontent.com/assets/779630/10402281/197f7d3e-6ee2-11e5-8ef7-1df338bb08ce.png)

###STR
1. Configure your monitor to least brightness available
2. Open element picker mode
3. You will see that rest of the unselected portion of the screen is little visible.

Note: This is not a problem if you set your monitor to high brightness. Unfortunately, i believe people like me who set their monitor lesser brightness, it is difficult to the eye to perceive the remaining portion of the screen..

Can you review and do something about this, like making it more transparent or sth else..

**Comment by harshanvn** [comment]
@gorhill 

just checking, if you got a chance to review this...

**Comment by gorhill** [comment]
Can you use the dev console to change the opacity (currently set at 0.75) and see what value works best?

**Comment by harshanvn** [comment]
Ok. I am away from my home. Will test this once i reach. should be 5-6 hrs from now.

**Comment by harshanvn** [comment]
<b>update 1:</b>
I tried it on my office PC, and i am seeing 1 as opacity not .75. Please see the screenshot.
And changing it to .70 was lot comfortable to the eye. Along with changing <code>aside</code> element to .3 from .1

Config: Firefox v41.0.2, uBlock v1.3.0, W7

![ublock opacity](https://cloud.githubusercontent.com/assets/779630/10636281/bcdb39d0-77cc-11e5-9a61-17d05b032cb6.png)

**Comment by gorhill** [comment]
You have to look at the first SVG `path` inside the `iframe`. What you are looking at is completely transparent, regardless of opacity.

**Comment by harshanvn** [comment]
Ok, thanks.
Changing it to <code>.5</code> is good. Lot better.
