### ISSUE TITLE
palemoon user.. Sad

### ISSUE THREAD

**Issue by delicacy1** [gorhill/uBlock#805]
i've just read this on palemoon forums:

"A serious warning: It is important to say, no one knows when Ublock does not work anymore with Palemoon. This add-on is Australis optimized, so any future change can break Palemoon support in a blink of an eye! So do not put too much hope into it. Because if the Author ever decides to go fully Australis style, it's over! I really cannot be bothered to continue any discussion about ublock just don't come crying to me when it breaks because you were duly warned before hand."

I actually dont have the icon, moreover, i believe the fact the picker doesn't work here
is because of a code incompatibility that outpasses simple application id change..

**Comment by gorhill** [comment]
Works fine here. This issue is invalid, it lacks any specifics.

**Comment by lewisje** [comment]
I just tried out uBlock Origin in Pale Moon yesterday, both fully updated, and I was able to add the icon to the main toolbar.

**Comment by LimboSlam** [comment]
@delicacy1: Excuse me, this was know where in our forums. So please stop spreading rumors, thanks. 

Though if you are referring these conversation here: https://forum.palemoon.org/viewtopic.php?f=46&t=7960&start=80#p64773, they should not to be relied as these are opinionated statements based off the users personal experience with Ublock Origin. 

Also, please don't quote one of our users statements without reading the full thread and knowing exactly what we are saying. 


Best regards,
LimboSlam

**Comment by gorhill** [comment]
@delicacy1 needs to cool down and take time to familiarize with uBlock Origin instead of eagerly opening vague or non-issues. @delicacy1 disrespected my demand to not be contacted by email. Given all this, I had to block @delicacy1 for the time being.

**Comment by gorhill** [comment]
@LimboSlam [This is the post quoted](http://forum.palemoon.org/viewtopic.php?t=7373&p=50644#p49552) from Pale Moon forum: This was _someone's_ opinion, 7 months ago.

**Comment by LimboSlam** [comment]
@gorhill: Yes I see that now and the user really should have followed this up more because this is no longer true. I mean yes their is always going to be bugs with us because we are not based on the same code as the current Firefox is and their will always be the possibility of you dropping support with us because of your own reason, but that is with every programs/apps either updated to work with current technology's or slit off for their own reasons, such as Pale Moon.         

Anyways, the user should have done his HW. So....... Lets forget about this and do something productive. :)

**Comment by lewisje** [comment]
If uBlock Origin does decide to drop Pale Moon support, there's always the possibility to fork it into "uBlock Latitude" (similarly to what Moonchild did with ABP).
