### ISSUE TITLE
Blocking cookies ?

### ISSUE THREAD

**Issue by gg8345** [gorhill/uBlock#827]
I didn't see it in the documentation, but can cookies be selectively disabled ?

Something like that (privacy badger from the EFF) :
https://www.eff.org/privacybadger

It seems it would reduce the amount of extensions that need to be installed if ublock was interested in having the same functionality.

**Comment by publicarray** [comment]
> can cookies be selectively disabled ?

No.

For me I have disabled 3rd party cookies in all of my browsers. I think that is enough to protect my privacy, also uBlock Origin can block domains and if you block them than they can't set cookies ether.

To disable 3rd-party cookies in Chrome: in Settings -> Sow Advanced settings... -> Content Settings... -> Block third-party cookies and site data
![screen shot 2015-10-15 at 1 39 52 pm](https://cloud.githubusercontent.com/assets/5497998/10504388/4713571a-7343-11e5-90c9-658c1cf0d81f.png)

In Firefox preferences -> Privacy -> History select `use custom settings for history` and select the following or modify to your needs
![screen shot 2015-10-15 at 1 46 55 pm](https://cloud.githubusercontent.com/assets/5497998/10504387/41f0e9b4-7343-11e5-8722-d79365eecc9d.png)

**Comment by CrisBRM** [comment]
For a finer-grained control, use https://github.com/gorhill/uMatrix

**Comment by flyingzebras** [comment]
@gorhill "Privacy Badger sends the Do Not Track header with each request and evaluates the likelihood that you are still being tracked. If a domain appears to be tracking you on multiple websites, Privacy Badger automatically blocks your request from being sent to the tracking domain." - https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/

Can uBO do this?


If not, would it be feasable to implement it?

**Comment by CrisBRM** [comment]
DNT is placebo, no one has to honour it and, to be honest, it's just additional information which leads to more bits of identifying information. Personally, I think you're more likely to be tracked (by intelligence agencies) by enabling it than leaving it as is, but that's just my opinion.

Lastly, it is the browser's job to do that, not uBlock's. On firefox, you do this by toggling ```privacy.donottrackheader.enabled```, or by going to preferences, privacy, and checking a box.

**Comment by publicarray** [comment]
To extend on @CrisBRM answer:

Privacy badger uses heuristics to determine what to block. I assume that one of it's rules is to send a web request with the DNT header, than it determines if it is honored or not.

To learn more about DNT see: http://www.allaboutdnt.com/

You can enable the DNT header in
 
 - Chrome you go in to Settings > Show advanced settings... and tick the 'Send a "Do Not Track" request with your browsing traffic' box.
 - Safari > Preferences... > Privacy check the box 'Ask websites not to track me'.

**Comment by gorhill** [comment]
> Can uBO do send Do Not Track header?

DNT is incompatible with the spirit of the project.

DNT is essentially acknowledging that a 3rd-party is the one in control of your privacy in the 1st place, and you have to resort to asking this 3rd-party -- which has financial interests in tracking you -- to not track/data mine you, and trusting that they respect your wish, with no way for you to find out whether your request is respected. In short, it's BS, and supporting tracking/data mining is agreeing that tracking/data mining is the natural, expected behavior and thus an opt-out "feature".

Nobody should ever agree to this.

I see it differently: tracking is opt-in, and the ideal is that users are in full control of their privacy by default. Those who want to track/data mine you should ask you to opt-in, along with **all the detailed information** of how the data collated from you will be used and monetized (lists **all** entities to which your data is sold), in the spirit of informed consent.

Currently the way for users to enforce their privacy choice is to use all the tools at their disposal to prevent their data from ending up in the hands of the trackers/data miners, and DNT is **not** one of these tools.

**Comment by publicarray** [comment]
@gorhill I fully agree with you. However I have elected to send DNT so that websites know that I am against tracking. I am hopeful that companies will eventually listen and change for the better. I know this does nothing in regards to my privacy but it does advocate the need for it.

**Comment by flyingzebras** [comment]
@gorhill So you recommend against using Privacy Badger?

**Comment by gorhill** [comment]
> So you recommend against using Privacy Badger?

Of course not. I am just saying I am against DNT specifically on principle ground. There is more to Privacy Badger than just setting the DNT header.

**Comment by flyingzebras** [comment]
@gorhill Ok, then I guess Privacy Badger has it place, to complement what uBlock.

**Comment by svnpenn** [comment]
@gorhill it appears you never answered OP, so I would like to report more clearly:

1. Can uBlock Origin and/or uMatrix block cookies

2. Can either of them block them by domain

3. Can either of them block by cookie name, allowing blockage of a specific cookie on a specific domain

4. If none or some of this is not possible with your tools, do you have a recommended add-on
