### ISSUE TITLE
titlebar should have a settings icon

### ISSUE THREAD

**Issue by elypter** [gorhill/uBlock#830]
(has been mentioned in #671 too)
the first line of the ublock dropdown dialog opens settings. the average user would not expect that behavior. even if someone thinks that it might be clickable he would expect it to link to the project homepage. my suggested solution: clicking the addon name takes you to the project page. on the top right corner there should be a gears icon which takes you to the settings. the tilte should be black on light grey like the rows below. light grey on dark grey is hard to read and doesnt look very nice.

**Comment by publicarray** [comment]
Why did you create a new issue? you could have commented on #671

**Comment by elypter** [comment]
#671 is 3 issues in 1. thats not very good style and adding yet another aspect would make it worse.

**Comment by gorhill** [comment]
> the first line of the ublock dropdown dialog opens settings

Tooltip says "Click to open the dashboard".

**Comment by elypter** [comment]
people dont scan the sceen with the mouse pointer for hidden tooltips. besides being obvious there are several bugreports supporting this.

**Comment by onestepbeyond** [comment]
@gorhill I'm surprized because here (FF 41.0.2 - Win XP Pro SP3), uBlock provides no tooltip hovering the first line, there is just a simple small tooltip saying "uBlock Origin", like over any blank area of the dropdown dialog.

![screenshot01393](https://cloud.githubusercontent.com/assets/11029138/10530385/d57016b0-73a7-11e5-8ee3-b89685b617b4.png)

However, all other clickable item in the popup have its explanatory tooltip. Only the first line does not have his own.

(uBlock 1.3.0rc1 in non-advanced mode).

**Comment by gorhill** [comment]
The tooltip for the title is implemented using stock tooltip. Firefox for some reasons does not render stock tooltip in an add-on popup.

**Comment by SW1FT** [comment]
I have to agree with @elypter, a settings icon would be more "new user friendly".
