### ISSUE TITLE
uBlock memory usage

### ISSUE THREAD

**Issue by ZuBB** [gorhill/uBlock#834]
Hi there!

Just a couple of minutes ago killed ubolck because it took 200+ Mb of memory accordingly to Chromiun task maneger

browser: Version 45.0.2454.101 Ubuntu 14.04 (64-bit)
addon:  1.2.0

This is not the first time when addot eats too much memory (as for me). but its first time when it take so much

**Comment by gorhill** [comment]
Many things can lead to this, some under normal conditions, and this applies to all extensions:

- logger opened and full of entries?
- dashboard opened?
- popup UI opened or recently opened?
- amount of filter lists in use?
- just reloaded the filter lists?
- auto update just kicked in?
- dev console opened and stepping through uBlock's content scripts or own code?
- uBlock running for very long? (memory fragmentation)
- failure to force GC when measuring memory figures? (I've seen tens of MBs reclaimed this way)
- recently used the feature which allows to identify the origin of a filter?
- recently got uBlock Origin blocked site warning page?
- etc.

Just reporting that "uBlock consumes 200 MB" alone is **completely** pointless. In all my benchmarks, I obviously took great care to avoid tainting the memory figures of all tested extensions, so that they could be meaningfully compared.
