### ISSUE TITLE
"Global" and "Local" icons

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#840]
See https://github.com/chrisaljoudi/uBlock/issues/1371

**Comment by zummuz** [comment]
This part of user interface is not available until *I am an advanced user* option is checked. And this option requires reading of the wiki. Once you have discovered there are local and global type of rules you will never be confused, because the local column has +/- sings to show local request. Its quite logical.

**Comment by gorhill** [comment]
I explained in the linked issue why I don't think it is a good idea:

- Space is precious in the dynamic filtering panel, I rather use it for something else than labels.
- Once you read the quick guide, remembering what is global/local should not be an issue. If it is for someone, then I argue that "advanced mode" is not suitable for that user.
- If I were to add the header, I suspect the layout would become an issue for some languages (too long strings).
- What @zummuz said: the local column can be easily distinguished by the `+`/`-`, so the headers would be redundant information, using precious limited space.
