### ISSUE TITLE
Opera µBlock -> uBlock Origin

### ISSUE THREAD

**Issue by x2k13** [gorhill/uBlock#844]
Will the Opera addon be updated anytime soon as well or is it considered dead-end at 1.1.1?
To avoid confusion with the "other" uBlock thing [...] maybe it would also be good to just add the future updates as a new addon in Opera-Add-ons titled as uBlock Origin and set the old one as deprecated, so people stop wondering. Just a suggestion, as I've read that the name of the Opera addon can't be changed, so why not just simply ditch the old one and re-add it with the proper name.

**Comment by Havokdan** [comment]
I Agree.

**Comment by gorhill** [comment]
If you look at what is new or has been fixed since 1.1.1, most of these are relevant to Firefox. There is nothing noteworthy for Chromium-based browsers, chances are most users would not see the difference with latest version. I will still update both Chrome store/Opera store to latest 1.3.0 later this week.

**Comment by gorhill** [comment]
I won't destroy the current entry on Opera store to start a fresh new one -- this could cause a lot of pain to existing users, and this would also cause the history of uBO in the Opera store to be lost.

Maybe eventually the Opera store will support name changing + URL redirection, in which case I will use this. For now we have to accept that in Opera store, µBlock = uBlock Origin.
