### ISSUE TITLE
Add ABP's "Blockable items on current page" and "Block this item" function

### ISSUE THREAD

**Issue by mewblock** [gorhill/uBlock#85]
These functions are useful to create custom blocklist(or whitelist).

**Comment by Mikey1993** [comment]
"Block this item" feature is already in there.
Check "Make use of context menu where appropriate" in Settings menu.

"Blockable items on current page" is a nice touch, but you can achieve that by opening the network request logger from uBlock's popup for a given page and record a live refresh of a page to show the requests that were blocked (not that for the moment, the logger shows only network requests).

Please refer to https://github.com/chrisaljoudi/uBlock/issues/308

**Comment by timmc** [comment]
The logger is not a sufficient replacement.

I am really missing ABP's "blockable items" screen because it allows me to see what the blocker has *already done* to a page, without reloading it. Lack of reload is key; I don't want to refresh a page halfway through a complicated multi-page form submission or a store checkout process just to see if the blocker has done something weird.

**Comment by gorhill** [comment]
You will have to use ABP for Firefox. I won't sacrifice uBO's efficiency for the vast majority of people for the small inconvenience of having to reload the page when opening the logger the first time.

**Comment by timmc** [comment]
OK, good to know the reasoning at least.
