### ISSUE TITLE
Medium mode: are static filters needed?

### ISSUE THREAD

**Issue by translit** [gorhill/uBlock#859]
The wiki advises to leave the static filters on in the medium mode to 'mop up' whatever slips through the dynamic filter. Do these static filters consume any system resources (CPU, memory)? If yes, is the extra protection they add worth the overhead? I figured the 'default deny' policy was robust enough to do without any static filters.

**Comment by gorhill** [comment]
> Do these static filters consume any system resources (CPU, memory)?

Of course they consume memory. As for CPU, the static filtering engine is executed only for network requests which have not been blocked by higher level filtering engine (see ["Overview of uBlock's network filtering engine"](https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock's-network-filtering-engine)).

> If yes, is the extra protection they add worth the overhead?

In my opinion, yes. Given uBO's efficiency, the "overhead" should not be construed as an issue -- unless it _really_ is one (on mobile maybe?). As said, the static filtering (URL pattern-based)  engine is executed if and only if something is not blocked through dynamic filtering.

Another good reason to keep static filters loaded is this give you the ability to neutralize partially or wholly dynamic filtering for a given site, without ending up completely "naked": the static filters will kick in for everything which is not filtered at a higher level.

Also, Sometimes EasyList/EasyPrivacy will filter stuff from 1st-party origin. For example, enable scripts for Youtube to allow an embedded video to play (noop `youtube.com`), and you will find that static filters will work to filter stuff from `youtube.com`.

It may very well happen that sometimes you do not feel like figuring to proper recipe of dynamic rules for a given site in order to unbreak it. Nooping the 3rd-party scripts for the current site is a quick way to unbreak a site in such case. At least in this instance, you know you fall back onto EasyList/EasyPrivacy.

Dynamic filtering is like a firewall, and creating noop rules for that firewall is exactly like punching holes in it. Whatever goes through these holes will be picked up by static filtering.

Yet another reason is cosmetic filtering, which is not something dynamic filtering can take care of.

**Comment by zummuz** [comment]
>Do these static filters consume any system resources (CPU, memory)? If yes, is the extra protection they add worth the overhead? 

I can't prove it with graphs, but logically, dynamic filtering doesn't need to compare each request to tens of thousands  filters from the lists, it should just check one thing - is it 1st party domain or not, and then allow/block it. So I assume dynamic filtering doesn't consume a lot resources.
> I figured the 'default deny' policy was robust enough to do without any static filters.  

There are still 1st party ads which static filters block. And from wiki:
>High likelihood of web pages being broken: you have to be ready and willing to fix them when this happen.

so you just create a noop rule (locally turn off dynamic filtering) on the broken page, and static filters kill ads, social, tracking garbage so you don't need to dynamically filter each domain.

**Comment by translit** [comment]
>In my opinion, yes.

And your opinion matters, gorhill. First, because you know what you're talking about. And, second, because your arguments are convincing. Thanks for the reply (and uBlock in the first place). I'm turning the static filters back on.
