### ISSUE TITLE
Barclaycard Verification site

### ISSUE THREAD

**Issue by R7914T** [gorhill/uBlock#866]
I just renewed my Railcard. I tried to pay via Barclaycard but the verification site would not open. I disabled ublock and tried again and this time the verification site came up. I have switched uBlock back on. What should I change so that the verification site will open without me having to disable ublock? No address of the verification site  appears in my history in firefox (Ubuntu 14.04-AMD64).

**Comment by gorhill** [comment]
Use the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what is blocked, and why.

**Comment by R7914T** [comment]
I have had a look at the most likely network request log. I can see any entry in plain language that suggests the barclays verification site. The entries are Image, script, css. As there is no new https in the list (other one for googleletagmanager.ccom^$third-party) I do not know how the verification screen is called. 

As the verifcation of visa cards is extremely common, can you suggest what settings in uBlock would block access to the verification system.

**Comment by gorhill** [comment]
> can you suggest what settings in uBlock would block access to the verification system

I have no clue. The only way to un-break a web site is to know which filter(s) from which filter lists(s) is(are) causing which required network request(s) to be blocked. I have no clue about what is "barclays verification site". Majority of filters in uBO are 3rd-party filter lists, with dedicated maintainers, normally you should report any issue with them, and even though, they will require the same things: details to reproduce the issue on their side.

**Comment by RoxKilly** [comment]
@R7914T Do you use any dynamic filters (in Advanced User mode)? Maybe it's a dynamic filter, rather than the 3rd party filter lists, that is blocking the transaction.

As you look for a likely URL, consider that Barclays may not be doing the verification itself.  Verification may be conducted from another domain, owned by Paypal, Braintree, Visa, Mastercard...

For instance, to make payments work on sites where I shop, I've had to add `* verifiedbyvisa.com * noop` and  `* braintreegateway.com * noop` to the `My Rules` tab because my dynamic filters were getting in the way
