### ISSUE TITLE
uBo Icon at FF startup

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#877]
Hello,

when FF is starting up (about:blank page) the uBo Button on the Addon-bar is showing for half a second red (not whitelisted) and then grey (whitelisted -> as about:blank sheme is whitelisted by default). OK, the about:blank page have not to be observed by uBo, cause there are no scripts or similar to block. But is it a cosmetic issue, that the Icon shortly comes up red... or in other words: Is it ok, if I mark about:blank not whitelisted at all so it shows up red (not whitelisted) all the time. In this case, I am aware that uBo is running at a first look. :)

**Comment by grabber24** [comment]
I agree with you simply because I am very new at all of this, so sure it is ok. Well I say ok trusting that you are being helpful and not malicious in your conduct. I've come across some untrustworthy people is the reason I say that, and I am making sure that it's clear of my intentions to agree with you.

**Comment by gorhill** [comment]
I re-read mutliple times, I am unable to understand the reported issue. Also, submitter left GitHub.

**Comment by Hrxn** [comment]
I guess he wants an option to have the 'active' (i.e. red) uBO icon even on whitelisted pages. Showing that uBO is loaded and running at first glance..
