### ISSUE TITLE
already blocks ghostery's job?

### ISSUE THREAD

**Issue by muhasturk** [gorhill/uBlock#902]
Does ublock blocks trackers that ghostery already blocks? Should I install ghostery and ublock at the same time in the browser?

**Comment by Notoll** [comment]
Ghostery is absolutely useless if uBO is installed... even with default settings. So why keep both?

**Comment by muhasturk** [comment]
That's why I ask this question, is it useless or block something that ublock cannot.

**Comment by Notoll** [comment]
uBlock blocks in the default config (default filterlists) more than ghostery might do.

**Comment by muhasturk** [comment]
any ideas for 
* Ghostery
* Disconnect 
* Privacy Badger?

**Comment by Notoll** [comment]
I use uBlock Origin because it is the much more powerful and reliable extension. Deal with it. :)

**Comment by RoxKilly** [comment]
I've never used Ghostery.  Users tend to really enjoy it, but the fact that its revenue comes from advertisers makes me distrustful (same story with Adblock Plus).

As for Disconnect, when it comes to tracking protection uBlock Origin is at least as good in its default configuration. When it comes to blocking ads, uBlock O. is far ahead because by default it integrates block lists specifically designed to kill ads whereas Disconnect is really focused on privacy/tracking but is not actually opposed to ads.  I have used Disconnect and I like it.

Privacy Badger has a similar goal to Disconnect (to stop tracking, not necessarily ads) but a very different approach.  Whereas Disconnect and uBlock use block-lists,  Privacy Badger is trusting by default.  It will allow you to be tracked for a while as it observes your network activity, then get progressively better as it learns which connections go to trackers and blocks those.  I have never used Privacy Badger.

You could use uBlock.O and still enjoy the protection of Disconnect. In uBlock's filter lists, just select all the Disconnect block-lists in addition to what's already selected.  By the way, Disconnect should be given lots of credit for making its block-lists freely available.

**Comment by gorhill** [comment]
https://www.diffchecker.com/zapbh5b9

**Comment by marcus-cr** [comment]
Been using uBlock Origin for years now. Tried Ghostery but didn't like it, or their practices. Same with AdBlock Plus before it went real popular. Disconnect is great for tracking but their tracking/privacy blocklists are available in uBlock.O to download, among many others. Did not find Privacy Badger useful, didn't learn anything until I starting actually selecting my level of blocking for each website after visiting several. uBlock Origin is the winner here, imho
