### ISSUE TITLE
Local shared objects

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#904]
"The quick and easy way to delete your browsing history, erase all temporary internet files, remove downloaded files history, cookies, Flash LSO, typed URLs. Allows to delete private data when Firefox closes. Supported ext. tools like CCleaner." - https://addons.mozilla.org/en-US/firefox/addon/clickclean/

"Local shared objects (LSOs), commonly called Flash cookies (due to their similarities with HTTP cookies), are pieces of data that websites which use Adobe Flash may store on a user's computer. Local shared objects have been used by all versions of Flash Player (developed by Macromedia, which was later acquired by Adobe Systems) since version 6.

Flash cookies, which can be stored or retrieved whenever a user accesses a page containing a Flash application, are a form of local storage. Similar to that of cookies, they can be used to store user preferences, save data from Flash games, or to track users' Internet activity. LSOs have been criticised as a breach of browser security, but there are browser settings and addons to limit the duration of their storage." - https://en.wikipedia.org/wiki/Local_shared_object

Can uBO block LSOs as Click&Clean?

If not, would you like to add it to your todo list?

**Comment by gorhill** [comment]
Best is to just set Flash to "Ask to Activate" or "Never Activate".

**Comment by flyingzebras** [comment]
@gorhill Yes, but all users that "Always Activate" will have LSOs on their computers. That is why it is good to have a tool like Click&Clean.

**Comment by RoxKilly** [comment]
> Can uBO block LSOs as Click&Clean? -@flyingzebras

Persistent Flash Cookies are no longer a problem. Since Firefox 5 or 6 and Flash Player 10.3, when your clear cookies in Firefox, these [LSOs are also deleted](https://bugzilla.mozilla.org/show_bug.cgi?id=625496).

You'll notice that the add-ons that focused just on clearing LSOs have typically not been updated in years, including the once popular [BetterPrivacy](https://addons.mozilla.org/en-us/firefox/addon/betterprivacy/versions/) as well as [Click&Clean](https://addons.mozilla.org/en-US/firefox/addon/clickclean/versions/).

There are two types of privacy measures: 
1) *pro-active measures* are taken before or as the privacy invasion occurs. This is where uBlock currently works, preventing shading network connections, hyperlink auditing, pre-fetching, and WebRTC.
2) *reactive measures* are taken after the privacy invasion has occured. This includes clearing cookies, deleting temporary internet files, clearing browser history and local cache etc...

Clearing LSOs is a reactive measure. In my opinion adding these measures to uBlock would be unwise because although it could help users enhance their privacy, it runs the risk of turning uBlock into a jack of all trades which will make for a more bloated, harder to maintain application.  I think the best avenue for reactive measures is to use Private or Incognito browsing modes.  This signals the browser to clean everything that persists after shutdown.

**Comment by flyingzebras** [comment]
@RoxKilly Very good answer, thank you!
