### ISSUE TITLE
Migrating useful uBlock code

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uBlock#905]
Have all really useful code of the project uBlock (unmaintained?) now been forked to uBlock Origin?

**Comment by CrisBRM** [comment]
You got it the other way around, friend. Gorhill is the creator of uBlock and has never stopped developing it; Chris merely changed the UI, and patched a few bugs using gorhill's code (post-'fork').
uBlock Origin is 688 commits ahead of uBlock. Actually, the real number is probably closer to 900, given the hundreds of README changes Aljoudi did (and committing the built in lists manually dozens of times).

**Comment by AlexVallat** [comment]
Only feature (rather than UI tweak) that isn't in from uBlock is the context menu Block command for the Firefox Inspector and Network devtools. This was a design decision in favour of using the DOM Inspector on the logger tab instead, which is cross-platform rather than Firefox specific.

I still find it useful, though, so I keep a fork with it in: https://github.com/AlexVallat/uBlockOrigin
