### ISSUE TITLE
Mouse context menu broken with newest uBlock 1.3.4b3

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#906]
Steps:
New Firefox 42.0 profile
Install: 
Classic Theme Restorer
https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/
Context Search
https://addons.mozilla.org/en-us/firefox/addon/context-search/
Tab Mix Plus
https://addons.mozilla.org/en-us/firefox/addon/tab-mix-plus/
uBlock 1.3.4b2
https://github.com/gorhill/uBlock/releases/tag/1.3.4b2
Restart Firefox.
Now notice how right clicking to search highlighted text no longer works.

This is the context menu of a site with uBlock 1.3.4b2
![untitled-4](https://cloud.githubusercontent.com/assets/930620/10950193/3040a18c-82fc-11e5-92cf-7e5affbfb706.png)
And this is the context menu with uBlock 1.3.3
![untitled-5](https://cloud.githubusercontent.com/assets/930620/10950192/303ee5c2-82fc-11e5-96b7-12c5f7c842bf.png)

Maybe not 100% uBlock's fault but I only noticed this when upgrading to the latest uBlock.

**Comment by gorhill** [comment]
I don't understand the reported issue. I install Tab Mix Plus and with uBO 1.3.4b2, my context menu looks just like the bottom one.

> Maybe not 100% uBlock's fault

Please, first investigate fully that there is indeed an issue with uBO.

**Comment by vzjrz** [comment]
Sorry, you have to install all 4 addons to see the effect.

**Comment by gorhill** [comment]
Did you try all three other add-ons _without_ uBO?

**Comment by vzjrz** [comment]
Ofcourse. It works fine without ublock or with 1.3.3

**Comment by gorhill** [comment]
Ok I can reproduce with only Tab Mix Plus and uBO.

**Comment by gorhill** [comment]
It occurs if I force the use of legacy toolbar button in uBO on my side. Is it your case?

In such case, I see errors reported in the browser console -- Tab Mix Plus throws:

![a](https://cloud.githubusercontent.com/assets/585534/10952679/ff1369d0-8311-11e5-900a-27a0afed9213.png)

**Comment by vzjrz** [comment]
Weird, I'm only able to reproduce when all 4 addons are installed. Tab Mix Plus plus uBlock seem to work fine.
By legacy toolbar do you mean setting "extensions.ublock0.forceLegacyToolbarButton" to true? This is with a clean profile so no settings are changed but enabling that setting did not produce different results.
With all 4 addons installed I get this in the console:
![untitled-2](https://cloud.githubusercontent.com/assets/930620/10953108/f02a83aa-830b-11e5-9578-a0c3c1802759.png)

**Comment by gorhill** [comment]
Ok, it's not clear what specific issue you have in mind. In your OP, you mention

> right clicking to search highlighted text no longer works

But _none_ of the screenshot shows an entry to search highlighted text, neither 1.3.3, neither 1.3.4 -- so now you have me confused. So far this is what we have:

- Tab Mix Plus throws as shown in browser console
- Context Search causes a deprecation warning on browser console

Why not take the issues with the maintainers of these add-ons?

**Comment by vzjrz** [comment]
Sorry, this is what I mean:
With ublock:
![untitled-6](https://cloud.githubusercontent.com/assets/930620/10953568/4cab1f34-830e-11e5-9ab1-8cf9c9d9ea49.png)
ublock disabled
![untitled-7](https://cloud.githubusercontent.com/assets/930620/10953569/4cace3a0-830e-11e5-8a3b-9343fb3d2bdf.png)
It seems the newest ublock blocks other addons from changing the context menu.

**Comment by gorhill** [comment]
For me the Context Search issue occurs only if I enabled Tab Mix Plus. As soon as I disable Tab Mix Plus, the Context Search entry shows up (after a restart of FF).

Can you confirm?

**Comment by vzjrz** [comment]
Yes all addons must be enabled. That's why I say ublock is not entirely to blame. But this problem does not occur in 1.3.3

**Comment by gorhill** [comment]
Ok, let me see what I can find -- might be difficult since for whatever reason there are no _Debug_  button for Tab Mix Plus or Context Search.

**Comment by gorhill** [comment]
Two observations so far:

- Toggling the option "Make use of context menu where relevant" fixes the issue.
- If opening a new window, the issue is not present in the new window.

**Comment by vzjrz** [comment]
Yep seems toggling "Make use of context menu where relevant" off and on fixes the issue. Thanks!

**Comment by gorhill** [comment]
Note however that if one disable Tab Mix Plus, restart FF, then re-enable Tab Mix Plus, restarts FF, the issue is back. So I think this confirms there is an issue in Tab Mix Plus and this should be reported to the author.

**Comment by gorhill** [comment]
Strike that, the issue is not back.

**Comment by gorhill** [comment]
Precision for above: it's back for the for the 1st restart. 2nd restart is ok...

Also, if reinstalling uBO, issue is back and must be solved using the toggle checkbox trick. I think we will need the TMP authors to provide some insights as to why this happens.

**Comment by Halibut80** [comment]
@gorhill I had no problems with beta 2 (TMP not installed), but now, new beta 3, breaks context menu for me.

isTextSelected, onTextInput, onLink, onLink & onImage, beta 2:
<a href="https://lh3.googleusercontent.com/-hFZIemWYCLI/VjzZHY1m91I/AAAAAAAAcDE/x0GVJkuqFU4/s0/clipboard2.png"><img src="https://lh3.googleusercontent.com/-XZOs9sKzoKg/VjzZIKkxQzI/AAAAAAAAcDI/wWhr3g8e1MY/s0/thumb2.png"></a><a href="https://lh3.googleusercontent.com/-oLwKnxUUF5w/VjzZIjqxMkI/AAAAAAAAcDM/KyAebm_wyEE/s0/clipboard3.png"><img src="https://lh3.googleusercontent.com/-oeLQLfVQn5I/VjzZJRFy9FI/AAAAAAAAcDU/dLlwXsitZgI/s0/thumb3.png"></a><a href="https://lh3.googleusercontent.com/-_WzE7cE-rC4/VjzZJ-R6G9I/AAAAAAAAcDc/tkCWwGx1S-s/s0/clipboard4.png"><img src="https://lh3.googleusercontent.com/-4jp9xSDNN2s/VjzZKVoOZBI/AAAAAAAAcDg/AwBCWfGLRzM/s0/thumb4.png"></a><a href="https://lh3.googleusercontent.com/-zTawJ9JBJ0A/VjzZLMyC2-I/AAAAAAAAcDo/vDQKzTiDN14/s0/clipboard5.png"><img src="https://lh3.googleusercontent.com/-Hle1V6OVddM/VjzZMOYhoQI/AAAAAAAAcDs/dT0ml-7F1sI/s0/thumb5.png"></a>

isTextSelected, onTextInput, onLink, onLink & onImage, after update to beta 3:
<a href="https://lh3.googleusercontent.com/-Zrgb6PFp4rg/VjzggcIQvWI/AAAAAAAAcEY/X8viu9St8G0/s0/clipboard6.png"><img src="https://lh3.googleusercontent.com/-Giqn58ydahw/Vjzgg-2RTJI/AAAAAAAAcEc/Yir7rh-h1Jg/s0/thumb6.png"></a><a href="https://lh3.googleusercontent.com/-rp2zTsZID5M/VjzghdNzXAI/AAAAAAAAcEk/46WheVZIw3U/s0/clipboard7.png"><img src="https://lh3.googleusercontent.com/-QdN8I4iPQ44/Vjzgh09JkNI/AAAAAAAAcEo/3axi-ZxcDEg/s0/thumb7.png"></a><a href="https://lh3.googleusercontent.com/-t4PX4qwUNy8/VjzgiQT9qVI/AAAAAAAAcEs/i91Lp3BPVr4/s0/clipboard8.png"><img src="https://lh3.googleusercontent.com/-1OTfV1qN15I/VjzgitU9uJI/AAAAAAAAcE0/v8PsvDNjkoY/s0/thumb8.png"></a><a href="https://lh3.googleusercontent.com/-_5XdwQsOU00/VjzgjDAHPzI/AAAAAAAAcE8/q-WLc9rohO4/s0/clipboard9.png"><img src="https://lh3.googleusercontent.com/-H8egriDHheU/Vjzgj9ZfHoI/AAAAAAAAcFA/62SOeDpVv4s/s0/thumb9.png"></a>
etc.

All menuitems added by another addons (BBCodeXtra, Context Search X, S3.Google Translator, Save Image in Folder, etc) are not displayed. Only added by Custom Buttons, non defaults items, still displayed. Sometimes browser restart fixes issue, but new restart can cause its again. I don't see any related errors in console.

**Comment by vzjrz** [comment]
@Halibut80 The newest release fixed the issue for me. Have you tried that?

**Comment by gorhill** [comment]
The only place uBO inserts its context menu entry is [here](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L3140). Whatever else is already in the context menu is completely left untouched.

Then afterward uBO will strictly set the visibility of this item again without touching anything else.

The only thing which changed with b3 is that the context menu entry is added at a later time -- as it used to be before changes in b2.

@AlexVallat any idea of what can explain all this weirdness with the context menu?

**Comment by Halibut80** [comment]
But fact: disabling uBlock or unchecking "Make use of context menu where appropriate" - solves issue with context menu for me. Also as downgrade to 1.3.4b2 or 1.3.3.

@gorhill Should I open a new issue?

**Comment by AlexVallat** [comment]
@gorhill No, it's a bit of a mystery to me. I'm trying to reproduce the issue using just Context Search and uBlock Origin, because Context Search seems to be a nice minimal implementation, only using the overlay to add a menu item. I haven't been able to see the problem, and there doesn't seem to be anything wrong with the code either. If I can figure out some reliable minimal (ideally a single simple addon) repro steps then I can investigate further. Otherwise, I'm out of ideas.

**Comment by gorhill** [comment]
@Halibut80 Can you reduce the repro steps to only one add-on aside uBO?

I was also unable to reproduce when I tried yesterday with Context Search Extra.

**Comment by gorhill** [comment]
For got there was a similar entry somewhere: #858.

**Comment by vzjrz** [comment]
It seems I was wrong, 1.3.4b4 does not permanently solve the issue for me. After a few restarts a reinstall of ublock is needed to get context menus back.

**Comment by Halibut80** [comment]
Ok, sorry. This issue causes by HTTPS-Everywhere. That strange, because this addon not use context menu.
Steps to reproduce:
1. Run latest Firefox Nightly x64 with new clean profile and with: xpinstall.signatures.required;false, browser.tabs.remote.autostart.2;false, extensions.update.autoUpdateDefault;false
2. Install HTTPS-Everywhere <s>5.0development.4 (for some reason I use this version. Also I use manually fixed version (<a href="http://ge.tt/api/1/files/8quOAOR2/0/blob?download">link</a>) with replaced let and const to var (<a href="https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/">because</a>)</s> same with latest stable <a href="https://www.eff.org/files/https-everywhere-5.1.1-eff.xpi">5.1.1</a>, <a href="https://addons.mozilla.org/ru/firefox/addon/s3google-translator/">S3.Google Translator 5.09</a> (for example), uBlock Origin 1.3.4b4
3. Restart browser (probably 1-4 restarts needed to got this issue), select text on any page, open context menu and:
<a href="https://lh3.googleusercontent.com/-a5eWtN-ggJk/Vj4p3GedspI/AAAAAAAAcF8/bISu4Pfd_po/s0/clipboard.png"><img src="https://lh3.googleusercontent.com/-_2FG4lTR6H0/Vj4p3UixpeI/AAAAAAAAcGA/TuCVIZ2DrlU/s0/thumb2.png" border=0></a>
instead:
<a href="https://lh3.googleusercontent.com/-v6lNm5H7184/Vj4p2OaER1I/AAAAAAAAcF0/7GE-BDFmnKg/s0/clipboard2.png"><img src="https://lh3.googleusercontent.com/-aZt9zCTlLKQ/Vj4p2gXCiMI/AAAAAAAAcF4/fqfbaYFtO_I/s0/thumb.png" border=0></a>

**Comment by gorhill** [comment]
OK I can reproduce with HTTP-E and uBO. Need S3.Google Translator to see the issue. I could not reproduce with Context Search or BB Extra. So it appears the issue is the combo uBO, HTTPS-E, S3 Google Translate.

- FF 42.
- Install uBO + S3.Google Translator + HTTPS-E + BBCodeXtra: restart FF.
- Context menu entry to translate is present.
- Restart FF.
- Context menu broken (*may* need to restart again).
    - Though it will be all OK in a new window.

So far this is what I have:
- uBO + HTTPS-E + S3.Google + BBCodeExtra = broken
- uBO + HTTPS-E + S3.Google = broken
- uBO + S3.Google + BBCodeExtra = ok
- HTTPS-E + S3.Google + BBCodeExtra = ok
- uBO + HTTPS-E + BBCodeExtra = ok

**Comment by Halibut80** [comment]
@gorhill Sometimes need more than one restart to achieve this. I can reproduce this issue without S3.Google Translator. Only HTTPS-Everywhere, Context Search X and uBlock Origin 1.3.4b4
<a href="https://lh3.googleusercontent.com/-G5wjO9Cau70/Vj5c-71DRGI/AAAAAAAAcGc/dQWCNcxr874/s0/clipboard2.png"><img src="https://lh3.googleusercontent.com/-8amAdNLVrDs/Vj5c_4SP9mI/AAAAAAAAcGk/f1Zti5qzYNg/s0/thumb.png" border=0></a>
<a href="https://lh3.googleusercontent.com/-EDn81C0FQGk/Vj5dBmZuLdI/AAAAAAAAcGs/Q-EJsKV92lk/s0/clipboard.png"><img src="https://lh3.googleusercontent.com/-TjGla2gVM0I/Vj5dCjOARYI/AAAAAAAAcG0/y0crjk08RsU/s0/thumb2.png" border=0></a>

**Comment by gorhill** [comment]
> need more than one restart

I do try at least five before giving up.

**Comment by gorhill** [comment]
I could reproduce your second image with Context Search X. A bit different than the breakages, as Context Search X is still able to have two of its entries shown.

At this point I am tempted to think it's a FF issue, I have no explanation of why this happens.

**Comment by Halibut80** [comment]
So... Should I file bug on bugzilla? Or on torproject bugtracker? But this issue caused only by upgrade to version uBlock beta2+, and I guess I'll be sent back here with this... :/

**Comment by gorhill** [comment]
> Or on torproject bugtracker?

I can reproduce without TOR, no point in dumping this on their plate.

> this issue caused only by upgrade to version uBlock beta2+

This means nothing. It could be a timing thing involved, i.e. the issue was always there ready to manifest itself. Ideally a Firefox dev knowing that area and what happens internally could provide insights -- it's easy to repro.

**Comment by onestepbeyond** [comment]
Same here with FF42, uBO 1.3.4b4 and following addons:
[Tab Mix Plus 0.4.2.0pre.151031a1](https://addons.mozilla.org/fr/firefox/addon/tab-mix-plus/#beta-channel)
[Element Properties 9.1-signed](https://addons.mozilla.org/fr/firefox/addon/element-properties/)
[Contextual Google Image Search 2.1.1.1-signed](https://addons.mozilla.org/fr/firefox/addon/conggl/?src=api)
[TinEye Reverse Image Search 1.2.1](https://addons.mozilla.org/fr/firefox/addon/tineye-reverse-image-search/)

The following addons are not affected by the issue, remain visible in both cases (uBO enabled/disabled) and work well:
[S3 Google Translator](https://addons.mozilla.org/fr/firefox/addon/s3google-translator/)
[Googlebar Lite](https://addons.mozilla.org/fr/firefox/addon/googlebar-lite/)

-- As far I remember, HTTPS Everywhere was never been installed within this FF profile. 

Just my two cents because of slow investigations with uBO 1.3.4b4 since I have to restart my entire system to make the issue appear/disappear. 
It was more easy with uBO 1.3.4b3 which just needed to restart Firefox after enabling/disabling uBO or unticking/ticking the option "Make use of context menu where appropriate".
(The latter option also works well with uBO 1.3.4b4 but needs also to restart the computer).

**Comment by gorhill** [comment]
Found out the `readyState` of the document passed to `vAPI.contextMenu.register()` could be `uninitialized` when launching FF -- probably when `vAPI.contextMenu.create()` is called before `tabWatcher.start()`.

Now ensuring `readyState` is `complete`.

**Comment by Halibut80** [comment]
@gorhill Thank you. So that uBlock related bug? No need anymore file bug on HTTPS-Everywhere bugtracker (they use torproject bugtracker) or on bugzilla?

**Comment by gorhill** [comment]
> So that uBlock related bug?

Yes, it was a uBO bug -- I had overlooked an entry point to the context menu creation. It was there since forever but as said, timing issue -- made more sensitive with recent changes

**Comment by onestepbeyond** [comment]
Thanks @gorhill for the fix and @vzjrz for posting this here, I was very closer from thinking to a Firefox 42 issue.
