### ISSUE TITLE
Youtube is laggy when logged in

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uBlock#907]
Firefox 42 64 bit
uBlock Origin 1.3.2
Windows 8.1 Pro 64 bit (clean install)
Surface Pro 2 (latest firmware)

I recently started noticing a lot of lag when viewing a Youtube tab, and beginning to load a video or  scrolling up and down a YT page it. What is worse is that when that happens, the whole browser stalls. I assumed it was a corrupt Firefox profile.

So I trying to pinpoint the problem I did a clean install of Firefox, started with a fresh new profile and installed only uBlock (and x-notifier), and left all settings at their defaults.

There is still noticeable lag (not as bad as my normal profile), and it becomes much more noticeable when logged in to Youtube.

Thanks, 
available for any clarification.

**Comment by gorhill** [comment]
And you know uBO is the cause how? If you think uBO is the cause, the proper test is to **not** install uBO in your clean profile -- the proper test is to install nothing in your clean profile (including not installing x-notifier), see the result, and work up from there, i.e. make one change at a time.

Lag in Youtube is such a generic issue with Firefox (search the web) that chances are that the cause is elsewhere than in your add-ons.

**Comment by AdKiller** [comment]
sorry I forgot to mention that with the clean profile and no addons, and not legged in to Youtube, there is no lag.

**Comment by gorhill** [comment]
Did you try with no add-on and logged into Youtube?

**Comment by AdKiller** [comment]
I tried again with clean profile, no addon
not logged in to YT: no lag
logged in to YT: noticeable lag when scrolling up and down.

another issue that seems to be related is that, sometimes right after the moment the lag happens, a strange thing happens. It is like Firefox throws up all the little icons on the page. This also happens in clean profile, no addon, logged in to YT.

see one sample screenshot:
http://i.imgur.com/LTwUMg6.jpg

**Comment by gorhill** [comment]
Is the video player Flash-based or HTML5-based when this happens?

**Comment by AdKiller** [comment]
HTML5 in all cases. I do not have Flash installed.

**Comment by gorhill** [comment]
> It is like Firefox throws up all the little icons on the page

Does the browser console contain anything noteworthy when all this happens?

**Comment by Philsmo** [comment]
Hi, I also am having this problem. Firefox becomes unresponsive (freezes) whenever the subscriptions page or a video page is loaded. I suspect it is related to UBO because during the freeze it shows that hundreds of things are being blocked.

Here is a screenshot: i.imgur.com/8o05L8d.png

Other times, the pages will not freeze, and UBO will have blocked <50 things.

**Comment by gorhill** [comment]
494 blocked network requests on Youtube is normal: it's just the number of blocked network requests since the last time a page was fully loaded.

**Comment by gorhill** [comment]
Fron now on, whoever wants to open an issue such as this one will have to substantiate that uBO is causing whatever slow down is observed -- especially that such issues appear to be specific to someone once in a while as I can't reproduce.

Here is an example of someone substantiating performance issue: <https://github.com/gorhill/uBlock/issues/266>.

**Comment by AdKiller** [comment]
Good news! adding this filter to uBlock gets rid of all the YouTube freeze and lags I was experiencing. unbelievable!

||youtube.com/watch_fragments_ajax?*

Thanks to:
https://www.reddit.com/r/firefox/comments/3lbd5b/a_few_days_ago_firefox_began_freezing_everytime_i/cvhhthd
