### ISSUE TITLE
Unable to block data:image/png src data using element picker

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#91]
When entering http://muzikosfanai.lt/, the site detects uBlock's blockage, and an alert appears on the center of the screen, rendering the site unusable.

It appears to be a span block with an id of #of4f which has an img element inside of it with a src property of data:image/png .
When trying to block the resource through the element picker it doesn't seem to work after a page refresh.

Is this a limitation of uBlock?
Tested on both FF and Chrome, uBlock Origin 0.9.4.4

Also, it seems like the site is monitoring its elements, because when trying to remove the span element  which is being shown with the alert (#of4f) using element picker, it seems have no effect and the alert comes .

The only thing that helps to not get the alert is to disable the cosmetic filtering on this page via site switches.

Thanks!

**Comment by gorhill** [comment]
You need to show me what filter(s) you created with the picker.

**Comment by lewisje** [comment]
Are you sure that `muzikosfanai.lt###of4f` doesn't hide the image? By the way, although you didn't mention it, I should say that `data:` URIs cannot be blocked, because all of their content is inside the document already rather than being sent by a separate request that uBlock could potentially block.

**Comment by my-password-is-password** [comment]
`muzikosfanai.lt###of4f` hides the image but you might get a blank white page sometimes because the `#of4f` span is placed at random spots.

Run `$$('style[type="text/css"]')` in the console. At the very end of the style, `#of4f ~ *{display:none}`

If you keep refreshing the page and run `$$('#of4f ~ *')` when the page completely loads, you can see it sometimes returns different elements.  If you see `<div id="wrapper">...</div>` in the results, the page is blank.

**Comment by lewisje** [comment]
BTW, for those debugging pages that *don't* use jQuery or its Sizzle component, use `document.querySelectorAll('style[type="text/css"]');` instead: The general selector `jQuery()`, its alias `$()`, and the CSS-specific `$$()` use `document.querySelectorAll()` where available and relevant, and a polyfill if such a thing is relevant but the platform, like old versions of IE, does not support it natively.

With that said, it looks like that site developed an effective anti-Adblock technique, and although you might do well to block the script that generates the URI (it's not in the original markup itself, so it is script-generated) as long as doing so won't also keep the content from being shown, another idea might be to make a UserScript that nullifies that style rule, and possibly ask Reek to incorporate that workaround into the Anti-Adblock Killer UserScript.

**Comment by gorhill** [comment]
This works:

    muzikosfanai.lt###of4f

**Plus** User Style and the following style for `http://muzikosfanai.lt/`:

    #of4f ~ * {
	    display: '';
    }

**Comment by my-password-is-password** [comment]
@lewisje My bad.  $ and $$ is not jQuery in chrome console.  

https://developer.chrome.com/devtools/docs/console

Under sectoin "Selecting Elements".  They are shortcuts for querySelector() and querySelectorAll()
