### ISSUE TITLE
*Storage used* value (in dashboard) increases suddenly

### ISSUE THREAD

**Issue by Molatisue** [gorhill/uBlock#910]
I don't know how but i must confess that the value (in bytes) in the dashboard for *storage used* increases sometimes from (first install and filter selection) 17.8 mb up to 20.9 mb in the end. If this occurs I replace the saved ublock0.sqlite with the increased one (for me better than the backup provided in the dashboard) and test again. The only coherence I can give (after several times of reproducing this) is that I watch videos on youtube, then surf some sites (not special ones). And after a while (15 minutes or so - the exact point is not aware yet) the value increases. And NO, I don't have auto updates for filters activated... nor other uBO related nor settings in general changed in the meantime.

Firefox Version: 42
uBlock Origin Version: 1.3.2
Linux

**Comment by gorhill** [comment]
Here is how I will start to require filing issue will work (there will be a wiki page for this):

Make the case there is an **actual** issue -- investigate and provide factual evidence there is something wrong with uBO. The SQlite code or the SQlite API in Firefox is not under control of uBO. That kind of issue is best investigated by the person making the claim there is an actual issue, rather than claiming this is an issue and having me spend an inordinate amount of time to find out for you there is nothing wrong.

Reopen when you have evidence there is something wrong.

**Comment by Molatisue** [comment]
Ok... but why is this "issue" not noticeable with uBO 1.3.1 as I tested meanwhile. In my eyes it has something to do with uBO. 
And: I didn't wrote the initial issue post to let this "bug" further inspected by you... I wrote it to mention that there is something strange... and maybe other people notice it, too.
Sorry for the circumstances.

**Comment by gorhill** [comment]
> there is something strange

I don't see anything strange given [how uBO works](https://github.com/gorhill/uBlock/wiki/Memory-footprint:-what-happens-inside-uBlock-after-installation):

> A few minutes later, assuming no change in selection of filter lists, or change in the content of selected filter lists, uBlock will make a selfie.

**Comment by Molatisue** [comment]
Yes, it makes selfies... but it doesn't mean its *storage used* value in the dashboard (and the sqlite file itself) increases about 1/6 just by running Firefox for some minutes and no filters added/removed/changed. Because by Version 1.3.1 this increase isn't noticeable. By your means it MUST shown even in that prior version, right?

**Comment by gorhill** [comment]
I obviously use latest version, and my storage used is stable at 6,720,310 bytes with default filter lists + plus a few custom rules. If I enable a filter list, it will increase. If I disable that same filter list, it will stay at the increased value. If I purge the cache for that now disabled filter list, the value will lower. When the selfie is created, it will go up. Etc. Nothing unexpected.

> I replace the saved ublock0.sqlite with the increased one

I **strongly** discourage anybody from doing this, it's asking for trouble. FF/SQlite may use an in-memory cache journal of SQL commands, and swapping the db may screw things up.

The thing is you are the one claiming there is an issue, I have no way to stand behind you and watch what you are doing to find out for you the explanation of your specific increase. Bottom line is that there has never been an issue with the storage used value, and as far as I am concerned, since you are making the claim there is an issue, make the case for it, _substantiate it_, just don't dump the work to prove your feeling whether there is an issue onto others.

This is what positively contributing is:

Install <https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/>, create snapshots of the db before and after the "jump" by exporting to CSV files, diff the two snapshots. Show that the diff contains stuff which should not be there. In other words, _make the case_ there is an issue and that it is in uBO. This should have been done before opening an issue.

> increases about 1/4

3 MB / 17.9 MB is not 0.25, it's 0.17 (~1.4 MB difference, not a trivial rounding). Already that kind of statement lead me to believe you want it badly that there is an issue to the point you will exaggerate the figures. And what you call a "simple seflie" is closer to a memory snapshot, so though it can be described as "simple", it's large.

**Comment by gorhill** [comment]
Some figures for guidance - assuming no SQlite file when launching FF with uBO:

- Default filter list, not updated (after install): 4.5 MB
- Default filter list, updated: 6.7 MB
- Default filter list, updated + selfie: (waiting for it to happen)

**Comment by Botempi** [comment]
RIGHT: >after a clean install of uBo there will be (after the first filter update) a selfie "shot" and the amount of data will raise up<

But try this: You still have the raised up "uBo install" after the selfie is shot (from 6mb up to 9 mb in your case)... then, 4-5 days later there comes up regulary updates for the selected filter lists, again. NOW, if you update these filterlists... the raised up "uBo install" comes from (in this case) 9.2 mb down to 6.2 mb... and it stays there, even if FF runs for half a hour.

So, I think the OP has noticed something... but didn't evaluate it right. 

Conclusion: First grows up as it should after the selfie... after the next filter update... it shrinks back to where it was before the selfie was taken and stays!
