### ISSUE TITLE
unresponsive script loop gmail freezing firefox

### ISSUE THREAD

**Issue by DiabSoule** [gorhill/uBlock#914]
Having trouble adding screenshot to this message for some reason. Gmail has become impossible to check with message unresponsive script:

Script: chrome://ublock0/content/js/contentscript-end.js:835

I looked but didn't see anything else relating to this issue.

Thanks

**Comment by gorhill** [comment]
Browser/version/custom filters/filter lists/etc. ([CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md))

**Comment by gorhill** [comment]
> chrome://ublock0/content/js/contentscript-end.js:835

This is the mutation handler, i.e. it's not uBO being in a loop, it's uBO being told the DOM changed. What other extensions do you have installed?

**Comment by DiabSoule** [comment]
i have several extensions. What particular nature of the extension would be most helpful? I don't always have everything enabled. Just listing them.
Ghostery
No Script
Pure URL
Click and Clean 
Https Everywhere
Clean Links
Redirect Cleaner
Sea onkies ....oops GREASEmonkey (joke from yesteryear)
SSleuth
Google Privacy
World IP
uBlock Origin of course
uMatrix-----stays disabled most of the time
Zenmate

Sorry about that I didn't know what to call it but a loop. If more nfo needed lemme know.

**Comment by gorhill** [comment]
Disable all extensions xcept uBlock Origin. See if problem persist. If not re-enable the other extensions one at a time.

Most likely another extensions is causing DOM change at a breakneck pace for whatever reasons (including bugs), and this is what is causing the freeze.

uBO listens to DOM changes, so this may affect it indirectly, but the code listening to those changes is very polite, i.e. it does so asynchronously.

In the reported line above, uBO does almost nothing except to store the mutated nodes for later examination (hence asynchronous), so that it was reported leads me to believe there is something else in there causing massive number DOM mutation changes -- you have to find out the culprit.

**Comment by DiabSoule** [comment]
Still unable to pin it down. When enabling/disabling it will pick a different extension. 

Examples:
              Script: chrome://gprivacy/content/gprivacy.js:271
              Script: resource://gre/modules/commonj…etpack/pure-url/data/inject.js:161

If uBlock is enabled it will always be the one named over anything else. If uBlock is disabled then it starts to become more random.

**Comment by gorhill** [comment]
> When enabling/disabling it will pick a different extension

It's why I suggest you disable all extensions and see if the problem occurs. If not, enable extensions one at a time until you find the one causing the issue.
