### ISSUE TITLE
Block content which contains xyz

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [gorhill/uBlock#915]
A lot of sites have this "containers" begging to turn off adblocker. Most of them name it a specific name for most containers.

I'd like to block them. For instance on esohead.com, these containers have the phrase block-content in them, I'm trying to block it with esohead.com## > *block-content* but to no avail.

**Comment by RoxKilly** [comment]
To defeat anti-adblock measures, consider the [Anti-AdBlock Killer project](https://github.com/reek/anti-adblock-killer#instruction).  it requires installation of another add-on, but it works well and is constantly updated to address new ad-block detection scripts.

**Comment by gorhill** [comment]
> `esohead.com## > block-content`

That is not a valid cosmetic filter. You must create valid cosmetic filter in the first place. See <https://adblockplus.org/filter-cheatsheet#elementhiding>.

**Comment by lewisje** [comment]
CSS cannot select an element based on its text content, so indeed, Reek's anti-adblock killer script is a better option.

**Comment by grabber24** [comment]
Hello, first of all, I'd like to say thanks for any input that you decide to leave. I am very new to this, so I really appreciate any feedback that may end up being useful in the future. I personally believe that almost any info that I have never seen will be more than likely helpful because for the simple fact I just have not ever learned it. Another wrinkle in the brain as my mom would say. I'm guessing that the Reek's anti adblock killer is a downloadable tool that's available among the Firefox extensions available for download, I hope.

**Comment by lewisje** [comment]
No, it's a combination of a UserScript (use TamperMonkey for Chrome, GreaseMonkey for Firefox, ViolentMonkey for Opera, or NinjaKit for Safari) and a filter-list: https://github.com/reek/anti-adblock-killer#instruction

I mention Safari because even though uBlock Origin is not available for Safari, its lesser variant (uBlock) is, and so are Adblock Plus and AdBlock.
