### ISSUE TITLE
Cosmetic Filters are saved by default

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#941]
Cosmetic Filters are saved by default into the Permanent rules, instead of Temporary rules.
This increases the size of Permanent rules but the real issue is keeping rules that where only meant temporarily or as test.

Example:
http://www.seamonkey-project.org/

OS: Windows 7 pro x64
uB: 1.3.3. and 1.3.4rc1
Browsers: SeaMonkey 1.33.1, Pale Moon 25.7.3, Firefox 42.0

**Comment by gorhill** [comment]
I don't understand the reported issue.

**Comment by LeafG** [comment]
I'll try to clarify:
Assume I installed ub for the first time, and there are no rules on "My rules" pane.

I now go to some site, http://www.seamonkey-project.org/ for this example.

I open the pop up and press the cosmetic rules "eye" on the bottom.

Now on "My rules" pane I see the 
<code>no-cosmetic-filtering: www.seamonkey-project.org true</code>
on the "Permanent rules" side (on the left) instead of the "Temporary rules" side (on the right).

**Comment by gorhill** [comment]
Ok, you are talking about the no-cosmetic-filtering switch. Referring to it as "Cosmetic Filters" did not help.

The per-site switches do not have a temporary state, because they are part of the basic panel. Everything in the basic panel is on or off without the need to persist the state -- for simplicity. I do not intend to change this.
