### ISSUE TITLE
Web Store

### ISSUE THREAD

**Issue by JeremyWW** [gorhill/uBlock#95]
In the latest release you say that 0.9.4.4 is pending review, yet the latest version in the store is actually 0.9.4.2.

Are Google messing about here? Any advance on news of the delay?

**Comment by gorhill** [comment]
I submitted 0.9.4.4 yesterday morning, this is what I have now:

![a](https://cloud.githubusercontent.com/assets/585534/7220327/2217342a-e691-11e4-9891-f86128a6a1ae.png)

HTTP Switchboard was also taken down, unsure why, but I am not sure I will bother trying to reinstate hi one, it has been superseded by uMatrix since very long now.

**Comment by JeremyWW** [comment]
Thanks. Here's hoping they get on with it. I wonder if they've tightened up their policies & procedures since disabling NPAPI plugins and extensions.

**Comment by Havokdan** [comment]
I just saw the store version of the Opera, she replaced the normal version, I thought his version would have the name of "uBlock Origin" also at the Opera.

**Comment by gorhill** [comment]
I didn't find a way to change the name, it's still the very old one, µBlock. I told the reviewer about the name change, so that if it can be changed I assume they will change it.
