### ISSUE TITLE
NoScript Force HTTPS feature interferes with uBlock Origin

### ISSUE THREAD

**Issue by LordJZ** [gorhill/uBlock#959]
Steps to reproduce:

1. Create a clean profile, install latest NoScript and uBlock Origin
2. Disable e10s (not reproducible in e10s mode), restart browser
3. Open this: http://geektimes.ru/company/audiomania/blog/266146/
4. In NoScript click "Allow all this page", refresh page
5. Open network console, see how 5th or so request goes to: https://vk.com/js/api/openapi.js?63
6. In uBlock Origin, create this filter: `||vk.com$third-party`
7. Refresh that tab, see how no requests to vk.com are made -- this is expected
8. Open NoScript options, go to Advanced, HTTPS, Behavior, Force, and put `vk.com` there
9. Refresh that tab, see how a request to vk.com is made -- this must not happen, request must be blocked

**Comment by gorhill** [comment]
The network requests which appear in the network console are seen as behind-the-scene by uBO -- as per uBO's logger.

I don't know much about the inner working of NoScript, but from what I see, NoScript is cancelling network requests to `http://vk.com/[...]` and replacing them with network requests to `https://vk.com/[...]`, however in the process of doing so, the information from where the network requests originate from is lost when uBO tries to look this up in its HTP observer.

**Comment by gorhill** [comment]
With uMatrix, the issue is not present, probably because when it stumbles upon a behind-the-scene it tries one last time to find out from where the network request originate ([source](https://github.com/gorhill/uMatrix/blob/6eaa85eee172cf541fd8d7e557c8f0f3f6bc7348/platform/firefox/vapi-background.js#L1882)).

I should import this code into uBO for when a behind-the-scene network requests are encountered.

**Comment by LordJZ** [comment]
Note that this is not reproduced in e10s mode, for whatever reason.
