### ISSUE TITLE
Ads not being blocked on Linux

### ISSUE THREAD

**Issue by max1c** [gorhill/uBlock#962]
I am using ublock in Opera on RHEL 7 and a lot of the ads that should be blocked and do get blocked on Windows 10 are not being blocked on RHEL 7. The same thing happens on other Linux distros. Is this a know issue? I couldn't find any reports about this.

**Comment by gorhill** [comment]
> I couldn't find any reports about this.

There is no issue here, or reported. See <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>. Without details it's impossible to do anything. Try to investigate first how this could happen on your side -- as it seems the issue is specific to you.

Always use the logger -- it's there to assist you to diagnose the working of uBO.

**Comment by gorhill** [comment]
I will remove the invalid label once you make the case there is an issue with uBO.

**Comment by gorhill** [comment]
Closing due to lack of feedback.
