### ISSUE TITLE
Local mirroring alternative

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#971]
@gorhill, someone is developing a Firefox extension called [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes/) that follows the same spirit as the [local mirroring feature](https://github.com/gorhill/uBlock/wiki/Experimental-features) present in earlier versions of uBlock.

I've told him that you worked on something similar in the past, and he has released the source code on Github for everyone interested in it to be able to contribute: https://github.com/Synzvato/decentraleyes  . If you have time, check it out. If you like it, you may have some advice to give him, or nominate it to be listed on [privacytools.io](https://github.com/privacytoolsIO/privacytools.io).

By the way, [the wiki page on local mirroring](https://github.com/gorhill/uBlock/wiki/Experimental-features) must be updated.

**Comment by RoxKilly** [comment]
@anewuser This is a really interesting concept. I notice that the add-on comes prepackaged with some frequently used libraries. Are you at all concerned about the possibility of malicious code running instead of the intended JavaScript resource?  I know we implicitly trust all our extensions since they have access to our network traffic, but having an extension run "substitute code" makes me a little weary. What do you guys think? I read around but couldn't find a good FAQ so I posted [a few questions](https://github.com/Synzvato/decentraleyes/issues/3) on the project's github.

**Comment by anewuser** [comment]
>. Are you at all concerned about the possibility of malicious code running instead of the intended JavaScript resource?
I posted it here exactly for it to be reviewed by someone more skilled. I personally haven't found any problems with it.

**Comment by gorhill** [comment]
> to be reviewed by someone more skilled

The add-on has been fully reviewed by Firefox, so it should be assumed it's fine. For the CDN resources themselves, in doubt just check their md5sum/shasum against the md5sum/shasum of their official versions on their home server.

I modified the wiki page to remove references to local mirroring.
