### ISSUE TITLE
Need statistics for each filter like in ABP.

### ISSUE THREAD

**Issue by antdude** [gorhill/uBlock#983]
In ABP, I could see the detailed statistics on each filter like how many times it was used, last used, etc. I would like to see this in UO as well.

**Comment by gorhill** [comment]
The rationale for a feature should never ever be "like in ABP" -- uBO is not a clone of ABP.

I consider features according to real and concrete issues for majority of users, not things just "nice to have" for a minority of users.

**Comment by lewisje** [comment]
Also, it should be noted that only the Firefox version of ABP has this feature: It has proven difficult to add it to ABP for other platforms (they were developed separately, not as forks of the Firefox extension).

**Comment by LifeIsStrange** [comment]
I think that this feature could be very useful for find a good compromise between performance and blocking ratio. 

For exemple I don't know if peter lowe's ad list is useful for me because I mostly see french sites. 
This feature could give me an answer.

**Comment by gorhill** [comment]
The only sensible implementation of this I can think of, is to make it an opt-in feature in the logger. Only those who actually open the logger incurs whatever resource overhead it causes. And if on top of this the filter stats are opt-in, this added overhead would be incurred only by those who care to open the logger **and** opt-in into filter stats.

This means if someone is interested in collating filter stats, one would have to open the logger, enabled filter stats collation, and keep it open for as long as filter stats have to be collected.

Just pondering how this could be reasonably implemented, causing zero resource overhead to be added overhead for those who do not care about these stats. I haven't decided whether I want to implement this, and I don't see this implemented in the short term, I consider there are more important things to work on.

**Comment by haarp** [comment]
I maintain a bunch of personal filters, both for ads and non-ad purposes. Websites change all the time - I would **really** appreciate being able to see when a filter was last used, to let me know if one is outdated. ABP had this feature and it was quite useful. Even if UO is not ABP, this is something I am sorely missing in UO.

**Comment by gomoku** [comment]
I agree with @LifeIsStrange's and @haarp's argumentation and I disagree with gorhill's:



> @gorhill : I consider there are more important things to work on.

Maybe at the moment yes, but generally from a design point of view, what you're saying is just strange,  because a filter hits stats counter (also with a possibility to manually tick/untick a particual filter by a mouse's click) just like in ADP, is a very important, handy and usefull thing which should have been done long ago, in the first releases of uBlock Origin, and also in every real ad blocker. The argumentation 'why', is the same as @LifeIsStrange's and @haarp's argumentation, and extending his point I can add that having xxx thousands filters while 90% of them are not being used and are just unnecessarily slowing down webbrowsing, is not a good idea. It seems logical to gain some hits statistics, and get rid of unnecessary ballast (filters) to improve webbrowsing speed. The filter hits counter stats thing could be turned off by default, and could be a turn on/off feature, so having it disabled wouldn't impact on the speed. Several months ago I've switched from ADP to uBO, because uBO is crazy fast + has a very usefull remove duplicates feature, but if I wanna optimize my filters I still have to switch to ADP to see the hits stats, and then get back to uBO then get rid of unnecessary ballast (filters).
