### ISSUE TITLE
personalized block list via host file

### ISSUE THREAD

**Issue by vendforce** [gorhill/uBlock#989]
how can I block firefox opening windows that are blocked via hosts file in linux
when a webpage or a domain is placed in hosts file , firefox blocks it from loading but still opens
an empty web page i.e 127.0.0.1 . I want to stop firefox opening any pages or tabs blocked by the hosts file

p.s Im sorry for putting this here but I dont know where else to ask I couldnt find a support forum for ublock origin. I've searched on the web but to no avail any help would be greatful

**Comment by gorhill** [comment]
Blocking popup windows work only when the `popup` filter option is present. Automatically applying the `popup` option to all hostnames in a filter list is not a good idea.

As usual, what real, concrete case you have on hands?

**Comment by vendforce** [comment]
Ok Thanks for your responce, sorry I was just trying to create a bash script and download all adblock lists and regex them to hosts list format i.e 0.0.0.0 domain.com and then thought I could figure a way to get firfox to stop thm poges loading in the background when they are blocked

I used to use adblock plus and thought it was the only reason I would keep using a browser. I just couldnt deal with the amount of ads being forced on the internet user theses days and if anything its going to get worse with compaines coming up with new ways to embed the ads etc .. and I just found out adblock are selling out .. which really annoys me

**Comment by vendforce** [comment]
Ok Thanks for your responce,I was just trying to create a bash script and download all adblock lists and regex them to hosts list format i.e 0.0.0.0 domain.com and then thought I could figure a way to get firefox to stop them pages loading in the background when they are blocked, and your asking yourself why would I do this ? why just not use ublock orgin 

The reason is I used to use adblock plus and it was the only reason I would keep using a browser to view the web, I just couldnt deal with the amount of ads popping up and intruding and bombarding my privacy it was like that game wack a mole 

of lately I have seen that even with adblock plus I'm starting to get an influx of ads which I thought weird until I found out that adblock plus are a sell out and now letting companys advertise if they pay ... what a sad day for the internet its a f**king disgrace... is that all it takes these days ? someone starts a project to help people view the web in a non intrustive way, and then when the project gets ground and takes off and they get approached by companys they see $$$ and they think ahh lets sell out .. do they forget why they started the project. Well if they can't remember let me remind them was becuase the believed in doing something for the great good and money wasnt on there minds when they started, it was about beating the ad companys and taking the web back 

I have started using ublock-orgin and have read into the saga of the whole ublock and ublock-orgin .. thats another f**king sad sate of affairs that cu*t should be shot with his own balls, anyway I now fear someday ublock-origin will sell out "no offence meant"  and I just wanted to try create a little project for myself so I dont have to try find a new adblocker or wait for someone else to start an ablocker project 

ublock-origin is as far as im concerned the reason I still bother viewing the web. I find the interface far superior to any other adblocker and after reading into the whole ublock-origin and ublock thing I got a little worried and thought here we go again this will died a sad death due to the bullshit that surrounds the whole project and it will be a real shame if it does  

please keep up this "ublock-origin" project because with out your amazing contribution the web is nothing but popups and annoyance  .. and if you do decide to stop contributing and hand it over make sure you dont hand it over to another d**khead

thanks for making the web viewable again

**Comment by lewisje** [comment]
Using a regex to turn typical ABP-style lists into HOSTS files will lead to tons of false positives, except maybe if your regex picks out only those filters that block at the same granularity (all files under a specific hostname), in which case you'll get tons of false negatives.

With that said, the technology behind ad-blocking is so freely available that even if Eyeo, Betafish,<sup><a href="#0">0</a></sup> and even gorhill (whom you have not accused of impropriety) sold out to the extent you're ranting about,<sup><a href="#1">1</a></sup> someone could fork their projects (as the Adblock Edge team did, prematurely IMO) or (as gorhill did a year and a half ago) figure out anew how to leverage the relevant browser APIs (some of which were put in *with pressure and assistance from the eventual founder of Eyeo, Wladimir Palant*) to block unwanted content.

To put it more briefly, your plan to make Hosts-file entries from ABP lists won't help much (compared to, say, using well curated Hosts files directly), and if ABP, AdBlock, and uBlock Origin all go to shit, it won't take long for a new generation of developers to make alternatives that you can quickly migrate to.<sup><a href="#2">2</a></sup>

---
<small id="0">*0: Eyeo GmbH is the company built around the Adblock Plus project; Betafish, Inc. is the company built around Michael Gundlach's AdBlock for Chrome and its ports to Safari and Firefox.*</small>

<small id="1">*1: They haven't: Eyeo was concerned about the viability of the free ad-supported Web if even the clueless masses got into ad-blocking and therefore started a project to get the better ads unblocked by default, charging only the bigger advertisers because of the expense involved in getting all __their__ ads whitelisted and verifying they're still worthy of being unblocked by default; Betafish came around to this conclusion after first marketing itself as the ad-blocker that __didn't__ do that, and both companies still allow the whitelist to be disabled by those who bother to change the default settings.*</small>

<small id="2">*2: The beauty of the GPL is that they can't legally close off the source code to their.existing releases, even if they try to make closed-source versions that force Acceptable Ads or a similar whitelist.*</small>

**Comment by gorhill** [comment]
> Eyeo was concerned about the viability of the free ad-supported Web if even the clueless masses got into ad-blocking

I believe the "clueless masses" can decide for themselves when to whitelist a site if they agree to help that site to fund itself through 3rd-party ads/data miners.
